' =============================================================================
' sap_function_group_gui_delete.vbs  -  SAP GUI Scripting: Delete a Function Group
'
' >>> Prefer invoking the /sap-function-group skill (delete mode) via the Skill
'     tool -- it wraps this VBS with TR resolution, the post-delete RFC
'     verification, and logging. This VBS is RELEASE-SELF-SELECTING and no longer
'     aborts on classic navigators (see "Path dispatch"), so a bare run no longer
'     mis-reports a deletable ECC6 FG as blocked (the field bug, 2026-06-22) --
'     but it does NOT RFC-verify removal on its own; the skill does. <<<
'
' Generated by the sap-function-group skill (Step 3e -- GUI delete sub-flow).
' Opens SE80 (Object Navigator), selects the Function Group object, triggers
' WB_DELETE via the repository-tree context menu, and walks the resulting
' confirmation popup chain. SE80's WB_DELETE is the canonical Workbench
' delete for function groups on S/4: it understands the FG/FM cascade, surfaces
' a single "FG still contains these FMs -- confirm?" dialog, then asks for the
' transport assignment and performs the cascade delete in one server round.
'
' Path dispatch (self-selecting INSIDE this VBS -- not in the SKILL.md):
'   * S/4HANA    -> SE80 WB_DELETE path (primary; the body below).
'   * ECC6/7.31  -> classic SE80 has no HTML type/name control, so this VBS
'     AUTO-FALLS-THROUGH to DeleteFgViaSe38() = SE38 SAPL<FUGR> delete via the
'     shared sap_delete_popups.vbs walker. Deleting the function-pool program
'     SAPL<FUGR> cascades the FG delete on ECC6 -- verified EC2/ERP 2026-06-21
'     (TLIBG=0, PROGDIR SAPL<FG>=0). The shared walker also clears the SAPLSETX
'     + KO007 popups, so the OLD false-SUCCESS caveat no longer applies.
'
' Tokens replaced at run time:
'   %%FUGR_ID%%        Function group name (UPPERCASE), e.g. "ZDEV_FG"
'   %%TRANSPORT%%      Transport request for the FG deletion. Empty when the
'                        FG is local ($TMP) or already locked to a
'                        modifiable TR. If the popup appears with TRANSPORT
'                        blank the script aborts so the caller can resolve a TR.
'   %%PACKAGE%%        Package for the SE38 SAPL<FG> fallback's KO007 popup
'                        (ECC6). Empty = accept pre-filled / Local Object.
'   %%ORIG_LANG%%      1-char original language for an empty KO007 package field.
'   %%ATTACH_LIB_VBS%% / %%SESSION_LOCK_VBS%% shared-script paths (the shared
'                        sap_delete_popups.vbs walker is derived from the
'                        attach-lib dir for the SE38 fallback).
'
' Recording reference: C:\Temp\Record_SE80_DeleteFunctionGroup_01.vbs (S/4HANA 1909).
'
' Outputs (last line of stdout, parseable):
'   SUCCESS: Function group <FUGR> deleted.
'   ERROR:   ...
' =============================================================================

Option Explicit

Const FUGR_ID      = "%%FUGR_ID%%"
Const SAP_TRANSPORT = "%%TRANSPORT%%"
Const SESSION_PATH  = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

' Optional fill for the ECC6 "Create Object Directory Entry" (SAPLSTRD) popup
' raised by the SE38 SAPL<FG> self-cascade fallback below. Empty => accept SAP's
' pre-filled package / Local Object; OBJDIR_LANG is the 1-char original language
' used only when filling an empty package field.
Dim OBJDIR_PKG  : OBJDIR_PKG  = "%%PACKAGE%%"
Dim OBJDIR_LANG : OBJDIR_LANG = "%%ORIG_LANG%%"
If Left(OBJDIR_PKG, 2)  = Chr(37) & Chr(37) Then OBJDIR_PKG  = ""
If Left(OBJDIR_LANG, 2) = Chr(37) & Chr(37) Then OBJDIR_LANG = ""
If OBJDIR_LANG = "" Then OBJDIR_LANG = "E"

Const VKEY_ENTER = 0
Const VKEY_F3    = 3
Const VKEY_F15   = 15  ' Exit transaction

' Include shared helpers (attach first; session-lock's pre-unlock sweep
' reads from oSession).
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()

' Shared post-delete popup walker (same dir as the attach lib) -- used by the
' SE38 SAPL<FG> self-cascade fallback (DeleteFgViaSe38) below.
Dim oDpFso, sDpDir
Set oDpFso = CreateObject("Scripting.FileSystemObject")
sDpDir = oDpFso.GetParentFolderName("%%ATTACH_LIB_VBS%%")
ExecuteGlobal oDpFso.OpenTextFile(oDpFso.BuildPath(sDpDir, "sap_delete_popups.vbs"), 1).ReadAll()

' ------ Attach to existing SAP GUI session (via shared attach helper) -------
Dim oSess
Set oSess = AttachSapSession(SESSION_PATH)
WScript.Echo "INFO: Session acquired."

' --- 1. Navigate to SE80 (Object Navigator) --------------------------------
WScript.Echo "INFO: Navigating to SE80 to delete function group " & UCase(FUGR_ID) & "..."
oSess.findById("wnd[0]").maximize
oSess.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE80"
oSess.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1500

' Locate the type/name HTML control. The recording uses
'   wnd[0]/shellcont/shell/shellcont[3]/shell/shellcont[0]/shell/shellcont[1]/shell
' but the shellcont indices depend on SE80's currently-open splitter layout.
' Walk a small fan of common paths and use the first one that responds.
Dim sTypeShellPath
Dim aTry : aTry = Array( _
    "wnd[0]/shellcont/shell/shellcont[3]/shell/shellcont[0]/shell/shellcont[1]/shell", _
    "wnd[0]/shellcont/shell/shellcont[2]/shell/shellcont[0]/shell/shellcont[1]/shell", _
    "wnd[0]/shellcont/shell/shellcont[1]/shell/shellcont[0]/shell/shellcont[1]/shell" _
)
Dim oTypeShell, iTry
Set oTypeShell = Nothing
For iTry = 0 To UBound(aTry)
    On Error Resume Next
    Set oTypeShell = oSess.findById(aTry(iTry))
    If Err.Number = 0 And Not (oTypeShell Is Nothing) Then
        sTypeShellPath = aTry(iTry)
        Err.Clear
        Exit For
    End If
    Err.Clear
    Set oTypeShell = Nothing
Next
On Error GoTo 0

If oTypeShell Is Nothing Then
    ' Classic / ECC6 SE80 has no HTML type/name control. This is NOT a terminal
    ' failure -- self-cascade to the SE38 SAPL<FG> delete (deleting the
    ' function-pool program cascades the FG delete on ECC6).
    WScript.Echo "INFO: SE80 type/name control not found (classic/ECC6 navigator); using SE38 SAPL<FG> fallback."
    WScript.Quit DeleteFgViaSe38(oSess, FUGR_ID, SAP_TRANSPORT, OBJDIR_PKG, OBJDIR_LANG)
End If
WScript.Echo "INFO: SE80 type/name control: " & sTypeShellPath

' --- 2. Select Function Group type + enter FG name -------------------------
' The recording's second sapEvent (line 20) submits type=F + name=<FG> with
' Enter. We replicate it directly -- the first sapEvent (TYPE_SELECTION) and
' the SUGGEST event are only relevant when the operator is typing
' interactively and can be skipped.
Dim sSubmitEvent
sSubmitEvent = "sapbu_cl= &sapse_cl= &sapin_cl=A1F1I2NAME:TYPE_NAMEsapENTER&A1F1S1=F&A1F1I2=" & UCase(FUGR_ID) & "&A1F1S4=WA"

On Error Resume Next
oTypeShell.sapEvent "Frame0", sSubmitEvent, "sapevent:A1F1"
If Err.Number <> 0 Then
    WScript.Echo "ERROR: SE80 sapEvent(A1F1) failed: " & Err.Description
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0
WScript.Sleep 2000

' --- 3. Lock the session for the delete + popup-confirm critical section ---
Dim wasLocked : wasLocked = TryLockSession(oSess)
If wasLocked Then
    WScript.Echo "INFO: Session UI locked for the delete + popup-confirm critical section."
Else
    WScript.Echo "INFO: LockSessionUI not available; continuing without lock."
End If

' --- 4. Locate the repository tree, select root node, open context menu ----
Dim sTreeShellPath, aTreeTry, oTreeShell
aTreeTry = Array( _
    "wnd[0]/shellcont/shell/shellcont[3]/shell/shellcont[2]/shell", _
    "wnd[0]/shellcont/shell/shellcont[2]/shell/shellcont[2]/shell", _
    "wnd[0]/shellcont/shell/shellcont[1]/shell/shellcont[2]/shell" _
)
Set oTreeShell = Nothing
For iTry = 0 To UBound(aTreeTry)
    On Error Resume Next
    Set oTreeShell = oSess.findById(aTreeTry(iTry))
    If Err.Number = 0 And Not (oTreeShell Is Nothing) Then
        sTreeShellPath = aTreeTry(iTry)
        Err.Clear
        Exit For
    End If
    Err.Clear
    Set oTreeShell = Nothing
Next
On Error GoTo 0

If oTreeShell Is Nothing Then
    ' SE80 loaded the type control but not the repository tree (classic/partial
    ' navigator). Fall through to the SE38 SAPL<FG> delete too. Release the lock
    ' first -- DeleteFgViaSe38 takes its own.
    WScript.Echo "INFO: SE80 repository tree not found; using SE38 SAPL<FG> fallback."
    ReleaseSession oSess, wasLocked
    WScript.Quit DeleteFgViaSe38(oSess, FUGR_ID, SAP_TRANSPORT, OBJDIR_PKG, OBJDIR_LANG)
End If
WScript.Echo "INFO: SE80 repository tree: " & sTreeShellPath

' Root node key from the recording. SE80 numbers the tree from "          1"
' (10 leading spaces + "1") for the top-level object header -- language- and
' release-independent.
Const ROOT_NODE = "          1"
On Error Resume Next
oTreeShell.selectNode ROOT_NODE
If Err.Number <> 0 Then
    WScript.Echo "ERROR: Could not select SE80 tree root node '" & ROOT_NODE & "': " & Err.Description
    WScript.Echo "       The function group likely does not exist, or SE80 failed to load it."
    ReleaseSession oSess, wasLocked
    WScript.Quit 1
End If
Err.Clear
oTreeShell.nodeContextMenu ROOT_NODE
oTreeShell.selectContextMenuItem "WB_DELETE"
If Err.Number <> 0 Then
    WScript.Echo "ERROR: Could not trigger WB_DELETE on tree node: " & Err.Description
    ReleaseSession oSess, wasLocked
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0
WScript.Sleep 2000

' --- 5. Walk the post-delete popup chain -----------------------------------
' Observed sequence on S/4HANA 1909:
'   wnd[1] = "Delete Function Group: Delete Function Module" -- lists the
'              dependent FMs (e.g. Z_HKFM_TEST007) and offers Delete /
'              Cancel. Press Continue (tbar[0]/btn[0]) to confirm.
'   wnd[2] = either the TR-prompt popup (ctxtKO008-TRKORR) or a second
'              "really delete?" confirmation. Press Continue (btn[0])
'              after filling TR if needed.
'   Then sbar reports the deletion result.
'
' On systems with non-EN install master language, the SAPLSETX
' "Different original and logon languages" info popup can interleave
' anywhere in this chain. Handle it generically.
Dim iPop, sActWnd, sActPrefix, posWnd
For iPop = 1 To 8
    sActWnd = ""
    On Error Resume Next
    sActWnd = oSess.ActiveWindow.Id
    On Error GoTo 0
    If sActWnd = "" Then Exit For
    If Right(sActWnd, 6) = "wnd[0]" Then Exit For

    posWnd = InStrRev(sActWnd, "/wnd[")
    If posWnd > 0 Then
        sActPrefix = Mid(sActWnd, posWnd + 1)
    Else
        sActPrefix = "wnd[1]"
    End If

    ' (a) SAPLSETX "Different original and logon languages" popup
    Dim bSetxHandled : bSetxHandled = False
    On Error Resume Next
    Dim oML : Set oML = Nothing
    Set oML = oSess.findById(sActPrefix & "/usr/ctxtRSETX-MASTERLANG")
    If Err.Number = 0 And Not (oML Is Nothing) Then
        Dim oMaintBtn : Set oMaintBtn = Nothing
        Set oMaintBtn = oSess.findById(sActPrefix & "/usr/btnPUSH1")
        If Err.Number = 0 And Not (oMaintBtn Is Nothing) Then
            WScript.Echo "INFO: SAPLSETX original-language popup on " & sActPrefix & _
                         " (MASTERLANG=" & oML.Text & ") - pressing 'Maint. in orig. lang.'..."
            oMaintBtn.press
            WScript.Sleep 1500
            bSetxHandled = True
        End If
    End If
    Err.Clear
    On Error GoTo 0
    If bSetxHandled Then
        ' Loop to re-evaluate the active window.
    Else

    ' (b) TR-prompt popup
    On Error Resume Next
    Dim oTr : Set oTr = Nothing
    Set oTr = oSess.findById(sActPrefix & "/usr/ctxtKO008-TRKORR")
    If Err.Number = 0 And Not (oTr Is Nothing) Then
        If SAP_TRANSPORT = "" Then
            WScript.Echo "ERROR: SAP prompted for a transport request but TRANSPORT is empty."
            WScript.Echo "       Resolve a TR via /sap-transport-request and re-run."
            ReleaseSession oSess, wasLocked
            WScript.Quit 1
        End If
        WScript.Echo "INFO: Filling transport " & SAP_TRANSPORT & " on " & sActPrefix & "..."
        oTr.Text = SAP_TRANSPORT
        oSess.findById(sActPrefix).sendVKey VKEY_ENTER
        WScript.Sleep 1500
        Err.Clear
    Else
        ' (c) Generic confirmation popup -- press the dialog's primary
        ' toolbar button (tbar[0]/btn[0] = Continue/Enter). This is the
        ' "Delete Function Group: Delete Function Module" dialog from the
        ' SE80 recording, which exposes only that button.
        Err.Clear
        Dim oCont : Set oCont = Nothing
        Set oCont = oSess.findById(sActPrefix & "/tbar[0]/btn[0]")
        If Err.Number = 0 And Not (oCont Is Nothing) Then
            WScript.Echo "INFO: Confirming popup " & iPop & " on " & sActPrefix & " (tbar[0]/btn[0])..."
            oCont.press
            WScript.Sleep 1500
            Err.Clear
        Else
            ' (d) Last-resort: Yes/Option1 button used by old SAPGUI info popups.
            Err.Clear
            Dim oYes : Set oYes = Nothing
            Set oYes = oSess.findById(sActPrefix & "/usr/btnSPOP-OPTION1")
            If Err.Number = 0 And Not (oYes Is Nothing) Then
                WScript.Echo "INFO: Confirming popup " & iPop & " on " & sActPrefix & " (btnSPOP-OPTION1)..."
                oYes.press
                WScript.Sleep 1500
                Err.Clear
            Else
                Err.Clear
                WScript.Echo "INFO: Confirming popup " & iPop & " on " & sActPrefix & " (Enter)..."
                oSess.findById(sActPrefix).sendVKey VKEY_ENTER
                WScript.Sleep 1500
                Err.Clear
            End If
        End If
        On Error GoTo 0
    End If
    End If  ' bSetxHandled dispatch
Next

If iPop > 8 Then
    WScript.Echo "WARN: Popup loop hit cap; SAP may have left a modal on screen."
End If

' --- 6. Capture status bar then back out of SE80 ---------------------------
Dim sFinalMsg, sFinalType
On Error Resume Next
sFinalMsg  = oSess.findById("wnd[0]/sbar").Text
sFinalType = oSess.findById("wnd[0]/sbar").MessageType
On Error GoTo 0
WScript.Echo "INFO: SAP status: [" & sFinalType & "] " & sFinalMsg

ReleaseSession oSess, wasLocked
If wasLocked Then WScript.Echo "INFO: Session UI lock released."

' Exit SE80 cleanly so the operator inherits a usable session.
On Error Resume Next
oSess.findById("wnd[0]/tbar[0]/btn[15]").press
WScript.Sleep 500
' If a "data was changed; save?" popup appears, decline (No / btnSPOP-OPTION2).
If InStr(oSess.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSess.findById("wnd[1]/usr/btnSPOP-OPTION2").press
    WScript.Sleep 500
End If
Err.Clear
On Error GoTo 0

' --- 7. Decide success / failure based on the status bar -------------------
' Caller is expected to follow this with an RFC verification step
' (TLIBG zero rows, TFDIR zero rows for SAPL<FUGR>) -- see SKILL.md Step 3e.
If sFinalType = "E" Or sFinalType = "A" Then
    WScript.Echo "ERROR: Delete failed with sbar [" & sFinalType & "] " & sFinalMsg
    WScript.Quit 1
End If

' The SE80 WB_DELETE path has no positive success signal of its own -- it relies
' on the caller's RFC verification (SKILL.md Step 3e). If the popup loop hit its
' cap, modals were left unresolved and the delete almost certainly did NOT
' complete (e.g. a $TMP/local FG whose WB_DELETE dialog this inline walker can't
' clear -- observed on S4D 2026-06-22, where it left TLIBG=1 yet sbar was empty).
' Do NOT claim SUCCESS on a cap-hit: report INCOMPLETE so the RFC verify is the
' decider and a skill-bypassing caller is not handed a false SUCCESS.
If iPop > 8 Then
    WScript.Echo "ERROR: SE80 popup loop hit cap -- FG delete likely INCOMPLETE; verify via RFC (TLIBG/TFDIR for SAPL" & UCase(FUGR_ID) & "). For a classic/$TMP layout, the SE38 SAPL<FG> path (this VBS's ECC6 self-cascade) is more robust."
    WScript.Quit 1
End If

WScript.Echo "SUCCESS: Function group " & UCase(FUGR_ID) & " deleted."
WScript.Quit 0

' ===========================================================================
' DeleteFgViaSe38 -- ECC6 / classic-navigator self-cascade fallback.
'
' Deletes the function-pool program SAPL<FG> via SE38 (Shift+F2 = sendVKey 14),
' which cascades the function-group delete on ECC6. Mirrors sap_se38_delete.vbs
' and reuses the shared WalkDeletePopups for the confirm / SAPLSETX / KO007 / TR
' chain. Takes its OWN session lock. Returns 0 on success, 1 on error. RFC
' verification of removal is the caller's job (SKILL.md Step 3e).
' ===========================================================================
Function DeleteFgViaSe38(oS, sFugr, sTransport, sObjdirPkg, sObjdirLang)
    DeleteFgViaSe38 = 1
    Dim sProg : sProg = "SAPL" & UCase(sFugr)
    WScript.Echo "INFO: SE38 fallback -- deleting function-pool program " & sProg & "..."

    oS.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE38"
    oS.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 1000

    On Error Resume Next
    oS.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM").Text = sProg
    oS.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM").caretPosition = Len(sProg)
    If Err.Number <> 0 Then
        WScript.Echo "ERROR: SE38 program-name field not found (ctxtRS38M-PROGRAMM): " & Err.Description
        Exit Function
    End If
    Err.Clear
    On Error GoTo 0

    Dim wlSe38 : wlSe38 = TryLockSession(oS)

    WScript.Echo "INFO: Pressing Delete (Shift+F2) in SE38..."
    On Error Resume Next
    oS.findById("wnd[0]").sendVKey 14
    WScript.Sleep 1500
    If Err.Number <> 0 Then
        WScript.Echo "ERROR: SE38 Shift+F2 (delete) failed: " & Err.Description
        ReleaseSession oS, wlSe38
        Exit Function
    End If
    Err.Clear
    On Error GoTo 0

    Dim dr : dr = WalkDeletePopups(oS, sObjdirPkg, sObjdirLang, sTransport)
    If dr = "ABORT_EMPTY_TR" Then
        WScript.Echo "ERROR: SAP prompted for a transport request but TRANSPORT is empty."
        WScript.Echo "       Resolve a TR via /sap-transport-request and re-run."
        ReleaseSession oS, wlSe38
        Exit Function
    End If

    ' Verify via Display: if the program-name field survives (Display stayed on
    ' the SE38 initial screen) the program is gone; if it vanished (Display
    ' opened the editor) the program still exists.
    WScript.Echo "INFO: Verifying deletion (try Display)..."
    On Error Resume Next
    oS.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM").Text = sProg
    oS.findById("wnd[0]/usr/btnSHOP").press
    WScript.Sleep 1500
    On Error GoTo 0

    Dim sMsg, sTyp
    On Error Resume Next
    sMsg = oS.findById("wnd[0]/sbar").Text
    sTyp = oS.findById("wnd[0]/sbar").MessageType
    On Error GoTo 0

    ReleaseSession oS, wlSe38

    Dim oNF : Set oNF = Nothing
    On Error Resume Next
    Set oNF = oS.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM")
    Dim bThere : bThere = (Err.Number = 0) And Not (oNF Is Nothing)
    Err.Clear
    On Error GoTo 0

    If Not bThere Then
        WScript.Echo "ERROR: " & sProg & " still exists after SE38 delete (Display opened the editor). sbar=[" & sTyp & "] " & sMsg
        oS.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE38"
        oS.findById("wnd[0]").sendVKey VKEY_ENTER
        Exit Function
    End If

    WScript.Echo "INFO: SAP status: [" & sTyp & "] " & sMsg
    WScript.Echo "SUCCESS: Function group " & UCase(sFugr) & " deleted (via SE38 " & sProg & " fallback)."
    DeleteFgViaSe38 = 0
End Function
