' =============================================================================
' sap_se54_check.vbs  -  SAP GUI Scripting: Check if table maintenance dialog exists
'
' Generated by the sap-se54 skill.
' Attaches to an existing SAP GUI session, navigates to SE54,
' selects "Generated Objects" and presses Create/Change.
' If a "Create maintenance module" popup appears, the dialog does NOT exist.
' If it goes directly to the Generation Environment screen, it EXISTS.
'
' Output: "EXIST" or "NOT_EXIST" (last line of stdout, parseable by skill).
'
' Tokens replaced at run time:
'   %%TABLE_NAME%%  Table or view name  e.g. "ZHKTBTEST005"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const TABLE_NAME   = "%%TABLE_NAME%%"
Const SESSION_PATH = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default
Const VKEY_ENTER   = 0

ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SE54 -------------------------------------------------
WScript.Echo "INFO: Navigating to SE54..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE54"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Enter table name, select Generated Objects, press Create/Change --
WScript.Echo "INFO: Checking table maintenance dialog for: " & UCase(TABLE_NAME)
oSession.findById("wnd[0]/usr/txtVIMDYNFLDS-VIEWNAME").Text = UCase(TABLE_NAME)
oSession.findById("wnd[0]/usr/radVIMDYNFLDS-ELEM_GEN").Select
oSession.findById("wnd[0]/usr/btnVIMDYNFLDS-PUSH_GMNT").Press
WScript.Sleep 1000

' ------ 4. Determine result -------------------------------------------------
' If dialog does NOT exist: wnd[1] popup "Create maintenance module" appears.
' If dialog EXISTS: goes directly to Generation Environment screen (no popup).
On Error Resume Next
Dim oPopup
Set oPopup = oSession.findById("wnd[1]")
Dim bPopup
bPopup = (Err.Number = 0) And Not (oPopup Is Nothing)
Err.Clear
On Error GoTo 0

If bPopup Then
    ' Popup appeared -> dialog does NOT exist
    WScript.Echo "INFO: Table " & UCase(TABLE_NAME) & " has no maintenance dialog."
    ' Press Cancel to go back
    oSession.findById("wnd[1]/usr/btnSPOP-OPTION_CAN").Press
    WScript.Sleep 500
    WScript.Echo "NOT_EXIST"
Else
    ' No popup -> went to Generation Environment -> dialog EXISTS.
    ' Confirm the screen by a control that exists ONLY there (the auth-group
    ' field ctxtTDDAT-CCLASS) -- locale-independent, no title text.
    On Error Resume Next
    Dim oGenEnvProbe
    Set oGenEnvProbe = Nothing
    Set oGenEnvProbe = oSession.findById("wnd[0]/usr/ctxtTDDAT-CCLASS")
    Dim bOnGenEnv
    bOnGenEnv = (Err.Number = 0) And Not (oGenEnvProbe Is Nothing)
    Err.Clear
    On Error GoTo 0
    If bOnGenEnv Then
        WScript.Echo "INFO: Table " & UCase(TABLE_NAME) & " has an existing maintenance dialog."
        ' Navigate back to SE54 initial screen
        oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE54"
        oSession.findById("wnd[0]").sendVKey VKEY_ENTER
        WScript.Sleep 500
        WScript.Echo "EXIST"
    Else
        ' Unexpected screen
        Dim sStatus
        sStatus = oSession.findById("wnd[0]/sbar").Text
        WScript.Echo "ERROR: Unexpected screen after Create/Change. Status: " & sStatus
        WScript.Quit 1
    End If
End If

WScript.Quit 0
