' =============================================================================
' sap_se54_generate.vbs  -  SAP GUI Scripting: Generate table maintenance dialog
'
' Generated by the sap-se54 skill.
' Attaches to an existing SAP GUI session, navigates to SE54, enters the
' table name, selects "Generated Objects", presses Create/Change, fills in
' generation parameters, and presses Create (F6) to generate the dialog.
'
' Tokens replaced at run time:
'   %%TABLE_NAME%%       Table or view name            e.g. "ZHKTBTEST005"
'   %%AUTH_GROUP%%        Authorization group           e.g. "&NC&"
'   %%FUNC_GROUP%%       Function group for generated code  e.g. "ZHKT05"
'   %%MAINT_TYPE%%       1 = one step, 2 = two step    e.g. "1"
'   %%OVERVIEW_SCREEN%%  Overview screen number         e.g. "0010"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909 (S4D).
' =============================================================================

Option Explicit

Const TABLE_NAME      = "%%TABLE_NAME%%"
Const AUTH_GROUP      = "%%AUTH_GROUP%%"
Const FUNC_GROUP      = "%%FUNC_GROUP%%"
Const MAINT_TYPE      = "%%MAINT_TYPE%%"
Const OVERVIEW_SCREEN = "%%OVERVIEW_SCREEN%%"
Const SESSION_PATH    = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER = 0
Const VKEY_F6    = 6

' Include shared attach helper.
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SE54 -------------------------------------------------
WScript.Echo "INFO: Navigating to SE54..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE54"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Enter table name, select Generated Objects, press Create/Change --
WScript.Echo "INFO: Generating maintenance dialog for: " & UCase(TABLE_NAME)
oSession.findById("wnd[0]/usr/txtVIMDYNFLDS-VIEWNAME").Text = UCase(TABLE_NAME)
oSession.findById("wnd[0]/usr/radVIMDYNFLDS-ELEM_GEN").Select
oSession.findById("wnd[0]/usr/btnVIMDYNFLDS-PUSH_GMNT").Press
WScript.Sleep 1000

' ------ 4. Handle "Create maintenance module" popup -------------------------
' This popup appears when no maintenance dialog exists for the table.
On Error Resume Next
Dim oPopup
Set oPopup = oSession.findById("wnd[1]")
Dim bPopup
bPopup = (Err.Number = 0) And Not (oPopup Is Nothing)
Err.Clear
On Error GoTo 0

If bPopup Then
    If InStr(oSession.findById("wnd[1]").Text, "Create maintenance module") > 0 Then
        WScript.Echo "INFO: No existing dialog found. Pressing Yes to create..."
        oSession.findById("wnd[1]/usr/btnSPOP-OPTION1").Press
        WScript.Sleep 1000
    Else
        WScript.Echo "ERROR: Unexpected popup: " & oSession.findById("wnd[1]").Text
        WScript.Quit 1
    End If
End If

' ------ 5. Verify we are on the Generation Environment screen ---------------
If InStr(oSession.findById("wnd[0]").Text, "Generation Environment") = 0 Then
    Dim sStatus
    On Error Resume Next
    sStatus = oSession.findById("wnd[0]/sbar").Text
    On Error GoTo 0
    WScript.Echo "ERROR: Not on Generation Environment screen. Status: " & sStatus
    WScript.Quit 1
End If
WScript.Echo "INFO: On Generation Environment screen."

' ------ 6. Fill generation parameters ---------------------------------------
oSession.findById("wnd[0]/usr/ctxtTDDAT-CCLASS").Text = AUTH_GROUP
oSession.findById("wnd[0]/usr/ctxtTVDIR-AREA").Text = FUNC_GROUP

If MAINT_TYPE = "1" Then
    oSession.findById("wnd[0]/usr/radVIMDYNFLDS-MTYPE1").Select
Else
    oSession.findById("wnd[0]/usr/radVIMDYNFLDS-MTYPE2").Select
End If

oSession.findById("wnd[0]/usr/txtTVDIR-LISTE").Text = OVERVIEW_SCREEN
oSession.findById("wnd[0]/usr/radVIMDYNFLDS-CORR_CON_S").Select

WScript.Echo "INFO: Parameters set - Auth:" & AUTH_GROUP & " FG:" & FUNC_GROUP & _
             " Type:" & MAINT_TYPE & " Screen:" & OVERVIEW_SCREEN

' ------ 7. Press Create (F6) to generate -----------------------------------
WScript.Echo "INFO: Pressing Create (F6)..."
oSession.findById("wnd[0]").sendVKey VKEY_F6
WScript.Sleep 3000

' ------ 8. Handle Object Directory Entry popups -----------------------------
' SAP may show multiple "Change Object Directory Entry" popups for FUGR and TOBJ.
' Save each one with the default package ($TMP).
Dim iLoop
For iLoop = 1 To 10
    On Error Resume Next
    Dim oW1
    Set oW1 = oSession.findById("wnd[1]")
    Dim bW1
    bW1 = (Err.Number = 0) And Not (oW1 Is Nothing)
    Err.Clear
    On Error GoTo 0

    If Not bW1 Then Exit For

    If InStr(oSession.findById("wnd[1]").Text, "Object Directory") > 0 Then
        On Error Resume Next
        Dim sObjName
        sObjName = oSession.findById("wnd[1]/usr/txtKO007-L_OBJ_NAME").Text
        On Error GoTo 0
        WScript.Echo "INFO: Saving Object Directory Entry for: " & sObjName
        oSession.findById("wnd[1]/tbar[0]/btn[0]").Press
        WScript.Sleep 2000
    ElseIf InStr(oSession.findById("wnd[1]").Text, "Prompt for") > 0 Or _
           InStr(oSession.findById("wnd[1]").Text, "Workbench") > 0 Or _
           InStr(oSession.findById("wnd[1]").Text, "Transport") > 0 Then
        ' Transport request popup - press Local Object or Enter
        WScript.Echo "INFO: Transport dialog - assigning to Local Object..."
        On Error Resume Next
        oSession.findById("wnd[1]/tbar[0]/btn[7]").Press
        If Err.Number <> 0 Then
            Err.Clear
            oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        End If
        On Error GoTo 0
        WScript.Sleep 2000
    Else
        WScript.Echo "WARNING: Unexpected popup: " & oSession.findById("wnd[1]").Text
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1000
    End If
Next

' ------ 9. Final status check -----------------------------------------------
Dim sFinalMsg, sFinalType
On Error Resume Next
sFinalMsg  = oSession.findById("wnd[0]/sbar").Text
sFinalType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

If sFinalType = "E" Then
    WScript.Echo "ERROR: Generation failed - " & sFinalMsg
    WScript.Quit 1
End If

WScript.Echo "INFO: SAP status: " & sFinalMsg
WScript.Echo "SUCCESS: Table maintenance dialog generated for " & UCase(TABLE_NAME) & "."
WScript.Quit 0
