' =============================================================================
' sap_se38_change_attrs.vbs  -  SAP GUI Scripting: Change SE38 program ATTRIBUTES
'
' Generated by the sap-se38 skill.
' Attaches to an existing SAP GUI session, opens the program in the SOURCE
' EDITOR in change mode (Source Code radio + Change), opens Attributes via
' Goto -> Attributes, updates Title / Status / Type, then PERSISTS the change
' by Saving the program object in the editor and Activating it so the active
' title / text-pool reflects the new value.
'
' Why the editor path (fixed 2026-06-07): the older "Attributes radio
' (FUNC_HEAD) + Change -> dialog -> Continue" path was a FALSE SUCCESS - the
' dialog Continue returns to the SE38 INITIAL screen, where Save is "virtual
' key not enabled", so the change is staged in memory and NEVER written to the
' DB. Verified on S/4HANA 1909: both a ZH title and a plain-ASCII probe left
' TRDIRT unchanged after a reported SUCCESS. The fix opens the editor first so
' the editor Save (Ctrl+S, VKey 11) persists the program object; Activate
' (Ctrl+F3, VKey 27) then syncs the active text-pool 'R' title (the runtime
' list header). RFC-verified clean.
'
' Tokens replaced at run time:
'   %%PROGRAM_NAME%%   ABAP program name        e.g. "ZHKTEST003"
'   %%TITLE%%          New title (max 70 chars). Empty = leave unchanged.
'   %%STATUS%%         New program status code. Empty = leave unchanged.
'                      Common codes (TRDIR-RSTAT):
'                        P = SAP Standard Production Program
'                        K = Customer Production Program
'                        S = System Program
'                        T = Test Program
'                        X = SAP Example Program
'   %%TYPE%%           New program type. Empty = leave unchanged.
'                      TRDIR-SUBC codes:
'                        1 = Executable program
'                        I = Include
'                        M = Module pool
'                        F = Function group
'                        K = Class definition
'                        S = Subroutine pool
'                        J = Interface pool
'   %%TRANSPORT%%      Transport request for the post-save / post-activate TR
'                      popup. Empty when the object is local ($TMP) or already
'                      locked to a modifiable TR. If SAP prompts for a TR and
'                      this is empty, the script aborts.
'
' Recorded baseline (S/4HANA 1909, re-record if the layout differs):
'   /nse38 -> radRS38M-FUNC_EDIT -> ctxtRS38M-PROGRAMM -> btnCHAP  (editor, change)
'   [optional wnd[1] SAPLSETX original-language popup -> btnPUSH1]
'   Goto -> Attributes : wnd[0]/mbar/menu[2]/menu[0]   (Goto is the 3rd top-level
'                        menu, Attributes its 1st item - positional + language-
'                        neutral; re-record with /sap-gui-record if it moves)
'   wnd[1]/usr/txtRS38M-REPTI = title ; cmbTRDIR-RSTAT.key ; cmbTRDIR-SUBC.key
'   wnd[1]/tbar[0]/btn[0]      (Continue -> back to editor)
'   wnd[0] sendVKey 11         (Save)     [optional TR popup -> ctxtKO008-TRKORR]
'   wnd[0] sendVKey 27         (Activate) [optional TR / inactive-objects popup]
' =============================================================================

Option Explicit

Const PROGRAM_NAME  = "%%PROGRAM_NAME%%"
Const NEW_TITLE     = "%%TITLE%%"
Const NEW_STATUS    = "%%STATUS%%"
Const NEW_TYPE      = "%%TYPE%%"
Const SAP_TRANSPORT = "%%TRANSPORT%%"
Const SESSION_PATH  = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER    = 0
Const VKEY_SAVE     = 11
Const VKEY_ACTIVATE = 27
Const VKEY_CANCEL   = 12

' Goto -> Attributes menu (positional: Goto = 3rd top-level menu, Attributes =
' its 1st item). Language-neutral on S/4HANA 1909; re-record if it moves.
Const MENU_GOTO_ATTRS = "wnd[0]/mbar/menu[2]/menu[0]"

' Include shared helpers. Order matters: attach lib first so session-lock's
' pre-unlock popup sweep has a resolved session reference to read from.
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()

' --- Helper: dismiss the conditional SAPLSETX original-language popup. -------
' Appears at the first change action when logon language <> TADIR-MASTERLANG.
' Presses btnPUSH1 ("Maint. in orig. lang.") so MASTERLANG is preserved. Only
' acts when the MASTERLANG field is present (so it ignores other wnd[1] popups).
Sub HandleOrigLangPopup(oSess)
    On Error Resume Next
    If InStr(oSess.ActiveWindow.Id, "wnd[1]") > 0 Then
        Dim oMasterLang : Set oMasterLang = Nothing
        Err.Clear
        Set oMasterLang = oSess.findById("wnd[1]/usr/ctxtRSETX-MASTERLANG")
        If Err.Number = 0 And Not (oMasterLang Is Nothing) Then
            Dim oMaintBtn : Set oMaintBtn = Nothing
            Err.Clear
            Set oMaintBtn = oSess.findById("wnd[1]/usr/btnPUSH1")
            If Err.Number = 0 And Not (oMaintBtn Is Nothing) Then
                WScript.Echo "INFO: Original-language popup (MASTERLANG=" & _
                             oMasterLang.Text & ") - pressing 'Maint. in orig. lang.'."
                oMaintBtn.press
                WScript.Sleep 1500
            End If
        End If
    End If
    Err.Clear
    On Error GoTo 0
End Sub

' --- Helper: drain up to nMax modal popups after Save / Activate. ------------
' Fills a TR popup (ctxtKO008-TRKORR, language-neutral) with SAP_TRANSPORT;
' aborts on an Error / locked popup; presses Enter on anything else (the
' inactive-objects worklist, informational popups). Returns "" on OK, else a
' blocking-popup message.
Function DrainPopups(oSess, nMax)
    DrainPopups = ""
    Dim i
    For i = 1 To nMax
        If InStr(oSess.ActiveWindow.Id, "wnd[1]") = 0 Then Exit Function
        On Error Resume Next
        Dim oTr : Set oTr = Nothing
        Err.Clear
        Set oTr = oSess.findById("wnd[1]/usr/ctxtKO008-TRKORR")
        If Err.Number = 0 And Not (oTr Is Nothing) Then
            If SAP_TRANSPORT = "" Then
                oSess.findById("wnd[1]").sendVKey VKEY_CANCEL
                DrainPopups = "SAP prompted for a transport request but TRANSPORT is empty. Resolve a modifiable TR via /sap-transport-request and re-run."
                Err.Clear : On Error GoTo 0
                Exit Function
            End If
            oTr.Text = SAP_TRANSPORT
            oSess.findById("wnd[1]").sendVKey VKEY_ENTER
            WScript.Echo "INFO: TR popup - entering " & SAP_TRANSPORT & "."
        Else
            Dim sTitle, oM1, oM2, sM1, sM2
            sTitle = oSess.ActiveWindow.Text
            sM1 = "" : sM2 = ""
            Err.Clear
            Set oM1 = oSess.findById("wnd[1]/usr/txtMESSTXT1")
            If Err.Number = 0 And Not (oM1 Is Nothing) Then sM1 = oM1.Text
            Err.Clear
            Set oM2 = oSess.findById("wnd[1]/usr/txtMESSTXT2")
            If Err.Number = 0 And Not (oM2 Is Nothing) Then sM2 = oM2.Text
            Err.Clear
            If InStr(LCase(sM1 & " " & sM2), "locked") > 0 Then
                oSess.findById("wnd[1]").sendVKey VKEY_CANCEL
                DrainPopups = "SAP popup [" & sTitle & "] " & Trim(sM1 & " " & sM2)
                Err.Clear : On Error GoTo 0
                Exit Function
            End If
            WScript.Echo "INFO: Confirming popup [" & sTitle & "] - pressing Enter."
            oSess.ActiveWindow.sendVKey VKEY_ENTER
        End If
        Err.Clear
        On Error GoTo 0
        WScript.Sleep 1000
    Next
End Function

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SE38 -------------------------------------------------
WScript.Echo "INFO: Navigating to SE38..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE38"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000
Err.Clear
On Error GoTo 0

' --- Lock the SAP session UI for the change + save critical section ---
Dim wasLocked : wasLocked = TryLockSession(oSession)
If wasLocked Then
    WScript.Echo "INFO: Session UI locked for the attribute change + save critical section."
Else
    WScript.Echo "INFO: LockSessionUI not available on this SAP GUI build; continuing without lock."
End If

' ------ 3. Open the program in the SOURCE EDITOR (change mode) --------------
' Attributes are reached FROM the editor (Goto -> Attributes) so the editor
' Save persists the program object. The Attributes-radio path does NOT persist.
On Error Resume Next
Dim oProgField, oRadioEdit
Set oRadioEdit = oSession.findById("wnd[0]/usr/radRS38M-FUNC_EDIT")
If Err.Number <> 0 Or oRadioEdit Is Nothing Then
    WScript.Echo "ERROR: SE38 Source Code radio not found (wnd[0]/usr/radRS38M-FUNC_EDIT)."
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If
oRadioEdit.select
Err.Clear

Set oProgField = oSession.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM")
If Err.Number <> 0 Or oProgField Is Nothing Then
    WScript.Echo "ERROR: SE38 program-name field not found (wnd[0]/usr/ctxtRS38M-PROGRAMM)."
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If
oProgField.Text = UCase(PROGRAM_NAME)
Err.Clear
On Error GoTo 0

WScript.Echo "INFO: Opening " & UCase(PROGRAM_NAME) & " in the editor (change mode)..."
On Error Resume Next
oSession.findById("wnd[0]/usr/btnCHAP").press
WScript.Sleep 1500
Err.Clear
On Error GoTo 0

' ------ 3a. Original-language popup (conditional) ---------------------------
HandleOrigLangPopup oSession

' ------ 3b. Goto -> Attributes (opens the attributes dialog) ----------------
WScript.Echo "INFO: Goto -> Attributes..."
On Error Resume Next
oSession.findById(MENU_GOTO_ATTRS).select
WScript.Sleep 1500
Err.Clear
On Error GoTo 0
' A second (rare) original-language popup can appear here.
HandleOrigLangPopup oSession

' ------ 4. Verify the Attributes dialog is open -----------------------------
Dim oTitleField, bInAttrDlg
bInAttrDlg = False
On Error Resume Next
Err.Clear
Set oTitleField = oSession.findById("wnd[1]/usr/txtRS38M-REPTI")
If Err.Number = 0 And Not (oTitleField Is Nothing) Then bInAttrDlg = True
Err.Clear
On Error GoTo 0

If Not bInAttrDlg Then
    WScript.Echo "ERROR: Attributes dialog (wnd[1]/usr/txtRS38M-REPTI) did not open." & vbCrLf & _
                 "       Check that the program exists, is not locked by another user," & vbCrLf & _
                 "       and that you have change authorization."
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If
WScript.Echo "INFO: Attributes dialog open."

' ------ 4a. Apply changes (only if value supplied) --------------------------
Dim sChanges
sChanges = ""

If NEW_TITLE <> "" Then
    On Error Resume Next
    oTitleField.Text = NEW_TITLE
    If Err.Number <> 0 Then
        WScript.Echo "ERROR: Could not set title: " & Err.Description
        ReleaseSession oSession, wasLocked
        WScript.Quit 1
    End If
    Err.Clear
    On Error GoTo 0
    sChanges = sChanges & " title='" & NEW_TITLE & "'"
End If

If NEW_STATUS <> "" Then
    On Error Resume Next
    Dim oStatusCmb
    Set oStatusCmb = oSession.findById("wnd[1]/usr/cmbTRDIR-RSTAT")
    If Err.Number = 0 And Not (oStatusCmb Is Nothing) Then
        oStatusCmb.setFocus
        oStatusCmb.Key = NEW_STATUS
        If Err.Number <> 0 Then
            WScript.Echo "ERROR: Invalid status code '" & NEW_STATUS & "': " & Err.Description
            ReleaseSession oSession, wasLocked
            WScript.Quit 1
        End If
        sChanges = sChanges & " status='" & NEW_STATUS & "'"
    Else
        WScript.Echo "ERROR: Status combobox not found (wnd[1]/usr/cmbTRDIR-RSTAT)."
        ReleaseSession oSession, wasLocked
        WScript.Quit 1
    End If
    Err.Clear
    On Error GoTo 0
End If

If NEW_TYPE <> "" Then
    On Error Resume Next
    Dim oTypeCmb
    Set oTypeCmb = oSession.findById("wnd[1]/usr/cmbTRDIR-SUBC")
    If Err.Number = 0 And Not (oTypeCmb Is Nothing) Then
        oTypeCmb.setFocus
        oTypeCmb.Key = NEW_TYPE
        If Err.Number <> 0 Then
            WScript.Echo "ERROR: Invalid type code '" & NEW_TYPE & "': " & Err.Description
            ReleaseSession oSession, wasLocked
            WScript.Quit 1
        End If
        sChanges = sChanges & " type='" & NEW_TYPE & "'"
    Else
        WScript.Echo "ERROR: Type combobox not found (wnd[1]/usr/cmbTRDIR-SUBC)."
        ReleaseSession oSession, wasLocked
        WScript.Quit 1
    End If
    Err.Clear
    On Error GoTo 0
End If

If sChanges = "" Then
    WScript.Echo "INFO: No attribute values supplied - nothing to change."
    On Error Resume Next
    oSession.findById("wnd[1]").sendVKey VKEY_CANCEL   ' cancel the attributes dialog
    WScript.Sleep 600
    ' back out of the editor so the change-mode lock is released
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    Err.Clear
    On Error GoTo 0
    WScript.Echo "DONE: NO_CHANGE"
    ReleaseSession oSession, wasLocked
    WScript.Quit 0
End If

WScript.Echo "INFO: Applying changes:" & sChanges

' ------ 5. Continue dialog -> editor, then SAVE (this is what persists) ------
On Error Resume Next
oSession.findById("wnd[1]/tbar[0]/btn[0]").press   ' Continue -> back to editor
WScript.Sleep 1200
Err.Clear
On Error GoTo 0

On Error Resume Next
oSession.findById("wnd[0]").sendVKey VKEY_SAVE
WScript.Sleep 1500
Err.Clear
On Error GoTo 0

Dim sErr
sErr = DrainPopups(oSession, 4)
If sErr <> "" Then
    WScript.Echo "ERROR: " & sErr
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

Dim sBarType1, sBarText1
On Error Resume Next
sBarText1 = oSession.findById("wnd[0]/sbar").Text
sBarType1 = oSession.findById("wnd[0]/sbar").MessageType
Err.Clear
On Error GoTo 0
WScript.Echo "INFO: After Save sbar [" & sBarType1 & "]: " & sBarText1
If LCase(sBarType1) = "e" Or LCase(sBarType1) = "a" Then
    WScript.Echo "ERROR: Save failed - " & sBarText1
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

' ------ 5a. Activate so the ACTIVE title / text-pool reflects the change -----
' Best-effort: Save already persisted TRDIR/TRDIRT; activation syncs the active
' text-pool 'R' title used in the runtime list header.
On Error Resume Next
oSession.findById("wnd[0]").sendVKey VKEY_ACTIVATE
WScript.Sleep 1800
Err.Clear
On Error GoTo 0

Dim sErr2
sErr2 = DrainPopups(oSession, 5)
If sErr2 <> "" Then
    WScript.Echo "WARN: activation popup issue - " & sErr2 & vbCrLf & _
                 "      The attribute change was saved; re-activate manually if the" & vbCrLf & _
                 "      runtime list-header title still shows the old value."
End If

' --- Release the session UI lock; status bar read is read-only ---
ReleaseSession oSession, wasLocked
If wasLocked Then WScript.Echo "INFO: Session UI lock released."

' ------ 6. Read status bar --------------------------------------------------
Dim sBarText, sBarType
sBarText = "" : sBarType = ""
On Error Resume Next
sBarText = oSession.findById("wnd[0]/sbar").Text
sBarType = oSession.findById("wnd[0]/sbar").MessageType
Err.Clear
On Error GoTo 0
WScript.Echo "INFO: Status bar [" & sBarType & "]: " & sBarText
If LCase(sBarType) = "a" Then
    WScript.Echo "ERROR: Activation aborted - " & sBarText
    WScript.Quit 1
End If

' ------ 7. Back to /n -------------------------------------------------------
On Error Resume Next
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
Err.Clear
On Error GoTo 0

WScript.Echo "SUCCESS: Attributes updated for " & UCase(PROGRAM_NAME) & "."
WScript.Quit 0
