' =============================================================================
' sap_se38_check.vbs  -  SAP GUI Scripting: Check if ABAP program exists
'
' Generated by the sap-se38 skill.
' Attaches to an existing SAP GUI session, opens SE16N on table TRDIR,
' and checks if the specified program name exists.
'
' Output: "EXIST" or "NOT_EXIST" (last line of stdout, parseable by skill).
'
' Tokens replaced at run time:
'   %%PROGRAM_NAME%%  ABAP program name  e.g. "ZMYREPORT"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' If a step fails, use SAP Logon > Help > Scripting Recorder to re-record
' the correct ID for your system.
' =============================================================================

Option Explicit

Const PROGRAM_NAME  = "%%PROGRAM_NAME%%"
Const SESSION_PATH  = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default
Const VKEY_ENTER    = 0
Const VKEY_F8_EXEC  = 8

' Include shared attach helper.
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SE16N and query TRDIR --------------------------------
WScript.Echo "INFO: Navigating to SE16N..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nse16n"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' Enter table name TRDIR
oSession.findById("wnd[0]/usr/ctxtGD-TAB").text = "TRDIR"
oSession.findById("wnd[0]/usr/ctxtGD-TAB").setFocus
oSession.findById("wnd[0]/usr/ctxtGD-TAB").caretPosition = 5
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Enter program name in NAME field (row 0, column 2) ---------------
On Error Resume Next
oSession.findById("wnd[0]/usr/tblSAPLSE16NSELFIELDS_TC/ctxtGS_SELFIELDS-LOW[2,0]").text = UCase(PROGRAM_NAME)
oSession.findById("wnd[0]/usr/tblSAPLSE16NSELFIELDS_TC/ctxtGS_SELFIELDS-LOW[2,0]").setFocus
oSession.findById("wnd[0]/usr/tblSAPLSE16NSELFIELDS_TC/ctxtGS_SELFIELDS-LOW[2,0]").caretPosition = Len(PROGRAM_NAME)
If Err.Number <> 0 Then
    WScript.Echo "ERROR: Could not fill program name in SE16N selection screen." & vbCrLf & _
                 "       Component ID may differ on your system. Use Scripting Recorder."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

' ------ 4. Execute query (F8) -----------------------------------------------
WScript.Echo "INFO: Executing query for program: " & UCase(PROGRAM_NAME)
oSession.findById("wnd[0]/tbar[1]/btn[7]").press
WScript.Sleep 1500

' ------ 5. Check result count ------------------------------------------------
' SE16N may show the result count in a popup (wnd[1]) OR navigate directly to
' the data browser screen. Zero-record systems may show only a status-bar
' message instead of a popup; the structural fallback below covers that case
' without branching on translated text.

On Error Resume Next
Dim sCount
sCount = ""

' Try popup first
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    sCount = oSession.findById("wnd[1]/usr/txtGD-NUMBER").text
    If Err.Number <> 0 Then sCount = "" : Err.Clear
    ' Close the popup
    oSession.findById("wnd[1]/tbar[0]/btn[0]").press
    WScript.Sleep 500
    Err.Clear
End If

' If no popup, decide structurally (locale-independent). The old middle tier
' matched EN-only sbar stems ("no entries" / "0 entries" / "entries"), so
' ZH/JA logons already took the structural path below exclusively -- EN now
' does the same: staying on SAPLSE16N (and not on output screen 200) after
' F8 means zero rows; navigating to the data browser means rows exist.
If sCount = "" Then
    Dim sProgName
    sProgName = oSession.Info.Program
    If Err.Number <> 0 Then sProgName = "" : Err.Clear
    If sProgName <> "" And sProgName <> "SAPLSE16N" Then
        ' Navigated away from SE16N -> likely viewing data -> program exists
        sCount = "1"
    ElseIf oSession.Info.ScreenNumber = 200 Then
        ' Screen 200 = data browser output -> program exists
        sCount = "1"
    Else
        sCount = "0"
    End If
End If
Err.Clear
On Error GoTo 0

' Navigate back to SE16N initial screen
On Error Resume Next
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nse16n"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 500
Err.Clear
On Error GoTo 0

' ------ 6. Output result ----------------------------------------------------
If CInt(sCount) >= 1 Then
    WScript.Echo "INFO: Program " & UCase(PROGRAM_NAME) & " found in TRDIR (count=" & sCount & ")."
    WScript.Echo "EXIST"
Else
    WScript.Echo "INFO: Program " & UCase(PROGRAM_NAME) & " not found in TRDIR."
    WScript.Echo "NOT_EXIST"
End If

WScript.Quit 0
