' =============================================================================
' sap_se38_delete.vbs  -  SAP GUI Scripting: Delete a program via SE38
'
' Generated by the sap-se38 skill (Step 5e).
' Attaches to an existing SAP GUI session, navigates to SE38, fills the
' program-name field, presses Delete (Shift+F2 = sendVKey 14) from the
' initial screen, confirms the deletion popup, handles the optional
' post-delete transport-request popup, and verifies removal via Display.
'
' Tokens replaced at run time:
'   %%PROGRAM_NAME%%   Program / report name (UPPERCASE)  e.g. "ZHKCM008R01"
'   %%TRANSPORT%%      Transport request for the post-delete TR popup.
'                       Optional. Empty = local ($TMP) or already locked to a
'                       modifiable TR. If the popup appears with TRANSPORT
'                       blank the script aborts so the caller can resolve a TR.
'   %%SESSION_LOCK_VBS%% Path to sap_session_lock.vbs (shared scripts).
'
' Recording reference: C:\Temp\Record_SE38_Delete_01.vbs (S/4HANA 1909).
' Field IDs:
'   wnd[0]/usr/ctxtRS38M-PROGRAMM   - program name on initial screen
'   wnd[0]/usr/btnSHOP              - Display (used for verify)
'   sendVKey 14                      - Shift+F2 = Delete from initial screen
'
' Outputs (last line of stdout, parseable):
'   SUCCESS: Program <NAME> deleted.
'   ERROR:   ...
' =============================================================================

Option Explicit

Const PROGRAM_NAME  = "%%PROGRAM_NAME%%"
Const SAP_TRANSPORT = "%%TRANSPORT%%"
Const SESSION_PATH  = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER    = 0
Const VKEY_SHIFT_F2 = 14

' Optional fill for the ECC6 "Create Object Directory Entry" (SAPLSTRD) popup.
' Empty / unsubstituted => accept SAP's pre-filled package (Continue), or press
' Local Object when the package field is required-empty. OBJDIR_LANG is the
' 1-character original language used only when filling an empty package field.
Dim OBJDIR_PKG  : OBJDIR_PKG  = "%%PACKAGE%%"
Dim OBJDIR_LANG : OBJDIR_LANG = "%%ORIG_LANG%%"
If Left(OBJDIR_PKG, 2)  = Chr(37) & Chr(37) Then OBJDIR_PKG  = ""
If Left(OBJDIR_LANG, 2) = Chr(37) & Chr(37) Then OBJDIR_LANG = ""
If OBJDIR_LANG = "" Then OBJDIR_LANG = "E"

' Include shared helpers (attach first; session-lock's pre-unlock sweep
' reads from oSession).
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()

' --- 1. Attach to existing SAP GUI session (via shared attach helper) ------
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' --- 2. Navigate to SE38 ---------------------------------------------------
WScript.Echo "INFO: Navigating to SE38 to delete program " & UCase(PROGRAM_NAME) & "..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE38"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' --- 3. Enter program name -------------------------------------------------
On Error Resume Next
oSession.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM").Text = UCase(PROGRAM_NAME)
oSession.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM").caretPosition = Len(PROGRAM_NAME)
If Err.Number <> 0 Then
    WScript.Echo "ERROR: Could not fill program-name field (ctxtRS38M-PROGRAMM): " & Err.Description
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

' --- Lock session for the delete + popup-confirm critical section ---
Dim wasLocked : wasLocked = TryLockSession(oSession)
If wasLocked Then
    WScript.Echo "INFO: Session UI locked for the delete + popup-confirm critical section."
Else
    WScript.Echo "INFO: LockSessionUI not available on this SAP GUI build; continuing without lock."
End If

' --- 4. Press Delete (Shift+F2 = sendVKey 14) ------------------------------
WScript.Echo "INFO: Pressing Delete (Shift+F2)..."
On Error Resume Next
oSession.findById("wnd[0]").sendVKey VKEY_SHIFT_F2
WScript.Sleep 1500
If Err.Number <> 0 Then
    WScript.Echo "ERROR: Could not send Shift+F2: " & Err.Description
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

' --- 5. Walk all post-delete confirmation popups ---------------------------
'
' SE38 deletion can chain up to ~5 popups depending on what the program is:
'
'   - Plain executable / include: usually 1 confirmation popup.
'   - Module pool, GUI status dependents: 2 popups (confirm + dependents).
'   - Function-group main program SAPL<FUGR>: 2 stacked popups (wnd[1]
'     listing dependents stays on screen while wnd[2] asks for the
'     final confirmation; both must be cleared in order).
'   - Transportable object: appends a TR-prompt popup with ctxtKO008-TRKORR.
'
' We loop on the active window. Each iteration:
'   (a) If the active window is the main wnd[0], we're done.
'   (b) If the popup carries a ctxtKO008-TRKORR field, fill the transport
'       (or abort if SAP_TRANSPORT is empty) and Enter.
'   (c) Otherwise try (in order) btnSPOP-OPTION1 (Yes), tbar[0]/btn[0]
'       (Continue on the popup's own toolbar, used by function-group
'       deletion popups), then sendVKey 0 (Enter) as a last resort.
'   The loop has a hard cap (8 iterations) so a stuck modal can't trap us.
Dim iPop, sActWnd, sActPrefix
For iPop = 1 To 8
    sActWnd = ""
    On Error Resume Next
    sActWnd = oSession.ActiveWindow.Id
    On Error GoTo 0
    If sActWnd = "" Then Exit For
    If Right(sActWnd, 6) = "wnd[0]" Then Exit For

    ' Compute prefix "wnd[N]" relative to session.
    Dim posWnd : posWnd = InStrRev(sActWnd, "/wnd[")
    If posWnd > 0 Then
        sActPrefix = Mid(sActWnd, posWnd + 1)
    Else
        sActPrefix = "wnd[1]"
    End If

    ' (a2) SAPLSETX "Different original and logon languages" popup.
    ' Fingerprint: ctxtRSETX-MASTERLANG present in the popup's usr area.
    ' Pressing Enter does NOT dismiss this dialog -- it just re-opens it,
    ' eventually tripping the iPop>8 cap and emitting a false SUCCESS.
    ' Click "Maint. in orig. lang." (btnPUSH1) which leaves TADIR-MASTERLANG
    ' unchanged and lets the delete flow continue.
    Dim bSetxHandled : bSetxHandled = False
    On Error Resume Next
    Dim oMasterLang : Set oMasterLang = Nothing
    Set oMasterLang = oSession.findById(sActPrefix & "/usr/ctxtRSETX-MASTERLANG")
    If Err.Number = 0 And Not (oMasterLang Is Nothing) Then
        Dim oMaintBtn : Set oMaintBtn = Nothing
        Set oMaintBtn = oSession.findById(sActPrefix & "/usr/btnPUSH1")
        If Err.Number = 0 And Not (oMaintBtn Is Nothing) Then
            WScript.Echo "INFO: SAPLSETX original-language popup on " & sActPrefix & _
                         " (MASTERLANG=" & oMasterLang.Text & ") - pressing 'Maint. in orig. lang.'..."
            oMaintBtn.press
            WScript.Sleep 1500
            bSetxHandled = True
        End If
    End If
    Err.Clear
    On Error GoTo 0

    ' (a3) "Create Object Directory Entry" (SAPLSTRD / KO007) popup -- ECC6
    ' raises this when the object's directory entry must be (re)created on
    ' delete. Fill an empty package from OBJDIR_PKG (+ 1-char original
    ' language), else accept the pre-filled entry; press Continue. If the
    ' package is required-empty and none supplied, press Local Object (btn[7]).
    Dim bObjDirHandled : bObjDirHandled = False
    If Not bSetxHandled Then
        On Error Resume Next
        Dim oDevc : Set oDevc = Nothing
        Set oDevc = oSession.findById(sActPrefix & "/usr/ctxtKO007-L_DEVCLASS")
        If Err.Number = 0 And Not (oDevc Is Nothing) Then
            If oDevc.Text = "" And OBJDIR_PKG <> "" Then
                oDevc.Text = OBJDIR_PKG
                Dim oObjLang : Set oObjLang = Nothing
                Set oObjLang = oSession.findById(sActPrefix & "/usr/ctxtKO007-L_MSTLANG")
                If Err.Number = 0 And Not (oObjLang Is Nothing) Then
                    If oObjLang.Text = "" Then oObjLang.Text = OBJDIR_LANG
                End If
                Err.Clear
                oSession.findById(sActPrefix & "/tbar[0]/btn[0]").press
                WScript.Echo "INFO: Object Directory Entry on " & sActPrefix & " -- package " & OBJDIR_PKG & ", Continue."
            ElseIf oDevc.Text = "" Then
                oSession.findById(sActPrefix & "/tbar[0]/btn[7]").press
                WScript.Echo "INFO: Object Directory Entry on " & sActPrefix & " -- empty package, none supplied; Local Object."
            Else
                oSession.findById(sActPrefix & "/tbar[0]/btn[0]").press
                WScript.Echo "INFO: Object Directory Entry on " & sActPrefix & " -- accepted pre-filled package, Continue."
            End If
            WScript.Sleep 1500
            bObjDirHandled = True
        End If
        Err.Clear
        On Error GoTo 0
    End If

    If (Not bSetxHandled) And (Not bObjDirHandled) Then
    ' (b) TR-prompt popup?
    On Error Resume Next
    Dim oTr : Set oTr = Nothing
    Set oTr = oSession.findById(sActPrefix & "/usr/ctxtKO008-TRKORR")
    If Err.Number = 0 And Not (oTr Is Nothing) Then
        If SAP_TRANSPORT = "" Then
            WScript.Echo "ERROR: SAP prompted for a transport request but TRANSPORT is empty."
            WScript.Echo "       Resolve a TR via /sap-transport-request and re-run."
            ReleaseSession oSession, wasLocked
            WScript.Quit 1
        End If
        WScript.Echo "INFO: Filling transport " & SAP_TRANSPORT & " on " & sActPrefix & "..."
        oTr.Text = SAP_TRANSPORT
        oSession.findById(sActPrefix).sendVKey VKEY_ENTER
        WScript.Sleep 1500
        Err.Clear
        On Error GoTo 0
    Else
        Err.Clear
        ' (c) Generic confirmation popup.
        Dim oYes : Set oYes = Nothing
        Set oYes = oSession.findById(sActPrefix & "/usr/btnSPOP-OPTION1")
        If Err.Number = 0 And Not (oYes Is Nothing) Then
            WScript.Echo "INFO: Confirming popup " & iPop & " on " & sActPrefix & " (Yes)..."
            oYes.press
            WScript.Sleep 1200
            Err.Clear
        Else
            Err.Clear
            Dim oCont : Set oCont = Nothing
            Set oCont = oSession.findById(sActPrefix & "/tbar[0]/btn[0]")
            If Err.Number = 0 And Not (oCont Is Nothing) Then
                WScript.Echo "INFO: Confirming popup " & iPop & " on " & sActPrefix & " (Continue/btn[0])..."
                oCont.press
                WScript.Sleep 1200
                Err.Clear
            Else
                Err.Clear
                WScript.Echo "INFO: Confirming popup " & iPop & " on " & sActPrefix & " (Enter)..."
                oSession.findById(sActPrefix).sendVKey VKEY_ENTER
                WScript.Sleep 1200
                Err.Clear
            End If
        End If
        On Error GoTo 0
    End If
    End If  ' bSetxHandled branch
Next

If iPop > 8 Then
    WScript.Echo "WARN: Popup loop hit cap; SAP may have left a modal on screen."
End If

' --- 8. Verify deletion via Display ----------------------------------------
WScript.Echo "INFO: Verifying deletion (try Display)..."
On Error Resume Next
oSession.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM").Text = UCase(PROGRAM_NAME)
oSession.findById("wnd[0]/usr/btnSHOP").press
WScript.Sleep 1500
On Error GoTo 0

Dim sFinalMsg, sFinalType
On Error Resume Next
sFinalMsg  = oSession.findById("wnd[0]/sbar").Text
sFinalType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

' Release the session UI lock; status read is read-only.
ReleaseSession oSession, wasLocked
If wasLocked Then WScript.Echo "INFO: Session UI lock released."

' Decide success: if Display navigated us into the editor (title leaves the
' SE38 initial screen), the program still exists. Otherwise it's gone.
On Error Resume Next
Dim sTitle : sTitle = ""
sTitle = oSession.findById("wnd[0]/titl").Text
If Err.Number <> 0 Then sTitle = "" : Err.Clear
On Error GoTo 0

Dim bStillOnInitial
bStillOnInitial = (InStr(1, sTitle, "Initial Screen", vbTextCompare) > 0) Or _
                  (InStr(1, sTitle, "ABAP Editor",    vbTextCompare) = 0)
' Belt-and-suspenders: also check that the program-name field is still
' findable (it only exists on the SE38 initial screen).
On Error Resume Next
Dim oNameField : Set oNameField = Nothing
Set oNameField = oSession.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM")
Dim bNameFieldStillThere : bNameFieldStillThere = _
    (Err.Number = 0) And Not (oNameField Is Nothing)
Err.Clear
On Error GoTo 0

If Not bNameFieldStillThere Then
    WScript.Echo "ERROR: Program still exists after delete (Display opened the editor)."
    WScript.Echo "       sbar=[" & sFinalType & "] " & sFinalMsg
    ' Back out so the operator inherits a clean SE38 initial screen.
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE38"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Quit 1
End If

WScript.Echo "INFO: SAP status: [" & sFinalType & "] " & sFinalMsg
WScript.Echo "SUCCESS: Program " & UCase(PROGRAM_NAME) & " deleted."
WScript.Quit 0
