' =============================================================================
' sap_se38_create.vbs  -  SAP GUI Scripting: Create new ABAP program via SE38
'
' Generated by the sap-se38 skill.
' Attaches to an existing SAP GUI session, navigates to SE38, creates a new
' program, sets attributes, uploads source code, saves (Ctrl+S), runs syntax
' check (Ctrl+F2), and activates.
'
' Tokens replaced at run time:
'   %%PROGRAM_NAME%%       ABAP program name         e.g. "ZMYREPORT"
'   %%PROGRAM_TYPE%%       Program type code          e.g. "1"
'   %%PROGRAM_TITLE%%      Short description          e.g. "My Report"
'   %%ABAP_SOURCE_FILE%%   Absolute path to .abap file
'   %%PACKAGE%%            SAP package               e.g. "ZHKA001" (empty = local object)
'   %%TRANSPORT%%          Transport number           e.g. "S4DK940992" (empty = local object)
'
' Program type codes:
'   1 = Executable program     I = Include program
'   M = Module Pool            F = Function Group
'   K = Class Pool             S = Subroutine Pool
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' If a step fails, use SAP Logon > Help > Scripting Recorder to re-record
' the correct ID for your system.
' =============================================================================

Option Explicit

Const PROGRAM_NAME     = "%%PROGRAM_NAME%%"
Const PROGRAM_TYPE     = "%%PROGRAM_TYPE%%"
Const PROGRAM_TITLE    = "%%PROGRAM_TITLE%%"
Const ABAP_SOURCE_FILE = "%%ABAP_SOURCE_FILE%%"
Const SAP_PACKAGE      = "%%PACKAGE%%"
Const SAP_TRANSPORT    = "%%TRANSPORT%%"
Const SESSION_PATH     = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER    = 0
Const VKEY_F3_BACK  = 3
Const VKEY_F11_SAVE = 11

' Include shared helpers (attach first; session-lock's pre-unlock sweep
' reads from oSession).
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SE38 -------------------------------------------------
WScript.Echo "INFO: Navigating to SE38..."
oSession.StartTransaction "SE38"
WScript.Sleep 1000

On Error Resume Next
Dim oProgField
Set oProgField = oSession.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM")
If Err.Number <> 0 Or oProgField Is Nothing Then
    WScript.Echo "ERROR: SE38 program name field not found (ID: wnd[0]/usr/ctxtRS38M-PROGRAMM)." & vbCrLf & _
                 "       Use Scripting Recorder to find the correct ID for your SAP version."
    WScript.Quit 1
End If
On Error GoTo 0

' ------ 3. Enter program name and press Create (btnNEW) ---------------------
oProgField.Text = UCase(PROGRAM_NAME)
On Error Resume Next
oSession.findById("wnd[0]/usr/radRS38M-FUNC_EDIT").select   ' Source Code radio
Err.Clear
On Error GoTo 0
WScript.Sleep 300

WScript.Echo "INFO: Creating new program: " & UCase(PROGRAM_NAME)
On Error Resume Next
oSession.findById("wnd[0]/usr/btnNEW").press
WScript.Sleep 1500

' Pre-check: if Create returned an error in the status bar (typically because
' the program already exists), abort cleanly BEFORE the Attributes / Object
' Directory Entry dialogs commit TRDIR / TADIR rows. This prevents a second
' attempt after a prior syntax-failure run from looping on the cryptic
' "Could not reach ABAP source editor" error.
Dim sCreateErrType, sCreateErrText
sCreateErrType = oSession.findById("wnd[0]/sbar").MessageType
sCreateErrText = oSession.findById("wnd[0]/sbar").Text
If Err.Number = 0 And (sCreateErrType = "E" Or sCreateErrType = "A") Then
    WScript.Echo "ERROR: SE38 rejected Create for " & UCase(PROGRAM_NAME) & ": [" & sCreateErrType & "] " & sCreateErrText
    WScript.Echo "       The program may already exist (e.g. from a prior run that aborted on syntax errors)."
    WScript.Echo "       Recovery: re-run with the SE38 update flow (skill mode 'update'), or /sap-check-fix."
    WScript.Quit 1
End If
Err.Clear
' DO NOT close error-resume scope here. Steps 4 + 5 below rely on the
' On Error Resume Next opened above the btnNEW press: their findById /
' Err.Number checks for tolerant package-field detection only work under
' active error-resume mode. The matching On Error GoTo 0 lives at the end
' of step 5 (after the ODE block).

' ------ 4. Handle Attributes dialog (wnd[1]) --------------------------------
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    WScript.Echo "INFO: Setting program attributes (type=" & PROGRAM_TYPE & ", title=" & PROGRAM_TITLE & ")..."
    oSession.findById("wnd[1]/usr/txtRS38M-REPTI").Text = PROGRAM_TITLE
    oSession.findById("wnd[1]/usr/cmbTRDIR-SUBC").Key   = PROGRAM_TYPE
    WScript.Sleep 300
    oSession.ActiveWindow.sendVKey VKEY_ENTER   ' Save attributes
    WScript.Sleep 1500
End If

' ------ 5. Handle Object Directory Entry dialog --------------------------------
' The dialog may appear at wnd[1] or wnd[2] depending on whether the Attributes dialog
' was shown. The package field may be ctxtSEUK-DEVCLASS or ctxtKO007-L_DEVCLASS.
Dim sODEWin
sODEWin = ""
If InStr(oSession.ActiveWindow.Id, "wnd[2]") > 0 Then
    sODEWin = "wnd[2]"
ElseIf InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    ' Check if this is the Object Directory Entry (has package field), not attributes
    Dim oTestPkg1
    Set oTestPkg1 = Nothing
    Err.Clear
    Set oTestPkg1 = oSession.findById("wnd[1]/usr/ctxtSEUK-DEVCLASS")
    If Err.Number = 0 Then
        If Not (oTestPkg1 Is Nothing) Then
            sODEWin = "wnd[1]"
        End If
    End If
    Err.Clear
    If sODEWin = "" Then
        Set oTestPkg1 = Nothing
        Err.Clear
        Set oTestPkg1 = oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS")
        If Err.Number = 0 Then
            If Not (oTestPkg1 Is Nothing) Then
                sODEWin = "wnd[1]"
            End If
        End If
    End If
    Err.Clear
End If

If sODEWin <> "" Then
    If SAP_PACKAGE <> "" And SAP_TRANSPORT <> "" Then
        ' Assign to package with transport
        WScript.Echo "INFO: Assigning to package " & SAP_PACKAGE & " with transport " & SAP_TRANSPORT & "..."
        Dim oCreatePkgField
        Dim bPkgSet
        bPkgSet = False
        Err.Clear
        Set oCreatePkgField = Nothing
        Set oCreatePkgField = oSession.findById(sODEWin & "/usr/ctxtSEUK-DEVCLASS")
        If Err.Number = 0 Then
            If Not (oCreatePkgField Is Nothing) Then
                oCreatePkgField.Text = SAP_PACKAGE
                bPkgSet = True
            End If
        End If
        Err.Clear
        If Not bPkgSet Then
            Set oCreatePkgField = Nothing
            Err.Clear
            Set oCreatePkgField = oSession.findById(sODEWin & "/usr/ctxtKO007-L_DEVCLASS")
            If Err.Number = 0 Then
                If Not (oCreatePkgField Is Nothing) Then
                    oCreatePkgField.Text = SAP_PACKAGE
                    bPkgSet = True
                End If
            End If
            Err.Clear
        End If
        If bPkgSet Then
            WScript.Echo "INFO: Package " & SAP_PACKAGE & " entered."
        Else
            WScript.Echo "WARNING: Could not find package field. Object may be saved to $TMP."
        End If
        oSession.findById(sODEWin).sendVKey VKEY_ENTER
        WScript.Sleep 3000
        ' Transport request dialog (may appear at same window or different window)
        ' On S/4HANA 1909, the transport dialog stays at the same wnd (e.g. wnd[2])
        ' and the field is ctxtKO008-TRKORR. Other systems may use ctxtKORR_TXT-REQ_NUM
        ' or ctxtKO007-L_REQ at wnd[1] or wnd[2].
        Dim sTrWin
        sTrWin = ""
        If InStr(oSession.ActiveWindow.Id, "wnd[2]") > 0 Then sTrWin = "wnd[2]"
        If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then sTrWin = "wnd[1]"
        If sTrWin <> "" Then
            Dim oCreateTrField
            Dim bTrSet
            bTrSet = False
            Set oCreateTrField = Nothing
            Err.Clear
            Set oCreateTrField = oSession.findById(sTrWin & "/usr/ctxtKO008-TRKORR")
            If Err.Number = 0 Then
                If Not (oCreateTrField Is Nothing) Then
                    oCreateTrField.Text = SAP_TRANSPORT
                    bTrSet = True
                End If
            End If
            Err.Clear
            If Not bTrSet Then
                Set oCreateTrField = Nothing
                Err.Clear
                Set oCreateTrField = oSession.findById(sTrWin & "/usr/ctxtKORR_TXT-REQ_NUM")
                If Err.Number = 0 Then
                    If Not (oCreateTrField Is Nothing) Then
                        oCreateTrField.Text = SAP_TRANSPORT
                        bTrSet = True
                    End If
                End If
                Err.Clear
            End If
            If Not bTrSet Then
                Set oCreateTrField = Nothing
                Err.Clear
                Set oCreateTrField = oSession.findById(sTrWin & "/usr/ctxtKO007-L_REQ")
                If Err.Number = 0 Then
                    If Not (oCreateTrField Is Nothing) Then
                        oCreateTrField.Text = SAP_TRANSPORT
                        bTrSet = True
                    End If
                End If
                Err.Clear
            End If
            If bTrSet Then
                WScript.Echo "INFO: Transport request " & SAP_TRANSPORT & " entered."
            End If
            oSession.findById(sTrWin).sendVKey VKEY_ENTER
            WScript.Sleep 1500
        End If
    Else
        WScript.Echo "INFO: Assigning to Local Object ($TMP) - no transport request."
        oSession.findById(sODEWin & "/tbar[0]/btn[7]").press   ' Local Object (F7)
        WScript.Sleep 1500
    End If
End If
Err.Clear
On Error GoTo 0

' Verify we are in the ABAP editor
Dim oEditorShell, bInEditor
Set oEditorShell = Nothing
bInEditor = False
On Error Resume Next
Err.Clear
Set oEditorShell = oSession.findById("wnd[0]/usr/cntlEDITOR/shellcont/shell")
If Err.Number = 0 Then
    If Not (oEditorShell Is Nothing) Then
        bInEditor = True
    End If
End If
Err.Clear
On Error GoTo 0

If Not bInEditor Then
    WScript.Echo "ERROR: Could not reach ABAP source editor after create." & vbCrLf & _
                 "       Check SAP status bar in SAP GUI window."
    WScript.Quit 1
End If
WScript.Echo "INFO: New program created and editor opened."

' ------ 6. Upload source code via clipboard + SendKeys ---------------------
WScript.Echo "INFO: Uploading source file: " & ABAP_SOURCE_FILE

Dim oFSO
Set oFSO = CreateObject("Scripting.FileSystemObject")
If Not oFSO.FileExists(ABAP_SOURCE_FILE) Then
    WScript.Echo "ERROR: Source file not found: " & ABAP_SOURCE_FILE
    WScript.Quit 1
End If

' Upload via clipboard + SendKeys.
'
' Why not shell.Text? On the new SAP ABAP editor (AbapEditor.1), shell.Text
' is READ-ONLY (assignment raises err 61837); reading it returns the class
' name "SAPGUI.AbapEditor.1" not the source. Some older builds expose
' shell.Text writeable, but we cannot rely on it.
'
' Why not the Utilities -> More Utilities -> Upload/Download -> Upload menu?
' That menu opens a NATIVE Windows file-picker dialog which is not
' scriptable from VBS via SAP Scripting once it is shown.
'
' Working approach (verified on S/4HANA, AbapEditor.1):
'   1. Stage source on the Windows clipboard (MSForms.DataObject; fall back
'      to clip.exe via cmd).
'   2. AppActivate the SAP main window.
'   3. SetFocus on the editor shell.
'   4. SendKeys "^a" {DEL} "^v".
WScript.Echo "INFO: Uploading source via clipboard + SendKeys..."

' --- 6a. Read source text (UTF-8) into memory ---
Dim oSrcStream, sSourceText
On Error Resume Next
Set oSrcStream = CreateObject("ADODB.Stream")
oSrcStream.Type = 2   ' adTypeText
oSrcStream.Charset = "utf-8"
oSrcStream.Open
oSrcStream.LoadFromFile ABAP_SOURCE_FILE
sSourceText = oSrcStream.ReadText
oSrcStream.Close
If Err.Number <> 0 Then
    WScript.Echo "ERROR: Could not read source file: " & Err.Description
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

' --- 6b. Stage on Windows clipboard ---
Dim bClipOk
bClipOk = False
On Error Resume Next
Dim oClipDO
Set oClipDO = CreateObject("MSForms.DataObject")
If Err.Number = 0 Then
    oClipDO.SetText sSourceText
    oClipDO.PutInClipboard
    If Err.Number = 0 Then bClipOk = True
End If
Err.Clear
On Error GoTo 0

If Not bClipOk Then
    ' clip.exe interprets stdin as OEM/ANSI unless it starts with a UTF-16 LE
    ' BOM (FF FE). Use UTF-16 LE so clip stores CF_UNICODETEXT cleanly and
    ' no spurious BOM bytes appear at the head of the editor on Japanese
    ' (or other non-UTF-8) locale machines.
    On Error Resume Next
    Dim sTmpClip, oTmpStream, oWshFallback
    sTmpClip = ABAP_SOURCE_FILE & ".clip.txt"
    Set oTmpStream = CreateObject("ADODB.Stream")
    oTmpStream.Type = 2
    oTmpStream.Charset = "utf-16"
    oTmpStream.Open
    oTmpStream.WriteText sSourceText
    oTmpStream.SaveToFile sTmpClip, 2
    oTmpStream.Close
    Set oWshFallback = CreateObject("WScript.Shell")
    oWshFallback.Run "cmd /c type """ & sTmpClip & """ | clip", 0, True
    If Err.Number = 0 Then bClipOk = True
    Err.Clear
    On Error GoTo 0
End If

If Not bClipOk Then
    WScript.Echo "ERROR: Could not place source on clipboard."
    WScript.Quit 1
End If

' --- Lock the SAP session UI for the paste + save + activate critical section ---
' Defence in depth (Rule 7): AppActivate guards external focus stealing;
' LockSessionUI guards in-session input races. Released after Step 9.
Dim wasLocked : wasLocked = TryLockSession(oSession)
If wasLocked Then
    WScript.Echo "INFO: Session UI locked for the paste+save+activate critical section."
Else
    WScript.Echo "INFO: LockSessionUI not available on this SAP GUI build; continuing without lock."
End If

' --- 6c. Focus editor (with foreground guard) and paste via SendKeys ---
'
' SAFETY: Before sending Ctrl+A / Del / Ctrl+V we MUST guarantee the SAP GUI
' window is in the foreground. If another application has stolen focus
' (mouse click, alt-tab, notification toast, etc.) SendKeys will paste the
' ABAP source into THAT application instead — silently overwriting whatever
' the user was editing. To prevent this we:
'   1. Restore the main window if iconified (a minimised window can never
'      receive keystrokes via SendKeys).
'   2. Loop AppActivate up to 10 times (200 ms apart). AppActivate returns
'      True only when activation actually succeeded; if all retries fail
'      we abort BEFORE sending any keystroke.
'   3. SetFocus on the editor shell (places caret inside the AbapEditor).
'
' Note: AbapEditor.1 does NOT expose readable text/numberOfLines on this
' SAP GUI build (every read returns either the class name or err 438), so
' we cannot programmatically confirm the paste landed in the editor. The
' AppActivate loop + Iconified check is the primary defence; the
' subsequent syntax check (Ctrl+F2) will catch an empty editor before save.

Dim oWshSend, sapTitle
Set oWshSend = CreateObject("WScript.Shell")
sapTitle = oSession.findById("wnd[0]").Text

' Restore the window if iconified so the Z-order operations have something
' to work with (an iconified window cannot become foreground).
On Error Resume Next
If oSession.findById("wnd[0]").Iconified Then
    oSession.findById("wnd[0]").Restore
    WScript.Sleep 200
End If
oSession.findById("wnd[0]").Maximize
WScript.Sleep 100
Err.Clear
On Error GoTo 0

' Force SAP GUI to OS-level foreground via the dedicated sidecar. WshShell's
' AppActivate (used to live here in a 20-retry loop) is unreliable on
' Windows 7+ because SetForegroundWindow is suppressed for processes that
' don't already own the foreground — it returns success while Windows just
' flashes the taskbar button, and SAP stays behind. The sidecar uses the
' AttachThreadInput trick to bypass that suppression.
'
' If the sidecar reports anything other than FOREGROUND:OK we ABORT BEFORE
' SendKeys so the source never lands in the user's Notepad / VS Code /
' browser. Bug surfaced 2026-05-11: user pasted into VS Code while AI
' was running this skill; the prior AppActivate loop "succeeded" but SAP
' stayed in the background.
Dim sFgGuardCmd, nFgGuardRc
sFgGuardCmd = "powershell -NoProfile -ExecutionPolicy Bypass -File """ & _
              "%%FOREGROUND_GUARD_PS1%%"" -TargetTitle """ & sapTitle & _
              """ -TimeoutSeconds 5"
nFgGuardRc = oWshSend.Run(sFgGuardCmd, 0, True)
If nFgGuardRc <> 0 Then
    WScript.Echo "ERROR: SAP GUI window is not the OS foreground window (sidecar exit " & nFgGuardRc & ")."
    WScript.Echo "       Aborting paste to prevent Ctrl+V from landing in another app (Notepad, VS Code, browser)."
    WScript.Echo "       Target window title: " & sapTitle
    WScript.Echo "       Recovery: close or minimize the focus-stealing app, click on the SAP GUI window,"
    WScript.Echo "                then re-run this skill. Or set Windows ForegroundLockTimeout to 0."
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

On Error Resume Next
oEditorShell.SetFocus
Err.Clear
On Error GoTo 0
WScript.Sleep 300

' --- Belt-and-suspenders clear-buffer-then-paste ---
'
' Why this isn't just Ctrl+A / Del / Ctrl+V: when SE38 freshly created the
' program at Step 5, the editor opens with SAP's auto-generated 4-line
' template:
'
'     *&---*
'     *& Report ZXXX
'     *&---*
'     REPORT ZXXX.
'
' On the FIRST deploy of a program (sap-dev-init Step 8 / sap-se38 create
' flow), `SendKeys "^a"` was observed to NOT select-all reliably — AbapEditor.1
' sometimes rebinds Ctrl+A to a function-code action (continue / scroll /
' nothing) depending on cursor position and editor sub-mode. When that
' happens `{DEL}` removes only one character and `^v` pastes the new source
' INSERTED above the leftover template — producing this syntactically
' invalid file:
'
'     " ...new source ends at line 652 with `).`
'     *&---*                      <- SAP default template, still there
'     *& Report ZCMRUPDATE_ADDON_TABLE
'     *&---*
'     REPORT ZCMRUPDATE_ADDON_TABLE.
'
' SAP rejects: "The statement '*&---*' is invalid. Check the spelling."
'
' Three-layer fix (any one of which removes the leftover template):
'   1. SAP-side `sendVKey 26` (SAP's own Ctrl+A binding) — bypasses Windows
'      focus / keystroke-routing entirely. Works even when the editor isn't
'      the OS-foreground window.
'   2. Windows `^{HOME}` (cursor to top) then `^+{END}` (Ctrl+Shift+End:
'      select from cursor to end-of-document) — standard Windows edit-control
'      idiom, more portable than `^a` against rebinding.
'   3. `^a` as the final fallback for older SAP GUI builds where layers 1+2
'      may not yet have wired the document-end correctly.
' Then `{DEL}` to clear the selection, then `^v` to paste.
'
' Bug surfaced 2026-05-11 evening on first-time deploy of
' ZCMRUPDATE_ADDON_TABLE via /sap-dev-init Step 8 (screenshot showed
' lines 653-658 still carrying the SAP default `*& Report …` header).
' Wait sizing: the original timings (80/150/300/1500 ms) were tuned for the
' SE38 create case where the editor holds only the 4-line auto-template.
' On a retry, or on a path where the editor was pre-loaded with a large
' file (any case where AbapEditor.1 already contains hundreds of lines),
' the {DEL} operation on a large selection takes much longer than 300 ms.
' If ^v fires before the editor finishes deleting, the new source
' interleaves with the leftover content — producing a syntactically
' invalid file (e.g. lines 653-656 still carrying the leftover SAP
' template). Bug re-surfaced 2026-05-11 PM during ZMMRMAT032R01 redeploy
' iteration #2 (450-line source). The post-{DEL} wait is the load-bearing
' delay; the other bumps add a few hundred ms of insurance against
' SendKeys keystroke drops on busy machines.
' Paste sub — refactored so we can retry on verify failure.
Sub DoPasteSequence(oSess, oWshS)
    On Error Resume Next
    oSess.findById("wnd[0]").sendVKey 26
    WScript.Sleep 400
    Err.Clear
    On Error GoTo 0
    oWshS.SendKeys "^{HOME}"
    WScript.Sleep 200
    oWshS.SendKeys "^+{END}"
    WScript.Sleep 200
    oWshS.SendKeys "^a"
    WScript.Sleep 300
    oWshS.SendKeys "{DEL}"
    WScript.Sleep 1500
    oWshS.SendKeys "^v"
    WScript.Sleep 2500
End Sub

' Verify sub — reads a deep line from the editor and compares to the source
' file. Returns True on match, False on mismatch (which means SendKeys went
' to the wrong window, or focus was lost mid-paste). Uses getLineText() —
' the one writable-editor API that the Frontend AbapEditor still exposes for
' READ (confirmed 2026-05-27 probe; Text/setSelectedText/setTextPart all
' return "property not supported" but getLineText works).
Function VerifyPaste(oEditor, sSourceFile)
    Dim oFS_v, oTs_v, sFull_v
    Set oFS_v = CreateObject("Scripting.FileSystemObject")
    On Error Resume Next
    Set oTs_v = oFS_v.OpenTextFile(sSourceFile, 1, False, 0)   ' ASCII; for UTF-8 we'd use ADODB but the SE38 paste path already feeds bytes through clipboard, so line-positional compare is what matters, not bytes
    If Err.Number <> 0 Then
        On Error GoTo 0
        WScript.Echo "WARN: VerifyPaste — cannot open source file for verify; skipping verify (NOT a paste failure)."
        VerifyPaste = True   ' fail-open on verify-infra issues (don't block a real success)
        Exit Function
    End If
    sFull_v = oTs_v.ReadAll
    oTs_v.Close
    On Error GoTo 0

    ' Normalise line endings, split.
    sFull_v = Replace(sFull_v, vbCrLf, vbLf)
    sFull_v = Replace(sFull_v, vbCr,   vbLf)
    Dim aLines_v : aLines_v = Split(sFull_v, vbLf)
    Dim nLines_v : nLines_v = UBound(aLines_v) + 1

    ' Pick a check line deep enough to discriminate an empty editor (default
    ' SE38 template = 6 lines) from a real paste. Source must have >= 8 lines
    ' for verify to be meaningful; otherwise skip-with-pass.
    If nLines_v < 8 Then
        WScript.Echo "INFO: VerifyPaste — source too short (" & nLines_v & " lines) for deep-line check; assuming OK."
        VerifyPaste = True
        Exit Function
    End If

    Dim chkIdx : chkIdx = nLines_v \ 2   ' middle line
    Dim sExpected : sExpected = aLines_v(chkIdx)
    Dim sActual
    sActual = ""
    On Error Resume Next
    sActual = oEditor.getLineText(chkIdx)
    Dim verifyErrNo : verifyErrNo = Err.Number
    Err.Clear
    On Error GoTo 0

    If verifyErrNo <> 0 Then
        ' getLineText raised — usually means editor has fewer lines than chkIdx.
        ' That's a strong signal the paste did NOT land.
        WScript.Echo "VERIFY: getLineText(" & chkIdx & ") errored — editor likely has < " & (chkIdx+1) & " lines."
        VerifyPaste = False
        Exit Function
    End If

    Dim sExpClean : sExpClean = Trim(Replace(sExpected, vbTab, " "))
    Dim sActClean : sActClean = Trim(Replace(sActual,   vbTab, " "))

    If sExpClean = sActClean Then
        VerifyPaste = True
    Else
        WScript.Echo "VERIFY: line " & chkIdx & " mismatch:"
        WScript.Echo "  expected: " & Left(sExpClean, 80)
        WScript.Echo "  actual:   " & Left(sActClean, 80)
        VerifyPaste = False
    End If
End Function

' ---- Paste + verify with bounded retry ----
Dim pasteAttempt, pasteOk
pasteOk = False
For pasteAttempt = 1 To 3
    Call DoPasteSequence(oSession, oWshSend)
    WScript.Echo "INFO: Paste attempt " & pasteAttempt & "/3 sent. Verifying via getLineText()..."
    WScript.Sleep 500
    If VerifyPaste(oEditorShell, ABAP_SOURCE_FILE) Then
        pasteOk = True
        WScript.Echo "PASTE_VERIFY: OK (attempt " & pasteAttempt & "/3)"
        Exit For
    End If
    If pasteAttempt < 3 Then
        WScript.Echo "WARN: Paste verify failed on attempt " & pasteAttempt & "/3 — re-bringing SAP foreground + re-pasting."
        ' Re-call foreground guard before retry.
        Dim retryFgRc
        retryFgRc = oWshSend.Run(sFgGuardCmd, 0, True)
        WScript.Echo "INFO: Foreground guard rc=" & retryFgRc & " (0=OK)"
        On Error Resume Next
        oEditorShell.SetFocus
        Err.Clear
        On Error GoTo 0
        WScript.Sleep 500
    End If
Next

If Not pasteOk Then
    WScript.Echo "PASTE_VERIFY: FAILED after 3 attempts."
    WScript.Echo "ERROR: Source paste did not land in editor. Likely causes:"
    WScript.Echo "  - SAP GUI lost foreground during SendKeys (focus stolen by another window)"
    WScript.Echo "  - Clipboard was clobbered by another process between clipboard-set and Ctrl+V"
    WScript.Echo "  - User input intercepted the SendKeys sequence"
    WScript.Echo "RECOVERY: ensure SAP GUI is in foreground, do not touch keyboard/mouse, re-run /sap-se38."
    WScript.Quit 1
End If

WScript.Echo "INFO: Source code pasted into ABAP editor (foreground-guarded, 3-layer clear, verified)."

' ------ 7. Save (Ctrl+S = VKey 11) -----------------------------------------
' Per design: paste -> Save (Ctrl+S) -> Check (Ctrl+F2) -> if no errors ->
' Activate (Ctrl+F3). The Object Directory Entry dialog at step 5 already
' registered the program to SAP_PACKAGE + SAP_TRANSPORT, so this Save will
' not re-prompt. Defensively handle any popup by pressing Enter.
WScript.Echo "INFO: Saving (Ctrl+S)..."
On Error Resume Next
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1500
Err.Clear
On Error GoTo 0

On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim oSaveTR
    Set oSaveTR = Nothing
    Err.Clear
    Set oSaveTR = oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR")
    If Err.Number = 0 And Not (oSaveTR Is Nothing) Then
        If SAP_TRANSPORT <> "" Then
            oSaveTR.Text = SAP_TRANSPORT
            WScript.Echo "INFO: Save TR popup — entering " & SAP_TRANSPORT & "."
        End If
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
    Else
        Err.Clear
        WScript.Echo "INFO: Save popup (no TR field) — pressing Enter."
        oSession.ActiveWindow.sendVKey VKEY_ENTER
    End If
    WScript.Sleep 1000
End If
Err.Clear
On Error GoTo 0
WScript.Echo "INFO: Saved."

' ------ 8. Syntax check (Ctrl+F2 = tbar[1]/btn[26]) ------------------------
' Per design: paste -> Save (Ctrl+S) -> Check (Ctrl+F2) -> if no errors ->
' Activate (Ctrl+F3). The Object Directory Entry dialog at step 5 already
' registered the program to SAP_PACKAGE + SAP_TRANSPORT, so activation
' will not re-prompt. The activation loop below contains a safety-net for
' the package/TR dialog just in case.
WScript.Echo "INFO: Running syntax check..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[1]/btn[26]").press
WScript.Sleep 3000
Err.Clear
On Error GoTo 0

' Read syntax errors from the error grid (shellcont[1]/shell)
Dim oChkGrid, lChkRows, iChk
Dim sChkType, sChkLine, sChkText
Dim bHasErrors
Dim lErrCount
bHasErrors = False
lErrCount  = 0

On Error Resume Next
Set oChkGrid = oSession.findById("wnd[0]/shellcont/shell/shellcont[1]/shell")
If Err.Number = 0 And Not (oChkGrid Is Nothing) Then
    lChkRows = oChkGrid.RowCount
    Err.Clear
    If lChkRows > 0 Then
        WScript.Echo "INFO: " & lChkRows & " syntax finding(s) for program " & UCase(PROGRAM_NAME) & ":"
        For iChk = 0 To lChkRows - 1
            sChkType = oChkGrid.getCellValue(iChk, "MSGTYPE")
            sChkLine = oChkGrid.getCellValue(iChk, "LINE")
            sChkText = oChkGrid.getCellValue(iChk, "TEXT")
            If Err.Number <> 0 Then Err.Clear: Exit For
            WScript.Echo "  [" & sChkType & "] Line " & sChkLine & ": " & sChkText
            ' MSGTYPE values: "1" or "E" = Error. SAP also returns icon-codes
            ' like "@5C\QError@" (Error) / "@5D\QWarning@" (Warning).
            If sChkType = "1" Or UCase(sChkType) = "E" _
               Or InStr(UCase(sChkType), "ERROR") > 0 Then
                bHasErrors = True
                lErrCount  = lErrCount + 1
            End If
        Next
        ' Distinct, parseable line so callers can detect "real errors" vs
        ' "warnings only" without re-parsing the per-finding text. Emit even
        ' when zero so the format is stable across runs.
        WScript.Echo "SYNTAX_ERRORS: " & lErrCount
    Else
        WScript.Echo "INFO: Syntax check passed — no findings."
        WScript.Echo "SYNTAX_ERRORS: 0"
    End If
Else
    ' Grid not found — fall back to status bar check
    Err.Clear
    Dim sSyntaxMsg, sSyntaxType
    sSyntaxMsg  = oSession.findById("wnd[0]/sbar").Text
    sSyntaxType = oSession.findById("wnd[0]/sbar").MessageType
    If sSyntaxType = "E" Then
        WScript.Echo "ERROR: Syntax check failed - " & sSyntaxMsg
        bHasErrors = True
    ElseIf sSyntaxMsg = "" Then
        ' Defensive abort. An EMPTY editor produces neither a findings
        ' grid (no statements to check, no errors to render) nor a
        ' status-bar message — exactly this state. Previously this
        ' branch was a "Result unknown — continuing" pass-through that
        ' let an empty paste reach Activate and produce a silent
        ' false-success ("Program created and activated" against
        ' zero-line source). The downstream ATC gate then ran against
        ' the empty active version and reported P1=P2=P3=0 — a false
        ' clean pass that masked the underlying paste failure.
        ' Fail-safe instead: refuse to activate when neither signal is
        ' available; the operator re-runs and the second attempt
        ' usually paints a non-empty editor (or fails loudly).
        WScript.Echo "ERROR: Syntax check produced neither a findings grid nor a status-bar message."
        WScript.Echo "       This is the documented signature of an EMPTY editor — paste likely failed silently."
        WScript.Echo "       Refusing to activate to prevent a false-success. Recovery:"
        WScript.Echo "         (a) If the program is new: re-run /sap-se38 update <name> <file>."
        WScript.Echo "         (b) If you intended an empty stub: add at least one comment line to the source file."
        bHasErrors = True
    Else
        WScript.Echo "INFO: Syntax check: [" & sSyntaxType & "] " & sSyntaxMsg
    End If
End If
Err.Clear
On Error GoTo 0

If bHasErrors Then
    WScript.Echo "ERROR: Syntax errors found in " & UCase(PROGRAM_NAME) & "."
    WScript.Echo "       NOTE: The program is already REGISTERED in TADIR/TRDIR (Object Directory"
    WScript.Echo "       Entry was confirmed before this syntax check). A second 'Create' run will"
    WScript.Echo "       fail with 'program already exists'. Recovery options:"
    WScript.Echo "         (a) Fix the source and re-run with the SE38 update flow (skill mode 'update'), or"
    WScript.Echo "         (b) Delete the orphan via SE38 delete flow, then re-create."
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

' ------ 9. Activate (Ctrl+F3 = tbar[1]/btn[27]) ----------------------------
' From inside the ABAP editor, btn[27] triggers activate. Multiple popups can
' appear in sequence (e.g. "Inactive Objects for <user>" worklist), so loop
' and press ENTER on each one until the main window is back.
WScript.Echo "INFO: Activating..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[1]/btn[27]").press
WScript.Sleep 2500

Dim iActPop
For iActPop = 1 To 5
    If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
        WScript.Echo "INFO: Activation popup " & iActPop & ": " & oSession.findById("wnd[1]").Text
        oSession.ActiveWindow.sendVKey VKEY_ENTER
        WScript.Sleep 2000
    Else
        Exit For
    End If
Next
Err.Clear
On Error GoTo 0

' Handle SAPLSPO1 activation worklist screen (appears when multiple inactive objects exist)
On Error Resume Next
If oSession.Info.Program = "SAPLSPO1" Then
    WScript.Echo "INFO: Activation worklist (SAPLSPO1) detected — pressing Continue (btn[0])..."
    oSession.findById("wnd[0]/tbar[0]/btn[0]").press
    WScript.Sleep 5000
    If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
        oSession.ActiveWindow.sendVKey VKEY_ENTER
        WScript.Sleep 2000
    End If
End If
Err.Clear
On Error GoTo 0

' --- Release the session UI lock; Step 10 is read-only verification ---
ReleaseSession oSession, wasLocked
If wasLocked Then WScript.Echo "INFO: Session UI lock released."

' ------ 10. Verify activation from SE38 initial screen ---------------------
WScript.Echo "INFO: Verifying activation..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSA38"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1500

oSession.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM").Text = UCase(PROGRAM_NAME)
oSession.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM").SetFocus
WScript.Sleep 300

' F8 = Execute
oSession.findById("wnd[0]").sendVKey 8
WScript.Sleep 3000

Dim sVerifyScreen, sVerifyProgram, sVerifyMsg, sVerifyType
sVerifyScreen  = CStr(oSession.Info.ScreenNumber)
sVerifyProgram = oSession.Info.Program
sVerifyMsg     = oSession.findById("wnd[0]/sbar").Text
sVerifyType    = oSession.findById("wnd[0]/sbar").MessageType
Err.Clear
On Error GoTo 0

If InStr(LCase(sVerifyMsg), "inactive") > 0 Or InStr(LCase(sVerifyMsg), "nicht aktiv") > 0 Then
    WScript.Echo "ERROR: Program " & UCase(PROGRAM_NAME) & " is still INACTIVE after activation attempt."
    WScript.Echo "       SAP message: [" & sVerifyType & "] " & sVerifyMsg
    WScript.Echo "       Check SE38 manually for activation errors."
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE38"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Quit 1
End If

' Activation verification — the final SUCCESS line at the bottom MUST be
' gated on this flag, NOT on absence of paste errors.
'
' History:
'   2026-05-11 (a) — false-success bug: program had SYNTAX errors → screen
'   stayed at 101 → script printed "WARNING: Unexpected screen 101" then
'   "SUCCESS" anyway. Fix at the time: fail-closed on any unrecognised
'   screen.
'   2026-05-11 (b) — false-failure bug surfaced by the MaterialUpload_JA
'   build: program was ACTIVE (PROGDIR.STATE='A' + ATC clean) but F8 from
'   SA38 returned to SE38 initial (screen 101) instead of the selection
'   screen, and the fail-closed rule reported "activation_uncertain"
'   incorrectly.
'
' Resolution: accept screen 101 ONLY when the status bar carries no error
' MessageType (E/A). The inactive-text substring check at the block above
' (lines ~660) still catches genuinely-inactive cases — SAP emits
' "Program X is inactive" with MessageType=E for those, so they fail
' through both gates.
Dim bActivationVerified : bActivationVerified = False
If sVerifyScreen = "1000" Or sVerifyScreen = "120" Or sVerifyScreen = "200" Then
    bActivationVerified = True
    WScript.Echo "INFO: Program is active (reached screen " & sVerifyScreen & ")."
ElseIf sVerifyScreen = "101" And sVerifyType <> "E" And sVerifyType <> "A" Then
    ' Screen 101 = SAPMS38M = SE38/SA38 initial screen. We land here when
    ' F8 ran a no-op program (instant return), the selection screen was
    ' suppressed, or an unexpected popup ate the F8 keystroke. A clean
    ' sbar type (S/I/W/empty) plus a passed syntax check earlier means
    ' the program activated cleanly — accept as success.
    bActivationVerified = True
    WScript.Echo "INFO: Program is active (SE38 initial screen 101, sbar type='" & sVerifyType & "' — no error)."
Else
    WScript.Echo "ERROR: Unexpected verification screen " & sVerifyScreen & " (program=" & sVerifyProgram & ", sbar type='" & sVerifyType & "'). Program activation could NOT be verified."
End If

' Navigate back to SE38 initial
On Error Resume Next
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE38"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000
Err.Clear
On Error GoTo 0

' ------ 11. Clean up temp clipboard file (only the .clip.txt fallback, never the original)
On Error Resume Next
Dim sClipTmp
sClipTmp = ABAP_SOURCE_FILE & ".clip.txt"
If oFSO.FileExists(sClipTmp) Then oFSO.DeleteFile sClipTmp
Err.Clear
On Error GoTo 0

' ------ 12. Final status report -----------------------------------------------
Dim sFinalMsg, sFinalType
On Error Resume Next
sFinalMsg  = oSession.findById("wnd[0]/sbar").Text
sFinalType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

If Not bActivationVerified Then
    WScript.Echo "ERROR: activation_uncertain — Program " & UCase(PROGRAM_NAME) & " was created and the paste pipeline did not error, but post-activate verification did not reach an active SE38 screen (1000/120/200). The program may still be INACTIVE on the SAP side."
    WScript.Echo "       Recovery: open SE38 for " & UCase(PROGRAM_NAME) & " manually, inspect the activation log, fix any reported issues, then run /sap-activate-object PROGRAM " & UCase(PROGRAM_NAME) & "."
    WScript.Quit 1
End If

WScript.Echo "SUCCESS: Program " & UCase(PROGRAM_NAME) & " created and activated in SAP."
WScript.Quit 0
