' =============================================================================
' sap_snro_update.vbs  -  SAP GUI Scripting: Update existing Number Range Object
'
' Generated by the sap-snro skill.
' Attaches to an existing SAP GUI session, navigates to SNRO, opens the NRO
' in Change mode (btnCHANGE), updates only the header fields whose token is
' non-empty (Short Text, Long Text, Domain length, Warning %), saves, and
' handles the package/transport popup.
'
' Tokens replaced at run time (empty token = leave field unchanged):
'   %%NRO_NAME%%     NRO name (UPPERCASE)           e.g. "ZMM_0004"
'   %%SHORT_TEXT%%   New TNROT-TXTSHORT
'   %%LONG_TEXT%%    New TNROT-TXT
'   %%DOMLEN%%       New TNRO-DOMLEN (e.g. "NUMC15")
'   %%PERCENTAGE%%   New TNRO-PERCENTAGE
'   %%PACKAGE%%      Package for TR popup (empty = $TMP if prompted)
'   %%TRANSPORT%%    TR (empty = let SNRO decide)
' =============================================================================

Option Explicit

Const NRO_NAME    = "%%NRO_NAME%%"
Const SHORT_TEXT  = "%%SHORT_TEXT%%"
Const LONG_TEXT   = "%%LONG_TEXT%%"
Const DOMLEN      = "%%DOMLEN%%"
Const PERCENTAGE  = "%%PERCENTAGE%%"
Const SAP_PACKAGE = "%%PACKAGE%%"
Const SAP_TRANSP  = "%%TRANSPORT%%"

Const VKEY_ENTER    = 0
Const VKEY_F11_SAVE = 11

Dim oSAPGUI, oApplication, oSession
Dim oCandidate, oSessIter

' ------ 1. Attach -----------------------------------------------------------
On Error Resume Next
Set oSAPGUI = GetObject("SAPGUI")
If Err.Number <> 0 Or oSAPGUI Is Nothing Then
    WScript.Echo "ERROR: SAP GUI is not running."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

Set oApplication = oSAPGUI.GetScriptingEngine
Set oSession = Nothing
On Error Resume Next
For Each oCandidate In oApplication.Children
    For Each oSessIter In oCandidate.Children
        Set oSession = oSessIter
        Exit For
    Next
    If Not (oSession Is Nothing) Then Exit For
Next
On Error GoTo 0

If oSession Is Nothing Then
    WScript.Echo "ERROR: No SAP GUI session found. Run the login step first."
    WScript.Quit 1
End If
WScript.Echo "INFO: Session acquired."

' ------ 2. Navigate to SNRO ----------------------------------------------
WScript.Echo "INFO: Navigating to SNRO..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nSNRO"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Open in Change mode ------------------------------------------
WScript.Echo "INFO: Opening NRO in Change mode: " & UCase(NRO_NAME)
oSession.findById("wnd[0]/usr/ctxtNRIV-OBJECT").Text = UCase(NRO_NAME)
WScript.Sleep 200
On Error Resume Next
oSession.findById("wnd[0]/usr/btnCHANGE").press
If Err.Number <> 0 Then
    Err.Clear
    ' Some releases label the change button differently — fall back to F6
    oSession.findById("wnd[0]").sendVKey 6
End If
On Error GoTo 0
WScript.Sleep 1500

Dim sTitle
sTitle = oSession.findById("wnd[0]").Text
If InStr(LCase(sTitle), "change") = 0 Then
    WScript.Echo "ERROR: Could not enter Change mode. Title=[" & sTitle & "] Status=[" & _
                 oSession.findById("wnd[0]/sbar").Text & "]"
    WScript.Quit 1
End If
WScript.Echo "INFO: " & sTitle

' ------ 4. Update fields conditionally ----------------------------------
If SHORT_TEXT <> "" Then
    On Error Resume Next
    oSession.findById("wnd[0]/usr/txtTNROT-TXTSHORT").Text = SHORT_TEXT
    If Err.Number <> 0 Then Err.Clear
    On Error GoTo 0
    WScript.Echo "INFO: Short text -> " & SHORT_TEXT
End If

If LONG_TEXT <> "" Then
    On Error Resume Next
    oSession.findById("wnd[0]/usr/txtTNROT-TXT").Text = LONG_TEXT
    If Err.Number <> 0 Then Err.Clear
    On Error GoTo 0
    WScript.Echo "INFO: Long text -> " & LONG_TEXT
End If

Dim sFc1
sFc1 = "wnd[0]/usr/tabsNUMMERNKREIS/tabpNUMMERNKREIS_FC1/ssubNUMMERNKREIS_SCA:SAPLSNR2:1201"

If DOMLEN <> "" Then
    On Error Resume Next
    oSession.findById(sFc1 & "/txtTNRO-DOMLEN").Text = DOMLEN
    If Err.Number <> 0 Then
        WScript.Echo "ERROR: Could not set TNRO-DOMLEN — " & Err.Description
        WScript.Quit 1
    End If
    On Error GoTo 0
    WScript.Echo "INFO: Domain length -> " & DOMLEN
End If

If PERCENTAGE <> "" Then
    On Error Resume Next
    oSession.findById(sFc1 & "/txtTNRO-PERCENTAGE").Text = PERCENTAGE
    If Err.Number <> 0 Then Err.Clear
    On Error GoTo 0
    WScript.Echo "INFO: Warning % -> " & PERCENTAGE
End If

' Validate
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 600

' ------ 5. Save ----------------------------------------------------------
WScript.Echo "INFO: Saving..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1500

' ------ 6. Package / transport popup (3-way pattern) -------------------
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    If SAP_PACKAGE <> "" And SAP_TRANSP <> "" Then
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1000
        If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
            oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR").Text = SAP_TRANSP
            oSession.findById("wnd[1]").sendVKey VKEY_ENTER
            WScript.Sleep 1000
        End If
    ElseIf SAP_PACKAGE <> "" Then
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1000
        If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
            oSession.findById("wnd[1]/tbar[0]/btn[8]").press
            WScript.Sleep 1000
            On Error Resume Next
            oSession.findById("wnd[2]/usr/txtKO013-AS4TEXT").Text = "NRO " & UCase(NRO_NAME)
            oSession.findById("wnd[2]/tbar[0]/btn[0]").press
            WScript.Sleep 1000
            oSession.findById("wnd[1]/tbar[0]/btn[0]").press
            WScript.Sleep 1000
            On Error GoTo 0
        End If
    Else
        oSession.findById("wnd[1]/tbar[0]/btn[7]").press   ' Local object
        WScript.Sleep 1500
    End If
End If
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSession.ActiveWindow.sendVKey VKEY_ENTER
    WScript.Sleep 800
End If
Err.Clear
On Error GoTo 0

Dim sStatus
sStatus = ""
On Error Resume Next
sStatus = oSession.findById("wnd[0]/sbar").Text
On Error GoTo 0
WScript.Echo "INFO: Status: " & sStatus

If InStr(LCase(sStatus), "error") > 0 Or InStr(LCase(sStatus), "not saved") > 0 Then
    WScript.Echo "ERROR: Save failed. Status: " & sStatus
    WScript.Quit 1
End If

On Error Resume Next
oSession.findById("wnd[0]/tbar[0]/btn[15]").press
WScript.Sleep 400
oSession.findById("wnd[0]/tbar[0]/btn[15]").press
WScript.Sleep 400
Err.Clear
On Error GoTo 0

WScript.Echo "SUCCESS: Number Range Object " & UCase(NRO_NAME) & " updated."
WScript.Quit 0
