' =============================================================================
' sap_snro_update.vbs  -  SAP GUI Scripting: Update existing Number Range Object
'
' Generated by the sap-snro skill.
' Attaches to an existing SAP GUI session, navigates to SNRO, opens the NRO
' in Change mode (btnUPDATE), updates only the header fields whose token is
' non-empty (Short Text, Long Text, Domain length, Warning %), saves, and
' handles the package/transport popup.
'
' Tokens replaced at run time (empty token = leave field unchanged):
'   %%NRO_NAME%%     NRO name (UPPERCASE)           e.g. "ZMM_0004"
'   %%SHORT_TEXT%%   New TNROT-TXTSHORT
'   %%LONG_TEXT%%    New TNROT-TXT
'   %%DOMLEN%%       New TNRO-DOMLEN (e.g. "NUMC15")
'   %%PERCENTAGE%%   New TNRO-PERCENTAGE
'   %%PACKAGE%%      Package for TR popup (empty = $TMP if prompted)
'   %%TRANSPORT%%    TR (empty = let SNRO decide)
' =============================================================================

Option Explicit

Const NRO_NAME    = "%%NRO_NAME%%"
Const SHORT_TEXT  = "%%SHORT_TEXT%%"
Const LONG_TEXT   = "%%LONG_TEXT%%"
Const DOMLEN      = "%%DOMLEN%%"
Const PERCENTAGE  = "%%PERCENTAGE%%"
Const SAP_PACKAGE = "%%PACKAGE%%"
Const SAP_TRANSP  = "%%TRANSPORT%%"
Const SESSION_PATH = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER    = 0
Const VKEY_F11_SAVE = 11

' Include shared attach helper.
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

' ------ 1. Attach (via shared attach helper) -------------------------------
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SNRO ----------------------------------------------
WScript.Echo "INFO: Navigating to SNRO..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nSNRO"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Open in Change mode ------------------------------------------
WScript.Echo "INFO: Opening NRO in Change mode: " & UCase(NRO_NAME)
oSession.findById("wnd[0]/usr/ctxtNRIV-OBJECT").Text = UCase(NRO_NAME)
WScript.Sleep 200
On Error Resume Next
' The Change button on SNRO's initial screen (SAPMSNRO/150) is btnUPDATE, NOT
' btnCHANGE -- verified by live control enumeration on S/4HANA 1909 AND ECC 6.0
' (2026-07-24): the usr area exposes exactly btnDISPLAY / btnUPDATE / btnINSERT.
' btnCHANGE does not exist on either release, so this press always failed.
oSession.findById("wnd[0]/usr/btnUPDATE").press
If Err.Number <> 0 Then
    Err.Clear
    ' Some releases label the change button differently -- fall back to F6
    oSession.findById("wnd[0]").sendVKey 6
End If
On Error GoTo 0
WScript.Sleep 1500

' Verify we entered Change mode -- locale-independently (per
' language_independence_rules.md; mirrors sap_snro_check.vbs). On the SNRO
' initial screen the name field ctxtNRIV-OBJECT is present; once the NRO opens in
' Change mode we are off the initial screen (that field is gone) and the header
' field txtTNROT-TXTSHORT is present. Title-text matching on "change" was
' English-only and blocked all updates under ZH/JA logons.
Dim bStillOnInitial, oInitProbe
On Error Resume Next
Set oInitProbe = Nothing
Set oInitProbe = oSession.findById("wnd[0]/usr/ctxtNRIV-OBJECT")
bStillOnInitial = (Err.Number = 0) And Not (oInitProbe Is Nothing)
Err.Clear
On Error GoTo 0
If bStillOnInitial Then
    Dim sInitStatus
    sInitStatus = ""
    On Error Resume Next
    sInitStatus = oSession.findById("wnd[0]/sbar").Text
    On Error GoTo 0
    WScript.Echo "ERROR: Could not enter Change mode (still on initial screen). Status=[" & sInitStatus & "]"
    WScript.Quit 1
End If
WScript.Echo "INFO: NRO " & UCase(NRO_NAME) & " opened in Change mode."

' ------ 4. Update fields conditionally ----------------------------------
If SHORT_TEXT <> "" Then
    On Error Resume Next
    oSession.findById("wnd[0]/usr/txtTNROT-TXTSHORT").Text = SHORT_TEXT
    If Err.Number <> 0 Then Err.Clear
    On Error GoTo 0
    WScript.Echo "INFO: Short text -> " & SHORT_TEXT
End If

If LONG_TEXT <> "" Then
    On Error Resume Next
    oSession.findById("wnd[0]/usr/txtTNROT-TXT").Text = LONG_TEXT
    If Err.Number <> 0 Then Err.Clear
    On Error GoTo 0
    WScript.Echo "INFO: Long text -> " & LONG_TEXT
End If

Dim sFc1
sFc1 = "wnd[0]/usr/tabsNUMMERNKREIS/tabpNUMMERNKREIS_FC1/ssubNUMMERNKREIS_SCA:SAPLSNR2:1201"

If DOMLEN <> "" Then
    On Error Resume Next
    oSession.findById(sFc1 & "/txtTNRO-DOMLEN").Text = DOMLEN
    If Err.Number <> 0 Then
        WScript.Echo "ERROR: Could not set TNRO-DOMLEN -- " & Err.Description
        WScript.Quit 1
    End If
    On Error GoTo 0
    WScript.Echo "INFO: Domain length -> " & DOMLEN
End If

If PERCENTAGE <> "" Then
    On Error Resume Next
    oSession.findById(sFc1 & "/txtTNRO-PERCENTAGE").Text = PERCENTAGE
    If Err.Number <> 0 Then Err.Clear
    On Error GoTo 0
    WScript.Echo "INFO: Warning % -> " & PERCENTAGE
End If

' Validate
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 600

' ------ 5. Save ----------------------------------------------------------
WScript.Echo "INFO: Saving..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1500

' ------ 6. Package / transport popup (3-way pattern) -------------------
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    If SAP_PACKAGE <> "" And SAP_TRANSP <> "" Then
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1000
        If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
            oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR").Text = SAP_TRANSP
            oSession.findById("wnd[1]").sendVKey VKEY_ENTER
            WScript.Sleep 1000
        End If
    ElseIf SAP_PACKAGE <> "" Then
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1000
        If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
            oSession.findById("wnd[1]/tbar[0]/btn[8]").press
            WScript.Sleep 1000
            On Error Resume Next
            oSession.findById("wnd[2]/usr/txtKO013-AS4TEXT").Text = "NRO " & UCase(NRO_NAME)
            oSession.findById("wnd[2]/tbar[0]/btn[0]").press
            WScript.Sleep 1000
            oSession.findById("wnd[1]/tbar[0]/btn[0]").press
            WScript.Sleep 1000
            On Error GoTo 0
        End If
    Else
        oSession.findById("wnd[1]/tbar[0]/btn[7]").press   ' Local object
        WScript.Sleep 1500
    End If
End If
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSession.ActiveWindow.sendVKey VKEY_ENTER
    WScript.Sleep 800
End If
Err.Clear
On Error GoTo 0

Dim sStatus, sStatusType
sStatus = "" : sStatusType = ""
On Error Resume Next
sStatus     = oSession.findById("wnd[0]/sbar").Text
sStatusType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0
WScript.Echo "INFO: Status [" & sStatusType & "]: " & sStatus

' Locale-independent verdict: branch on the MessageType code (S/W/E/I/A), never
' on translated text. The pre-fix English substring match silently passed a real
' failure on any non-EN logon, reporting a false SUCCESS while the NRO was not
' written (Audit P5).
If LCase(sStatusType) = "e" Or LCase(sStatusType) = "a" Then
    WScript.Echo "ERROR: Save failed - " & sStatus
    WScript.Quit 1
End If

On Error Resume Next
oSession.findById("wnd[0]/tbar[0]/btn[15]").press
WScript.Sleep 400
oSession.findById("wnd[0]/tbar[0]/btn[15]").press
WScript.Sleep 400
Err.Clear
On Error GoTo 0

WScript.Echo "SUCCESS: Number Range Object " & UCase(NRO_NAME) & " updated."
WScript.Quit 0
