' =============================================================================
' sap_se11_typegroup_update.vbs  -  SAP GUI Scripting: Update type group in SE11
'
' Generated by the sap-se11 skill.
' Opens an existing type group in Change mode, replaces the source text
' from a definition file (raw ABAP source), saves, and activates.
'
' Tokens replaced at run time:
'   %%OBJECT_NAME%%      Type group name       e.g. "ZTYP"
'   %%DEFINITION_FILE%%  Absolute path to ABAP source file
'
' Definition file is raw ABAP source (same as create).
'
' Component IDs recorded from SAP S4D system (S/4HANA).
' =============================================================================

Option Explicit

Const OBJECT_NAME     = "%%OBJECT_NAME%%"
Const DEFINITION_FILE = "%%DEFINITION_FILE%%"
Const SAP_PACKAGE     = "%%PACKAGE%%"
Const SAP_TRANSPORT   = "%%TRANSPORT%%"
Const SESSION_PATH    = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER    = 0
Const VKEY_F3_BACK  = 3
Const VKEY_F11_SAVE = 11

' Include shared attach helper.
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

' UTF-8/16 BOM-detect text-encoding helper.
' Lets the OpenTextFile read below accept UTF-8 inputs from upstream tools
' (sap-docs-extract, the Write tool, hand-authored TSVs) -- full docstring
' in sap_se11_table_create.vbs. Always returns a UTF-16 LE path so callers
' must open the result with mode -1.
Function EnsureUnicodeFile(sSrcPath)
    Dim oFSOLocal, oBin, aBytes, b1, b2, oIn, sText, oOut, sTempPath, sCharset
    Set oFSOLocal = CreateObject("Scripting.FileSystemObject")
    Set oBin = CreateObject("ADODB.Stream") : oBin.Type = 1 : oBin.Open
    oBin.LoadFromFile sSrcPath
    aBytes = oBin.Read(2) : oBin.Close
    b1 = 0 : b2 = 0
    If LenB(aBytes) >= 1 Then b1 = AscB(MidB(aBytes, 1, 1))
    If LenB(aBytes) >= 2 Then b2 = AscB(MidB(aBytes, 2, 1))
    If b1 = &HFF And b2 = &HFE Then EnsureUnicodeFile = sSrcPath : Exit Function
    sCharset = "utf-8"
    If b1 = &HFE And b2 = &HFF Then sCharset = "utf-16BE"
    Set oIn = CreateObject("ADODB.Stream")
    oIn.Type = 2 : oIn.Charset = sCharset : oIn.Open
    oIn.LoadFromFile sSrcPath
    sText = oIn.ReadText : oIn.Close
    sTempPath = oFSOLocal.GetSpecialFolder(2) & "\sap_def_" & _
                oFSOLocal.GetTempName() & ".txt"
    Set oOut = CreateObject("ADODB.Stream")
    oOut.Type = 2 : oOut.Charset = "unicode" : oOut.Open
    oOut.WriteText sText
    oOut.SaveToFile sTempPath, 2
    oOut.Close
    EnsureUnicodeFile = sTempPath
End Function

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SE11 and open type group in Change mode ---------------
WScript.Echo "INFO: Navigating to SE11..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE11"
oSession.findById("wnd[0]").sendVKey 0
WScript.Sleep 1000

oSession.findById("wnd[0]/usr/radRSRD1-TYMA").select
WScript.Sleep 300
oSession.findById("wnd[0]/usr/ctxtRSRD1-TYMA_VAL").Text = UCase(OBJECT_NAME)
WScript.Sleep 300

WScript.Echo "INFO: Opening type group in Change mode: " & UCase(OBJECT_NAME)
oSession.findById("wnd[0]/usr/btnPUSHEDIT").press
WScript.Sleep 1500

' ------ 2a. Original-language mismatch popup (program SAPLSETX) -------------
' If wnd[1] is the "Different original and logon languages" dialog, press
' "Maint. in orig. lang." (btnPUSH1). Keeps TADIR-MASTERLANG unchanged.
' Fingerprint: ctxtRSETX-MASTERLANG present in wnd[1]/usr.
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim oMasterLangFld
    Set oMasterLangFld = Nothing
    Err.Clear
    Set oMasterLangFld = oSession.findById("wnd[1]/usr/ctxtRSETX-MASTERLANG")
    If Err.Number = 0 Then
        If Not (oMasterLangFld Is Nothing) Then
            Dim oMaintBtn
            Set oMaintBtn = Nothing
            Err.Clear
            Set oMaintBtn = oSession.findById("wnd[1]/usr/btnPUSH1")
            If Err.Number = 0 Then
                If Not (oMaintBtn Is Nothing) Then
                    WScript.Echo "INFO: Original-language popup detected (logon != MASTERLANG=" & _
                                 oMasterLangFld.Text & ") -- pressing 'Maint. in orig. lang.'."
                    oMaintBtn.press
                    WScript.Sleep 1500
                End If
            End If
        End If
    End If
End If
Err.Clear
On Error GoTo 0

' ------ 2b. Pre-save TR claim --------------------------------------------------
' Send Ctrl+S to provoke any "Prompt for local Workbench request" popup.
' (a) wnd[1] with ctxtKO008-TRKORR -> fill SAP_TRANSPORT, Enter.
' (b) Other popup -> Enter to dismiss.
' (c) No popup -> object is local ($TMP) or already locked to a modifiable TR.
' Diagnostics: TADIR-DEVCLASS, E071, E070-TRSTATUS.
WScript.Echo "INFO: Pre-save (Ctrl+S) to check whether a TR popup appears..."
On Error Resume Next
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1500
Err.Clear
On Error GoTo 0

On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim oPreTR
    Set oPreTR = oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR")
    If Err.Number = 0 And Not (oPreTR Is Nothing) Then
        Err.Clear
        If SAP_TRANSPORT = "" Then
            WScript.Echo "ERROR: SE11 prompted for a transport request but SAP_TRANSPORT is empty." & vbCrLf & _
                         "       Resolve a modifiable TR via /sap-transport-request and re-run."
            WScript.Quit 1
        End If
        oPreTR.Text = SAP_TRANSPORT
        WScript.Echo "INFO: Pre-save TR popup detected -- entering " & SAP_TRANSPORT & "."
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1000
    Else
        Err.Clear
        WScript.Echo "INFO: Pre-save popup (no TR field) -- pressing Enter to dismiss."
        oSession.ActiveWindow.sendVKey VKEY_ENTER
        WScript.Sleep 800
    End If
Else
    WScript.Echo "INFO: No pre-save popup -- object is local ($TMP) or already locked to a modifiable TR."
End If
Err.Clear
On Error GoTo 0

' ------ 3. Read source lines from definition file ---------------------------
Dim oFSO, oFile
Set oFSO = CreateObject("Scripting.FileSystemObject")

If Not oFSO.FileExists(DEFINITION_FILE) Then
    WScript.Echo "ERROR: Definition file not found: " & DEFINITION_FILE
    WScript.Quit 1
End If

Dim arrLines()
Dim iLineCount
iLineCount = 0

Set oFile = oFSO.OpenTextFile(EnsureUnicodeFile(DEFINITION_FILE), 1, False, -1)
Do While Not oFile.AtEndOfStream
    ReDim Preserve arrLines(iLineCount)
    arrLines(iLineCount) = oFile.ReadLine
    iLineCount = iLineCount + 1
Loop
oFile.Close

WScript.Echo "INFO: Read " & iLineCount & " source lines."

' ------ 4. Replace source via editor control or upload ----------------------
Dim sFullSource, i
sFullSource = ""
For i = 0 To iLineCount - 1
    If i > 0 Then sFullSource = sFullSource & vbCrLf
    sFullSource = sFullSource & arrLines(i)
Next

On Error Resume Next

Dim oEditor
Set oEditor = oSession.findById("wnd[0]/usr/txtED_EDIT-36[0,0]")
If Err.Number <> 0 Then
    Err.Clear
    Set oEditor = oSession.findById("wnd[0]/usr/cntlEDITOR_CONTAINER/shellcont/shell")
    If Err.Number <> 0 Then
        Err.Clear
        Set oEditor = oSession.findById("wnd[0]/usr/cntlED_EDIT/shellcont/shell")
    End If
End If

If Not (oEditor Is Nothing) And Err.Number = 0 Then
    WScript.Echo "INFO: Found editor control, replacing source..."
    
    oEditor.SetSelAll
    WScript.Sleep 200
    
    Dim bInserted
    bInserted = False
    
    ' Clear existing content first
    oEditor.SetSelAll
    oEditor.PressKeys "{DEL}", 0
    WScript.Sleep 200
    
    For i = 0 To iLineCount - 1
        oEditor.SetLineText i + 1, arrLines(i)
        If Err.Number <> 0 Then
            Err.Clear
            Exit For
        End If
        bInserted = True
    Next
    
    If Not bInserted Then
        Err.Clear
        Dim oIE
        Set oIE = CreateObject("htmlfile")
        oIE.ParentWindow.ClipboardData.SetData "text", sFullSource
        Set oIE = Nothing
        
        oEditor.SetSelAll
        WScript.Sleep 200
        oEditor.PressKeys "v", 2  ' Ctrl+V
        WScript.Sleep 500
    End If
    Err.Clear
Else
    Err.Clear
    WScript.Echo "INFO: Using file upload approach..."
    
    oSession.findById("wnd[0]/mbar/menu[3]/menu[5]").select
    If Err.Number <> 0 Then
        Err.Clear
        oSession.findById("wnd[0]/mbar/menu[3]/menu[3]").select
        If Err.Number <> 0 Then
            Err.Clear
            oSession.findById("wnd[0]/mbar/menu[2]/menu[5]").select
        End If
    End If
    WScript.Sleep 1000
    
    If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
        oSession.findById("wnd[1]/usr/ctxtDY_FILENAME").Text = DEFINITION_FILE
        WScript.Sleep 300
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 2000
    End If
End If
On Error GoTo 0

' ------ 5. Save (F11) -------------------------------------------------------
WScript.Echo "INFO: Saving type group..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1500

On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    If SAP_PACKAGE <> "" And UCase(SAP_PACKAGE) <> "$TMP" And SAP_TRANSPORT <> "" Then
        ' Case 1: Both package and transport provided
        WScript.Echo "INFO: Assigning to package " & SAP_PACKAGE & " with transport " & SAP_TRANSPORT & "..."
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR").Text = SAP_TRANSPORT
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
    ElseIf SAP_PACKAGE <> "" And UCase(SAP_PACKAGE) <> "$TMP" And SAP_TRANSPORT = "" Then
        ' Case 3: Package provided, no transport -> create new transport
        WScript.Echo "INFO: Assigning to package " & SAP_PACKAGE & " (creating new transport)..."
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/tbar[0]/btn[8]").press
        WScript.Sleep 1000
        oSession.findById("wnd[2]/usr/txtKO013-AS4TEXT").Text = UCase(OBJECT_NAME)
        oSession.findById("wnd[2]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
    Else
        ' Case 2: No package or $TMP -> Local Object
        WScript.Echo "INFO: Saving as local object ($TMP)..."
        oSession.findById("wnd[1]/tbar[0]/btn[7]").press
        WScript.Sleep 1000
    End If
End If
Err.Clear
On Error GoTo 0
WScript.Echo "INFO: Saved."

' ------ 6. Activate (Ctrl+F3) -----------------------------------------------
WScript.Echo "INFO: Activating..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[1]/btn[27]").press
WScript.Sleep 3000
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSession.ActiveWindow.sendVKey VKEY_ENTER
    WScript.Sleep 1500
End If
Err.Clear
On Error GoTo 0

Dim sFinalMsg, sFinalType
On Error Resume Next
sFinalMsg  = oSession.findById("wnd[0]/sbar").Text
sFinalType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

If sFinalType = "E" Then
    WScript.Echo "WARNING: Activation may have errors - " & sFinalMsg
Else
    WScript.Echo "INFO: SAP status: " & sFinalMsg
End If

WScript.Echo "SUCCESS: Type group " & UCase(OBJECT_NAME) & " updated and activated in SAP."
WScript.Quit 0
