' =============================================================================
' sap_se11_table_create.vbs  -  SAP GUI Scripting: Create database table in SE11
'
' Generated by the sap-se11 skill.
' Attaches to an existing SAP GUI session, navigates to SE11, creates a new
' database table, fills fields from a tab-delimited definition file, sets
' technical settings and enhancement category, saves, checks, and activates.
'
' Tokens replaced at run time:
'   %%OBJECT_NAME%%          Table name            e.g. "ZTABLE001"
'   %%OBJECT_DESCRIPTION%%   Short description     e.g. "My Custom Table"
'   %%DELIVERY_CLASS%%       Delivery class        e.g. "A" (A/C/L/G/E/S/W)
'   %%DATA_CLASS%%           Data class            e.g. "APPL0"
'   %%SIZE_CATEGORY%%        Size category         e.g. "0" (0-4)
'   %%DEFINITION_FILE%%      Absolute path to tab-delimited field definitions
'   %%PACKAGE%%              SAP package (empty = $TMP)
'   %%TRANSPORT%%            Transport request number (empty = local or new)
'
' Definition file format (tab-delimited, first line is header):
'   FIELDNAME	KEY	INITIAL	DATAELEMENT	ReferenceTable	Ref.Field
'   MANDT	X	X	MANDT
'   BUKRS	X	X	BUKRS
'   AMT			DZWERT	ZHKTBL001	WAERK
'
' Component IDs recorded from SAP S/4HANA 1909 system.
' =============================================================================

Option Explicit

Const OBJECT_NAME        = "%%OBJECT_NAME%%"
Const OBJECT_DESCRIPTION = "%%OBJECT_DESCRIPTION%%"
Const DELIVERY_CLASS     = "%%DELIVERY_CLASS%%"
Const DATA_CLASS         = "%%DATA_CLASS%%"
Const SIZE_CATEGORY      = "%%SIZE_CATEGORY%%"
Const DEFINITION_FILE    = "%%DEFINITION_FILE%%"
Const SAP_PACKAGE        = "%%PACKAGE%%"
Const SAP_TRANSPORT      = "%%TRANSPORT%%"
' Enhancement category to set BEFORE Activate so SAP doesn't warn / pop up.
' Accepted: NOT_EXTENSIBLE (default), FLAT, FLAT_NUMERIC, DEEP. See
' sap_se11_set_enh_category.vbs for the full mapping.
Const ENH_CATEGORY       = "%%ENHANCEMENT_CATEGORY%%"
Const SESSION_PATH       = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default
Const POST_ACTIVATE_VERIFY_PS1 = "%%POST_ACTIVATE_VERIFY_PS1%%"   ' empty = skip verify

Const VKEY_ENTER    = 0
Const VKEY_F3_BACK  = 3
Const VKEY_F11_SAVE = 11

' Include shared helpers (attach first; session-lock's pre-unlock sweep
' reads from oSession).
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%POST_ACTIVATE_VERIFY_VBS%%", 1).ReadAll()

' Include shared activation-log capture (CaptureActivationLog /
' ExtractTopActivationError). Used after Activate (Ctrl+F3) when
' sbar.MessageType = "E" or "A" to write the SE11 activation log to a
' local file so the operator sees the *specific* failure (e.g. which
' field is missing a reference table) instead of just "refer to log".
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ACTIVATION_LOG_VBS%%", 1).ReadAll()

' Include SE11-local enhancement-category helper (SetEnhancementCategory).
' Used after Save and before Activate so the activation step doesn't
' surface "Table/Structure is not flagged for any enhancement category".
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ENH_CATEGORY_VBS%%", 1).ReadAll()

' ----------------------------------------------------------------------------
' Helper: ensure the definition file is in UTF-16 LE so the existing
' OpenTextFile(..., -1) reads succeed regardless of the source encoding.
'
' Background: every read pass in this script uses FSO mode -1 (Unicode), but
' upstream tools (sap-docs-extract, customer-authored TSVs, the Write tool)
' emit UTF-8. Feeding UTF-8 bytes to mode -1 produces silent garbage and
' the VBS parses zero usable rows, surfacing as "DATATYPE is empty in
' definition file." Sibling skill sap-se91 already handles UTF-8 natively
' via ADODB.Stream; this helper brings sap-se11 to parity without rewriting
' every read loop.
'
' BOM detection on first 3 bytes:
'   FF FE       -> already UTF-16 LE: return path unchanged
'   FE FF       -> UTF-16 BE: re-encode to a temp UTF-16 LE file
'   EF BB BF    -> UTF-8 with BOM: re-encode
'   anything else (incl. no BOM) -> assume UTF-8, re-encode
' Returns the path that OpenTextFile(..., -1) will read correctly.
' ----------------------------------------------------------------------------
Function EnsureUnicodeFile(sSrcPath)
    Dim oFSOLocal, oBin, aBytes, b1, b2
    Dim oIn, sText, oOut, sTempPath, sCharset
    Set oFSOLocal = CreateObject("Scripting.FileSystemObject")
    Set oBin = CreateObject("ADODB.Stream")
    oBin.Type = 1   ' adTypeBinary
    oBin.Open
    oBin.LoadFromFile sSrcPath
    aBytes = oBin.Read(2)
    oBin.Close
    b1 = 0 : b2 = 0
    If LenB(aBytes) >= 1 Then b1 = AscB(MidB(aBytes, 1, 1))
    If LenB(aBytes) >= 2 Then b2 = AscB(MidB(aBytes, 2, 1))
    If b1 = &HFF And b2 = &HFE Then
        EnsureUnicodeFile = sSrcPath
        Exit Function
    End If
    sCharset = "utf-8"
    If b1 = &HFE And b2 = &HFF Then sCharset = "utf-16BE"
    Set oIn = CreateObject("ADODB.Stream")
    oIn.Type = 2 : oIn.Charset = sCharset : oIn.Open
    oIn.LoadFromFile sSrcPath
    sText = oIn.ReadText
    oIn.Close
    sTempPath = oFSOLocal.GetSpecialFolder(2) & "\sap_def_" & _
                oFSOLocal.GetTempName() & ".txt"
    Set oOut = CreateObject("ADODB.Stream")
    oOut.Type = 2 : oOut.Charset = "unicode" : oOut.Open
    oOut.WriteText sText
    oOut.SaveToFile sTempPath, 2   ' adSaveCreateOverWrite
    oOut.Close
    EnsureUnicodeFile = sTempPath
End Function


' ------ 0. Pre-flight: validate definition file --------------------------------
Dim oPFSO
Set oPFSO = CreateObject("Scripting.FileSystemObject")
If Not oPFSO.FileExists(DEFINITION_FILE) Then
    WScript.Echo "ERROR: Definition file not found: " & DEFINITION_FILE
    WScript.Quit 1
End If

' Reject any field row that supplies DATATYPE without DATAELEMENT.
' SAP GUI Scripting cannot fill the DD03P-DATATYPE / -LENG / -DECIMALS
' columns of the SE11 fields grid (Changeable=False on those columns,
' regardless of the row's REFTYPE combobox or "Component Type" toolbar
' button). The table-fields .def format documents this -- the only
' supported field shape is FIELDNAME / KEY / INITIAL / DATAELEMENT.
' Catch the unsupported shape here, before any GUI input.
Dim oPVal, sPLine, aPFlds, iPRow, sPField, sPDE, sPDT
Set oPVal = oPFSO.OpenTextFile(EnsureUnicodeFile(DEFINITION_FILE), 1, False, -1)
If Not oPVal.AtEndOfStream Then oPVal.ReadLine ' header
iPRow = 0
Do While Not oPVal.AtEndOfStream
    sPLine = oPVal.ReadLine
    If Trim(sPLine) <> "" Then
        aPFlds = Split(sPLine, vbTab)
        sPField = "" : sPDE = "" : sPDT = ""
        ' Table .def column order: FIELDNAME / KEY / INITIAL / DATAELEMENT / RefTable / RefField
        If UBound(aPFlds) >= 0 Then sPField = Trim(aPFlds(0))
        If UBound(aPFlds) >= 3 Then sPDE    = Trim(aPFlds(3))
        ' Optional 7th col (DATATYPE) is not part of the documented format
        ' but operators sometimes paste it; flag it as a misuse.
        If UBound(aPFlds) >= 6 Then sPDT    = Trim(aPFlds(6))
        If sPField <> "" _
           And Left(sPField, 1) <> "." _
           And sPDE = "" And sPDT <> "" Then
            WScript.Echo "ERROR: Field '" & sPField & "' (row " & iPRow & ") supplies direct DATATYPE='" & sPDT & "'."
            WScript.Echo "       SAP GUI Scripting cannot fill DD03P-DATATYPE on the SE11 fields grid."
            WScript.Echo "       Predefine a data element via /sap-se11 DATAELEMENT and reference it in"
            WScript.Echo "       the DATAELEMENT column (col 4) of this row, then re-run."
            oPVal.Close
            WScript.Quit 1
        End If
        iPRow = iPRow + 1
    End If
Loop
oPVal.Close
WScript.Echo "INFO: Definition file validated OK."

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) --------
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SE11 and create new table --------------------------------
WScript.Echo "INFO: Navigating to SE11..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE11"
oSession.findById("wnd[0]").sendVKey 0
WScript.Sleep 1000

' Select Database table radio and enter name
oSession.findById("wnd[0]/usr/radRSRD1-TBMA").select
WScript.Sleep 300
oSession.findById("wnd[0]/usr/ctxtRSRD1-TBMA_VAL").Text = UCase(OBJECT_NAME)
WScript.Sleep 300

' Press Create button
WScript.Echo "INFO: Creating table: " & UCase(OBJECT_NAME)
On Error Resume Next
oSession.findById("wnd[0]/usr/btnPUSHADD").press
WScript.Sleep 1500
If Err.Number <> 0 Then
    WScript.Echo "ERROR: Could not press Create button: " & Err.Description
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

' --- Lock the SAP session UI for the fill fields + save + technical settings + activate critical section ---
' Defence in depth (Rule 7): AppActivate guards external focus stealing;
' LockSessionUI guards in-session input races. Released after activation.
Dim wasLocked : wasLocked = TryLockSession(oSession)
If wasLocked Then
    WScript.Echo "INFO: Session UI locked for the fill fields + save + technical settings + activate critical section."
Else
    WScript.Echo "INFO: LockSessionUI not available on this SAP GUI build; continuing without lock."
End If

' --- Drain the SAPLSETX original-language popup (and any other Information ---
' modal) that SAP shows after Create when logon language <> object's master
' language. Without this, the subsequent findById on wnd[0] fails because
' the active window is the popup at wnd[1], description doesn't get filled,
' the Fields-tab grid writes also no-op against wnd[0], and SE11 saves a
' TADIR shell with empty DD03L. table_update has the same handler at its
' Change-button step; create needs it too.
Dim iSetx, sSetxId
On Error Resume Next
For iSetx = 1 To 3
    sSetxId = oSession.ActiveWindow.Id
    If Err.Number <> 0 Then
        Err.Clear
        Exit For
    End If
    If Right(sSetxId, 6) = "wnd[0]" Then Exit For
    WScript.Echo "INFO: Post-Create popup " & iSetx & " at " & sSetxId & " (" & oSession.ActiveWindow.Text & ") -- pressing Enter (accept default / logon language)."
    oSession.ActiveWindow.sendVKey VKEY_ENTER
    If Err.Number <> 0 Then Err.Clear
    WScript.Sleep 800
Next
On Error GoTo 0

' ------ 3. Fill table description and delivery class ----------------------------
On Error Resume Next
oSession.findById("wnd[0]/usr/txtDD02D-DDTEXT").Text = OBJECT_DESCRIPTION
If Err.Number <> 0 Then
    WScript.Echo "ERROR: Could not fill table description (active window: " & oSession.ActiveWindow.Id & ")."
    WScript.Echo "       If the active window is wnd[1], an unhandled popup is blocking input. Re-record the popup chain."
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0
WScript.Sleep 300

' Set delivery class and maintenance flag on Delivery and Maintenance tab.
' The subscreen path varies by S/4HANA release -- recorded on 1909 as
' SAPLSD41:2202 under tabpMAIN, but other builds expose tabpHEAD or move
' the fields to a different subscreen number (2201, 2203). Walk a
' candidate list and use the first one that accepts the write. If all
' fail, warn loudly so the operator knows delivery class wasn't set
' (table will activate but with the SAP default class instead of the
' spec-supplied one).
Dim deliveryBases : deliveryBases = Array( _
    "wnd[0]/usr/tabsTAB_STRIP/tabpMAIN/ssubTS_SCREEN:SAPLSD41:2202/", _
    "wnd[0]/usr/tabsTAB_STRIP/tabpMAIN/ssubTS_SCREEN:SAPLSD41:2201/", _
    "wnd[0]/usr/tabsTAB_STRIP/tabpMAIN/ssubTS_SCREEN:SAPLSD41:2203/", _
    "wnd[0]/usr/tabsTAB_STRIP/tabpHEAD/ssubTS_SCREEN:SAPLSD41:2202/", _
    "wnd[0]/usr/tabsTAB_STRIP/tabpHEAD/ssubTS_SCREEN:SAPLSD41:2201/", _
    "wnd[0]/usr/tabsTAB_STRIP/tabpMAIN/")
Dim iDb, sDbBase, bDeliverySet : bDeliverySet = False
On Error Resume Next
For iDb = 0 To UBound(deliveryBases)
    sDbBase = deliveryBases(iDb)
    Err.Clear
    oSession.findById(sDbBase & "ctxtDD02D-CONTFLAG").Text = UCase(DELIVERY_CLASS)
    If Err.Number = 0 Then
        oSession.findById(sDbBase & "cmbDD02D-MAINFLAG").Key = "X"
        If Err.Number = 0 Then
            bDeliverySet = True
            WScript.Echo "INFO: Delivery class + maintenance flag set via " & sDbBase
            Exit For
        End If
    End If
    Err.Clear
Next
If Not bDeliverySet Then
    WScript.Echo "WARNING: Could not set delivery class -- none of the " & (UBound(deliveryBases) + 1) & " candidate subscreen paths matched."
    WScript.Echo "         Table will activate with SAP default class (likely 'A'). Re-record the Delivery and Maintenance tab via /sap-gui-record."
End If
Err.Clear
On Error GoTo 0

oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 500
WScript.Echo "INFO: Description and delivery class set."

' ------ 4. Switch to Fields tab and fill fields ---------------------------------
On Error Resume Next
oSession.findById("wnd[0]/usr/tabsTAB_STRIP/tabpDEF").select
WScript.Sleep 500
Err.Clear
On Error GoTo 0

' Read the definition file
Dim oFSO, oFile, sLine, aFields
Set oFSO = CreateObject("Scripting.FileSystemObject")
Set oFile = oFSO.OpenTextFile(EnsureUnicodeFile(DEFINITION_FILE), 1, False, -1)

' Skip header line
If Not oFile.AtEndOfStream Then oFile.ReadLine

' Collect all field data first (for reference tab)
Dim iRow, sFieldName, sKey, sInitial, sDataElement, sRefTable, sRefField
Dim sGridBase, sRefBase
sGridBase = "wnd[0]/usr/tabsTAB_STRIP/tabpDEF/ssubTS_SCREEN:SAPLSD41:2201/tblSAPLSD41TC0"
sRefBase  = "wnd[0]/usr/tabsTAB_STRIP/tabpREFF/ssubTS_SCREEN:SAPLSD41:2103/tblSAPLSD41TC0"

' Arrays to store reference data
Dim arrRefTable(100), arrRefField(100), nTotalRows
nTotalRows = 0

' --- Version-aware column index resolution (added 2026-05-10) ---
' The SE11 table fields grid layout differs between SAP releases. Observed:
'   S/4HANA  : FIELDNAME=0, KEYFLAG=1, NOTNULL=2, ROLLNAME=3
'   ECC      : FIELDNAME=0, KEYFLAG=4, NOTNULL=5, ROLLNAME=6
' Probe columns 0..15 for each known field; cache once at run start so the
' loop below uses the right indices regardless of release. -1 means the
' column was not found at this release; treat as a hard error for the
' two mandatory columns (FIELDNAME, ROLLNAME).
Dim COL_TBL_FIELDNAME, COL_TBL_KEYFLAG, COL_TBL_NOTNULL, COL_TBL_ROLLNAME
COL_TBL_FIELDNAME = ResolveTableGridCol(oSession, sGridBase, "txt",  "DD03D-FIELDNAME")
COL_TBL_KEYFLAG   = ResolveTableGridCol(oSession, sGridBase, "chk",  "DD03P-KEYFLAG")
COL_TBL_NOTNULL   = ResolveTableGridCol(oSession, sGridBase, "chk",  "DD03P-NOTNULL")
COL_TBL_ROLLNAME  = ResolveTableGridCol(oSession, sGridBase, "ctxt", "DD03D-ROLLNAME")
WScript.Echo "INFO: Table grid columns resolved: FIELDNAME=" & COL_TBL_FIELDNAME & " KEYFLAG=" & COL_TBL_KEYFLAG & " NOTNULL=" & COL_TBL_NOTNULL & " ROLLNAME=" & COL_TBL_ROLLNAME
If COL_TBL_FIELDNAME < 0 Or COL_TBL_ROLLNAME < 0 Then
    WScript.Echo "ERROR: Could not locate FIELDNAME or ROLLNAME column in table grid. Layout differs from known SAP releases."
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

iRow = 0
Do While Not oFile.AtEndOfStream
    sLine = oFile.ReadLine
    If Trim(sLine) = "" Then
        ' skip empty lines
    Else
        aFields = Split(sLine, vbTab)
        sFieldName   = ""
        sKey         = ""
        sInitial     = ""
        sDataElement = ""
        sRefTable    = ""
        sRefField    = ""

        If UBound(aFields) >= 0 Then sFieldName   = Trim(aFields(0))
        If UBound(aFields) >= 1 Then sKey         = Trim(aFields(1))
        If UBound(aFields) >= 2 Then sInitial     = Trim(aFields(2))
        If UBound(aFields) >= 3 Then sDataElement = Trim(aFields(3))
        If UBound(aFields) >= 4 Then sRefTable    = Trim(aFields(4))
        If UBound(aFields) >= 5 Then sRefField    = Trim(aFields(5))

        If sFieldName <> "" Then
            WScript.Echo "INFO: Adding field [" & iRow & "]: " & sFieldName

            On Error Resume Next
            ' Field name
            oSession.findById(sGridBase & "/txtDD03D-FIELDNAME[" & COL_TBL_FIELDNAME & "," & iRow & "]").Text = UCase(sFieldName)
            ' Key flag
            If UCase(sKey) = "X" And COL_TBL_KEYFLAG >= 0 Then
                oSession.findById(sGridBase & "/chkDD03P-KEYFLAG[" & COL_TBL_KEYFLAG & "," & iRow & "]").Selected = True
            End If
            ' Initial/Not Null flag
            If UCase(sInitial) = "X" And COL_TBL_NOTNULL >= 0 Then
                oSession.findById(sGridBase & "/chkDD03P-NOTNULL[" & COL_TBL_NOTNULL & "," & iRow & "]").Selected = True
            End If
            ' Data element
            If sDataElement <> "" Then
                oSession.findById(sGridBase & "/ctxtDD03D-ROLLNAME[" & COL_TBL_ROLLNAME & "," & iRow & "]").Text = UCase(sDataElement)
            End If
            Err.Clear
            On Error GoTo 0

            ' Store reference data for later
            arrRefTable(iRow) = sRefTable
            arrRefField(iRow) = sRefField

            iRow = iRow + 1

            ' Scroll grid periodically (22 visible rows)
            If iRow Mod 22 = 0 Then
                oSession.findById("wnd[0]").sendVKey VKEY_ENTER
                WScript.Sleep 500
            End If
        End If
    End If
Loop
oFile.Close
nTotalRows = iRow

' Note: NO trailing sendVKey VKEY_ENTER here. The recording
' Record_SE11_EnhancementCategory_03.vbs (2026-05-11) shows the menu
' flow requires the editor in an un-auto-validated state to open the
' radio dialog cleanly. Inserting Enter triggers extra info popups.
WScript.Sleep 500
Dim nPopupLoop : nPopupLoop = 0   ' kept for the reference-tab popup loop below
WScript.Echo "INFO: " & nTotalRows & " fields added."

' ------ 5. Fill Reference tab (if any fields have reference table/field) --------
Dim bHasRef, iRef
bHasRef = False
For iRef = 0 To nTotalRows - 1
    If arrRefTable(iRef) <> "" And arrRefField(iRef) <> "" Then
        bHasRef = True
        Exit For
    End If
Next

If bHasRef Then
    WScript.Echo "INFO: Setting reference table/field entries..."
    On Error Resume Next
    oSession.findById("wnd[0]/usr/tabsTAB_STRIP/tabpREFF").select
    WScript.Sleep 500
    Err.Clear
    On Error GoTo 0

    ' Detect Currency/Quantity Fields tab column layout. Two layouts seen:
    '   Layout A (older):  [Short Desc, Field, DTEL, Type, RefTable, RefField]
    '                      -> REFTABLE at column 4, REFFIELD at column 5
    '   Layout B (newer):  [Field, DTEL, Type, RefTable, RefField, Short Desc]
    '                      -> REFTABLE at column 3, REFFIELD at column 4
    ' The DDIC field name (DD03P_D-REFTABLE / -REFFIELD) is identical on
    ' both -- only the column index differs. Probe column 4 first; if it
    ' doesn't exist, fall back to column 3.
    Dim nColRefTab : nColRefTab = 4
    Dim nColRefFld : nColRefFld = 5
    On Error Resume Next
    Dim oProbe : Set oProbe = Nothing
    Set oProbe = oSession.findById(sRefBase & "/txtDD03P_D-REFTABLE[4,0]")
    If Err.Number <> 0 Or oProbe Is Nothing Then
        Err.Clear
        Set oProbe = Nothing
        Set oProbe = oSession.findById(sRefBase & "/txtDD03P_D-REFTABLE[3,0]")
        If Err.Number = 0 And Not (oProbe Is Nothing) Then
            nColRefTab = 3
            nColRefFld = 4
            WScript.Echo "INFO: Currency/Qty layout B detected -- REFTABLE col 3, REFFIELD col 4 (Short Desc at end)."
        Else
            ' Neither column 4 nor 3 worked -- table empty or layout unknown.
            ' Keep the col-4/5 default; the per-row writes below are wrapped
            ' in On Error Resume Next so silent no-op is the failure mode.
            WScript.Echo "WARN: Could not probe Currency/Qty column layout -- using default cols 4/5. Rows may not write."
        End If
        Err.Clear
    Else
        WScript.Echo "INFO: Currency/Qty layout A detected -- REFTABLE col 4, REFFIELD col 5 (Short Desc first)."
    End If
    On Error GoTo 0

    For iRef = 0 To nTotalRows - 1
        If arrRefTable(iRef) <> "" And arrRefField(iRef) <> "" Then
            On Error Resume Next
            oSession.findById(sRefBase & "/txtDD03P_D-REFTABLE[" & nColRefTab & "," & iRef & "]").Text = UCase(arrRefTable(iRef))
            oSession.findById(sRefBase & "/txtDD03P_D-REFFIELD[" & nColRefFld & "," & iRef & "]").Text = UCase(arrRefField(iRef))
            Err.Clear
            On Error GoTo 0
            WScript.Echo "INFO: Ref [" & iRef & "]: " & arrRefTable(iRef) & "." & arrRefField(iRef)
        End If
    Next

    ' Note: NO trailing sendVKey VKEY_ENTER here either -- same reason as
    ' the Fields tab above. Auto-validate would block the menu flow.
    WScript.Sleep 500
End If

' ------ 5b. Set Enhancement Category (matches recording 2026-05-11) -------
'
' Place the helper RIGHT AFTER fields + reference data are filled, BEFORE
' the first Save. See sap_se11_structure_create.vbs Step 5b for the full
' recording-based rationale. SetEnhancementCategory commits the chosen
' radDESED7-* into the unsaved edit; the subsequent Save then persists
' the new EXCLASS along with the table definition in one shot.
'
' setFocus on the last field's ROLLNAME cell to mirror the recording's
' "focus on last row" state before menu click. Uses the same grid base
' + resolved column index as the field-fill loop above.
On Error Resume Next
If nTotalRows > 0 Then
    oSession.findById(sGridBase & "/ctxtDD03D-ROLLNAME[" & COL_TBL_ROLLNAME & "," & (nTotalRows - 1) & "]").SetFocus
End If
Err.Clear
On Error GoTo 0

Call SetEnhancementCategory(oSession, ENH_CATEGORY, SAP_TRANSPORT)

' ------ 6. Save (Ctrl+S) -------------------------------------------------------
WScript.Echo "INFO: Saving table..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1500

' Handle package/transport dialog
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    If SAP_PACKAGE <> "" And UCase(SAP_PACKAGE) <> "$TMP" And SAP_TRANSPORT <> "" Then
        ' Case 1: Both package and transport provided
        WScript.Echo "INFO: Assigning to package " & SAP_PACKAGE & " with transport " & SAP_TRANSPORT & "..."
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR").Text = SAP_TRANSPORT
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
    ElseIf SAP_PACKAGE <> "" And UCase(SAP_PACKAGE) <> "$TMP" And SAP_TRANSPORT = "" Then
        ' Case 3: Package provided, no transport -> create new transport
        WScript.Echo "INFO: Assigning to package " & SAP_PACKAGE & " (creating new transport)..."
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/tbar[0]/btn[8]").press
        WScript.Sleep 1000
        oSession.findById("wnd[2]/usr/txtKO013-AS4TEXT").Text = UCase(OBJECT_NAME)
        oSession.findById("wnd[2]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
    Else
        ' Case 2: No package or $TMP -> Local Object
        WScript.Echo "INFO: Saving as local object ($TMP)..."
        oSession.findById("wnd[1]/tbar[0]/btn[7]").press
        WScript.Sleep 1000
    End If
End If
Err.Clear
On Error GoTo 0
WScript.Echo "INFO: Table saved."

' ------ 7. Technical Settings ---------------------------------------------------
WScript.Echo "INFO: Opening Technical Settings..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[1]/btn[45]").press
WScript.Sleep 1000
Err.Clear
On Error GoTo 0

' Fill Data class and Size category.
' NOTE: On S/4HANA 1909 the Tech Settings form fields live directly under
' wnd[0]/usr/ (not inside the SAPMSEDS1:0050 subscreen). Try the flat path
' first, then fall back to the legacy nested path.
Dim sTechBaseFlat, sTechBaseNested
sTechBaseFlat   = "wnd[0]/usr/"
sTechBaseNested = "wnd[0]/usr/tabsTABS/tabpGNRL/ssubTABS_SUBSC:SAPMSEDS1:0050/"
On Error Resume Next
oSession.findById(sTechBaseFlat & "ctxtDD09V-TABART").Text = UCase(DATA_CLASS)
If Err.Number <> 0 Then
    Err.Clear
    oSession.findById(sTechBaseNested & "ctxtDD09V-TABART").Text = UCase(DATA_CLASS)
    oSession.findById(sTechBaseNested & "ctxtDD09V-TABKAT").Text = SIZE_CATEGORY
Else
    oSession.findById(sTechBaseFlat & "ctxtDD09V-TABKAT").Text = SIZE_CATEGORY
End If
Err.Clear
On Error GoTo 0

oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 500

' Save technical settings
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1000

' Handle transport dialog for tech settings (usually not needed if already saved)
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSession.findById("wnd[1]/tbar[0]/btn[7]").press
    WScript.Sleep 500
End If
Err.Clear
On Error GoTo 0

WScript.Echo "INFO: Technical settings saved."

' Go back to table definition
oSession.findById("wnd[0]").sendVKey VKEY_F3_BACK
WScript.Sleep 1000

' Enhancement Category was already set at Step 5b, BEFORE the first Save.
' The chosen EXCLASS was committed by Step 6 (Save) and Step 7 (Tech
' Settings) saves; no second invocation is needed.

' ------ 9. Check (Ctrl+F2) -----------------------------------------------------
WScript.Echo "INFO: Checking table consistency..."
oSession.findById("wnd[0]/tbar[1]/btn[26]").press
WScript.Sleep 2000

' Dismiss check popups
On Error Resume Next
For nPopupLoop = 1 To 10
    WScript.Sleep 500
    If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 500
        Err.Clear
    Else
        Err.Clear
        Exit For
    End If
Next
On Error GoTo 0

Dim sCheckMsg, sCheckType
On Error Resume Next
sCheckMsg  = oSession.findById("wnd[0]/sbar").Text
sCheckType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

If sCheckType = "E" Then
    WScript.Echo "WARNING: Check found issues - " & sCheckMsg
Else
    WScript.Echo "INFO: Check passed."
End If

' ------ 10. Activate (Ctrl+F3) -------------------------------------------------
WScript.Echo "INFO: Activating..."
oSession.findById("wnd[0]/tbar[1]/btn[27]").press
WScript.Sleep 2000

' Dismiss all activation popups. Each popup is classified by DDIC component
' IDs (locale-independent per language_independence_rules.md):
'   (b) 3-button SPOP popup (OPTION1=Yes, OPTION2=No, OPTION3=Cancel):
'       The "Warning during activation -- display activation log?" popup is
'       the canonical case here. Press OPTION2 (No) to skip the log viewer
'       and let activation finish. (Saying Yes opens a log sub-window that
'       blocks the script; the log is still captured separately below if
'       sbar.MessageType ends up E/A.)
'   (c) 2-button SPOP popup (OPTION1 + OPTION2): press OPTION1 (Yes).
'   (d) Information / single-action popup: ENTER.
On Error Resume Next
Dim oTblPop2, oTblPop3, oTblPop1
For nPopupLoop = 1 To 10
    WScript.Sleep 500
    If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
        Set oTblPop2 = Nothing
        Set oTblPop3 = Nothing
        Set oTblPop2 = oSession.findById("wnd[1]/usr/btnSPOP-OPTION2")
        Set oTblPop3 = oSession.findById("wnd[1]/usr/btnSPOP-OPTION3")
        If Err.Number = 0 And Not (oTblPop2 Is Nothing) And Not (oTblPop3 Is Nothing) Then
            oTblPop2.press
            WScript.Echo "INFO: wnd[1] 3-button SPOP popup; pressed OPTION2 (No) to skip activation log."
            WScript.Sleep 800
        Else
            Err.Clear
            Set oTblPop1 = Nothing
            Set oTblPop1 = oSession.findById("wnd[1]/usr/btnSPOP-OPTION1")
            If Err.Number = 0 And Not (oTblPop1 Is Nothing) Then
                oTblPop1.press
                WScript.Echo "INFO: wnd[1] 2-button SPOP popup; pressed OPTION1 (Yes)."
                WScript.Sleep 800
            Else
                Err.Clear
                oSession.findById("wnd[1]").sendVKey VKEY_ENTER
                WScript.Sleep 500
            End If
        End If
        Err.Clear
    Else
        Err.Clear
        Exit For
    End If
Next
On Error GoTo 0

' --- Release the session UI lock; Step 11 is read-only final status ---
ReleaseSession oSession, wasLocked
If wasLocked Then WScript.Echo "INFO: Session UI lock released."

' ------ 11. Final status --------------------------------------------------------
Dim sFinalMsg, sFinalType
On Error Resume Next
sFinalMsg  = oSession.findById("wnd[0]/sbar").Text
sFinalType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

If sFinalType = "E" Or sFinalType = "A" Then
    WScript.Echo "WARNING: Activation may have errors - " & sFinalMsg
    ' Capture the activation log so the operator sees the actual failing
    ' field/rule, not just "refer to log". CaptureActivationLog returns ""
    ' on any failure (missing menu, changed layout, etc.) -- fall back to
    ' the status-bar text in that case.
    Dim sLogPath, sTopErr
    sLogPath = CaptureActivationLog(oSession, OBJECT_NAME, "%%TEMP_DIR%%", _
                                    VKEY_ENTER, VKEY_F3_BACK)
    If Len(sLogPath) > 0 Then
        WScript.Echo "INFO: Activation log saved to: " & sLogPath
        sTopErr = ExtractTopActivationError(sLogPath)
        If Len(sTopErr) > 0 Then
            WScript.Echo "ACTIVATION_ERROR: " & sTopErr
        End If
    Else
        WScript.Echo "INFO: Activation log could not be captured automatically -- open SE11 and use Utilities > Activation Log."
    End If
    WScript.Echo "FAILED: Table " & UCase(OBJECT_NAME) & " was NOT activated. See activation log above."
    WScript.Quit 1
Else
    WScript.Echo "INFO: SAP status: " & sFinalMsg
End If

' Post-activate RFC verify (Phase 4.3 -- mandatory per SKILL.md Step 5d).
PostActivateVerifyOrFail POST_ACTIVATE_VERIFY_PS1, "TABLE", OBJECT_NAME

WScript.Echo "SUCCESS: Table " & UCase(OBJECT_NAME) & " created and activated in SAP."
WScript.Quit 0

' --- Helper: ResolveTableGridCol -------------------------------------------
' Probes the SE11 table-fields grid for the column index that hosts the
' given DDIC component (e.g. "DD03D-FIELDNAME"). Iterates 0..15 at row 0
' and returns the first column where findById succeeds. Returns -1 if the
' field is not present in the grid.
'
' Why: SE11 column indices for the table fields grid differ between
' S/4HANA (FIELDNAME=0, KEYFLAG=1, NOTNULL=2, ROLLNAME=3) and ECC
' (FIELDNAME=0, KEYFLAG=4, NOTNULL=5, ROLLNAME=6). Probing at run start
' keeps the VBS forward-compatible without explicit version branches.
Function ResolveTableGridCol(oSess, sGrid, sPrefix, sName)
    Dim col, sId, oCell
    For col = 0 To 15
        On Error Resume Next
        Set oCell = Nothing
        sId = sGrid & "/" & sPrefix & sName & "[" & col & ",0]"
        Set oCell = oSess.findById(sId)
        On Error GoTo 0
        If Not (oCell Is Nothing) Then
            ResolveTableGridCol = col
            Exit Function
        End If
    Next
    ResolveTableGridCol = -1
End Function
