' =============================================================================
' sap_se11_tabletype_update.vbs  -  SAP GUI Scripting: Update table type in SE11
'
' Generated by the sap-se11 skill.
' Opens an existing table type in Change mode, updates line type, access mode,
' and key definition from the definition file, saves, and activates.
'
' Tokens replaced at run time:
'   %%OBJECT_NAME%%      Table type name       e.g. "ZTT_ITEMS"
'   %%DEFINITION_FILE%%  Absolute path to tab-delimited definition
'
' Definition file format (same as create):
'   Line 1 (header):  LINE_TYPE_CATEGORY	LINE_TYPE_NAME	ACCESS_MODE	KEY_DEF
'   Line 2 (values):  STRUCTURE	ZSITEMS	S	
'
' Component IDs recorded from SAP S4D system (S/4HANA).
' =============================================================================

Option Explicit

Const OBJECT_NAME    = "%%OBJECT_NAME%%"
Const DEFINITION_FILE = "%%DEFINITION_FILE%%"
Const SAP_PACKAGE     = "%%PACKAGE%%"
Const SAP_TRANSPORT   = "%%TRANSPORT%%"

Const VKEY_ENTER    = 0
Const VKEY_F3_BACK  = 3
Const VKEY_F11_SAVE = 11

' UTF-8/16 BOM-detect text-encoding helper.
' Lets the OpenTextFile(..., -1) reads below accept UTF-8 inputs from
' upstream tools (sap-docs-extract, the Write tool, hand-authored TSVs)
' as well as the legacy UTF-16 LE format. Full docstring in
' sap_se11_table_create.vbs.
Function EnsureUnicodeFile(sSrcPath)
    Dim oFSOLocal, oBin, aBytes, b1, b2, oIn, sText, oOut, sTempPath, sCharset
    Set oFSOLocal = CreateObject("Scripting.FileSystemObject")
    Set oBin = CreateObject("ADODB.Stream") : oBin.Type = 1 : oBin.Open
    oBin.LoadFromFile sSrcPath
    aBytes = oBin.Read(2) : oBin.Close
    b1 = 0 : b2 = 0
    If LenB(aBytes) >= 1 Then b1 = AscB(MidB(aBytes, 1, 1))
    If LenB(aBytes) >= 2 Then b2 = AscB(MidB(aBytes, 2, 1))
    If b1 = &HFF And b2 = &HFE Then EnsureUnicodeFile = sSrcPath : Exit Function
    sCharset = "utf-8"
    If b1 = &HFE And b2 = &HFF Then sCharset = "utf-16BE"
    Set oIn = CreateObject("ADODB.Stream")
    oIn.Type = 2 : oIn.Charset = sCharset : oIn.Open
    oIn.LoadFromFile sSrcPath
    sText = oIn.ReadText : oIn.Close
    sTempPath = oFSOLocal.GetSpecialFolder(2) & "\sap_def_" & _
                oFSOLocal.GetTempName() & ".txt"
    Set oOut = CreateObject("ADODB.Stream")
    oOut.Type = 2 : oOut.Charset = "unicode" : oOut.Open
    oOut.WriteText sText
    oOut.SaveToFile sTempPath, 2
    oOut.Close
    EnsureUnicodeFile = sTempPath
End Function

Dim oSAPGUI, oApplication, oSession
Dim oCandidate, oSessIter

' ------ 1. Attach to existing SAP GUI session -------------------------------
On Error Resume Next
Set oSAPGUI = GetObject("SAPGUI")
If Err.Number <> 0 Or oSAPGUI Is Nothing Then
    WScript.Echo "ERROR: SAP GUI is not running."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

Set oApplication = oSAPGUI.GetScriptingEngine
If oApplication Is Nothing Then
    WScript.Echo "ERROR: Could not get SAP Scripting Engine."
    WScript.Quit 1
End If

Set oSession = Nothing
On Error Resume Next
For Each oCandidate In oApplication.Children
    For Each oSessIter In oCandidate.Children
        Set oSession = oSessIter
        Exit For
    Next
    If Not (oSession Is Nothing) Then Exit For
Next
On Error GoTo 0

If oSession Is Nothing Then
    WScript.Echo "ERROR: No SAP GUI session found. Run the login step first."
    WScript.Quit 1
End If
WScript.Echo "INFO: Session acquired."

' ------ 2. Navigate to SE11 and open table type in Change mode ---------------
WScript.Echo "INFO: Navigating to SE11..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE11"
oSession.findById("wnd[0]").sendVKey 0
WScript.Sleep 1000

oSession.findById("wnd[0]/usr/radRSRD1-DDTYPE").select
WScript.Sleep 300
oSession.findById("wnd[0]/usr/ctxtRSRD1-DDTYPE_VAL").Text = UCase(OBJECT_NAME)
WScript.Sleep 300

WScript.Echo "INFO: Opening table type in Change mode: " & UCase(OBJECT_NAME)
oSession.findById("wnd[0]/usr/btnPUSHEDIT").press
WScript.Sleep 1500

' ------ 2a. Original-language mismatch popup (program SAPLSETX) -------------
' If wnd[1] is the "Different original and logon languages" dialog, press
' "Maint. in orig. lang." (btnPUSH1). Keeps TADIR-MASTERLANG unchanged.
' Fingerprint: ctxtRSETX-MASTERLANG present in wnd[1]/usr.
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim oMasterLangFld
    Set oMasterLangFld = Nothing
    Err.Clear
    Set oMasterLangFld = oSession.findById("wnd[1]/usr/ctxtRSETX-MASTERLANG")
    If Err.Number = 0 Then
        If Not (oMasterLangFld Is Nothing) Then
            Dim oMaintBtn
            Set oMaintBtn = Nothing
            Err.Clear
            Set oMaintBtn = oSession.findById("wnd[1]/usr/btnPUSH1")
            If Err.Number = 0 Then
                If Not (oMaintBtn Is Nothing) Then
                    WScript.Echo "INFO: Original-language popup detected (logon != MASTERLANG=" & _
                                 oMasterLangFld.Text & ") — pressing 'Maint. in orig. lang.'."
                    oMaintBtn.press
                    WScript.Sleep 1500
                End If
            End If
        End If
    End If
End If
Err.Clear
On Error GoTo 0

' ------ 2b. Pre-save TR claim --------------------------------------------------
' Send Ctrl+S to provoke any "Prompt for local Workbench request" popup.
' (a) wnd[1] with ctxtKO008-TRKORR → fill SAP_TRANSPORT, Enter.
' (b) Other popup → Enter to dismiss.
' (c) No popup → object is local ($TMP) or already locked to a modifiable TR.
' Diagnostics: TADIR-DEVCLASS, E071, E070-TRSTATUS.
WScript.Echo "INFO: Pre-save (Ctrl+S) to check whether a TR popup appears..."
On Error Resume Next
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1500
Err.Clear
On Error GoTo 0

On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim oPreTR
    Set oPreTR = oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR")
    If Err.Number = 0 And Not (oPreTR Is Nothing) Then
        Err.Clear
        If SAP_TRANSPORT = "" Then
            WScript.Echo "ERROR: SE11 prompted for a transport request but SAP_TRANSPORT is empty." & vbCrLf & _
                         "       Resolve a modifiable TR via /sap-transport-request and re-run."
            WScript.Quit 1
        End If
        oPreTR.Text = SAP_TRANSPORT
        WScript.Echo "INFO: Pre-save TR popup detected — entering " & SAP_TRANSPORT & "."
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1000
    Else
        Err.Clear
        WScript.Echo "INFO: Pre-save popup (no TR field) — pressing Enter to dismiss."
        oSession.ActiveWindow.sendVKey VKEY_ENTER
        WScript.Sleep 800
    End If
Else
    WScript.Echo "INFO: No pre-save popup — object is local ($TMP) or already locked to a modifiable TR."
End If
Err.Clear
On Error GoTo 0

' ------ 3. Read definition file ---------------------------------------------
Dim oFSO, oFile, sLine, aFields
Set oFSO = CreateObject("Scripting.FileSystemObject")

If Not oFSO.FileExists(DEFINITION_FILE) Then
    WScript.Echo "ERROR: Definition file not found: " & DEFINITION_FILE
    WScript.Quit 1
End If

Set oFile = oFSO.OpenTextFile(EnsureUnicodeFile(DEFINITION_FILE), 1, False, -1)

' Skip header
If Not oFile.AtEndOfStream Then oFile.ReadLine

Dim sLineTypeCat, sLineTypeName, sAccessMode, sKeyDef
sLineTypeCat = "" : sLineTypeName = "" : sAccessMode = "" : sKeyDef = ""

If Not oFile.AtEndOfStream Then
    sLine = oFile.ReadLine
    aFields = Split(sLine, vbTab)
    If UBound(aFields) >= 0 Then sLineTypeCat  = UCase(Trim(aFields(0)))
    If UBound(aFields) >= 1 Then sLineTypeName = Trim(aFields(1))
    If UBound(aFields) >= 2 Then sAccessMode   = UCase(Trim(aFields(2)))
    If UBound(aFields) >= 3 Then sKeyDef       = Trim(aFields(3))
End If
oFile.Close

' ------ 4. Update Line Type tab fields --------------------------------------
WScript.Echo "INFO: Updating line type: " & sLineTypeName & " (" & sLineTypeCat & ")"

' Navigate to Line Type tab
oSession.findById("wnd[0]/usr/tabsTAB_STRIP/tabpLINE").Select
WScript.Sleep 500

On Error Resume Next
If sLineTypeName <> "" Then
    oSession.findById("wnd[0]/usr/tabsTAB_STRIP/tabpLINE/ssubTS_SCREEN:SAPLSD40:1105/ctxtDD40D-ROWTYPE").Text = UCase(sLineTypeName)
End If
If Err.Number <> 0 Then
    WScript.Echo "WARNING: Could not update row type: " & Err.Description
    Err.Clear
End If
On Error GoTo 0

oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' Update access mode / key definition on Initialization and Access tab
If sAccessMode <> "" Or sKeyDef <> "" Then
    oSession.findById("wnd[0]/usr/tabsTAB_STRIP/tabpACCS").Select
    WScript.Sleep 500
    On Error Resume Next
    If sAccessMode <> "" Then
        oSession.findById("wnd[0]/usr/tabsTAB_STRIP/tabpACCS/ssubTS_SCREEN:SAPLSD40:1107/cmbDD40V-ACCESSMODE").Key = sAccessMode
    End If
    If sKeyDef <> "" Then
        oSession.findById("wnd[0]/usr/tabsTAB_STRIP/tabpACCS/ssubTS_SCREEN:SAPLSD40:1107/cmbDD40V-KEYDEF").Key = sKeyDef
    End If
    If Err.Number <> 0 Then
        WScript.Echo "WARNING: Some access/key fields could not be updated: " & Err.Description
        Err.Clear
    End If
    On Error GoTo 0
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 1000
End If

' ------ 5. Check (Ctrl+F2) before saving ------------------------------------
WScript.Echo "INFO: Checking table type consistency..."
oSession.findById("wnd[0]/tbar[1]/btn[26]").press
WScript.Sleep 2000

' Handle "Save object?" popup (table type check requires save first)
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim sChkDiag1
    sChkDiag1 = ""
    sChkDiag1 = oSession.findById("wnd[1]/usr/txtSPOP-DIAGNOSE1").Text
    If Err.Number <> 0 Then sChkDiag1 = "" : Err.Clear
    If InStr(sChkDiag1, "saved") > 0 Then
        WScript.Echo "INFO: Check requires save - pressing Yes..."
        oSession.findById("wnd[1]/usr/btnSPOP-OPTION1").press
        WScript.Sleep 2000
        If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
            If SAP_PACKAGE <> "" And UCase(SAP_PACKAGE) <> "$TMP" And SAP_TRANSPORT <> "" Then
                oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
                oSession.findById("wnd[1]/tbar[0]/btn[0]").press
                WScript.Sleep 1000
                oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR").Text = SAP_TRANSPORT
                oSession.findById("wnd[1]/tbar[0]/btn[0]").press
                WScript.Sleep 1000
            ElseIf SAP_PACKAGE <> "" And UCase(SAP_PACKAGE) <> "$TMP" And SAP_TRANSPORT = "" Then
                oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
                oSession.findById("wnd[1]/tbar[0]/btn[0]").press
                WScript.Sleep 1000
                oSession.findById("wnd[1]/tbar[0]/btn[8]").press
                WScript.Sleep 1000
                oSession.findById("wnd[2]/usr/txtKO013-AS4TEXT").Text = UCase(OBJECT_NAME)
                oSession.findById("wnd[2]/tbar[0]/btn[0]").press
                WScript.Sleep 1000
                oSession.findById("wnd[1]/tbar[0]/btn[0]").press
                WScript.Sleep 1000
            Else
                oSession.findById("wnd[1]/tbar[0]/btn[7]").press
                WScript.Sleep 1000
            End If
        End If
    Else
        Err.Clear
        oSession.ActiveWindow.sendVKey VKEY_ENTER
        WScript.Sleep 1000
    End If
End If
Err.Clear
On Error GoTo 0

If oSession.Info.Program = "SAPMSSY0" Then
    WScript.Echo "INFO: Reading check log..."
    Dim bCheckError
    bCheckError = False
    Dim sCheckErrors
    sCheckErrors = ""
    On Error Resume Next
    Dim oChkUsr, oChkChild, sChkText
    Set oChkUsr = oSession.findById("wnd[0]/usr")
    If Err.Number = 0 Then
        For Each oChkChild In oChkUsr.Children
            sChkText = ""
            sChkText = oChkChild.Text
            If Err.Number <> 0 Then sChkText = "" : Err.Clear
            If InStr(sChkText, "resulted in errors") > 0 Or _
               InStr(sChkText, "is inconsistent") > 0 Then
                bCheckError = True
            End If
            If sChkText <> "" Then
                Dim sChkId
                sChkId = oChkChild.Id
                If Err.Number <> 0 Then sChkId = "" : Err.Clear
                If InStr(sChkId, "lbl[13,") > 0 Then
                    sCheckErrors = sCheckErrors & sChkText & vbCrLf
                End If
            End If
        Next
    End If
    Err.Clear
    On Error GoTo 0

    oSession.findById("wnd[0]").sendVKey VKEY_F3_BACK
    WScript.Sleep 1000

    If bCheckError Then
        WScript.Echo "ERROR: Check found errors:"
        WScript.Echo sCheckErrors
        WScript.Quit 1
    Else
        WScript.Echo "INFO: Check passed."
    End If
Else
    Dim sChkSbarMsg, sChkSbarType
    On Error Resume Next
    sChkSbarMsg  = oSession.findById("wnd[0]/sbar").Text
    sChkSbarType = oSession.findById("wnd[0]/sbar").MessageType
    On Error GoTo 0
    If sChkSbarType = "E" Then
        WScript.Echo "ERROR: Check failed - " & sChkSbarMsg
        WScript.Quit 1
    End If
    WScript.Echo "INFO: Check passed."
End If

' ------ 6. Save (F11) --- (may be already saved by Check) --------------------
WScript.Echo "INFO: Saving table type..."
On Error Resume Next
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
If Err.Number <> 0 Then
    WScript.Echo "WARNING: Save not available (no changes made): " & Err.Description
    Err.Clear
    On Error GoTo 0
    WScript.Echo "INFO: No changes to save or activate."
    WScript.Echo "SUCCESS: Table type " & UCase(OBJECT_NAME) & " checked (no changes needed)."
    WScript.Quit 0
End If
On Error GoTo 0
WScript.Sleep 1500

On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    If SAP_PACKAGE <> "" And UCase(SAP_PACKAGE) <> "$TMP" And SAP_TRANSPORT <> "" Then
        ' Case 1: Both package and transport provided
        WScript.Echo "INFO: Assigning to package " & SAP_PACKAGE & " with transport " & SAP_TRANSPORT & "..."
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR").Text = SAP_TRANSPORT
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
    ElseIf SAP_PACKAGE <> "" And UCase(SAP_PACKAGE) <> "$TMP" And SAP_TRANSPORT = "" Then
        ' Case 3: Package provided, no transport -> create new transport
        WScript.Echo "INFO: Assigning to package " & SAP_PACKAGE & " (creating new transport)..."
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/tbar[0]/btn[8]").press
        WScript.Sleep 1000
        oSession.findById("wnd[2]/usr/txtKO013-AS4TEXT").Text = UCase(OBJECT_NAME)
        oSession.findById("wnd[2]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
    Else
        ' Case 2: No package or $TMP -> Local Object
        WScript.Echo "INFO: Saving as local object ($TMP)..."
        oSession.findById("wnd[1]/tbar[0]/btn[7]").press
        WScript.Sleep 1000
    End If
End If
Err.Clear
On Error GoTo 0
WScript.Echo "INFO: Saved."

' ------ 6. Activate (Ctrl+F3) -----------------------------------------------
WScript.Echo "INFO: Activating..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[1]/btn[27]").press
WScript.Sleep 3000

' Handle "Inactive Objects" popup
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    WScript.Echo "INFO: Confirming activation list..."
    oSession.ActiveWindow.sendVKey VKEY_ENTER
    WScript.Sleep 2000
End If

' Handle "Warning during activation" popup
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    WScript.Echo "INFO: Dismissing activation warning..."
    oSession.findById("wnd[1]/usr/btnSPOP-OPTION2").press
    If Err.Number <> 0 Then
        Err.Clear
        oSession.ActiveWindow.sendVKey VKEY_ENTER
    End If
    WScript.Sleep 1500
End If
Err.Clear
On Error GoTo 0

Dim sFinalMsg, sFinalType
On Error Resume Next
sFinalMsg  = oSession.findById("wnd[0]/sbar").Text
sFinalType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

If sFinalType = "E" Then
    WScript.Echo "WARNING: Activation may have errors - " & sFinalMsg
Else
    WScript.Echo "INFO: SAP status: " & sFinalMsg
End If

WScript.Echo "SUCCESS: Table type " & UCase(OBJECT_NAME) & " updated and activated in SAP."
WScript.Quit 0
