' =============================================================================
' sap_se11_searchhelp_create.vbs  -  SAP GUI Scripting: Create search help in SE11
'
' Generated by the sap-se11 skill.
' Navigates to SE11, creates a new elementary search help with selection method,
' dialog type, and parameter list, saves, and activates.
'
' Tokens replaced at run time:
'   %%OBJECT_NAME%%          Search help name      e.g. "ZSH_PLANT"
'   %%OBJECT_DESCRIPTION%%   Short description     e.g. "Search help for plants"
'   %%DEFINITION_FILE%%      Absolute path to tab-delimited definition
'
' Definition file format (tab-delimited, multi-section):
'   SELECTION_METHOD	ZTABLE
'   DIALOG_TYPE	C
'   HOT_KEY	
'   PARAMETERS
'   SHLP_PARAM	LPOS	SPOS	SDIS	IMP	EXP	DATA_ELEMENT
'   FIELD1	1	1	X	X	X	BUKRS
'   FIELD2	2	2	X		X	WERKS_D
'
' DIALOG_TYPE: A=Display values immediately, C=Dialog with value restriction,
'              D=Dialog depends on set of values
'
' Component IDs recorded from SAP S4D system (S/4HANA).
' =============================================================================

Option Explicit

Const OBJECT_NAME        = "%%OBJECT_NAME%%"
Const OBJECT_DESCRIPTION = "%%OBJECT_DESCRIPTION%%"
Const DEFINITION_FILE    = "%%DEFINITION_FILE%%"
Const SAP_PACKAGE        = "%%PACKAGE%%"
Const SAP_TRANSPORT      = "%%TRANSPORT%%"

Const VKEY_ENTER    = 0
Const VKEY_F3_BACK  = 3
Const VKEY_F11_SAVE = 11

' Include shared session-lock helpers (TryLockSession / ReleaseSession).
' Per language_independence_rules.md Rule 7.
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()

' UTF-8/16 BOM-detect text-encoding helper.
' Lets the OpenTextFile read below accept UTF-8 inputs from upstream tools
' (sap-docs-extract, the Write tool, hand-authored TSVs) — full docstring
' in sap_se11_table_create.vbs. Always returns a UTF-16 LE path so callers
' must open the result with mode -1.
Function EnsureUnicodeFile(sSrcPath)
    Dim oFSOLocal, oBin, aBytes, b1, b2, oIn, sText, oOut, sTempPath, sCharset
    Set oFSOLocal = CreateObject("Scripting.FileSystemObject")
    Set oBin = CreateObject("ADODB.Stream") : oBin.Type = 1 : oBin.Open
    oBin.LoadFromFile sSrcPath
    aBytes = oBin.Read(2) : oBin.Close
    b1 = 0 : b2 = 0
    If LenB(aBytes) >= 1 Then b1 = AscB(MidB(aBytes, 1, 1))
    If LenB(aBytes) >= 2 Then b2 = AscB(MidB(aBytes, 2, 1))
    If b1 = &HFF And b2 = &HFE Then EnsureUnicodeFile = sSrcPath : Exit Function
    sCharset = "utf-8"
    If b1 = &HFE And b2 = &HFF Then sCharset = "utf-16BE"
    Set oIn = CreateObject("ADODB.Stream")
    oIn.Type = 2 : oIn.Charset = sCharset : oIn.Open
    oIn.LoadFromFile sSrcPath
    sText = oIn.ReadText : oIn.Close
    sTempPath = oFSOLocal.GetSpecialFolder(2) & "\sap_def_" & _
                oFSOLocal.GetTempName() & ".txt"
    Set oOut = CreateObject("ADODB.Stream")
    oOut.Type = 2 : oOut.Charset = "unicode" : oOut.Open
    oOut.WriteText sText
    oOut.SaveToFile sTempPath, 2
    oOut.Close
    EnsureUnicodeFile = sTempPath
End Function

Dim oSAPGUI, oApplication, oSession
Dim oCandidate, oSessIter

' ------ 1. Attach to existing SAP GUI session -------------------------------
On Error Resume Next
Set oSAPGUI = GetObject("SAPGUI")
If Err.Number <> 0 Or oSAPGUI Is Nothing Then
    WScript.Echo "ERROR: SAP GUI is not running."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

Set oApplication = oSAPGUI.GetScriptingEngine
If oApplication Is Nothing Then
    WScript.Echo "ERROR: Could not get SAP Scripting Engine."
    WScript.Quit 1
End If

Set oSession = Nothing
On Error Resume Next
For Each oCandidate In oApplication.Children
    For Each oSessIter In oCandidate.Children
        Set oSession = oSessIter
        Exit For
    Next
    If Not (oSession Is Nothing) Then Exit For
Next
On Error GoTo 0

If oSession Is Nothing Then
    WScript.Echo "ERROR: No SAP GUI session found. Run the login step first."
    WScript.Quit 1
End If
WScript.Echo "INFO: Session acquired."

' ------ 2. Navigate to SE11 and create search help --------------------------
WScript.Echo "INFO: Navigating to SE11..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE11"
oSession.findById("wnd[0]").sendVKey 0
WScript.Sleep 1000

oSession.findById("wnd[0]/usr/radRSRD1-SHMA").select
WScript.Sleep 300
oSession.findById("wnd[0]/usr/ctxtRSRD1-SHMA_VAL").Text = UCase(OBJECT_NAME)
WScript.Sleep 300

WScript.Echo "INFO: Creating search help: " & UCase(OBJECT_NAME)
oSession.findById("wnd[0]/usr/btnPUSHADD").press
WScript.Sleep 1500

' --- Lock the SAP session UI for the fill search-help fields + save + activate critical section ---
' Defence in depth (Rule 7): AppActivate guards external focus stealing;
' LockSessionUI guards in-session input races. Released after activation.
Dim wasLocked : wasLocked = TryLockSession(oSession)
If wasLocked Then
    WScript.Echo "INFO: Session UI locked for the fill search-help fields + save + activate critical section."
Else
    WScript.Echo "INFO: LockSessionUI not available on this SAP GUI build; continuing without lock."
End If

' ------ 3. Handle search help type popup (elementary vs collective) ----------
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    WScript.Echo "INFO: Search help type popup detected - selecting Elementary..."
    oSession.findById("wnd[1]/usr/radRAD_ELEM").select
    If Err.Number <> 0 Then
        Err.Clear
        ' Try alternate ID
        oSession.findById("wnd[1]/usr/radDD30L-SHTYPE_E").select
    End If
    WScript.Sleep 300
    oSession.findById("wnd[1]").sendVKey VKEY_ENTER
    WScript.Sleep 1500
End If
Err.Clear
On Error GoTo 0

' ------ 4. Fill description -------------------------------------------------
On Error Resume Next
oSession.findById("wnd[0]/usr/txtDD30L-DDTEXT").Text = OBJECT_DESCRIPTION
If Err.Number <> 0 Then
    WScript.Echo "WARNING: Could not set description: " & Err.Description
    Err.Clear
End If
On Error GoTo 0

' ------ 5. Parse definition file --------------------------------------------
Dim oFSO, oFile, sLine, aFields
Set oFSO = CreateObject("Scripting.FileSystemObject")

If Not oFSO.FileExists(DEFINITION_FILE) Then
    WScript.Echo "ERROR: Definition file not found: " & DEFINITION_FILE
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

Dim sSelMethod, sDialogType, sHotKey
sSelMethod = "" : sDialogType = "" : sHotKey = ""

Dim arrParams()
Dim iParamCount
iParamCount = 0

Dim sSection
sSection = "HEADER"

Set oFile = oFSO.OpenTextFile(EnsureUnicodeFile(DEFINITION_FILE), 1, False, -1)
Do While Not oFile.AtEndOfStream
    sLine = Trim(oFile.ReadLine)
    If sLine = "" Then
        ' skip
    ElseIf UCase(sLine) = "PARAMETERS" Then
        sSection = "PARAMS"
    Else
        aFields = Split(sLine, vbTab)
        Select Case sSection
            Case "HEADER"
                If UBound(aFields) >= 1 Then
                    Select Case UCase(Trim(aFields(0)))
                        Case "SELECTION_METHOD"
                            sSelMethod = Trim(aFields(1))
                        Case "DIALOG_TYPE"
                            sDialogType = UCase(Trim(aFields(1)))
                        Case "HOT_KEY"
                            sHotKey = Trim(aFields(1))
                    End Select
                End If
            Case "PARAMS"
                ' Skip header line
                If UBound(aFields) >= 0 And UCase(Trim(aFields(0))) <> "SHLP_PARAM" Then
                    ReDim Preserve arrParams(iParamCount)
                    arrParams(iParamCount) = sLine
                    iParamCount = iParamCount + 1
                End If
        End Select
    End If
Loop
oFile.Close

WScript.Echo "INFO: Selection method: " & sSelMethod & ", Dialog type: " & sDialogType & ", Parameters: " & iParamCount

' ------ 6. Fill selection method + dialog type + hot key ---------------------
On Error Resume Next
If sSelMethod <> "" Then
    oSession.findById("wnd[0]/usr/ctxtDD30L-SELMETHOD").Text = UCase(sSelMethod)
End If
If sDialogType <> "" Then
    oSession.findById("wnd[0]/usr/cmbDD30L-DIALOGTYPE").Key = sDialogType
End If
If sHotKey <> "" Then
    oSession.findById("wnd[0]/usr/txtDD30L-HOTKEY").Text = sHotKey
End If
If Err.Number <> 0 Then
    WScript.Echo "WARNING: Could not set some header fields: " & Err.Description
    Err.Clear
End If
On Error GoTo 0

oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 7. Fill parameters grid ----------------------------------------------
If iParamCount > 0 Then
    WScript.Echo "INFO: Filling search help parameters..."
    On Error Resume Next
    
    Dim sGridBase, iRow, i, aParamFields
    sGridBase = "wnd[0]/usr/tblSAPLSD31TC_PARAM_TAB/"
    
    For i = 0 To iParamCount - 1
        aParamFields = Split(arrParams(i), vbTab)
        iRow = i
        
        ' Column 0: SHLP parameter name
        If UBound(aParamFields) >= 0 Then
            oSession.findById(sGridBase & "ctxtDD32S-FIELDNAME[0," & iRow & "]").Text = UCase(Trim(aParamFields(0)))
        End If
        ' Column 1: LPOS (list position)
        If UBound(aParamFields) >= 1 And Trim(aParamFields(1)) <> "" Then
            oSession.findById(sGridBase & "txtDD32S-FLPOSITION[1," & iRow & "]").Text = Trim(aParamFields(1))
        End If
        ' Column 2: SPOS (selection position)
        If UBound(aParamFields) >= 2 And Trim(aParamFields(2)) <> "" Then
            oSession.findById(sGridBase & "txtDD32S-POSITION[2," & iRow & "]").Text = Trim(aParamFields(2))
        End If
        ' Column 3: SDIS (display in list)
        If UBound(aParamFields) >= 3 And UCase(Trim(aParamFields(3))) = "X" Then
            oSession.findById(sGridBase & "chkDD32S-SHDISPLAY[3," & iRow & "]").Selected = True
        End If
        ' Column 4: IMP (import)
        If UBound(aParamFields) >= 4 And UCase(Trim(aParamFields(4))) = "X" Then
            oSession.findById(sGridBase & "chkDD32S-SHSELOPT[4," & iRow & "]").Selected = True
        End If
        ' Column 5: EXP (export)
        If UBound(aParamFields) >= 5 And UCase(Trim(aParamFields(5))) = "X" Then
            oSession.findById(sGridBase & "chkDD32S-SHRESULT[5," & iRow & "]").Selected = True
        End If
        ' Column 6: Data element
        If UBound(aParamFields) >= 6 And Trim(aParamFields(6)) <> "" Then
            oSession.findById(sGridBase & "ctxtDD32S-ROLLNAME[6," & iRow & "]").Text = UCase(Trim(aParamFields(6)))
        End If
        
        If Err.Number <> 0 Then
            WScript.Echo "WARNING: Error filling parameter row " & iRow & ": " & Err.Description
            Err.Clear
        Else
            WScript.Echo "INFO:   Parameter " & (i+1) & ": " & UCase(Trim(aParamFields(0)))
        End If
        WScript.Sleep 200
        
        ' Scroll grid periodically
        If (iRow + 1) Mod 14 = 0 And i < iParamCount - 1 Then
            oSession.findById("wnd[0]").sendVKey VKEY_ENTER
            WScript.Sleep 500
        End If
    Next
    
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 1000
    Err.Clear
    On Error GoTo 0
End If

' ------ 8. Check (Ctrl+F2) before saving ------------------------------------
WScript.Echo "INFO: Checking search help consistency..."
oSession.findById("wnd[0]/tbar[1]/btn[26]").press
WScript.Sleep 2000

Dim sCheckMsg, sCheckType
On Error Resume Next
sCheckMsg  = oSession.findById("wnd[0]/sbar").Text
sCheckType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

If sCheckType = "E" Then
    WScript.Echo "ERROR: Check failed - " & sCheckMsg
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If
WScript.Echo "INFO: Check passed."

' ------ 9. Save (F11) -------------------------------------------------------
WScript.Echo "INFO: Saving search help..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1500

On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    If SAP_PACKAGE <> "" And UCase(SAP_PACKAGE) <> "$TMP" And SAP_TRANSPORT <> "" Then
        ' Case 1: Both package and transport provided
        WScript.Echo "INFO: Assigning to package " & SAP_PACKAGE & " with transport " & SAP_TRANSPORT & "..."
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR").Text = SAP_TRANSPORT
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
    ElseIf SAP_PACKAGE <> "" And UCase(SAP_PACKAGE) <> "$TMP" And SAP_TRANSPORT = "" Then
        ' Case 3: Package provided, no transport -> create new transport
        WScript.Echo "INFO: Assigning to package " & SAP_PACKAGE & " (creating new transport)..."
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/tbar[0]/btn[8]").press
        WScript.Sleep 1000
        oSession.findById("wnd[2]/usr/txtKO013-AS4TEXT").Text = UCase(OBJECT_NAME)
        oSession.findById("wnd[2]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
    Else
        ' Case 2: No package or $TMP -> Local Object
        WScript.Echo "INFO: Saving as local object ($TMP)..."
        oSession.findById("wnd[1]/tbar[0]/btn[7]").press
        WScript.Sleep 1000
    End If
End If
Err.Clear
On Error GoTo 0
WScript.Echo "INFO: Saved."

' ------ 9. Activate (Ctrl+F3) -----------------------------------------------
WScript.Echo "INFO: Activating..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[1]/btn[27]").press
WScript.Sleep 3000
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSession.ActiveWindow.sendVKey VKEY_ENTER
    WScript.Sleep 1500
End If
Err.Clear
On Error GoTo 0

' --- Release the session UI lock; final-status read is read-only ---
ReleaseSession oSession, wasLocked
If wasLocked Then WScript.Echo "INFO: Session UI lock released."

Dim sFinalMsg, sFinalType
On Error Resume Next
sFinalMsg  = oSession.findById("wnd[0]/sbar").Text
sFinalType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

If sFinalType = "E" Then
    WScript.Echo "WARNING: Activation may have errors - " & sFinalMsg
Else
    WScript.Echo "INFO: SAP status: " & sFinalMsg
End If

WScript.Echo "SUCCESS: Search help " & UCase(OBJECT_NAME) & " created and activated in SAP."
WScript.Quit 0
