' =============================================================================
' sap_se11_searchhelp_update.vbs  -  SAP GUI Scripting: Update search help in SE11
'
' Generated by the sap-se11 skill.
' Opens an existing search help in Change mode, updates selection method,
' dialog type, and parameters from definition file, saves, and activates.
'
' Tokens replaced at run time:
'   %%OBJECT_NAME%%      Search help name      e.g. "ZSH_PLANT"
'   %%DEFINITION_FILE%%  Absolute path to tab-delimited definition
'
' Definition file format (same as create -- see sap_se11_searchhelp_create.vbs)
'
' Component IDs recorded from SAP S4D system (S/4HANA).
' =============================================================================

Option Explicit

Const OBJECT_NAME     = "%%OBJECT_NAME%%"
Const DEFINITION_FILE = "%%DEFINITION_FILE%%"
Const SAP_PACKAGE     = "%%PACKAGE%%"
Const SAP_TRANSPORT   = "%%TRANSPORT%%"
Const SESSION_PATH    = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER    = 0
Const VKEY_F3_BACK  = 3
Const VKEY_F11_SAVE = 11

' Include shared attach helper.
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

' UTF-8/16 BOM-detect text-encoding helper.
' Lets the OpenTextFile read below accept UTF-8 inputs from upstream tools
' (sap-docs-extract, the Write tool, hand-authored TSVs) -- full docstring
' in sap_se11_table_create.vbs. Always returns a UTF-16 LE path so callers
' must open the result with mode -1.
Function EnsureUnicodeFile(sSrcPath)
    Dim oFSOLocal, oBin, aBytes, b1, b2, oIn, sText, oOut, sTempPath, sCharset
    Set oFSOLocal = CreateObject("Scripting.FileSystemObject")
    Set oBin = CreateObject("ADODB.Stream") : oBin.Type = 1 : oBin.Open
    oBin.LoadFromFile sSrcPath
    aBytes = oBin.Read(2) : oBin.Close
    b1 = 0 : b2 = 0
    If LenB(aBytes) >= 1 Then b1 = AscB(MidB(aBytes, 1, 1))
    If LenB(aBytes) >= 2 Then b2 = AscB(MidB(aBytes, 2, 1))
    If b1 = &HFF And b2 = &HFE Then EnsureUnicodeFile = sSrcPath : Exit Function
    sCharset = "utf-8"
    If b1 = &HFE And b2 = &HFF Then sCharset = "utf-16BE"
    Set oIn = CreateObject("ADODB.Stream")
    oIn.Type = 2 : oIn.Charset = sCharset : oIn.Open
    oIn.LoadFromFile sSrcPath
    sText = oIn.ReadText : oIn.Close
    sTempPath = oFSOLocal.GetSpecialFolder(2) & "\sap_def_" & _
                oFSOLocal.GetTempName() & ".txt"
    Set oOut = CreateObject("ADODB.Stream")
    oOut.Type = 2 : oOut.Charset = "unicode" : oOut.Open
    oOut.WriteText sText
    oOut.SaveToFile sTempPath, 2
    oOut.Close
    EnsureUnicodeFile = sTempPath
End Function

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SE11 and open search help in Change mode --------------
WScript.Echo "INFO: Navigating to SE11..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE11"
oSession.findById("wnd[0]").sendVKey 0
WScript.Sleep 1000

oSession.findById("wnd[0]/usr/radRSRD1-SHMA").select
WScript.Sleep 300
oSession.findById("wnd[0]/usr/ctxtRSRD1-SHMA_VAL").Text = UCase(OBJECT_NAME)
WScript.Sleep 300

WScript.Echo "INFO: Opening search help in Change mode: " & UCase(OBJECT_NAME)
oSession.findById("wnd[0]/usr/btnPUSHEDIT").press
WScript.Sleep 1500

' ------ 2a. Original-language mismatch popup (program SAPLSETX) -------------
' If wnd[1] is the "Different original and logon languages" dialog, press
' "Maint. in orig. lang." (btnPUSH1). Keeps TADIR-MASTERLANG unchanged.
' Fingerprint: ctxtRSETX-MASTERLANG present in wnd[1]/usr.
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim oMasterLangFld
    Set oMasterLangFld = Nothing
    Err.Clear
    Set oMasterLangFld = oSession.findById("wnd[1]/usr/ctxtRSETX-MASTERLANG")
    If Err.Number = 0 Then
        If Not (oMasterLangFld Is Nothing) Then
            Dim oMaintBtn
            Set oMaintBtn = Nothing
            Err.Clear
            Set oMaintBtn = oSession.findById("wnd[1]/usr/btnPUSH1")
            If Err.Number = 0 Then
                If Not (oMaintBtn Is Nothing) Then
                    WScript.Echo "INFO: Original-language popup detected (logon != MASTERLANG=" & _
                                 oMasterLangFld.Text & ") -- pressing 'Maint. in orig. lang.'."
                    oMaintBtn.press
                    WScript.Sleep 1500
                End If
            End If
        End If
    End If
End If
Err.Clear
On Error GoTo 0

' ------ 2b. Pre-save TR claim --------------------------------------------------
' Send Ctrl+S to provoke any "Prompt for local Workbench request" popup.
' (a) wnd[1] with ctxtKO008-TRKORR -> fill SAP_TRANSPORT, Enter.
' (b) Other popup -> Enter to dismiss.
' (c) No popup -> object is local ($TMP) or already locked to a modifiable TR.
' Diagnostics: TADIR-DEVCLASS, E071, E070-TRSTATUS.
WScript.Echo "INFO: Pre-save (Ctrl+S) to check whether a TR popup appears..."
On Error Resume Next
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1500
Err.Clear
On Error GoTo 0

On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim oPreTR
    Set oPreTR = oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR")
    If Err.Number = 0 And Not (oPreTR Is Nothing) Then
        Err.Clear
        If SAP_TRANSPORT = "" Then
            WScript.Echo "ERROR: SE11 prompted for a transport request but SAP_TRANSPORT is empty." & vbCrLf & _
                         "       Resolve a modifiable TR via /sap-transport-request and re-run."
            WScript.Quit 1
        End If
        oPreTR.Text = SAP_TRANSPORT
        WScript.Echo "INFO: Pre-save TR popup detected -- entering " & SAP_TRANSPORT & "."
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1000
    Else
        Err.Clear
        WScript.Echo "INFO: Pre-save popup (no TR field) -- pressing Enter to dismiss."
        oSession.ActiveWindow.sendVKey VKEY_ENTER
        WScript.Sleep 800
    End If
Else
    WScript.Echo "INFO: No pre-save popup -- object is local ($TMP) or already locked to a modifiable TR."
End If
Err.Clear
On Error GoTo 0

' ------ 3. Parse definition file --------------------------------------------
Dim oFSO, oFile, sLine, aFields
Set oFSO = CreateObject("Scripting.FileSystemObject")

If Not oFSO.FileExists(DEFINITION_FILE) Then
    WScript.Echo "ERROR: Definition file not found: " & DEFINITION_FILE
    WScript.Quit 1
End If

Dim sSelMethod, sDialogType, sHotKey
sSelMethod = "" : sDialogType = "" : sHotKey = ""

Dim arrParams()
Dim iParamCount
iParamCount = 0

Dim sSection
sSection = "HEADER"

Set oFile = oFSO.OpenTextFile(EnsureUnicodeFile(DEFINITION_FILE), 1, False, -1)
Do While Not oFile.AtEndOfStream
    sLine = Trim(oFile.ReadLine)
    If sLine = "" Then
        ' skip
    ElseIf UCase(sLine) = "PARAMETERS" Then
        sSection = "PARAMS"
    Else
        aFields = Split(sLine, vbTab)
        Select Case sSection
            Case "HEADER"
                If UBound(aFields) >= 1 Then
                    Select Case UCase(Trim(aFields(0)))
                        Case "SELECTION_METHOD"
                            sSelMethod = Trim(aFields(1))
                        Case "DIALOG_TYPE"
                            sDialogType = UCase(Trim(aFields(1)))
                        Case "HOT_KEY"
                            sHotKey = Trim(aFields(1))
                    End Select
                End If
            Case "PARAMS"
                If UBound(aFields) >= 0 And UCase(Trim(aFields(0))) <> "SHLP_PARAM" Then
                    ReDim Preserve arrParams(iParamCount)
                    arrParams(iParamCount) = sLine
                    iParamCount = iParamCount + 1
                End If
        End Select
    End If
Loop
oFile.Close

WScript.Echo "INFO: Selection method: " & sSelMethod & ", Dialog type: " & sDialogType & ", Parameters: " & iParamCount

' ------ 4. Update selection method + dialog type + hot key -------------------
On Error Resume Next
If sSelMethod <> "" Then
    oSession.findById("wnd[0]/usr/ctxtDD30L-SELMETHOD").Text = UCase(sSelMethod)
End If
If sDialogType <> "" Then
    oSession.findById("wnd[0]/usr/cmbDD30L-DIALOGTYPE").Key = sDialogType
End If
If sHotKey <> "" Then
    oSession.findById("wnd[0]/usr/txtDD30L-HOTKEY").Text = sHotKey
End If
If Err.Number <> 0 Then
    WScript.Echo "WARNING: Could not set some header fields: " & Err.Description
    Err.Clear
End If
On Error GoTo 0

oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 5. Update parameters grid -- scan existing + add/overwrite ------------
If iParamCount > 0 Then
    WScript.Echo "INFO: Updating search help parameters..."
    On Error Resume Next
    
    ' Scan existing parameters
    Dim dictExisting
    Set dictExisting = CreateObject("Scripting.Dictionary")
    dictExisting.CompareMode = 1
    
    Dim sGridBase, iScanRow, sExistVal
    sGridBase = "wnd[0]/usr/tblSAPLSD31TC_PARAM_TAB/"
    iScanRow = 0
    
    Do While True
        sExistVal = ""
        Err.Clear
        sExistVal = oSession.findById(sGridBase & "ctxtDD32S-FIELDNAME[0," & iScanRow & "]").Text
        If Err.Number <> 0 Then
            Err.Clear
            Exit Do
        End If
        If Trim(sExistVal) = "" Then Exit Do
        dictExisting(UCase(Trim(sExistVal))) = iScanRow
        iScanRow = iScanRow + 1
        If iScanRow Mod 14 = 0 Then
            oSession.findById("wnd[0]").sendVKey VKEY_ENTER
            WScript.Sleep 300
        End If
    Loop
    
    Dim iNextRow, i, aParamFields, iRow, sParamName
    iNextRow = iScanRow
    
    For i = 0 To iParamCount - 1
        aParamFields = Split(arrParams(i), vbTab)
        sParamName = UCase(Trim(aParamFields(0)))
        
        ' Use existing row if parameter already exists, else append
        If dictExisting.Exists(sParamName) Then
            iRow = dictExisting(sParamName)
            WScript.Echo "INFO:   Updating existing parameter: " & sParamName & " (row " & iRow & ")"
        Else
            iRow = iNextRow
            iNextRow = iNextRow + 1
            WScript.Echo "INFO:   Adding new parameter: " & sParamName & " (row " & iRow & ")"
        End If
        
        ' Column 0: SHLP parameter name
        oSession.findById(sGridBase & "ctxtDD32S-FIELDNAME[0," & iRow & "]").Text = sParamName
        ' Column 1: LPOS
        If UBound(aParamFields) >= 1 And Trim(aParamFields(1)) <> "" Then
            oSession.findById(sGridBase & "txtDD32S-FLPOSITION[1," & iRow & "]").Text = Trim(aParamFields(1))
        End If
        ' Column 2: SPOS
        If UBound(aParamFields) >= 2 And Trim(aParamFields(2)) <> "" Then
            oSession.findById(sGridBase & "txtDD32S-POSITION[2," & iRow & "]").Text = Trim(aParamFields(2))
        End If
        ' Column 3: SDIS
        If UBound(aParamFields) >= 3 Then
            oSession.findById(sGridBase & "chkDD32S-SHDISPLAY[3," & iRow & "]").Selected = (UCase(Trim(aParamFields(3))) = "X")
        End If
        ' Column 4: IMP
        If UBound(aParamFields) >= 4 Then
            oSession.findById(sGridBase & "chkDD32S-SHSELOPT[4," & iRow & "]").Selected = (UCase(Trim(aParamFields(4))) = "X")
        End If
        ' Column 5: EXP
        If UBound(aParamFields) >= 5 Then
            oSession.findById(sGridBase & "chkDD32S-SHRESULT[5," & iRow & "]").Selected = (UCase(Trim(aParamFields(5))) = "X")
        End If
        ' Column 6: Data element
        If UBound(aParamFields) >= 6 And Trim(aParamFields(6)) <> "" Then
            oSession.findById(sGridBase & "ctxtDD32S-ROLLNAME[6," & iRow & "]").Text = UCase(Trim(aParamFields(6)))
        End If
        
        If Err.Number <> 0 Then
            WScript.Echo "WARNING: Error updating parameter row " & iRow & ": " & Err.Description
            Err.Clear
        End If
        WScript.Sleep 200
        
        If (iRow + 1) Mod 14 = 0 Then
            oSession.findById("wnd[0]").sendVKey VKEY_ENTER
            WScript.Sleep 500
        End If
    Next
    
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 1000
    Err.Clear
    On Error GoTo 0
End If

' ------ 6. Check (Ctrl+F2) before saving ------------------------------------
WScript.Echo "INFO: Checking search help consistency..."
oSession.findById("wnd[0]/tbar[1]/btn[26]").press
WScript.Sleep 2000

Dim sCheckMsg, sCheckType
On Error Resume Next
sCheckMsg  = oSession.findById("wnd[0]/sbar").Text
sCheckType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

If sCheckType = "E" Then
    WScript.Echo "ERROR: Check failed - " & sCheckMsg
    WScript.Quit 1
End If
WScript.Echo "INFO: Check passed."

' ------ 7. Save (F11) -------------------------------------------------------
WScript.Echo "INFO: Saving search help..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1500

On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    If SAP_PACKAGE <> "" And UCase(SAP_PACKAGE) <> "$TMP" And SAP_TRANSPORT <> "" Then
        ' Case 1: Both package and transport provided
        WScript.Echo "INFO: Assigning to package " & SAP_PACKAGE & " with transport " & SAP_TRANSPORT & "..."
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR").Text = SAP_TRANSPORT
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
    ElseIf SAP_PACKAGE <> "" And UCase(SAP_PACKAGE) <> "$TMP" And SAP_TRANSPORT = "" Then
        ' Case 3: Package provided, no transport -> create new transport
        WScript.Echo "INFO: Assigning to package " & SAP_PACKAGE & " (creating new transport)..."
        oSession.findById("wnd[1]/usr/ctxtKO007-L_DEVCLASS").Text = SAP_PACKAGE
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/tbar[0]/btn[8]").press
        WScript.Sleep 1000
        oSession.findById("wnd[2]/usr/txtKO013-AS4TEXT").Text = UCase(OBJECT_NAME)
        oSession.findById("wnd[2]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
        oSession.findById("wnd[1]/tbar[0]/btn[0]").press
        WScript.Sleep 1000
    Else
        ' Case 2: No package or $TMP -> Local Object
        WScript.Echo "INFO: Saving as local object ($TMP)..."
        oSession.findById("wnd[1]/tbar[0]/btn[7]").press
        WScript.Sleep 1000
    End If
End If
Err.Clear
On Error GoTo 0
WScript.Echo "INFO: Saved."

' ------ 7. Activate (Ctrl+F3) -----------------------------------------------
WScript.Echo "INFO: Activating..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[1]/btn[27]").press
WScript.Sleep 3000
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSession.ActiveWindow.sendVKey VKEY_ENTER
    WScript.Sleep 1500
End If
Err.Clear
On Error GoTo 0

Dim sFinalMsg, sFinalType
On Error Resume Next
sFinalMsg  = oSession.findById("wnd[0]/sbar").Text
sFinalType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

If sFinalType = "E" Then
    WScript.Echo "WARNING: Activation may have errors - " & sFinalMsg
Else
    WScript.Echo "INFO: SAP status: " & sFinalMsg
End If

WScript.Echo "SUCCESS: Search help " & UCase(OBJECT_NAME) & " updated and activated in SAP."
WScript.Quit 0
