' =============================================================================
' sap_se16h_agg.vbs  -  SAP GUI Scripting: server-side aggregation via SE16H
'
' Generated by the sap-se16n skill (`agg` mode). Pushes GROUP BY + per-column
' aggregation down to the database through SE16H (program SAPLSE16N, the
' "General Table Display" advanced screen) so the caller never downloads the
' raw rows. The grouped ALV result is read directly through the GridView
' scripting API and written as a TSV -- no ALV export dialog, so no SAP GUI
' Security file-IO prompt is raised.
'
' Flow:
'   1. Attach to the existing SAP GUI session (shared attach helper).
'   2. Open SE16H, enter the table name, Enter -> the field list loads.
'   3. Raise GD-MAX_LINES to MAX_GROUPS so groups are not silently dropped
'      (SE16H caps the number of RESULT GROUPS returned, NOT the pre-aggregation
'      input; each returned group is still computed over the whole table -- so a
'      cap smaller than the distinct-group count truncates the GROUP SET while
'      leaving every returned aggregate correct). Optional GD-MIN_COUNT filter.
'   4. Read PARAMS_FILE (GROUP / AGG / FILTER sections -- see below).
'   5. FILTER rows: locate the field by FIELDNAME (col 13, scrolling the TC) and
'      set LOW/HIGH or a multi-select popup (same criteria columns as SE16N).
'   6. GROUP rows: tick chkGS_SELFIELDS-GROUP_BY (col 8) on each field.
'   7. AGG rows: set cmbGS_SELFIELDS-AGGREGATE (col 12) .Key to MIN | MAX | AVG.
'      SE16H (SAPLSE16N, verified live S/4HANA 1909) offers ONLY Minimum /
'      Maximum / Average in this combo -- there is NO Sum/Total. COUNT per group
'      is implicit: a grouped result always carries a LINE_INDEX ("Number of
'      Entries") column. --sum is therefore handled by the caller's local-
'      aggregation fallback, never here; a SUM/COUNT func reaching this script is
'      rejected as AGG_NOT_APPLICABLE rather than silently mis-set.
'   8. Enter (PAI) then Execute (tbar[1]/btn[8] = F8) -> result screen 200.
'   9. Read the result ALV (cntlRESULT_LIST) via ColumnOrder + GetCellValue,
'      paging firstVisibleRow so large grids fully render, and write a TSV.
'  10. Truncation disclosure: if result RowCount >= MAX_GROUPS the group set may
'      be truncated -> truncated=1 (never a silent partial pass).
'
' Tokens replaced at run time:
'   %%TABLE_NAME%%   target table, e.g. "MSEG"
'   %%PARAMS_FILE%%  tab-delimited spec:
'                       GROUP
'                       WERKS
'                       BWART
'                       AGG
'                       MENGE<TAB>AVG
'                       FILTER
'                       BWART<TAB>EQ<TAB>101
'                    Sections introduced by the literal lines GROUP / AGG /
'                    FILTER; any may be empty or omitted. AGG func in
'                    {MIN,MAX,AVG}. FILTER operators as SE16N (EQ/NE/GT/LT/GE/
'                    LE/BT/NB/CP/NP/IN).
'   %%OUTPUT_FILE%%  absolute path of the resulting tab-delimited file.
'   %%MAX_GROUPS%%   integer cap on returned groups (default 100000 when blank).
'   %%MIN_COUNT%%    optional grouping-minimum (GD-MIN_COUNT); blank = none.
'
' Component IDs recorded live from SE16H on S/4HANA 1909 (kernel 754, GUI 7700),
' 2026-07-11. Selection field table control = tblSAPLSE16NSELFIELDS_TC. SE16H
' exposes MORE columns than SE16N -- the indices below are SE16H's, not SE16N's:
'   col 2  ctxtGS_SELFIELDS-LOW        Fr.Value
'   col 3  ctxtGS_SELFIELDS-HIGH       To value
'   col 4  btnPUSH                     Multi-select icon
'   col 6  chkGS_SELFIELDS-MARK        Output checkbox
'   col 8  chkGS_SELFIELDS-GROUP_BY    Group-by checkbox
'   col 10 chkGS_SELFIELDS-ORDER_BY    Order-by checkbox
'   col 12 cmbGS_SELFIELDS-AGGREGATE   Aggregate combo (keys MIN/MAX/AVG)
'   col 13 txtGS_SELFIELDS-FIELDNAME   Technical name
' Result grid = wnd[0]/usr/cntlRESULT_LIST/shellcont/shell (GridView subType).
' =============================================================================

Option Explicit

Const TABLE_NAME   = "%%TABLE_NAME%%"
Const PARAMS_FILE  = "%%PARAMS_FILE%%"
Const OUTPUT_FILE  = "%%OUTPUT_FILE%%"
Const MAX_GROUPS_S = "%%MAX_GROUPS%%"
Const MIN_COUNT_S  = "%%MIN_COUNT%%"
Const SESSION_PATH = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER = 0
Const VKEY_F8    = 8
Const VKEY_F12   = 12

Const TC_PATH      = "wnd[0]/usr/tblSAPLSE16NSELFIELDS_TC"
Const COL_LOW      = 2
Const COL_HIGH     = 3
Const COL_BTNPUSH  = 4
Const COL_GROUP_BY = 8
Const COL_AGGREG   = 12
Const COL_FIELD    = 13
Const RESULT_GRID  = "wnd[0]/usr/cntlRESULT_LIST/shellcont/shell"

' Include shared attach helper -- resolves the target session by explicit hint
' -> SAPDEV_SESSION_PATH env var -> sole-connection default; handles all error
' paths internally (WScript.Echo + Quit).
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

Dim oSession, oFSO, oTS, sLine, sMode
Dim maxGroups, minCount

' spec storage
Dim aGroup() : ReDim aGroup(200)
Dim nGroup : nGroup = 0
Dim aAggF() : ReDim aAggF(200)      ' field
Dim aAggK() : ReDim aAggK(200)      ' func key (MIN/MAX/AVG)
Dim nAgg : nAgg = 0
Dim aFiltF() : ReDim aFiltF(200)
Dim aFiltOp() : ReDim aFiltOp(200)
Dim aFiltVals() : ReDim aFiltVals(200)   ' tab-joined values
Dim nFilt : nFilt = 0

maxGroups = 100000
If Len(Trim(MAX_GROUPS_S)) > 0 And IsNumeric(MAX_GROUPS_S) Then maxGroups = CLng(MAX_GROUPS_S)
If maxGroups < 1 Then maxGroups = 100000
minCount = Trim(MIN_COUNT_S)

' ----------------------------------------------------------------------------
' 1. Attach + read PARAMS_FILE
' ----------------------------------------------------------------------------
Set oSession = AttachSapSession(SESSION_PATH)

Set oFSO = CreateObject("Scripting.FileSystemObject")
If Not oFSO.FileExists(PARAMS_FILE) Then
    WScript.Echo "ERROR: Params file not found: " & PARAMS_FILE
    WScript.Echo "STATUS: INPUT_ERROR"
    WScript.Quit 2
End If
Set oTS = oFSO.OpenTextFile(PARAMS_FILE, 1, False, -2)
sMode = ""
Do While Not oTS.AtEndOfStream
    sLine = oTS.ReadLine
    Dim t : t = Trim(sLine)
    If Len(t) = 0 Then
        ' skip
    ElseIf UCase(t) = "GROUP" Then
        sMode = "GROUP"
    ElseIf UCase(t) = "AGG" Then
        sMode = "AGG"
    ElseIf UCase(t) = "FILTER" Then
        sMode = "FILTER"
    ElseIf sMode = "GROUP" Then
        aGroup(nGroup) = UCase(t) : nGroup = nGroup + 1
    ElseIf sMode = "AGG" Then
        Dim ap : ap = Split(sLine, vbTab)
        If UBound(ap) >= 1 Then
            aAggF(nAgg) = UCase(Trim(ap(0)))
            aAggK(nAgg) = UCase(Trim(ap(1)))
            nAgg = nAgg + 1
        End If
    ElseIf sMode = "FILTER" Then
        Dim fp : fp = Split(sLine, vbTab)
        If UBound(fp) >= 1 Then
            aFiltF(nFilt) = UCase(Trim(fp(0)))
            aFiltOp(nFilt) = UCase(Trim(fp(1)))
            Dim vv, kk : vv = ""
            For kk = 2 To UBound(fp)
                If kk > 2 Then vv = vv & vbTab
                vv = vv & fp(kk)
            Next
            aFiltVals(nFilt) = vv
            nFilt = nFilt + 1
        End If
    End If
Loop
oTS.Close

If nGroup = 0 And nAgg = 0 Then
    WScript.Echo "ERROR: no GROUP and no AGG requested -- nothing to aggregate."
    WScript.Echo "STATUS: INPUT_ERROR"
    WScript.Quit 2
End If

' Reject SUM/COUNT before touching SAP -- SE16H's aggregate combo cannot do them
' (Sum/Total absent; count is implicit via LINE_INDEX). The caller routes --sum
' to local aggregation; if one still reaches here, fail loud, never silent.
Dim g
For g = 0 To nAgg - 1
    If aAggK(g) <> "MIN" And aAggK(g) <> "MAX" And aAggK(g) <> "AVG" Then
        WScript.Echo "ERROR: aggregate func '" & aAggK(g) & "' on " & aAggF(g) & _
            " is not supported by SE16H (only MIN/MAX/AVG; SUM/COUNT are not in the combo)."
        WScript.Echo "STATUS: AGG_NOT_APPLICABLE field=" & aAggF(g) & " func=" & aAggK(g)
        WScript.Quit 1
    End If
Next

' ----------------------------------------------------------------------------
' 2. Open SE16H + enter table
' ----------------------------------------------------------------------------
oSession.findById("wnd[0]").maximize
DismissModals
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nSE16H"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 800

' Guard: SE16H must be available (older releases / missing auth). If the
' selection screen's table field is absent, we cannot drive the aggregation.
On Error Resume Next
Dim probeTab : Set probeTab = Nothing
Set probeTab = oSession.findById("wnd[0]/usr/ctxtGD-TAB")
On Error GoTo 0
If probeTab Is Nothing Then
    WScript.Echo "STATUS: COULD_NOT_CHECK reason=SE16H_selection_screen_absent"
    WScript.Quit 2
End If

oSession.findById("wnd[0]/usr/ctxtGD-TAB").text = UCase(TABLE_NAME)
oSession.findById("wnd[0]/usr/ctxtGD-TAB").setFocus
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' Table valid? An invalid/forbidden table raises a locale-independent E/A status
' (e.g. E2/007 "<T> does not exist") but ALSO leaves the PREVIOUS table's field
' list on screen (verified live: field list + GD_TABL_TEXT both stay stale) -- so
' the sbar MessageType is authoritative, NOT the field list. Branch on the code,
' never the translated text (language_independence_rules.md).
Dim mt0 : mt0 = SbarType()
If mt0 = "E" Or mt0 = "A" Then
    WScript.Echo "ERROR: table " & UCase(TABLE_NAME) & " rejected (sbar [" & mt0 & "] " & SbarText() & ")."
    WScript.Echo "STATUS: TABLE_NOT_FOUND table=" & UCase(TABLE_NAME)
    WScript.Quit 1
End If
' Secondary guard for a fresh session where an invalid table simply loads no list.
Dim firstField : firstField = ""
On Error Resume Next
firstField = oSession.findById(TC_PATH & "/txtGS_SELFIELDS-FIELDNAME[" & COL_FIELD & ",0]").text
On Error GoTo 0
If Len(Trim(firstField)) = 0 Then
    WScript.Echo "ERROR: table " & UCase(TABLE_NAME) & " did not load a field list (sbar [" & SbarType() & "] " & SbarText() & ")."
    WScript.Echo "STATUS: TABLE_NOT_FOUND table=" & UCase(TABLE_NAME)
    WScript.Quit 1
End If

' Guard: the aggregation columns must exist on this release (GROUP_BY combo/
' checkbox). Absence => SE16H present but without the outline model => caller
' should use the local fallback.
On Error Resume Next
Dim probeGB : Set probeGB = Nothing
Set probeGB = oSession.findById(TC_PATH & "/chkGS_SELFIELDS-GROUP_BY[" & COL_GROUP_BY & ",0]")
On Error GoTo 0
If probeGB Is Nothing Then
    WScript.Echo "STATUS: COULD_NOT_CHECK reason=SE16H_outline_controls_absent"
    WScript.Quit 2
End If

' ----------------------------------------------------------------------------
' 3. Caps: MAX_LINES (returned groups) + optional grouping minimum
' ----------------------------------------------------------------------------
On Error Resume Next
oSession.findById("wnd[0]/usr/txtGD-MAX_LINES").text = CStr(maxGroups)
If Len(minCount) > 0 And IsNumeric(minCount) Then _
    oSession.findById("wnd[0]/usr/txtGD-MIN_COUNT").text = minCount
On Error GoTo 0

' ----------------------------------------------------------------------------
' 4. FILTERs (scope the aggregation)
' ----------------------------------------------------------------------------
Dim i, vRow
For i = 0 To nFilt - 1
    vRow = FindRowByFieldName(aFiltF(i))
    If vRow < 0 Then
        WScript.Echo "ERROR: filter field " & aFiltF(i) & " not found in " & UCase(TABLE_NAME)
        WScript.Echo "STATUS: FIELD_NOT_FOUND field=" & aFiltF(i)
        WScript.Quit 1
    End If
    Dim vals : vals = Split(aFiltVals(i), vbTab)
    If (aFiltOp(i) = "BT" Or aFiltOp(i) = "NB") And UBound(vals) = 1 Then
        SetCell TC_PATH & "/ctxtGS_SELFIELDS-LOW[" & COL_LOW & "," & vRow & "]", vals(0)
        SetCell TC_PATH & "/ctxtGS_SELFIELDS-HIGH[" & COL_HIGH & "," & vRow & "]", vals(1)
        oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    ElseIf aFiltOp(i) = "IN" Or UBound(vals) >= 1 Then
        FillMultiSelect vRow, vals
    Else
        SetCell TC_PATH & "/ctxtGS_SELFIELDS-LOW[" & COL_LOW & "," & vRow & "]", vals(0)
        oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    End If
    WScript.Sleep 150
Next

' ----------------------------------------------------------------------------
' 5. GROUP BY ticks
' ----------------------------------------------------------------------------
For i = 0 To nGroup - 1
    vRow = FindRowByFieldName(aGroup(i))
    If vRow < 0 Then
        WScript.Echo "ERROR: group-by field " & aGroup(i) & " not found in " & UCase(TABLE_NAME)
        WScript.Echo "STATUS: FIELD_NOT_FOUND field=" & aGroup(i)
        WScript.Quit 1
    End If
    On Error Resume Next
    oSession.findById(TC_PATH & "/chkGS_SELFIELDS-GROUP_BY[" & COL_GROUP_BY & "," & vRow & "]").selected = True
    If Err.Number <> 0 Then
        On Error GoTo 0
        WScript.Echo "STATUS: FIELD_NOT_GROUPABLE field=" & aGroup(i)
        WScript.Quit 1
    End If
    On Error GoTo 0
Next

' ----------------------------------------------------------------------------
' 6. AGGREGATE combo (MIN/MAX/AVG)
' ----------------------------------------------------------------------------
For i = 0 To nAgg - 1
    vRow = FindRowByFieldName(aAggF(i))
    If vRow < 0 Then
        WScript.Echo "ERROR: aggregate field " & aAggF(i) & " not found in " & UCase(TABLE_NAME)
        WScript.Echo "STATUS: FIELD_NOT_FOUND field=" & aAggF(i)
        WScript.Quit 1
    End If
    On Error Resume Next
    oSession.findById(TC_PATH & "/cmbGS_SELFIELDS-AGGREGATE[" & COL_AGGREG & "," & vRow & "]").key = aAggK(i)
    If Err.Number <> 0 Then
        On Error GoTo 0
        ' The combo rejects a func the field type does not support (e.g. AVG on a
        ' char field on some builds). Report per-field rather than a wrong result.
        WScript.Echo "STATUS: AGG_NOT_APPLICABLE field=" & aAggF(i) & " func=" & aAggK(i)
        WScript.Quit 1
    End If
    On Error GoTo 0
Next

' ----------------------------------------------------------------------------
' 7. Execute
' ----------------------------------------------------------------------------
oSession.findById("wnd[0]").sendVKey VKEY_ENTER          ' PAI: register outline
WScript.Sleep 300
oSession.findById("wnd[0]/tbar[1]/btn[8]").press         ' F8 execute
WScript.Sleep 1200

' ----------------------------------------------------------------------------
' 8. Result grid -> TSV
' ----------------------------------------------------------------------------
Dim oGrid : Set oGrid = Nothing
Dim tries
For tries = 1 To 8
    On Error Resume Next
    Set oGrid = Nothing
    Set oGrid = oSession.findById(RESULT_GRID)
    On Error GoTo 0
    If Not (oGrid Is Nothing) Then Exit For
    WScript.Sleep 400
Next
If oGrid Is Nothing Then
    WScript.Echo "ERROR: no result ALV after execute (sbar [" & SbarType() & "] " & SbarText() & ")"
    WScript.Echo "STATUS: NO_RESULT_GRID sbar_type=" & SbarType()
    WScript.Quit 1
End If

Dim rowCount : rowCount = oGrid.RowCount
Dim cols : Set cols = oGrid.ColumnOrder
Dim nCols : nCols = cols.Count

Dim oOut : Set oOut = oFSO.CreateTextFile(OUTPUT_FILE, True, True)   ' Unicode
' header (technical column ids)
Dim hdr, c
hdr = ""
For c = 0 To nCols - 1
    If c > 0 Then hdr = hdr & vbTab
    hdr = hdr & cols.ElementAt(c)
Next
oOut.WriteLine hdr

' rows -- page firstVisibleRow so a large grid fully renders before reads
Dim r, rr, line, vis, pageEnd
r = 0
Do While r < rowCount
    On Error Resume Next
    oGrid.firstVisibleRow = r
    On Error GoTo 0
    vis = oGrid.VisibleRowCount
    If vis < 1 Then vis = 1
    pageEnd = r + vis - 1
    If pageEnd > rowCount - 1 Then pageEnd = rowCount - 1
    For rr = r To pageEnd
        line = ""
        For c = 0 To nCols - 1
            If c > 0 Then line = line & vbTab
            Dim cv : cv = ""
            On Error Resume Next
            cv = oGrid.GetCellValue(rr, cols.ElementAt(c))
            On Error GoTo 0
            line = line & cv
        Next
        oOut.WriteLine line
    Next
    r = pageEnd + 1
Loop
oOut.Close

Dim truncated : truncated = 0
If rowCount >= maxGroups Then truncated = 1

Dim gbList : gbList = JoinArr(aGroup, nGroup, ",")
Dim agList : agList = ""
For i = 0 To nAgg - 1
    If i > 0 Then agList = agList & ","
    agList = agList & aAggF(i) & ":" & aAggK(i)
Next

WScript.Echo "SE16H_AGG: table=" & UCase(TABLE_NAME) & " groups=" & rowCount & _
    " cols=" & nCols & " truncated=" & truncated & " group_by=[" & gbList & "] agg=[" & agList & "]"
WScript.Echo "ROWS=" & rowCount
WScript.Echo "STATUS: OK"
WScript.Quit 0

' =============================================================================
' Helpers
' =============================================================================
Function FindRowByFieldName(byval target)
    Dim tbl, maxScroll, pageSize, scrollPos, r2, sName
    Set tbl = oSession.findById(TC_PATH)
    maxScroll = 0 : pageSize = 0
    On Error Resume Next
    maxScroll = tbl.verticalScrollbar.maximum
    pageSize  = tbl.verticalScrollbar.pageSize
    Err.Clear
    On Error GoTo 0
    If pageSize <= 0 Then pageSize = 14
    target = UCase(Trim(target))
    scrollPos = 0
    Do
        On Error Resume Next
        tbl.verticalScrollbar.position = scrollPos
        Err.Clear
        On Error GoTo 0
        WScript.Sleep 40
        For r2 = 0 To pageSize - 1
            On Error Resume Next
            sName = ""
            sName = oSession.findById(TC_PATH & "/txtGS_SELFIELDS-FIELDNAME[" & COL_FIELD & "," & r2 & "]").text
            If Err.Number = 0 And UCase(Trim(sName)) = target Then
                Err.Clear
                On Error GoTo 0
                FindRowByFieldName = r2
                Exit Function
            End If
            Err.Clear
            On Error GoTo 0
        Next
        If scrollPos >= maxScroll Then Exit Do
        scrollPos = scrollPos + pageSize
        If scrollPos > maxScroll Then scrollPos = maxScroll
    Loop
    FindRowByFieldName = -1
End Function

Sub SetCell(byval sId, byval sVal)
    On Error Resume Next
    oSession.findById(sId).text = sVal
    Err.Clear
    On Error GoTo 0
End Sub

Sub FillMultiSelect(byval vRow, byval vals)
    On Error Resume Next
    oSession.findById(TC_PATH & "/btnPUSH[" & COL_BTNPUSH & "," & vRow & "]").press
    WScript.Sleep 1000
    Dim j, popupRow
    For j = 0 To UBound(vals)
        popupRow = j
        If j >= 8 Then
            oSession.findById("wnd[1]/usr/tblSAPLSE16NMULTI_TC").verticalScrollbar.position = j - 7
            popupRow = 7
        End If
        oSession.findById("wnd[1]/usr/tblSAPLSE16NMULTI_TC/ctxtGS_MULTI_SELECT-LOW[1," & popupRow & "]").text = vals(j)
        Err.Clear
    Next
    oSession.findById("wnd[1]/tbar[0]/btn[0]").press    ' validate
    WScript.Sleep 300
    oSession.findById("wnd[1]/tbar[0]/btn[8]").press    ' copy
    If Err.Number <> 0 Then
        Err.Clear
        oSession.findById("wnd[1]").sendVKey VKEY_F8
    End If
    Err.Clear
    On Error GoTo 0
    WScript.Sleep 500
End Sub

Function SbarText()
    On Error Resume Next
    SbarText = oSession.findById("wnd[0]/sbar").text
    If Err.Number <> 0 Then SbarText = ""
    Err.Clear
    On Error GoTo 0
End Function

Function SbarType()
    On Error Resume Next
    SbarType = oSession.findById("wnd[0]/sbar").messageType
    If Err.Number <> 0 Then SbarType = ""
    Err.Clear
    On Error GoTo 0
End Function

Function JoinArr(byref arr, byval n, byval sep)
    Dim s, i2 : s = ""
    For i2 = 0 To n - 1
        If i2 > 0 Then s = s & sep
        s = s & arr(i2)
    Next
    JoinArr = s
End Function

Sub DismissModals()
    Dim attempt, idx, oWnd, oCancel
    For attempt = 1 To 5
        Dim any : any = False
        For idx = 5 To 1 Step -1
            On Error Resume Next
            Set oWnd = Nothing
            Set oWnd = oSession.findById("wnd[" & idx & "]")
            If Err.Number = 0 And Not (oWnd Is Nothing) Then
                Err.Clear
                Set oCancel = Nothing
                Set oCancel = oSession.findById("wnd[" & idx & "]/usr/btnSPOP-OPTION2")
                If Err.Number = 0 And Not (oCancel Is Nothing) Then
                    Err.Clear
                    oCancel.press
                Else
                    Err.Clear
                    oWnd.sendVKey VKEY_F12
                End If
                any = True
                WScript.Sleep 250
            End If
            Err.Clear
            On Error GoTo 0
        Next
        If Not any Then Exit Sub
    Next
End Sub
