' =============================================================================
' sap_se91_change_props.vbs  -  SAP GUI Scripting: Change SE91 Message Class
'                                Header (Short Text, Person Responsible, ...)
'
' Generated by the sap-se91 skill.
' Attaches to an existing SAP GUI session, navigates to SE91, opens the
' message class HEADER (radRSDAG-MIDFLAG) in change mode (btnMODTASTE),
' then updates the supplied fields on
'   wnd[0]/usr/tabsCONTROL1000/tabpHEAD/ssubSUB:SAPLWBMESSAGES:0102/...
' and Saves (toolbar btn[11]). Handles the conditional original-language
' popup (SAPLSETX) and the post-save Workbench-request popup (per
' /sap-transport-request).
'
' Tokens replaced at run time:
'   %%MSG_CLASS%%    Message class name             e.g. "ZHKA01"
'   %%SHORT_TEXT%%   New T100A-STEXT (max 60 chars). Empty = leave unchanged.
'   %%RESPONSIBLE%%  New person responsible (T100A-RESPUSER). Empty = unchanged.
'   %%TRANSPORT%%    TR for the post-save TR popup. Empty when local ($TMP)
'                    or already locked to a modifiable TR.
'
' Recorded baseline (Record_SE91_ChangeClassAttributes.vbs):
'   /nSE91 -> ctxtRSDAG-ARBGB -> radRSDAG-MIDFLAG -> btnMODTASTE
'   tabsCONTROL1000/tabpHEAD/ssubSUB:SAPLWBMESSAGES:0102/txtT100A-STEXT
'   tbar[0]/btn[11]  (Save)
'   tbar[0]/btn[15]  (Back)
' =============================================================================

Option Explicit

Const MSG_CLASS        = "%%MSG_CLASS%%"
Const NEW_SHORT_TEXT   = "%%SHORT_TEXT%%"
Const NEW_RESPONSIBLE  = "%%RESPONSIBLE%%"
Const SAP_TRANSPORT    = "%%TRANSPORT%%"

Const VKEY_ENTER     = 0
Const VKEY_F11_SAVE  = 11
Const VKEY_F3_BACK   = 3
Const HEAD_BASE      = "wnd[0]/usr/tabsCONTROL1000/tabpHEAD/ssubSUB:SAPLWBMESSAGES:0102"

Dim oSAPGUI, oApp, oSession, oCandidate, oSessIter

' ------ 1. Attach to existing SAP GUI session -------------------------------
On Error Resume Next
Set oSAPGUI = GetObject("SAPGUI")
If Err.Number <> 0 Or oSAPGUI Is Nothing Then
    WScript.Echo "ERROR: SAP GUI is not running."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

Set oApp = oSAPGUI.GetScriptingEngine
Set oSession = Nothing
On Error Resume Next
For Each oCandidate In oApp.Children
    For Each oSessIter In oCandidate.Children
        Set oSession = oSessIter
        Exit For
    Next
    If Not (oSession Is Nothing) Then Exit For
Next
On Error GoTo 0

If oSession Is Nothing Then
    WScript.Echo "ERROR: No SAP GUI session found. Run the login step first."
    WScript.Quit 1
End If
WScript.Echo "INFO: Session acquired."

' ------ 2. Navigate to SE91 -------------------------------------------------
WScript.Echo "INFO: Navigating to SE91..."
On Error Resume Next
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE91"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000
Err.Clear
On Error GoTo 0

' ------ 3. Enter message class + select Header radio + Change ---------------
WScript.Echo "INFO: Opening message class header in change mode: " & UCase(MSG_CLASS)
On Error Resume Next
Dim oArbgb
Set oArbgb = oSession.findById("wnd[0]/usr/ctxtRSDAG-ARBGB")
If Err.Number <> 0 Or oArbgb Is Nothing Then
    WScript.Echo "ERROR: SE91 initial screen field ctxtRSDAG-ARBGB not found."
    WScript.Quit 1
End If
oArbgb.Text = UCase(MSG_CLASS)

Dim oRad
Err.Clear
Set oRad = oSession.findById("wnd[0]/usr/radRSDAG-MIDFLAG")
If Err.Number <> 0 Or oRad Is Nothing Then
    WScript.Echo "ERROR: SE91 'Message Class' radio (radRSDAG-MIDFLAG) not found."
    WScript.Quit 1
End If
oRad.setFocus
oRad.select
WScript.Sleep 200

Dim oChg
Err.Clear
Set oChg = oSession.findById("wnd[0]/usr/btnMODTASTE")
If Err.Number <> 0 Or oChg Is Nothing Then
    WScript.Echo "ERROR: SE91 Change button (btnMODTASTE) not found."
    WScript.Quit 1
End If
oChg.press
WScript.Sleep 1500
Err.Clear
On Error GoTo 0

' ------ 3a. Original-language popup (SAPLSETX, conditional) -----------------
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim oML
    Set oML = Nothing
    Err.Clear
    Set oML = oSession.findById("wnd[1]/usr/ctxtRSETX-MASTERLANG")
    If Err.Number = 0 And Not (oML Is Nothing) Then
        Dim oMaintBtn
        Set oMaintBtn = Nothing
        Err.Clear
        Set oMaintBtn = oSession.findById("wnd[1]/usr/btnPUSH1")
        If Err.Number = 0 And Not (oMaintBtn Is Nothing) Then
            WScript.Echo "INFO: Original-language popup (MASTERLANG=" & _
                         oML.Text & ") - pressing 'Maint. in orig. lang.'."
            oMaintBtn.press
            WScript.Sleep 1500
        End If
    End If
End If
Err.Clear
On Error GoTo 0

' ------ 4. Verify Header tab is reachable -----------------------------------
Dim oStext
On Error Resume Next
Err.Clear
Set oStext = oSession.findById(HEAD_BASE & "/txtT100A-STEXT")
If Err.Number <> 0 Or oStext Is Nothing Then
    ' May need to click the HEAD tab explicitly if not active
    Err.Clear
    Dim oTab
    Set oTab = oSession.findById("wnd[0]/usr/tabsCONTROL1000/tabpHEAD")
    If Err.Number = 0 And Not (oTab Is Nothing) Then
        oTab.select
        WScript.Sleep 500
    End If
    Err.Clear
    Set oStext = oSession.findById(HEAD_BASE & "/txtT100A-STEXT")
End If
If Err.Number <> 0 Or oStext Is Nothing Then
    WScript.Echo "ERROR: Header tab field " & HEAD_BASE & "/txtT100A-STEXT not reachable."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0
WScript.Echo "INFO: Header tab open."

' ------ 5. Apply changes ----------------------------------------------------
Dim sChanges
sChanges = ""

If NEW_SHORT_TEXT <> "" Then
    On Error Resume Next
    oStext.Text = NEW_SHORT_TEXT
    If Err.Number <> 0 Then
        WScript.Echo "ERROR: Could not set short text (screen may still be display-only). " & Err.Description
        WScript.Quit 1
    End If
    Err.Clear
    On Error GoTo 0
    sChanges = sChanges & " short_text='" & NEW_SHORT_TEXT & "'"
End If

If NEW_RESPONSIBLE <> "" Then
    On Error Resume Next
    Dim oResp
    Err.Clear
    Set oResp = oSession.findById(HEAD_BASE & "/ctxtT100A-RESPUSER")
    If Err.Number <> 0 Or oResp Is Nothing Then
        Err.Clear
        Set oResp = oSession.findById(HEAD_BASE & "/txtT100A-RESPUSER")
    End If
    If Err.Number <> 0 Or oResp Is Nothing Then
        WScript.Echo "ERROR: Person-responsible field (T100A-RESPUSER) not found on header tab."
        WScript.Quit 1
    End If
    oResp.Text = UCase(NEW_RESPONSIBLE)
    If Err.Number <> 0 Then
        WScript.Echo "ERROR: Could not set person responsible. " & Err.Description
        WScript.Quit 1
    End If
    Err.Clear
    On Error GoTo 0
    sChanges = sChanges & " responsible='" & UCase(NEW_RESPONSIBLE) & "'"
End If

If sChanges = "" Then
    WScript.Echo "INFO: No header values supplied - nothing to change."
    WScript.Echo "INFO: Backing out without saving (F3)."
    On Error Resume Next
    oSession.findById("wnd[0]").sendVKey VKEY_F3_BACK
    WScript.Sleep 1000
    ' Decline 'data has changed' popup if it appears (it shouldn't, but be safe)
    If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
        Err.Clear
        Dim oNo
        Set oNo = oSession.findById("wnd[1]/usr/btnSPOP-OPTION2")
        If Err.Number = 0 And Not (oNo Is Nothing) Then oNo.press
    End If
    Err.Clear
    On Error GoTo 0
    WScript.Echo "DONE: NO_CHANGE"
    WScript.Quit 0
End If

WScript.Echo "INFO: Applying changes:" & sChanges

' ------ 6. Save (toolbar btn[11] = Ctrl+S) ----------------------------------
WScript.Echo "INFO: Saving (tbar[0]/btn[11])..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[0]/btn[11]").press
WScript.Sleep 1500
Err.Clear
On Error GoTo 0

' ------ 6a. Optional Workbench-request / Error popup loop -------------------
On Error Resume Next
Dim iLoop
For iLoop = 1 To 3
    If InStr(oSession.ActiveWindow.Id, "wnd[1]") = 0 Then Exit For

    Dim oTrField
    Set oTrField = Nothing
    Err.Clear
    Set oTrField = oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR")
    If Err.Number = 0 And Not (oTrField Is Nothing) Then
        If SAP_TRANSPORT = "" Then
            WScript.Echo "ERROR: SAP prompted for a transport request but TRANSPORT is empty." & vbCrLf & _
                         "       Resolve a modifiable TR via /sap-transport-request and re-run."
            On Error Resume Next
            oSession.findById("wnd[1]").sendVKey 12
            Err.Clear
            On Error GoTo 0
            WScript.Quit 1
        End If
        oTrField.Text = SAP_TRANSPORT
        WScript.Echo "INFO: TR popup - entering " & SAP_TRANSPORT & "."
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1200
    Else
        Dim sTitle, oM1, oM2, sM1, sM2
        sTitle = oSession.ActiveWindow.Text
        sM1 = "" : sM2 = ""
        Err.Clear
        Set oM1 = oSession.findById("wnd[1]/usr/txtMESSTXT1")
        If Err.Number = 0 And Not (oM1 Is Nothing) Then sM1 = oM1.Text
        Err.Clear
        Set oM2 = oSession.findById("wnd[1]/usr/txtMESSTXT2")
        If Err.Number = 0 And Not (oM2 Is Nothing) Then sM2 = oM2.Text
        Err.Clear
        If LCase(sTitle) = "error" Or InStr(LCase(sM1 & " " & sM2), "locked") > 0 Then
            WScript.Echo "ERROR: SAP popup [" & sTitle & "] " & Trim(sM1 & " " & sM2)
            On Error Resume Next
            oSession.findById("wnd[1]/tbar[0]/btn[12]").press
            If Err.Number <> 0 Then
                Err.Clear
                oSession.findById("wnd[1]").sendVKey 12
            End If
            Err.Clear
            On Error GoTo 0
            WScript.Quit 1
        End If
        WScript.Echo "INFO: Confirming popup [" & sTitle & "] - pressing Enter."
        oSession.ActiveWindow.sendVKey VKEY_ENTER
        WScript.Sleep 1000
    End If
Next
Err.Clear
On Error GoTo 0

' ------ 7. Read status bar --------------------------------------------------
Dim sBarText, sBarType
sBarText = "" : sBarType = ""
On Error Resume Next
sBarText = oSession.findById("wnd[0]/sbar").Text
sBarType = oSession.findById("wnd[0]/sbar").MessageType
Err.Clear
On Error GoTo 0

WScript.Echo "INFO: Status bar [" & sBarType & "]: " & sBarText
If LCase(sBarType) = "e" Or LCase(sBarType) = "a" Then
    WScript.Echo "ERROR: Save failed - " & sBarText
    WScript.Quit 1
End If

' ------ 8. Back to /n -------------------------------------------------------
On Error Resume Next
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
Err.Clear
On Error GoTo 0

WScript.Echo "SUCCESS: Header updated for " & UCase(MSG_CLASS) & "."
WScript.Quit 0
