' =============================================================================
' sap_se91_check.vbs  -  SAP GUI Scripting: Check if message class exists
'
' Generated by the sap-se91 skill.
' Attaches to an existing SAP GUI session, navigates to SE91,
' attempts Display, and checks if the editor opens (vs Initial Screen).
'
' Output: "EXIST" or "NOT_EXIST" (last line of stdout, parseable by skill).
'
' Tokens replaced at run time:
'   %%MSG_CLASS%%  Message class name  e.g. "ZHKMSG01"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const MSG_CLASS    = "%%MSG_CLASS%%"
Const SESSION_PATH = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default
Const VKEY_ENTER   = 0

ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SE91 -------------------------------------------------
WScript.Echo "INFO: Navigating to SE91..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nSE91"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Enter message class name and click Display -----------------------
WScript.Echo "INFO: Checking message class: " & UCase(MSG_CLASS)
oSession.findById("wnd[0]/usr/ctxtRSDAG-ARBGB").Text = UCase(MSG_CLASS)
oSession.findById("wnd[0]/usr/radRSDAG-MIDFLAG").select   ' Attributes radio
WScript.Sleep 300
oSession.findById("wnd[0]/usr/btnANZTASTE").press   ' Display
WScript.Sleep 2000

' ------ 4. Determine result -------------------------------------------------
' Language-independent detection (per language_independence_rules.md):
' the SE91 initial screen has a name input field at
' wnd[0]/usr/ctxtRSDAG-ARBGB. If that ID still resolves after pressing
' Display, we did NOT navigate into the editor → class does not exist.
' (Title-text branching on "Initial" was English-only and produced
' false-positive EXIST for nonexistent classes under JA logon.)
Dim bStillOnInitial, oInitProbe
On Error Resume Next
Set oInitProbe = oSession.findById("wnd[0]/usr/ctxtRSDAG-ARBGB")
bStillOnInitial = (Err.Number = 0) And Not (oInitProbe Is Nothing)
Err.Clear
On Error GoTo 0

If bStillOnInitial Then
    Dim sStatus, sType
    On Error Resume Next
    sStatus = oSession.findById("wnd[0]/sbar").Text
    sType   = oSession.findById("wnd[0]/sbar").MessageType
    Err.Clear
    On Error GoTo 0
    WScript.Echo "INFO: " & sStatus & " (type=" & sType & ")"
    WScript.Echo "NOT_EXIST"
Else
    WScript.Echo "INFO: Message class " & UCase(MSG_CLASS) & " exists."
    ' Navigate back to SE91 initial screen
    oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nSE91"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    WScript.Echo "EXIST"
End If

WScript.Quit 0
