' =============================================================================
' sap_mm01_create.vbs  -  SAP GUI Scripting: Create material master via MM01
'
' Generated by the sap-mm01 skill.
' Attaches to an existing SAP GUI session, navigates to MM01, creates a new
' material with the given type and industry sector, selects all views,
' sets organizational levels, fills field values from a definition file,
' and saves.
'
' Definition file format (tab-separated, one field per line):
'   ORG	RMMG1-WERKS	1000
'   SP01	MAKT-MAKTX	Test Material
'   SP01	MARA-MEINS	PC
'   SP13	MARC-DISMM	PD
'
' Sections: ORG (organizational levels popup), SP01-SP35 (tab panels)
' Lines starting with # are comments. Blank lines are skipped.
'
' Tokens replaced at run time:
'   %%MATERIAL%%         Material number          e.g. "ZHKMAT013"
'   %%INDUSTRY%%         Industry sector key      e.g. "M"
'   %%MATERIAL_TYPE%%    Material type key         e.g. "FERT"
'   %%DEFINITION_FILE%%  Path to field definitions e.g. "{WORK_TEMP}\mm01_fields.txt"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const MATERIAL        = "%%MATERIAL%%"
Const INDUSTRY        = "%%INDUSTRY%%"
Const MATERIAL_TYPE   = "%%MATERIAL_TYPE%%"
Const DEFINITION_FILE = "%%DEFINITION_FILE%%"

Const VKEY_ENTER    = 0
Const VKEY_F11_SAVE = 11
Const SESSION_PATH  = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

' Include shared helpers (attach first; session-lock's pre-unlock sweep
' reads from oSession).
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()

' ------ Helper: Find input field by name within a container (recursive) -----
Function FindField(oContainer, sFieldName)
    Set FindField = Nothing
    On Error Resume Next
    Dim ch
    Set ch = oContainer.Children
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    On Error GoTo 0

    Dim j, c, cName, cType
    For j = 0 To ch.Count - 1
        Set c = ch(CLng(j))
        On Error Resume Next
        cName = c.Name
        cType = c.Type
        Err.Clear
        On Error GoTo 0

        If cName = sFieldName Then
            If cType = "GuiTextField" Or cType = "GuiCTextField" Or _
               cType = "GuiComboBox" Or cType = "GuiCheckBox" Then
                Set FindField = c
                Exit Function
            End If
        End If

        If cType = "GuiSimpleContainer" Or cType = "GuiScrollContainer" Or _
           cType = "GuiTabStrip" Or cType = "GuiTab" Then
            Dim found
            Set found = FindField(c, sFieldName)
            If Not (found Is Nothing) Then
                Set FindField = found
                Exit Function
            End If
        End If
    Next
End Function

' ------ Helper: Set field value based on control type -----------------------
Sub SetFieldValue(oField, sValue)
    Select Case oField.Type
        Case "GuiTextField", "GuiCTextField"
            oField.Text = sValue
        Case "GuiComboBox"
            oField.Key = sValue
        Case "GuiCheckBox"
            If UCase(sValue) = "X" Or sValue = "1" Or UCase(sValue) = "TRUE" Then
                oField.Selected = True
            Else
                oField.Selected = False
            End If
    End Select
End Sub

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Read definition file ---------------------------------------------
Dim oFSO, oFile, sLine
Set oFSO = CreateObject("Scripting.FileSystemObject")

If Not oFSO.FileExists(DEFINITION_FILE) Then
    WScript.Echo "ERROR: Definition file not found: " & DEFINITION_FILE
    WScript.Quit 1
End If

' Parse into arrays: section, field name, value
Dim arrSections(), arrFields(), arrValues()
Dim iCount
iCount = 0

Set oFile = oFSO.OpenTextFile(DEFINITION_FILE, 1, False)
Do While Not oFile.AtEndOfStream
    sLine = oFile.ReadLine
    ' Strip UTF-8 BOM if present on first line
    If iCount = 0 And Len(sLine) > 0 Then
        Do While Len(sLine) > 0 And Asc(Left(sLine, 1)) > 127
            sLine = Mid(sLine, 2)
        Loop
    End If

    sLine = Trim(sLine)

    If Len(sLine) > 0 And Left(sLine, 1) <> "#" Then
        Dim iParts
        iParts = InStr(sLine, vbTab)

        If iParts > 0 Then
            Dim sSection, sRest
            sSection = Trim(Left(sLine, iParts - 1))
            sRest = Mid(sLine, iParts + 1)

            Dim iParts2
            iParts2 = InStr(sRest, vbTab)

            If iParts2 > 0 Then
                Dim sField, sValue
                sField = Trim(Left(sRest, iParts2 - 1))
                sValue = Mid(sRest, iParts2 + 1)

                ReDim Preserve arrSections(iCount)
                ReDim Preserve arrFields(iCount)
                ReDim Preserve arrValues(iCount)
                arrSections(iCount) = UCase(sSection)
                arrFields(iCount) = sField
                arrValues(iCount) = sValue
                iCount = iCount + 1
            End If
        End If
    End If
Loop
oFile.Close

WScript.Echo "INFO: Read " & iCount & " field definitions from file."

' --- Lock the SAP session UI for the MM01 multi-view input + save critical section ---
' Defence in depth (Rule 7): AppActivate guards external focus stealing;
' LockSessionUI guards in-session input races. Released after activation.
Dim wasLocked : wasLocked = TryLockSession(oSession)
If wasLocked Then
    WScript.Echo "INFO: Session UI locked for the MM01 multi-view input + save critical section."
Else
    WScript.Echo "INFO: LockSessionUI not available on this SAP GUI build; continuing without lock."
End If

' ------ 3. Navigate to MM01 -------------------------------------------------
WScript.Echo "INFO: Navigating to MM01..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nMM01"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 4. Fill initial screen ----------------------------------------------
WScript.Echo "INFO: Creating material: " & MATERIAL & " (Industry=" & INDUSTRY & ", Type=" & MATERIAL_TYPE & ")"
oSession.findById("wnd[0]/usr/ctxtRMMG1-MATNR").Text = MATERIAL
oSession.findById("wnd[0]/usr/cmbRMMG1-MBRSH").Key = INDUSTRY
oSession.findById("wnd[0]/usr/cmbRMMG1-MTART").Key = MATERIAL_TYPE
WScript.Sleep 300

oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' Check for errors
Dim sStatus
sStatus = oSession.findById("wnd[0]/sbar").Text
If oSession.findById("wnd[0]/sbar").MessageType = "E" Then
    WScript.Echo "ERROR: " & sStatus
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

' ------ 5. View selection popup - Select All --------------------------------
On Error Resume Next
Dim oPopup
Set oPopup = oSession.findById("wnd[1]")
If Err.Number = 0 And InStr(oPopup.Text, "View") > 0 Then
    WScript.Echo "INFO: Selecting all views..."
    oPopup.findById("tbar[0]/btn[20]").Press   ' Select All
    WScript.Sleep 300
    oPopup.findById("tbar[0]/btn[0]").Press    ' Enter/Continue
    WScript.Sleep 500
Else
    Err.Clear
End If
On Error GoTo 0

' ------ 6. Organizational Levels popup --------------------------------------
On Error Resume Next
Set oPopup = oSession.findById("wnd[1]")
If Err.Number = 0 And InStr(oPopup.Text, "Org") > 0 Then
    WScript.Echo "INFO: Setting organizational levels..."
    Dim oPopupUsr
    Set oPopupUsr = oPopup.findById("usr")
    Dim iOrg
    For iOrg = 0 To iCount - 1
        If arrSections(iOrg) = "ORG" Then
            Dim oOrgField
            Set oOrgField = FindField(oPopupUsr, arrFields(iOrg))
            If Not (oOrgField Is Nothing) Then
                SetFieldValue oOrgField, arrValues(iOrg)
                WScript.Echo "INFO:   " & arrFields(iOrg) & " = " & arrValues(iOrg)
            Else
                WScript.Echo "WARNING: Org field not found: " & arrFields(iOrg)
            End If
        End If
    Next
    WScript.Sleep 300
    oPopup.findById("tbar[0]/btn[0]").Press   ' Enter/Continue
    WScript.Sleep 2000
Else
    Err.Clear
End If
On Error GoTo 0

' Check if we reached the data screen
Dim sTitle
sTitle = oSession.findById("wnd[0]").Text
If InStr(sTitle, "Create Material") = 0 Or InStr(sTitle, "Initial") > 0 Then
    sStatus = oSession.findById("wnd[0]/sbar").Text
    WScript.Echo "ERROR: Failed to reach data screen. Title: " & sTitle
    WScript.Echo "ERROR: Status: " & sStatus
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If
WScript.Echo "INFO: Data screen reached: " & sTitle

' ------ 7. Fill tab fields --------------------------------------------------
' Collect unique tab IDs in order
Dim arrTabs()
Dim iTabCount
iTabCount = 0

Dim iTmp
For iTmp = 0 To iCount - 1
    If arrSections(iTmp) <> "ORG" Then
        ' Check if tab already in array
        Dim bFound
        bFound = False
        Dim iChk
        For iChk = 0 To iTabCount - 1
            If arrTabs(iChk) = arrSections(iTmp) Then
                bFound = True
                Exit For
            End If
        Next
        If Not bFound Then
            ReDim Preserve arrTabs(iTabCount)
            arrTabs(iTabCount) = arrSections(iTmp)
            iTabCount = iTabCount + 1
        End If
    End If
Next

WScript.Echo "INFO: Processing " & iTabCount & " tabs..."

Dim iTab, sTabSection, sTabId
For iTab = 0 To iTabCount - 1
    sTabSection = arrTabs(iTab)
    sTabId = "tabp" & sTabSection

    ' Select the tab
    Dim bTabOk
    bTabOk = True
    On Error Resume Next
    oSession.findById("wnd[0]/usr/tabsTABSPR1/" & sTabId).Select
    WScript.Sleep 500
    If Err.Number <> 0 Then
        WScript.Echo "WARNING: Tab " & sTabSection & " not found, skipping."
        Err.Clear
        bTabOk = False
    End If
    On Error GoTo 0

    If bTabOk Then
        WScript.Echo "INFO: Tab " & sTabSection & "..."

        ' Get tab panel reference
        Dim oTabPanel
        Set oTabPanel = oSession.findById("wnd[0]/usr/tabsTABSPR1/" & sTabId)

        ' Set each field for this tab
        Dim iFld
        For iFld = 0 To iCount - 1
            If arrSections(iFld) = sTabSection Then
                On Error Resume Next
                Dim oField
                Set oField = FindField(oTabPanel, arrFields(iFld))
                If oField Is Nothing Then
                    WScript.Echo "WARNING:   Field not found: " & arrFields(iFld)
                Else
                    SetFieldValue oField, arrValues(iFld)
                    WScript.Echo "INFO:   " & arrFields(iFld) & " = " & arrValues(iFld)
                End If
                Err.Clear
                On Error GoTo 0
            End If
        Next
    End If
Next

' Press Enter to commit inline edits
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 8. Save -------------------------------------------------------------
WScript.Echo "INFO: Saving material..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 2000

' Handle warning: SAP shows warning in status bar - press Enter to acknowledge, then save again
Dim sSaveStatus, sSaveType
sSaveStatus = oSession.findById("wnd[0]/sbar").Text
sSaveType = oSession.findById("wnd[0]/sbar").MessageType
If sSaveType = "W" Then
    WScript.Echo "INFO: Warning after save: " & sSaveStatus & " - acknowledging with Enter..."
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 1000
    oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
    WScript.Sleep 2000
End If

' Handle transport / package popup
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    WScript.Echo "INFO: Package/transport dialog detected."
    ' Try "Local Object" button first
    oSession.findById("wnd[1]/tbar[0]/btn[7]").Press
    If Err.Number <> 0 Then
        Err.Clear
        oSession.ActiveWindow.sendVKey VKEY_ENTER
    End If
    WScript.Sleep 2000
End If

' Handle second popup if any
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSession.ActiveWindow.sendVKey VKEY_ENTER
    WScript.Sleep 1000
End If
Err.Clear
On Error GoTo 0

' --- Release the session UI lock; result check is read-only ---
ReleaseSession oSession, wasLocked
If wasLocked Then WScript.Echo "INFO: Session UI lock released."

' ------ 9. Check result -----------------------------------------------------
sStatus = oSession.findById("wnd[0]/sbar").Text
Dim sStatusType
sStatusType = oSession.findById("wnd[0]/sbar").MessageType

' After save, SAP may continue to additional views (Classification etc.)
' Navigate back to a clean state
Dim sCurTitle
sCurTitle = oSession.findById("wnd[0]").Text
If InStr(sCurTitle, "Initial") = 0 Then
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    ' Handle data-loss popup if any
    On Error Resume Next
    oSession.findById("wnd[1]/usr/btnSPOP-OPTION1").Press
    Err.Clear
    On Error GoTo 0
    WScript.Sleep 500
End If

WScript.Echo "INFO: Status (" & sStatusType & "): " & sStatus

If sStatusType = "E" Or sStatusType = "A" Then
    WScript.Echo "ERROR: Material creation failed. " & sStatus
    WScript.Quit 1
End If

WScript.Echo "SUCCESS: Material " & MATERIAL & " created in SAP."
WScript.Quit 0
