' =============================================================================
' sap_mm01_check.vbs  -  SAP GUI Scripting: Check if material master exists
'
' Generated by the sap-mm01 skill.
' Attaches to an existing SAP GUI session, navigates to MM03,
' enters the material number, and checks the status bar response.
'
' Output: "EXIST" or "NOT_EXIST" (last line of stdout, parseable by skill).
'
' Tokens replaced at run time:
'   %%MATERIAL%%  Material number  e.g. "ZHKMAT013"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const MATERIAL   = "%%MATERIAL%%"
Const VKEY_ENTER = 0

Dim oSAPGUI, oApplication, oSession
Dim oCandidate, oSessIter

' ------ 1. Attach to existing SAP GUI session -------------------------------
On Error Resume Next
Set oSAPGUI = GetObject("SAPGUI")
If Err.Number <> 0 Or oSAPGUI Is Nothing Then
    WScript.Echo "ERROR: SAP GUI is not running."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

Set oApplication = oSAPGUI.GetScriptingEngine
If oApplication Is Nothing Then
    WScript.Echo "ERROR: Could not get SAP Scripting Engine."
    WScript.Quit 1
End If

Set oSession = Nothing
On Error Resume Next
For Each oCandidate In oApplication.Children
    For Each oSessIter In oCandidate.Children
        Set oSession = oSessIter
        Exit For
    Next
    If Not (oSession Is Nothing) Then Exit For
Next
On Error GoTo 0

If oSession Is Nothing Then
    WScript.Echo "ERROR: No SAP GUI session found. Run the login step first."
    WScript.Quit 1
End If
WScript.Echo "INFO: Session acquired."

' ------ 2. Navigate to MM03 -------------------------------------------------
WScript.Echo "INFO: Navigating to MM03..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nMM03"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Enter material number and press Enter ---------------------------
WScript.Echo "INFO: Checking material: " & MATERIAL
oSession.findById("wnd[0]/usr/ctxtRMMG1-MATNR").Text = MATERIAL
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 4. Determine result -------------------------------------------------
' If material does not exist: status bar shows error "does not exist or is not activated"
' If material exists: a view selection popup (wnd[1]) appears
Dim sStatus, sStatusType
sStatus = oSession.findById("wnd[0]/sbar").Text
sStatusType = oSession.findById("wnd[0]/sbar").MessageType

If sStatusType = "E" Then
    WScript.Echo "INFO: " & sStatus
    WScript.Echo "NOT_EXIST"
    WScript.Quit 0
End If

' Check for view selection popup (material exists)
On Error Resume Next
Dim oPopup
Set oPopup = oSession.findById("wnd[1]")
If Err.Number = 0 Then
    WScript.Echo "INFO: Material " & MATERIAL & " exists (view selection popup appeared)."
    ' Close popup and navigate back
    oPopup.findById("tbar[0]/btn[12]").Press  ' Cancel
    WScript.Sleep 300
    Err.Clear
    On Error GoTo 0
    WScript.Echo "EXIST"
    WScript.Quit 0
End If
Err.Clear
On Error GoTo 0

' Also check if we went straight to data screen (no view selection)
Dim sTitle
sTitle = oSession.findById("wnd[0]").Text
If InStr(sTitle, "Display Material") > 0 And InStr(sTitle, "Initial") = 0 Then
    WScript.Echo "INFO: Material " & MATERIAL & " exists."
    ' Navigate back
    oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nMM03"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    WScript.Echo "EXIST"
    WScript.Quit 0
End If

WScript.Echo "NOT_EXIST"
WScript.Quit 0
