' =============================================================================
' sap_mm01_check.vbs  -  SAP GUI Scripting: Check if material master exists
'
' Generated by the sap-mm01 skill.
' Attaches to an existing SAP GUI session, navigates to MM03,
' enters the material number, and determines existence.
'
' Locale-independent contract (language_independence_rules.md):
'   * Screen identity via control-ID probes only:
'       - MM03 initial screen ...... wnd[0]/usr/ctxtRMMG1-MATNR
'       - view-selection popup ..... wnd[1]/usr/tblSAPLMGMMTCTRL_AUSWAHL
'       - material data screen ..... wnd[0]/usr/tabsTABSPR1
'   * Message identity via sbar MessageType + MessageId/MessageNumber:
'       - M3 305 = "The material ... does not exist or is not activated"
'   * Window titles / status texts are echoed for diagnostics only --
'     control flow never branches on them.
'
' Output (last line of stdout, parseable by skill):
'   EXIST / NOT_EXIST / ERROR: ...
'   An sbar E that is NOT the known not-found message (authorization,
'   lock, ...) is reported as ERROR (exit 1), never as NOT_EXIST.
'
' Tokens replaced at run time:
'   %%MATERIAL%%  Material number  e.g. "ZHKMAT013"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const MATERIAL   = "%%MATERIAL%%"
Const VKEY_ENTER = 0
Const SESSION_PATH  = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

' MM03 not-found message identity (locale-independent; the text is translated).
Const NOTFOUND_MSGID = "M3"
Const NOTFOUND_MSGNO = "305"

ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

' ------ Helper: True when a control id resolves ------------------------------
Function ProbeId(oSess, sId)
    Dim o
    ProbeId = False
    On Error Resume Next
    Set o = Nothing
    Set o = oSess.findById(sId)
    If Err.Number = 0 And Not (o Is Nothing) Then ProbeId = True
    Err.Clear
    On Error GoTo 0
End Function

' ------ Helper: one-line sbar diagnostic ([type] id no - text) ---------------
Function SbarDiag(oSess)
    Dim t, i, n, x
    t = "" : i = "" : n = "" : x = ""
    On Error Resume Next
    t = oSess.findById("wnd[0]/sbar").MessageType
    i = oSess.findById("wnd[0]/sbar").MessageId
    n = oSess.findById("wnd[0]/sbar").MessageNumber
    x = oSess.findById("wnd[0]/sbar").Text
    Err.Clear
    On Error GoTo 0
    SbarDiag = "[" & t & "] " & i & " " & n & " - " & x
End Function

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to MM03 -------------------------------------------------
WScript.Echo "INFO: Navigating to MM03..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nMM03"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' Screen-identity gate: a missing transaction authorization (or an unexpected
' landing screen) must surface as ERROR, not fall through to NOT_EXIST.
If Not ProbeId(oSession, "wnd[0]/usr/ctxtRMMG1-MATNR") Then
    WScript.Echo "ERROR: Did not reach the MM03 initial screen (RMMG1-MATNR not found)."
    WScript.Echo "       Status (diagnostic): " & SbarDiag(oSession)
    WScript.Quit 1
End If

' ------ 3. Enter material number and press Enter ---------------------------
WScript.Echo "INFO: Checking material: " & MATERIAL
oSession.findById("wnd[0]/usr/ctxtRMMG1-MATNR").Text = MATERIAL
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 4. Determine result -------------------------------------------------
' Existence evidence is structural:
'   * view-selection popup (SAPLMGMM view table) ......... EXIST
'   * material data screen (view tabstrip TABSPR1) ....... EXIST
'   * still on initial screen + the M3 305 not-found E ... NOT_EXIST
'   * anything else (auth/lock E, unknown state) ......... ERROR
Dim sStatus, sStatusType, sMsgId, sMsgNo
sStatus     = ""
sStatusType = ""
sMsgId      = ""
sMsgNo      = ""
On Error Resume Next
sStatus     = oSession.findById("wnd[0]/sbar").Text
sStatusType = oSession.findById("wnd[0]/sbar").MessageType
sMsgId      = UCase(Trim(oSession.findById("wnd[0]/sbar").MessageId))
sMsgNo      = Trim(oSession.findById("wnd[0]/sbar").MessageNumber)
Err.Clear
On Error GoTo 0

' (a) View-selection popup -> the material exists. The view-table control id is
'     RELEASE-specific: tblSAPLMGMMTCTRL_AUSWAHL on S/4HANA (7.5x+),
'     tblSAPLMGMMTC_VIEW on ECC6 / AS ABAP 7.31 -- probe both so the check
'     works across releases (locale-independence alone is not enough).
If ProbeId(oSession, "wnd[1]/usr/tblSAPLMGMMTCTRL_AUSWAHL") _
   Or ProbeId(oSession, "wnd[1]/usr/tblSAPLMGMMTC_VIEW") Then
    WScript.Echo "INFO: Material " & MATERIAL & " exists (view-selection popup appeared)."
    On Error Resume Next
    oSession.findById("wnd[1]/tbar[0]/btn[12]").Press  ' Cancel
    Err.Clear
    On Error GoTo 0
    WScript.Sleep 300
    WScript.Echo "EXIST"
    WScript.Quit 0
End If

' (b) Some other popup is up -> unknown state, fail loud.
Dim sActWnd, sPopTitle
sActWnd = ""
On Error Resume Next
sActWnd = oSession.ActiveWindow.Id
Err.Clear
On Error GoTo 0
If InStr(sActWnd, "wnd[1]") > 0 Then
    sPopTitle = ""
    On Error Resume Next
    sPopTitle = oSession.ActiveWindow.Text   ' diagnostic only
    Err.Clear
    On Error GoTo 0
    WScript.Echo "ERROR: Unexpected popup while checking material: " & sActWnd & " -- title (diagnostic): " & sPopTitle
    WScript.Echo "       Status (diagnostic): " & SbarDiag(oSession)
    WScript.Quit 1
End If

' (c) Material data screen (single-view materials open directly).
If ProbeId(oSession, "wnd[0]/usr/tabsTABSPR1") Then
    WScript.Echo "INFO: Material " & MATERIAL & " exists (data screen reached)."
    oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nMM03"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    WScript.Echo "EXIST"
    WScript.Quit 0
End If

' (d) Still on the MM03 initial screen.
If ProbeId(oSession, "wnd[0]/usr/ctxtRMMG1-MATNR") Then
    If sStatusType = "E" And sMsgId = NOTFOUND_MSGID And sMsgNo = NOTFOUND_MSGNO Then
        WScript.Echo "INFO: Not found -- " & SbarDiag(oSession)
        WScript.Echo "NOT_EXIST"
        WScript.Quit 0
    End If
    ' Any other E (authorization, lock, ...) or an unexpected quiet state.
    WScript.Echo "ERROR: Could not determine existence -- still on the MM03 initial screen with an"
    WScript.Echo "       unrecognized status. Status (diagnostic): " & SbarDiag(oSession)
    WScript.Echo "       (NOT_EXIST is only assumed for message " & NOTFOUND_MSGID & " " & NOTFOUND_MSGNO & ".)"
    WScript.Quit 1
End If

' (e) Left the initial screen without any recognized evidence.
WScript.Echo "ERROR: Unrecognized screen state after Enter. Status (diagnostic): " & SbarDiag(oSession)
WScript.Quit 1
