' =============================================================================
' sap_mm01_create.vbs  -  SAP GUI Scripting: Create material master via MM01
'
' Generated by the sap-mm01 skill.
' Attaches to an existing SAP GUI session, navigates to MM01, creates a new
' material with the given type and industry sector, selects all views,
' sets organizational levels, fills field values from a definition file,
' and saves.
'
' Definition file format (tab-separated, one field per line):
'   ORG	RMMG1-WERKS	1000
'   SP01	MAKT-MAKTX	Test Material
'   SP01	MARA-MEINS	PC
'   SP13	MARC-DISMM	PD
'
' Sections: ORG (organizational levels popup), SP01-SP35 (tab panels)
' Lines starting with # are comments. Blank lines are skipped.
'
' Tokens replaced at run time:
'   %%MATERIAL%%         Material number          e.g. "ZHKMAT013"
'   %%INDUSTRY%%         Industry sector key      e.g. "M"
'   %%MATERIAL_TYPE%%    Material type key         e.g. "FERT"
'   %%DEFINITION_FILE%%  Path to field definitions e.g. "{RUN_TEMP}\mm01_fields.txt"
'
' Locale-independent contract (language_independence_rules.md): popups and
' screens are identified by control ids (SAPLMGMM view table, RMMG1 org
' fields, TABSPR1 tabstrip), results by sbar MessageType; titles / status
' texts are echoed for diagnostics only. On success a machine-readable
' "MATERIAL: <number>" line is echoed before the final SUCCESS line.
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const MATERIAL        = "%%MATERIAL%%"
Const INDUSTRY        = "%%INDUSTRY%%"
Const MATERIAL_TYPE   = "%%MATERIAL_TYPE%%"
Const DEFINITION_FILE = "%%DEFINITION_FILE%%"

Const VKEY_ENTER    = 0
Const VKEY_F11_SAVE = 11
Const SESSION_PATH  = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

' Include shared helpers (attach first; session-lock's pre-unlock sweep
' reads from oSession).
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()

' ------ Helper: Find input field by name within a container (recursive) -----
Function FindField(oContainer, sFieldName)
    Set FindField = Nothing
    On Error Resume Next
    Dim ch
    Set ch = oContainer.Children
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    On Error GoTo 0

    Dim j, c, cName, cType
    For j = 0 To ch.Count - 1
        Set c = ch(CLng(j))
        On Error Resume Next
        cName = c.Name
        cType = c.Type
        Err.Clear
        On Error GoTo 0

        If cName = sFieldName Then
            If cType = "GuiTextField" Or cType = "GuiCTextField" Or _
               cType = "GuiComboBox" Or cType = "GuiCheckBox" Then
                Set FindField = c
                Exit Function
            End If
        End If

        If cType = "GuiSimpleContainer" Or cType = "GuiScrollContainer" Or _
           cType = "GuiTabStrip" Or cType = "GuiTab" Then
            Dim found
            Set found = FindField(c, sFieldName)
            If Not (found Is Nothing) Then
                Set FindField = found
                Exit Function
            End If
        End If
    Next
End Function

' ------ Helper: Set field value based on control type -----------------------
Sub SetFieldValue(oField, sValue)
    Select Case oField.Type
        Case "GuiTextField", "GuiCTextField"
            oField.Text = sValue
        Case "GuiComboBox"
            oField.Key = sValue
        Case "GuiCheckBox"
            If UCase(sValue) = "X" Or sValue = "1" Or UCase(sValue) = "TRUE" Then
                oField.Selected = True
            Else
                oField.Selected = False
            End If
    End Select
End Sub

' ------ Helper: longest digit run in a string --------------------------------
Function LongestDigitRun(sText)
    Dim sBest, sCur, i, ch
    sBest = "" : sCur = ""
    For i = 1 To Len(sText)
        ch = Mid(sText, i, 1)
        If ch >= "0" And ch <= "9" Then
            sCur = sCur & ch
        Else
            If Len(sCur) > Len(sBest) Then sBest = sCur
            sCur = ""
        End If
    Next
    If Len(sCur) > Len(sBest) Then sBest = sCur
    LongestDigitRun = sBest
End Function

' ------ Helper: saved-document number from the status bar --------------------
' Locale-independent: prefers the sbar's structured MessageParameter values
' (the raw document number in any logon language; not exposed on every SAP
' GUI build, hence the On Error guards), falls back to the longest digit run
' in the localized message text.
Function ExtractSavedId(oSess, sFallbackText)
    Dim sId, oBar, iP, sCand
    sId = ""
    On Error Resume Next
    Set oBar = Nothing
    Set oBar = oSess.findById("wnd[0]/sbar")
    If Err.Number = 0 And Not (oBar Is Nothing) Then
        For iP = 0 To 7
            Err.Clear
            sCand = ""
            sCand = Trim(CStr(oBar.MessageParameter(iP)))
            If Err.Number = 0 And sCand <> "" Then
                If sCand = LongestDigitRun(sCand) Then
                    sId = sCand   ' first pure-digit parameter wins
                    Exit For
                End If
            End If
        Next
    End If
    Err.Clear
    On Error GoTo 0
    If sId = "" Then sId = LongestDigitRun(sFallbackText)
    ExtractSavedId = sId
End Function

' ------ Helper: is wnd[1] the Organizational Levels popup? -------------------
' Locale-independent discriminator: the popup is recognized by the org-level
' fields it carries (the definition file's own ORG fields first, then the
' standard RMMG1 org-level fields) -- never by the translated window title.
Function IsOrgLevelsPopup(oPopupUsr)
    Dim k, arrStd, s
    IsOrgLevelsPopup = False
    For k = 0 To iCount - 1
        If arrSections(k) = "ORG" Then
            If Not (FindField(oPopupUsr, arrFields(k)) Is Nothing) Then
                IsOrgLevelsPopup = True
                Exit Function
            End If
        End If
    Next
    arrStd = Array("RMMG1-WERKS", "RMMG1-LGORT", "RMMG1-VKORG", "RMMG1-VTWEG", "RMMG1-BWTAR", "RMMG1-LGNUM")
    For Each s In arrStd
        If Not (FindField(oPopupUsr, s) Is Nothing) Then
            IsOrgLevelsPopup = True
            Exit Function
        End If
    Next
End Function

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Read definition file ---------------------------------------------
Dim oFSO, sLine
Set oFSO = CreateObject("Scripting.FileSystemObject")

If Not oFSO.FileExists(DEFINITION_FILE) Then
    WScript.Echo "ERROR: Definition file not found: " & DEFINITION_FILE
    WScript.Quit 1
End If

' Parse into arrays: section, field name, value
' NOTE: read via ADODB.Stream with explicit Charset="utf-8". FSO.OpenTextFile
' decodes bytes with the system code page (cp932 on Japanese Windows, cp1252
' on Western), which mangles UTF-8 multi-byte sequences -- JA/ZH values would
' mojibake INTO the saved business record. ADODB.Stream decodes to the
' Unicode that the SAP GUI controls expect.
Dim arrSections(), arrFields(), arrValues()
Dim iCount
iCount = 0

Dim oStream, sAll, arrLines, iLine
Set oStream = CreateObject("ADODB.Stream")
oStream.Type = 2                    ' adTypeText
oStream.Charset = "utf-8"
oStream.Open
oStream.LoadFromFile DEFINITION_FILE
sAll = oStream.ReadText
oStream.Close

sAll = Replace(sAll, vbCrLf, vbLf)
sAll = Replace(sAll, vbCr,   vbLf)
arrLines = Split(sAll, vbLf)

For iLine = 0 To UBound(arrLines)
    sLine = arrLines(iLine)
    ' Strip a residual BOM character on the first line (belt and braces --
    ' ADODB.Stream normally consumes the UTF-8 BOM itself).
    If iLine = 0 And Len(sLine) > 0 Then
        If Left(sLine, 1) = ChrW(&HFEFF) Then sLine = Mid(sLine, 2)
    End If

    sLine = Trim(sLine)

    If Len(sLine) > 0 And Left(sLine, 1) <> "#" Then
        Dim iParts
        iParts = InStr(sLine, vbTab)

        If iParts > 0 Then
            Dim sSection, sRest
            sSection = Trim(Left(sLine, iParts - 1))
            sRest = Mid(sLine, iParts + 1)

            Dim iParts2
            iParts2 = InStr(sRest, vbTab)

            If iParts2 > 0 Then
                Dim sField, sValue
                sField = Trim(Left(sRest, iParts2 - 1))
                sValue = Mid(sRest, iParts2 + 1)

                ReDim Preserve arrSections(iCount)
                ReDim Preserve arrFields(iCount)
                ReDim Preserve arrValues(iCount)
                arrSections(iCount) = UCase(sSection)
                arrFields(iCount) = sField
                arrValues(iCount) = sValue
                iCount = iCount + 1
            End If
        End If
    End If
Next

WScript.Echo "INFO: Read " & iCount & " field definitions from file."

' --- Lock the SAP session UI for the MM01 multi-view input + save critical section ---
' Defence in depth (Rule 7): AppActivate guards external focus stealing;
' LockSessionUI guards in-session input races. Released after activation.
Dim wasLocked : wasLocked = TryLockSession(oSession)
If wasLocked Then
    WScript.Echo "INFO: Session UI locked for the MM01 multi-view input + save critical section."
Else
    WScript.Echo "INFO: LockSessionUI not available on this SAP GUI build; continuing without lock."
End If

' ------ 3. Navigate to MM01 -------------------------------------------------
WScript.Echo "INFO: Navigating to MM01..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nMM01"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 4. Fill initial screen ----------------------------------------------
WScript.Echo "INFO: Creating material: " & MATERIAL & " (Industry=" & INDUSTRY & ", Type=" & MATERIAL_TYPE & ")"
oSession.findById("wnd[0]/usr/ctxtRMMG1-MATNR").Text = MATERIAL
oSession.findById("wnd[0]/usr/cmbRMMG1-MBRSH").Key = INDUSTRY
oSession.findById("wnd[0]/usr/cmbRMMG1-MTART").Key = MATERIAL_TYPE
WScript.Sleep 300

oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' Check for errors
Dim sStatus
sStatus = oSession.findById("wnd[0]/sbar").Text
If oSession.findById("wnd[0]/sbar").MessageType = "E" Then
    WScript.Echo "ERROR: " & sStatus
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

' ------ 5. View selection popup - Select All --------------------------------
' Locale-independent: the popup is identified by its SAPLMGMM view table
' control id, never by the translated window title. The id is RELEASE-specific:
' tblSAPLMGMMTCTRL_AUSWAHL on S/4HANA (7.5x+), tblSAPLMGMMTC_VIEW on ECC6 /
' AS ABAP 7.31 -- probe both so create works across releases.
Dim oViewTbl
Set oViewTbl = Nothing
On Error Resume Next
Set oViewTbl = oSession.findById("wnd[1]/usr/tblSAPLMGMMTCTRL_AUSWAHL")
If oViewTbl Is Nothing Then Set oViewTbl = oSession.findById("wnd[1]/usr/tblSAPLMGMMTC_VIEW")
Err.Clear
On Error GoTo 0
If Not (oViewTbl Is Nothing) Then
    WScript.Echo "INFO: View-selection popup detected - selecting all views..."
    On Error Resume Next
    oSession.findById("wnd[1]/tbar[0]/btn[20]").Press   ' Select All (toolbar; S/4HANA)
    If Err.Number <> 0 Then
        Err.Clear
        ' ECC6 / 7.31 fallback: tick the "select all views" checkbox chkUSRM1-AAUSW.
        oSession.findById("wnd[1]/usr/chkUSRM1-AAUSW").Selected = True
    End If
    Err.Clear
    On Error GoTo 0
    WScript.Sleep 300
    oSession.findById("wnd[1]/tbar[0]/btn[0]").Press    ' Enter/Continue
    WScript.Sleep 500
End If

' ------ 6. Organizational Levels popup --------------------------------------
Dim oPopupUsr, bIsOrgPopup
Set oPopupUsr = Nothing
On Error Resume Next
Set oPopupUsr = oSession.findById("wnd[1]/usr")
Err.Clear
On Error GoTo 0
bIsOrgPopup = False
If Not (oPopupUsr Is Nothing) Then bIsOrgPopup = IsOrgLevelsPopup(oPopupUsr)
If bIsOrgPopup Then
    WScript.Echo "INFO: Setting organizational levels..."
    Dim iOrg
    For iOrg = 0 To iCount - 1
        If arrSections(iOrg) = "ORG" Then
            Dim oOrgField
            On Error Resume Next
            Set oOrgField = FindField(oPopupUsr, arrFields(iOrg))
            If Not (oOrgField Is Nothing) Then
                SetFieldValue oOrgField, arrValues(iOrg)
                If Err.Number <> 0 Then
                    WScript.Echo "WARNING: Error setting org field " & arrFields(iOrg) & ": " & Err.Description
                Else
                    WScript.Echo "INFO:   " & arrFields(iOrg) & " = " & arrValues(iOrg)
                End If
            Else
                WScript.Echo "WARNING: Org field not found: " & arrFields(iOrg)
            End If
            Err.Clear
            On Error GoTo 0
        End If
    Next
    WScript.Sleep 300
    oSession.findById("wnd[1]/tbar[0]/btn[0]").Press   ' Enter/Continue
    WScript.Sleep 2000
End If

' Any popup still up here is neither of the two known MM01 popups: fail loud
' instead of guessing (this flow writes a REAL business record).
Dim sActWnd, sActTitle
sActWnd = ""
On Error Resume Next
sActWnd = oSession.ActiveWindow.Id
Err.Clear
On Error GoTo 0
If InStr(sActWnd, "wnd[1]") > 0 Then
    sActTitle = ""
    On Error Resume Next
    sActTitle = oSession.ActiveWindow.Text   ' diagnostic only
    Err.Clear
    On Error GoTo 0
    WScript.Echo "ERROR: Unexpected popup before the data screen: " & sActWnd & " -- title (diagnostic): " & sActTitle
    WScript.Echo "       Refusing to blind-dismiss. Status (diagnostic): " & oSession.findById("wnd[0]/sbar").Text
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

' Check if we reached the data screen -- locale-independent: probe the view
' tabstrip (TABSPR1) the field loop below drives, not the translated title.
Dim oTabStrip
Set oTabStrip = Nothing
On Error Resume Next
Set oTabStrip = oSession.findById("wnd[0]/usr/tabsTABSPR1")
Err.Clear
On Error GoTo 0
If oTabStrip Is Nothing Then
    sStatus = oSession.findById("wnd[0]/sbar").Text
    WScript.Echo "ERROR: Failed to reach data screen (view tabstrip TABSPR1 not found)."
    WScript.Echo "ERROR: Status (diagnostic): " & sStatus
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If
WScript.Echo "INFO: Material data screen reached."

' ------ 7. Fill tab fields --------------------------------------------------
' Collect unique tab IDs in order
Dim arrTabs()
Dim iTabCount
iTabCount = 0

Dim iTmp
For iTmp = 0 To iCount - 1
    If arrSections(iTmp) <> "ORG" Then
        ' Check if tab already in array
        Dim bFound
        bFound = False
        Dim iChk
        For iChk = 0 To iTabCount - 1
            If arrTabs(iChk) = arrSections(iTmp) Then
                bFound = True
                Exit For
            End If
        Next
        If Not bFound Then
            ReDim Preserve arrTabs(iTabCount)
            arrTabs(iTabCount) = arrSections(iTmp)
            iTabCount = iTabCount + 1
        End If
    End If
Next

WScript.Echo "INFO: Processing " & iTabCount & " tabs..."

Dim iTab, sTabSection, sTabId
For iTab = 0 To iTabCount - 1
    sTabSection = arrTabs(iTab)
    sTabId = "tabp" & sTabSection

    ' Select the tab
    Dim bTabOk
    bTabOk = True
    On Error Resume Next
    oSession.findById("wnd[0]/usr/tabsTABSPR1/" & sTabId).Select
    WScript.Sleep 500
    If Err.Number <> 0 Then
        WScript.Echo "WARNING: Tab " & sTabSection & " not found, skipping."
        Err.Clear
        bTabOk = False
    End If
    On Error GoTo 0

    If bTabOk Then
        WScript.Echo "INFO: Tab " & sTabSection & "..."

        ' Get tab panel reference
        Dim oTabPanel
        Set oTabPanel = oSession.findById("wnd[0]/usr/tabsTABSPR1/" & sTabId)

        ' Set each field for this tab
        Dim iFld
        For iFld = 0 To iCount - 1
            If arrSections(iFld) = sTabSection Then
                On Error Resume Next
                Dim oField
                Set oField = FindField(oTabPanel, arrFields(iFld))
                If oField Is Nothing Then
                    WScript.Echo "WARNING:   Field not found: " & arrFields(iFld)
                Else
                    SetFieldValue oField, arrValues(iFld)
                    WScript.Echo "INFO:   " & arrFields(iFld) & " = " & arrValues(iFld)
                End If
                Err.Clear
                On Error GoTo 0
            End If
        Next
    End If
Next

' Press Enter to commit inline edits
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 8. Save -------------------------------------------------------------
WScript.Echo "INFO: Saving material..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 2000

' Handle warning: SAP shows warning in status bar - press Enter to acknowledge, then save again
Dim sSaveStatus, sSaveType
sSaveStatus = oSession.findById("wnd[0]/sbar").Text
sSaveType = oSession.findById("wnd[0]/sbar").MessageType
If sSaveType = "W" Then
    WScript.Echo "INFO: Warning after save: " & sSaveStatus & " - acknowledging with Enter..."
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 1000
    oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
    WScript.Sleep 2000
End If

' ------ 8b. Post-save popup guard --------------------------------------------
' MM01 never raises a workbench transport popup -- material masters are not
' workbench objects. Any modal at this point is unexpected: fail loud instead
' of blind-dismissing (a guessed keypress on a REAL business record could
' commit or discard the wrong thing). ReleaseSession sweeps the modal (F12)
' so the operator gets a clean session back.
Dim sPopId, sPopTitle
sPopId = ""
On Error Resume Next
sPopId = oSession.ActiveWindow.Id
Err.Clear
On Error GoTo 0
If InStr(sPopId, "wnd[1]") > 0 Then
    sPopTitle = ""
    On Error Resume Next
    sPopTitle = oSession.ActiveWindow.Text   ' diagnostic only
    Err.Clear
    On Error GoTo 0
    WScript.Echo "ERROR: Unexpected popup after save: " & sPopId & " -- title (diagnostic): " & sPopTitle
    WScript.Echo "       Refusing to blind-dismiss. Resolve the popup manually, then re-run."
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

' --- Release the session UI lock; result check is read-only ---
ReleaseSession oSession, wasLocked
If wasLocked Then WScript.Echo "INFO: Session UI lock released."

' ------ 9. Check result -----------------------------------------------------
sStatus = oSession.findById("wnd[0]/sbar").Text
Dim sStatusType
sStatusType = oSession.findById("wnd[0]/sbar").MessageType

' Extract the machine-readable material number BEFORE leaving the screen
' (navigation clears the structured sbar properties).
Dim sSavedId
sSavedId = MATERIAL
If sSavedId = "" And sStatusType = "S" Then sSavedId = ExtractSavedId(oSession, sStatus)

' After save, SAP may continue to additional views (Classification etc.)
' Navigate back to a clean state unconditionally (locale-independent; the
' data-loss confirm, if any, is dismissed by its SPOP control id).
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 500
On Error Resume Next
oSession.findById("wnd[1]/usr/btnSPOP-OPTION1").Press
Err.Clear
On Error GoTo 0
WScript.Sleep 500

WScript.Echo "INFO: Status (" & sStatusType & "): " & sStatus

If sStatusType = "E" Or sStatusType = "A" Then
    WScript.Echo "ERROR: Material creation failed. " & sStatus
    WScript.Quit 1
End If

' Fail loud on anything but a positive success message: an empty or
' unrecognized status after Save must never be reported as SUCCESS.
If sStatusType <> "S" Then
    WScript.Echo "ERROR: Could not confirm the save -- status bar type is '" & sStatusType & "' (expected S). Message: " & sStatus
    WScript.Quit 1
End If

If sSavedId <> "" Then
    WScript.Echo "MATERIAL: " & sSavedId
Else
    WScript.Echo "WARNING: Could not extract the saved material number from the status bar."
End If
WScript.Echo "SUCCESS: Material " & sSavedId & " created in SAP."
WScript.Quit 0
