' =============================================================================
' sap_va01_update.vbs  -  SAP GUI Scripting: Update sales order via VA02
'
' Generated by the sap-va01 skill.
' Attaches to an existing SAP GUI session, navigates to VA02, opens the
' sales order for change, fills header and sales tab fields, updates item
' lines from a definition file, and saves.
'
' Definition file format (tab-separated, one field per line):
'   HEADER	VBKD-BSTKD	PO-REF-002
'   SALES	VBKD-ZTERM	0002
'   ITEM_01	RV45A-KWMENG	10
'
' Sections:
'   HEADER   - Header fields (above the tab strip)
'   SALES    - Sales tab fields (header frame within Sales tab T\01)
'   ITEM_NN  - Item table rows (NN = 01, 02, ...; mapped to row 0, 1, ...)
'
' Lines starting with # are comments. Blank lines are skipped.
'
' Tokens replaced at run time:
'   %%ORDER_NUMBER%%     Sales order number      e.g. "1659"
'   %%DEFINITION_FILE%%  Path to field defs      e.g. "{RUN_TEMP}\va02_fields.txt"
'   %%ALLOW_INCOMPLETE%% "X" = save even when SAP raises the incompletion
'                        popup; anything else (default: empty) = abort
'                        UNSAVED with ERROR: INCOMPLETE_DOCUMENT
'
' Locale-independent contract (language_independence_rules.md): screens are
' identified by control ids (TAXI_TABSTRIP_OVERVIEW tabstrip, SPOP button
' ids), results by sbar MessageType; titles / status texts are echoed for
' diagnostics only. On success a machine-readable "ORDER: <number>" line is
' echoed before the final SUCCESS line.
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const ORDER_NUMBER     = "%%ORDER_NUMBER%%"
Const DEFINITION_FILE  = "%%DEFINITION_FILE%%"
Const ALLOW_INCOMPLETE = "%%ALLOW_INCOMPLETE%%"   ' "X" = opt-in incomplete save

Const VKEY_ENTER      = 0
Const VKEY_F11_SAVE   = 11
Const VKEY_F12_CANCEL = 12
Const SESSION_PATH  = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

' Include shared helpers (attach first; session-lock's pre-unlock sweep
' reads from oSession).
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()

' ------ Helper: Find input field by name within a container (recursive) -----
Function FindField(oContainer, sFieldName)
    Set FindField = Nothing
    On Error Resume Next
    Dim ch
    Set ch = oContainer.Children
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    On Error GoTo 0

    Dim j, c, cName, cType
    For j = 0 To ch.Count - 1
        Set c = ch(CLng(j))
        On Error Resume Next
        cName = c.Name
        cType = c.Type
        Err.Clear
        On Error GoTo 0

        If cName = sFieldName Then
            If cType = "GuiTextField" Or cType = "GuiCTextField" Or _
               cType = "GuiComboBox" Or cType = "GuiCheckBox" Then
                Set FindField = c
                Exit Function
            End If
        End If

        If cType = "GuiSimpleContainer" Or cType = "GuiScrollContainer" Or _
           cType = "GuiTabStrip" Or cType = "GuiTab" Then
            Dim found
            Set found = FindField(c, sFieldName)
            If Not (found Is Nothing) Then
                Set FindField = found
                Exit Function
            End If
        End If
    Next
End Function

' ------ Helper: Find table control within a container (recursive) -----------
Function FindTable(oContainer)
    Set FindTable = Nothing
    On Error Resume Next
    Dim ch
    Set ch = oContainer.Children
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    On Error GoTo 0

    Dim j, c, cType
    For j = 0 To ch.Count - 1
        Set c = ch(CLng(j))
        On Error Resume Next
        cType = c.Type
        Err.Clear
        On Error GoTo 0

        If cType = "GuiTableControl" Then
            Set FindTable = c
            Exit Function
        End If

        If cType = "GuiSimpleContainer" Or cType = "GuiScrollContainer" Or _
           cType = "GuiTabStrip" Or cType = "GuiTab" Then
            Dim found
            Set found = FindTable(c)
            If Not (found Is Nothing) Then
                Set FindTable = found
                Exit Function
            End If
        End If
    Next
End Function

' ------ Helper: Set field value based on control type -----------------------
Sub SetFieldValue(oField, sValue)
    Select Case oField.Type
        Case "GuiTextField", "GuiCTextField"
            oField.Text = sValue
        Case "GuiComboBox"
            oField.Key = sValue
        Case "GuiCheckBox"
            If UCase(sValue) = "X" Or sValue = "1" Or UCase(sValue) = "TRUE" Then
                oField.Selected = True
            Else
                oField.Selected = False
            End If
    End Select
End Sub

' ------ Helper: abort WITHOUT saving and leave a clean session ---------------
' Cancels any open popup (F12 commits nothing), releases the session lock
' (its sweep clears residual modals), then leaves the transaction discarding
' unsaved input (/n + ID-gated data-loss confirm). Echoes sErrLine last and
' quits 1. Uses the script-global oSession / wasLocked.
Sub AbortUnsaved(sErrLine)
    On Error Resume Next
    If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
        oSession.findById("wnd[1]").sendVKey VKEY_F12_CANCEL
        WScript.Sleep 800
    End If
    Err.Clear
    On Error GoTo 0
    ReleaseSession oSession, wasLocked
    On Error Resume Next
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    oSession.findById("wnd[1]/usr/btnSPOP-OPTION1").Press
    Err.Clear
    On Error GoTo 0
    WScript.Echo sErrLine
    WScript.Quit 1
End Sub

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Read definition file ---------------------------------------------
Dim oFSO, sLine
Set oFSO = CreateObject("Scripting.FileSystemObject")

If Not oFSO.FileExists(DEFINITION_FILE) Then
    WScript.Echo "ERROR: Definition file not found: " & DEFINITION_FILE
    WScript.Quit 1
End If

' Parse into arrays: section, field name, value
' NOTE: read via ADODB.Stream with explicit Charset="utf-8". FSO.OpenTextFile
' decodes bytes with the system code page (cp932 on Japanese Windows, cp1252
' on Western), which mangles UTF-8 multi-byte sequences -- JA/ZH values would
' mojibake INTO the saved business record. ADODB.Stream decodes to the
' Unicode that the SAP GUI controls expect.
Dim arrSections(), arrFields(), arrValues()
Dim iCount
iCount = 0

Dim oStream, sAll, arrLines, iLine
Set oStream = CreateObject("ADODB.Stream")
oStream.Type = 2                    ' adTypeText
oStream.Charset = "utf-8"
oStream.Open
oStream.LoadFromFile DEFINITION_FILE
sAll = oStream.ReadText
oStream.Close

sAll = Replace(sAll, vbCrLf, vbLf)
sAll = Replace(sAll, vbCr,   vbLf)
arrLines = Split(sAll, vbLf)

For iLine = 0 To UBound(arrLines)
    sLine = arrLines(iLine)
    ' Strip a residual BOM character on the first line (belt and braces --
    ' ADODB.Stream normally consumes the UTF-8 BOM itself).
    If iLine = 0 And Len(sLine) > 0 Then
        If Left(sLine, 1) = ChrW(&HFEFF) Then sLine = Mid(sLine, 2)
    End If

    sLine = Trim(sLine)

    If Len(sLine) > 0 And Left(sLine, 1) <> "#" Then
        Dim iParts
        iParts = InStr(sLine, vbTab)

        If iParts > 0 Then
            Dim sSection, sRest
            sSection = Trim(Left(sLine, iParts - 1))
            sRest = Mid(sLine, iParts + 1)

            Dim iParts2
            iParts2 = InStr(sRest, vbTab)

            If iParts2 > 0 Then
                Dim sField, sValue
                sField = Trim(Left(sRest, iParts2 - 1))
                sValue = Mid(sRest, iParts2 + 1)

                ReDim Preserve arrSections(iCount)
                ReDim Preserve arrFields(iCount)
                ReDim Preserve arrValues(iCount)
                arrSections(iCount) = UCase(sSection)
                arrFields(iCount) = sField
                arrValues(iCount) = sValue
                iCount = iCount + 1
            End If
        End If
    End If
Next

WScript.Echo "INFO: Read " & iCount & " field definitions from file."

' --- Lock the SAP session UI for the VA02 sales-order input + save critical section ---
' Defence in depth (Rule 7): AppActivate guards external focus stealing;
' LockSessionUI guards in-session input races. Released after the save.
Dim wasLocked : wasLocked = TryLockSession(oSession)
If wasLocked Then
    WScript.Echo "INFO: Session UI locked for the VA02 sales-order input + save critical section."
Else
    WScript.Echo "INFO: LockSessionUI not available on this SAP GUI build; continuing without lock."
End If

' ------ 3. Navigate to VA02 -------------------------------------------------
WScript.Echo "INFO: Navigating to VA02..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nVA02"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 4. Enter order number ------------------------------------------------
WScript.Echo "INFO: Changing sales order: " & ORDER_NUMBER
oSession.findById("wnd[0]/usr/ctxtVBAK-VBELN").Text = ORDER_NUMBER
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 2000

' Check for errors
Dim sStatus, sStatusType
sStatus = oSession.findById("wnd[0]/sbar").Text
sStatusType = oSession.findById("wnd[0]/sbar").MessageType
If sStatusType = "E" Then
    WScript.Echo "ERROR: " & sStatus
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

' Verify we reached the change overview screen -- locale-independent: probe
' the overview tabstrip (TAXI_TABSTRIP_OVERVIEW) that the tab/field steps
' below drive, not the translated window title.
Dim oOvTab
Set oOvTab = Nothing
On Error Resume Next
Set oOvTab = oSession.findById("wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW")
Err.Clear
On Error GoTo 0
If oOvTab Is Nothing Then
    WScript.Echo "ERROR: Failed to reach the change overview screen (TAXI_TABSTRIP_OVERVIEW not found)."
    WScript.Echo "ERROR: Status (diagnostic): " & sStatus
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If
WScript.Echo "INFO: Change overview screen reached."

' ------ 5. Fill header fields -----------------------------------------------
Dim oUsr, oField, iFld
Set oUsr = oSession.findById("wnd[0]/usr")

WScript.Echo "INFO: Setting header fields..."
For iFld = 0 To iCount - 1
    If arrSections(iFld) = "HEADER" Then
        On Error Resume Next
        Set oField = FindField(oUsr, arrFields(iFld))
        If oField Is Nothing Then
            WScript.Echo "WARNING: Header field not found: " & arrFields(iFld)
        Else
            SetFieldValue oField, arrValues(iFld)
            WScript.Echo "INFO:   " & arrFields(iFld) & " = " & arrValues(iFld)
        End If
        Err.Clear
        On Error GoTo 0
    End If
Next

' ------ 6. Select Sales tab and fill sales fields ---------------------------
oSession.findById("wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\01").Select
WScript.Sleep 500

Set oUsr = oSession.findById("wnd[0]/usr")

WScript.Echo "INFO: Setting sales tab fields..."
For iFld = 0 To iCount - 1
    If arrSections(iFld) = "SALES" Then
        On Error Resume Next
        Set oField = FindField(oUsr, arrFields(iFld))
        If oField Is Nothing Then
            WScript.Echo "WARNING: Sales field not found: " & arrFields(iFld)
        Else
            SetFieldValue oField, arrValues(iFld)
            WScript.Echo "INFO:   " & arrFields(iFld) & " = " & arrValues(iFld)
        End If
        Err.Clear
        On Error GoTo 0
    End If
Next

' ------ 7. Update item table -------------------------------------------------
' Collect unique ITEM_xx sections in order
Dim arrItemSections()
Dim iItemCount
iItemCount = 0

Dim iTmp
For iTmp = 0 To iCount - 1
    If Left(arrSections(iTmp), 5) = "ITEM_" Then
        Dim bItemFound
        bItemFound = False
        Dim iItemChk
        For iItemChk = 0 To iItemCount - 1
            If arrItemSections(iItemChk) = arrSections(iTmp) Then
                bItemFound = True
                Exit For
            End If
        Next
        If Not bItemFound Then
            ReDim Preserve arrItemSections(iItemCount)
            arrItemSections(iItemCount) = arrSections(iTmp)
            iItemCount = iItemCount + 1
        End If
    End If
Next

If iItemCount > 0 Then
    WScript.Echo "INFO: Updating " & iItemCount & " item line(s)..."

    Set oUsr = oSession.findById("wnd[0]/usr")
    Dim oTable
    Set oTable = FindTable(oUsr)

    If oTable Is Nothing Then
        WScript.Echo "ERROR: Item table not found."
        ReleaseSession oSession, wasLocked
        WScript.Quit 1
    End If

    ' Build column name -> index mapping
    Dim colMap
    Set colMap = CreateObject("Scripting.Dictionary")
    Dim iCol, cellName
    For iCol = 0 To oTable.Columns.Count - 1
        On Error Resume Next
        cellName = oTable.GetCell(0, iCol).Name
        Err.Clear
        On Error GoTo 0
        If cellName <> "" And Not colMap.Exists(cellName) Then
            colMap.Add cellName, iCol
        End If
    Next

    ' Update each item row
    Dim iItem, sItemSection, iRow
    For iItem = 0 To iItemCount - 1
        sItemSection = arrItemSections(iItem)
        iRow = iItem

        WScript.Echo "INFO: Item row " & (iRow + 1) & "..."

        For iFld = 0 To iCount - 1
            If arrSections(iFld) = sItemSection Then
                If colMap.Exists(arrFields(iFld)) Then
                    Dim iColIdx
                    iColIdx = colMap(arrFields(iFld))
                    On Error Resume Next
                    Dim oCell
                    Set oCell = oTable.GetCell(iRow, iColIdx)
                    If oCell.Changeable Then
                        SetFieldValue oCell, arrValues(iFld)
                        WScript.Echo "INFO:     " & arrFields(iFld) & " = " & arrValues(iFld)
                    Else
                        WScript.Echo "WARNING:  " & arrFields(iFld) & " is read-only, skipping."
                    End If
                    Err.Clear
                    On Error GoTo 0
                Else
                    WScript.Echo "WARNING:  Item column not found: " & arrFields(iFld)
                End If
            End If
        Next
    Next
End If

' Press Enter to validate
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 2000

' Handle information/warning popups that may follow validation
Dim oPopCheck
On Error Resume Next
Set oPopCheck = oSession.findById("wnd[1]")
Do While Err.Number = 0 And Not (oPopCheck Is Nothing)
    WScript.Echo "INFO: Popup after validation: " & oPopCheck.Text
    oPopCheck.sendVKey VKEY_ENTER
    WScript.Sleep 1000
    Set oPopCheck = Nothing
    Err.Clear
    Set oPopCheck = oSession.findById("wnd[1]")
Loop
Err.Clear
On Error GoTo 0

' ------ 8. Save --------------------------------------------------------------
WScript.Echo "INFO: Saving sales order..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 3000

' ------ 8b. Save popups: incomplete-document guard ---------------------------
' The incompletion popup is identified by its SPOP option-button control ids
' (usr/btnSPOP-VAROPTION1 = Save, usr/btnSPOP-VAROPTION2 = Edit), never by
' the translated title. Default: do NOT save an incomplete document -- back
' out unsaved and fail loud. Opt-in via ALLOW_INCOMPLETE = "X". Any OTHER
' popup at save time is unexpected: fail loud, never blind-dismiss.
Dim popCount, btnSaveInc, btnEditInc, bIncompleteSaved, sPopId, sPopTitle
bIncompleteSaved = False
For popCount = 1 To 3
    sPopId = ""
    On Error Resume Next
    sPopId = oSession.ActiveWindow.Id
    Err.Clear
    On Error GoTo 0
    If InStr(sPopId, "wnd[1]") = 0 Then Exit For

    sPopTitle = ""
    On Error Resume Next
    sPopTitle = oSession.ActiveWindow.Text   ' diagnostic only
    Err.Clear
    On Error GoTo 0
    WScript.Echo "INFO: Popup after save (diagnostic): " & sPopId & " -- " & sPopTitle

    Set btnSaveInc = Nothing
    On Error Resume Next
    Set btnSaveInc = oSession.findById("wnd[1]/usr/btnSPOP-VAROPTION1")
    Err.Clear
    On Error GoTo 0

    If Not (btnSaveInc Is Nothing) Then
        If ALLOW_INCOMPLETE = "X" Then
            WScript.Echo "INFO: Incompletion popup -- saving anyway (ALLOW_INCOMPLETE=X)."
            btnSaveInc.Press
            bIncompleteSaved = True
            WScript.Sleep 2000
        Else
            ' Choose the non-save option (Edit) so the popup closes without
            ' committing, then back out of the transaction unsaved.
            Set btnEditInc = Nothing
            On Error Resume Next
            Set btnEditInc = oSession.findById("wnd[1]/usr/btnSPOP-VAROPTION2")
            If Not (btnEditInc Is Nothing) Then btnEditInc.Press
            Err.Clear
            On Error GoTo 0
            WScript.Sleep 1000
            AbortUnsaved "ERROR: INCOMPLETE_DOCUMENT - incompletion log must be resolved" & vbCrLf & _
                         "       The order was NOT saved. Re-run with --allow-incomplete to save an incomplete document."
        End If
    Else
        AbortUnsaved "ERROR: Unexpected popup while saving: " & sPopId & " -- title (diagnostic): " & sPopTitle & vbCrLf & _
                     "       Refusing to blind-dismiss. Save state UNKNOWN -- verify via VA03 before retrying."
    End If
Next

' --- Release the session UI lock; result check is read-only ---
ReleaseSession oSession, wasLocked
If wasLocked Then WScript.Echo "INFO: Session UI lock released."

' ------ 9. Check result ------------------------------------------------------
sStatus = oSession.findById("wnd[0]/sbar").Text
sStatusType = oSession.findById("wnd[0]/sbar").MessageType

WScript.Echo "INFO: Status (" & sStatusType & "): " & sStatus

' Navigate back to a clean state unconditionally (locale-independent; the
' data-loss confirm, if any, is dismissed by its SPOP control id).
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 500
On Error Resume Next
oSession.findById("wnd[1]/usr/btnSPOP-OPTION1").Press
Err.Clear
On Error GoTo 0
WScript.Sleep 500

If sStatusType = "E" Or sStatusType = "A" Then
    WScript.Echo "ERROR: Sales order update failed. " & sStatus
    WScript.Quit 1
End If

' Fail loud on anything but a positive success message: an empty or
' unrecognized status after Save must never be reported as SUCCESS.
If sStatusType <> "S" Then
    WScript.Echo "ERROR: Could not confirm the save -- status bar type is '" & sStatusType & "' (expected S). Message: " & sStatus
    WScript.Quit 1
End If

WScript.Echo "ORDER: " & ORDER_NUMBER
If bIncompleteSaved Then WScript.Echo "WARNING: INCOMPLETE_DOCUMENT_SAVED"
WScript.Echo "SUCCESS: Sales order " & ORDER_NUMBER & " updated in SAP."
WScript.Quit 0
