' =============================================================================
' sap_va01_check.vbs  -  SAP GUI Scripting: Check if sales order exists
'
' Generated by the sap-va01 skill.
' Attaches to an existing SAP GUI session, navigates to VA03,
' enters the sales order number, and checks if it exists.
'
' Output: "EXIST" or "NOT_EXIST" (last line of stdout, parseable by skill).
'
' Tokens replaced at run time:
'   %%ORDER_NUMBER%%  Sales order number  e.g. "5770000516"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const ORDER_NUMBER = "%%ORDER_NUMBER%%"
Const VKEY_ENTER   = 0
Const SESSION_PATH  = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to VA03 -------------------------------------------------
WScript.Echo "INFO: Navigating to VA03..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nVA03"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Enter order number and press Enter -------------------------------
WScript.Echo "INFO: Checking sales order: " & ORDER_NUMBER
oSession.findById("wnd[0]/usr/ctxtVBAK-VBELN").Text = ORDER_NUMBER
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 2000

' ------ 4. Determine result -------------------------------------------------
Dim sStatus, sStatusType
sStatus = oSession.findById("wnd[0]/sbar").Text
sStatusType = oSession.findById("wnd[0]/sbar").MessageType

' If order does not exist: status bar shows error (E)
If sStatusType = "E" Then
    WScript.Echo "INFO: " & sStatus
    ' Navigate back to clean state
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    WScript.Echo "NOT_EXIST"
    WScript.Quit 0
End If

' If title contains "Display" and a document number - order exists
Dim sTitle
sTitle = oSession.findById("wnd[0]").Text
If InStr(sTitle, "Display") > 0 And InStr(sTitle, "order") > 0 Then
    WScript.Echo "INFO: Sales order " & ORDER_NUMBER & " exists."
    ' Navigate back to clean state
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    WScript.Echo "EXIST"
    WScript.Quit 0
End If

' Fallback: check if we're still on initial screen (order doesn't exist)
If InStr(sTitle, "Display Sales Document") > 0 Then
    WScript.Echo "INFO: " & sStatus
    WScript.Echo "NOT_EXIST"
    WScript.Quit 0
End If

' If we got here, assume order exists
WScript.Echo "INFO: Title: " & sTitle
WScript.Echo "EXIST"
WScript.Quit 0
