' =============================================================================
' sap_va01_update.vbs  -  SAP GUI Scripting: Update sales order via VA02
'
' Generated by the sap-va01 skill.
' Attaches to an existing SAP GUI session, navigates to VA02, opens the
' sales order for change, fills header and sales tab fields, updates item
' lines from a definition file, and saves.
'
' Definition file format (tab-separated, one field per line):
'   HEADER	VBKD-BSTKD	PO-REF-002
'   SALES	VBKD-ZTERM	0002
'   ITEM_01	RV45A-KWMENG	10
'
' Sections:
'   HEADER   - Header fields (above the tab strip)
'   SALES    - Sales tab fields (header frame within Sales tab T\01)
'   ITEM_NN  - Item table rows (NN = 01, 02, ...; mapped to row 0, 1, ...)
'
' Lines starting with # are comments. Blank lines are skipped.
'
' Tokens replaced at run time:
'   %%ORDER_NUMBER%%     Sales order number      e.g. "1659"
'   %%DEFINITION_FILE%%  Path to field defs      e.g. "{WORK_TEMP}\va02_fields.txt"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const ORDER_NUMBER    = "%%ORDER_NUMBER%%"
Const DEFINITION_FILE = "%%DEFINITION_FILE%%"

Const VKEY_ENTER    = 0
Const VKEY_F11_SAVE = 11

Dim oSAPGUI, oApplication, oSession
Dim oCandidate, oSessIter

' ------ Helper: Find input field by name within a container (recursive) -----
Function FindField(oContainer, sFieldName)
    Set FindField = Nothing
    On Error Resume Next
    Dim ch
    Set ch = oContainer.Children
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    On Error GoTo 0

    Dim j, c, cName, cType
    For j = 0 To ch.Count - 1
        Set c = ch(CLng(j))
        On Error Resume Next
        cName = c.Name
        cType = c.Type
        Err.Clear
        On Error GoTo 0

        If cName = sFieldName Then
            If cType = "GuiTextField" Or cType = "GuiCTextField" Or _
               cType = "GuiComboBox" Or cType = "GuiCheckBox" Then
                Set FindField = c
                Exit Function
            End If
        End If

        If cType = "GuiSimpleContainer" Or cType = "GuiScrollContainer" Or _
           cType = "GuiTabStrip" Or cType = "GuiTab" Then
            Dim found
            Set found = FindField(c, sFieldName)
            If Not (found Is Nothing) Then
                Set FindField = found
                Exit Function
            End If
        End If
    Next
End Function

' ------ Helper: Find table control within a container (recursive) -----------
Function FindTable(oContainer)
    Set FindTable = Nothing
    On Error Resume Next
    Dim ch
    Set ch = oContainer.Children
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    On Error GoTo 0

    Dim j, c, cType
    For j = 0 To ch.Count - 1
        Set c = ch(CLng(j))
        On Error Resume Next
        cType = c.Type
        Err.Clear
        On Error GoTo 0

        If cType = "GuiTableControl" Then
            Set FindTable = c
            Exit Function
        End If

        If cType = "GuiSimpleContainer" Or cType = "GuiScrollContainer" Or _
           cType = "GuiTabStrip" Or cType = "GuiTab" Then
            Dim found
            Set found = FindTable(c)
            If Not (found Is Nothing) Then
                Set FindTable = found
                Exit Function
            End If
        End If
    Next
End Function

' ------ Helper: Set field value based on control type -----------------------
Sub SetFieldValue(oField, sValue)
    Select Case oField.Type
        Case "GuiTextField", "GuiCTextField"
            oField.Text = sValue
        Case "GuiComboBox"
            oField.Key = sValue
        Case "GuiCheckBox"
            If UCase(sValue) = "X" Or sValue = "1" Or UCase(sValue) = "TRUE" Then
                oField.Selected = True
            Else
                oField.Selected = False
            End If
    End Select
End Sub

' ------ 1. Attach to existing SAP GUI session -------------------------------
On Error Resume Next
Set oSAPGUI = GetObject("SAPGUI")
If Err.Number <> 0 Or oSAPGUI Is Nothing Then
    WScript.Echo "ERROR: SAP GUI is not running."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

Set oApplication = oSAPGUI.GetScriptingEngine
If oApplication Is Nothing Then
    WScript.Echo "ERROR: Could not get SAP Scripting Engine."
    WScript.Quit 1
End If

Set oSession = Nothing
On Error Resume Next
For Each oCandidate In oApplication.Children
    For Each oSessIter In oCandidate.Children
        Set oSession = oSessIter
        Exit For
    Next
    If Not (oSession Is Nothing) Then Exit For
Next
On Error GoTo 0

If oSession Is Nothing Then
    WScript.Echo "ERROR: No SAP GUI session found. Run the login step first."
    WScript.Quit 1
End If
WScript.Echo "INFO: Session acquired."

' ------ 2. Read definition file ---------------------------------------------
Dim oFSO, oFile, sLine
Set oFSO = CreateObject("Scripting.FileSystemObject")

If Not oFSO.FileExists(DEFINITION_FILE) Then
    WScript.Echo "ERROR: Definition file not found: " & DEFINITION_FILE
    WScript.Quit 1
End If

Dim arrSections(), arrFields(), arrValues()
Dim iCount
iCount = 0

Set oFile = oFSO.OpenTextFile(DEFINITION_FILE, 1, False)
Do While Not oFile.AtEndOfStream
    sLine = oFile.ReadLine
    If iCount = 0 And Len(sLine) > 0 Then
        Do While Len(sLine) > 0 And Asc(Left(sLine, 1)) > 127
            sLine = Mid(sLine, 2)
        Loop
    End If

    sLine = Trim(sLine)

    If Len(sLine) > 0 And Left(sLine, 1) <> "#" Then
        Dim iParts
        iParts = InStr(sLine, vbTab)

        If iParts > 0 Then
            Dim sSection, sRest
            sSection = Trim(Left(sLine, iParts - 1))
            sRest = Mid(sLine, iParts + 1)

            Dim iParts2
            iParts2 = InStr(sRest, vbTab)

            If iParts2 > 0 Then
                Dim sField, sValue
                sField = Trim(Left(sRest, iParts2 - 1))
                sValue = Mid(sRest, iParts2 + 1)

                ReDim Preserve arrSections(iCount)
                ReDim Preserve arrFields(iCount)
                ReDim Preserve arrValues(iCount)
                arrSections(iCount) = UCase(sSection)
                arrFields(iCount) = sField
                arrValues(iCount) = sValue
                iCount = iCount + 1
            End If
        End If
    End If
Loop
oFile.Close

WScript.Echo "INFO: Read " & iCount & " field definitions from file."

' ------ 3. Navigate to VA02 -------------------------------------------------
WScript.Echo "INFO: Navigating to VA02..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nVA02"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 4. Enter order number ------------------------------------------------
WScript.Echo "INFO: Changing sales order: " & ORDER_NUMBER
oSession.findById("wnd[0]/usr/ctxtVBAK-VBELN").Text = ORDER_NUMBER
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 2000

' Check for errors
Dim sStatus, sStatusType
sStatus = oSession.findById("wnd[0]/sbar").Text
sStatusType = oSession.findById("wnd[0]/sbar").MessageType
If sStatusType = "E" Then
    WScript.Echo "ERROR: " & sStatus
    WScript.Quit 1
End If

' Verify we reached change screen
Dim sTitle
sTitle = oSession.findById("wnd[0]").Text
If InStr(sTitle, "Change") = 0 Or InStr(sTitle, "Overview") = 0 Then
    WScript.Echo "ERROR: Failed to reach change screen. Title: " & sTitle
    WScript.Echo "ERROR: Status: " & sStatus
    WScript.Quit 1
End If
WScript.Echo "INFO: Change screen reached: " & sTitle

' ------ 5. Fill header fields -----------------------------------------------
Dim oUsr, oField, iFld
Set oUsr = oSession.findById("wnd[0]/usr")

WScript.Echo "INFO: Setting header fields..."
For iFld = 0 To iCount - 1
    If arrSections(iFld) = "HEADER" Then
        On Error Resume Next
        Set oField = FindField(oUsr, arrFields(iFld))
        If oField Is Nothing Then
            WScript.Echo "WARNING: Header field not found: " & arrFields(iFld)
        Else
            SetFieldValue oField, arrValues(iFld)
            WScript.Echo "INFO:   " & arrFields(iFld) & " = " & arrValues(iFld)
        End If
        Err.Clear
        On Error GoTo 0
    End If
Next

' ------ 6. Select Sales tab and fill sales fields ---------------------------
oSession.findById("wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\01").Select
WScript.Sleep 500

Set oUsr = oSession.findById("wnd[0]/usr")

WScript.Echo "INFO: Setting sales tab fields..."
For iFld = 0 To iCount - 1
    If arrSections(iFld) = "SALES" Then
        On Error Resume Next
        Set oField = FindField(oUsr, arrFields(iFld))
        If oField Is Nothing Then
            WScript.Echo "WARNING: Sales field not found: " & arrFields(iFld)
        Else
            SetFieldValue oField, arrValues(iFld)
            WScript.Echo "INFO:   " & arrFields(iFld) & " = " & arrValues(iFld)
        End If
        Err.Clear
        On Error GoTo 0
    End If
Next

' ------ 7. Update item table -------------------------------------------------
' Collect unique ITEM_xx sections in order
Dim arrItemSections()
Dim iItemCount
iItemCount = 0

Dim iTmp
For iTmp = 0 To iCount - 1
    If Left(arrSections(iTmp), 5) = "ITEM_" Then
        Dim bItemFound
        bItemFound = False
        Dim iItemChk
        For iItemChk = 0 To iItemCount - 1
            If arrItemSections(iItemChk) = arrSections(iTmp) Then
                bItemFound = True
                Exit For
            End If
        Next
        If Not bItemFound Then
            ReDim Preserve arrItemSections(iItemCount)
            arrItemSections(iItemCount) = arrSections(iTmp)
            iItemCount = iItemCount + 1
        End If
    End If
Next

If iItemCount > 0 Then
    WScript.Echo "INFO: Updating " & iItemCount & " item line(s)..."

    Set oUsr = oSession.findById("wnd[0]/usr")
    Dim oTable
    Set oTable = FindTable(oUsr)

    If oTable Is Nothing Then
        WScript.Echo "ERROR: Item table not found."
        WScript.Quit 1
    End If

    ' Build column name -> index mapping
    Dim colMap
    Set colMap = CreateObject("Scripting.Dictionary")
    Dim iCol, cellName
    For iCol = 0 To oTable.Columns.Count - 1
        On Error Resume Next
        cellName = oTable.GetCell(0, iCol).Name
        Err.Clear
        On Error GoTo 0
        If cellName <> "" And Not colMap.Exists(cellName) Then
            colMap.Add cellName, iCol
        End If
    Next

    ' Update each item row
    Dim iItem, sItemSection, iRow
    For iItem = 0 To iItemCount - 1
        sItemSection = arrItemSections(iItem)
        iRow = iItem

        WScript.Echo "INFO: Item row " & (iRow + 1) & "..."

        For iFld = 0 To iCount - 1
            If arrSections(iFld) = sItemSection Then
                If colMap.Exists(arrFields(iFld)) Then
                    Dim iColIdx
                    iColIdx = colMap(arrFields(iFld))
                    On Error Resume Next
                    Dim oCell
                    Set oCell = oTable.GetCell(iRow, iColIdx)
                    If oCell.Changeable Then
                        SetFieldValue oCell, arrValues(iFld)
                        WScript.Echo "INFO:     " & arrFields(iFld) & " = " & arrValues(iFld)
                    Else
                        WScript.Echo "WARNING:  " & arrFields(iFld) & " is read-only, skipping."
                    End If
                    Err.Clear
                    On Error GoTo 0
                Else
                    WScript.Echo "WARNING:  Item column not found: " & arrFields(iFld)
                End If
            End If
        Next
    Next
End If

' Press Enter to validate
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 2000

' Handle information/warning popups that may follow validation
Dim oPopCheck
On Error Resume Next
Set oPopCheck = oSession.findById("wnd[1]")
Do While Err.Number = 0 And Not (oPopCheck Is Nothing)
    WScript.Echo "INFO: Popup after validation: " & oPopCheck.Text
    oPopCheck.sendVKey VKEY_ENTER
    WScript.Sleep 1000
    Set oPopCheck = Nothing
    Err.Clear
    Set oPopCheck = oSession.findById("wnd[1]")
Loop
Err.Clear
On Error GoTo 0

' ------ 8. Save --------------------------------------------------------------
WScript.Echo "INFO: Saving sales order..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 3000

' Handle "Save Incomplete Document" popup
Dim popCount, oPop, btnSave
For popCount = 1 To 3
    On Error Resume Next
    Set oPop = oSession.findById("wnd[1]")
    If Err.Number <> 0 Then
        Err.Clear
        Exit For
    End If
    On Error GoTo 0

    WScript.Echo "INFO: Popup: " & oPop.Text

    On Error Resume Next
    Set btnSave = oPop.findById("usr/btnSPOP-VAROPTION1")
    If Err.Number = 0 Then
        btnSave.Press
    Else
        Err.Clear
        oPop.sendVKey VKEY_ENTER
    End If
    Err.Clear
    On Error GoTo 0
    WScript.Sleep 2000
Next

' ------ 9. Check result ------------------------------------------------------
sStatus = oSession.findById("wnd[0]/sbar").Text
sStatusType = oSession.findById("wnd[0]/sbar").MessageType

WScript.Echo "INFO: Status (" & sStatusType & "): " & sStatus

' Navigate back to clean state
sTitle = oSession.findById("wnd[0]").Text
If InStr(sTitle, "Overview") > 0 Then
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    On Error Resume Next
    oSession.findById("wnd[1]/usr/btnSPOP-OPTION1").Press
    Err.Clear
    On Error GoTo 0
    WScript.Sleep 500
End If

If sStatusType = "E" Or sStatusType = "A" Then
    WScript.Echo "ERROR: Sales order update failed. " & sStatus
    WScript.Quit 1
End If

WScript.Echo "SUCCESS: Sales order " & ORDER_NUMBER & " updated in SAP."
WScript.Quit 0
