' =============================================================================
' sap_se51_add_element.vbs  -  SAP GUI Scripting: add layout elements to a
'                              dynpro via SE51's ALPHANUMERIC Screen Painter.
'
' Generated by the sap-se51 skill.
' Attaches to an existing SAP GUI session, opens the screen's LAYOUT in change
' mode, and adds one or more elements (static Text labels, Input/Output
' fields, checkboxes, pushbuttons, radio buttons) via Edit > Create Element.
' Saves and activates.
'
' WHY THIS EXISTS
' --------------
' The GRAPHICAL Layout Editor (drag-and-drop canvas) is a non-scriptable
' ActiveX control: the SAP GUI recorder captures nothing and findById() cannot
' reach its widgets. SE51's element-list grid is read-only for placement (empty
' rows are Changeable=False; FELD-LINE / FELD-COLN are not editable). The only
' reliable scripted placement path is the classic ALPHANUMERIC Screen Painter
' (program SAPMSSY0, dynpro 120) driven through Edit > Create Element -- exactly
' what the SAP recorder produces.
'
' PREREQUISITE -- graphical editor must be OFF
' -------------------------------------------
' The alphanumeric editor only appears when the user's SE51 setting
' "Graphical Layout Editor" is DISABLED (Utilities > Settings, per-user). When
' ON, the Change button opens the graphical canvas and this script aborts with
' NOT_ALPHANUMERIC. Detection is by program name (SAPMSSY0) -- language-neutral.
'
' Tokens replaced at run time:
'   %%PROGRAM_NAME%%   Program / function pool   e.g. "ZHKTESTSE51001"
'   %%SCREEN_NUMBER%%  4-digit dynpro number     e.g. "9001"
'   %%TRANSPORT%%      Transport request          e.g. "S4DK941230" (empty=local)
'   %%PACKAGE%%        Package (ObjDirEntry fallback if field empty) e.g. ZCMPKGV49
'   %%ELEMENT_FILE%%   Path to a tab-delimited element definition file (UTF-8)
'   %%LOG_FILE%%       Path for the run log
'
' Element file format -- one element per line, TAB-separated, '#' lines ignored:
'   TYPE <TAB> NAME <TAB> TEXT <TAB> LENGTH <TAB> LINE <TAB> COLUMN
'     TYPE   = TEXT | IO | CHECKBOX | PUSHBUTTON | RADIO   (case-insensitive)
'     NAME   = element / field name (for IO: a program or DDIC field, e.g.
'              T001-BUKRS; for TEXT a name is optional)
'     TEXT   = displayed text (TEXT/PUSHBUTTON/CHECKBOX label; ignored for IO)
'     LENGTH = output / field length (characters)
'     LINE   = dynpro line   (1-based)
'     COLUMN = dynpro column (0-based, matches the work-area txt[col,row] grid)
'
' Output: human-readable log + a final parseable line:
'   SUCCESS: <n> element(s) added to <PROG> <DYNNR>.
'   ERROR: <reason>
'
' Component IDs recorded on SAP GUI 7.70 / S/4HANA 1909 (S4D), logon EN.
' =============================================================================

Option Explicit

Const PROGRAM_NAME  = "%%PROGRAM_NAME%%"
Const SCREEN_NUMBER = "%%SCREEN_NUMBER%%"
Const SAP_TRANSPORT = "%%TRANSPORT%%"
Const SAP_PACKAGE   = "%%PACKAGE%%"        ' used only if ObjDirEntry pkg field is empty
Const ELEMENT_FILE  = "%%ELEMENT_FILE%%"
Const LOG_FILE      = "%%LOG_FILE%%"
Const SESSION_PATH  = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER = 0
Const VKEY_F12   = 12   ' Cancel

' ------ shared helpers ------------------------------------------------------
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

Dim oFSO, oLog
Set oFSO = CreateObject("Scripting.FileSystemObject")
Set oLog = oFSO.CreateTextFile(LOG_FILE, True)
Sub L(s) : oLog.WriteLine s : End Sub

Dim oSession

' ------ menu index for Edit > Create Element > <type> -----------------------
' Edit = mbar/menu[1], Create Element = menu[2]; sub-indices recorded on 1909:
'   0=Text Field 1=Input/Output Field 2=Radio Button 3=Checkbox 4=Pushbutton
'   5=Pushbutton(Help) 6=Frames 7=Table Control 8=Custom 9=Tabstrip
'   10=Subscreen 11=Splitter
Function CreateMenuIndex(sType)
    Select Case UCase(Trim(sType))
        Case "TEXT"       : CreateMenuIndex = 0
        Case "IO"         : CreateMenuIndex = 1
        Case "RADIO"      : CreateMenuIndex = 2
        Case "CHECKBOX"   : CreateMenuIndex = 3
        Case "PUSHBUTTON" : CreateMenuIndex = 4
        Case Else         : CreateMenuIndex = -1
    End Select
End Function

' ------ 1. Attach -----------------------------------------------------------
Set oSession = AttachSapSession(SESSION_PATH)
L "INFO: Session acquired."

' ------ 2. Read element definition file -------------------------------------
If Not oFSO.FileExists(ELEMENT_FILE) Then
    L "ERROR: element file not found: " & ELEMENT_FILE
    oLog.Close : WScript.Quit 1
End If

Dim oStream, sAll
Set oStream = CreateObject("ADODB.Stream")
oStream.Type = 2 : oStream.Charset = "utf-8" : oStream.Open
oStream.LoadFromFile ELEMENT_FILE
sAll = oStream.ReadText
oStream.Close

Dim aLines, aEls(), nEl
aLines = Split(Replace(sAll, vbCr, ""), vbLf)
ReDim aEls(UBound(aLines))
nEl = 0
Dim i, ln
For i = 0 To UBound(aLines)
    ln = Trim(aLines(i))
    If Len(ln) > 0 And Left(ln, 1) <> "#" Then
        aEls(nEl) = aLines(i)
        nEl = nEl + 1
    End If
Next
If nEl = 0 Then
    L "ERROR: element file contained no element rows."
    oLog.Close : WScript.Quit 1
End If
L "INFO: " & nEl & " element(s) to add."

' ------ 3. Navigate to SE51, open LAYOUT in change mode ----------------------
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE51"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1200

On Error Resume Next
oSession.findById("wnd[0]/usr/ctxtRS37A-DYNPROG").Text = UCase(PROGRAM_NAME)
oSession.findById("wnd[0]/usr/ctxtFELD-DYNNR").Text   = SCREEN_NUMBER
oSession.findById("wnd[0]/usr/radRS37A-FUNED").Select   ' Layout radio
If Err.Number <> 0 Then
    L "ERROR: SE51 initial screen fields not found (ID mismatch?): " & Err.Description
    oLog.Close : WScript.Quit 1
End If
Err.Clear
On Error GoTo 0
WScript.Sleep 300

oSession.findById("wnd[0]/usr/btnAENDERN").press   ' Change
WScript.Sleep 3000

' dismiss any benign info popup after entering change mode
Dim g
On Error Resume Next
g = 0
Do While InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 And g < 3
    L "INFO: popup after change: " & oSession.findById("wnd[1]").Text
    oSession.findById("wnd[1]").sendVKey VKEY_ENTER
    WScript.Sleep 700
    g = g + 1
Loop
Err.Clear
On Error GoTo 0

' ------ 3a. Confirm ALPHANUMERIC Screen Painter (program SAPMSSY0) -----------
If oSession.Info.Program <> "SAPMSSY0" Then
    L "ERROR: NOT_ALPHANUMERIC -- the Change button opened the graphical Layout"
    L "       Editor (program=" & oSession.Info.Program & "), which cannot be"
    L "       scripted. Turn OFF SE51 > Utilities > Settings > 'Graphical Layout"
    L "       Editor' for this user, then re-run. (Per-user setting.)"
    oLog.Close : WScript.Quit 1
End If
L "INFO: alphanumeric Screen Painter active (SAPMSSY0 / screen " & _
   oSession.Info.ScreenNumber & ")."

' ------ 4. Add each element --------------------------------------------------
Dim added
added = 0
For i = 0 To nEl - 1
    Dim parts, sType, sName, sText, sLen, sLine, sCol
    parts = Split(aEls(i), vbTab)
    sType = "" : sName = "" : sText = "" : sLen = "" : sLine = "" : sCol = ""
    If UBound(parts) >= 0 Then sType = Trim(parts(0))
    If UBound(parts) >= 1 Then sName = Trim(parts(1))
    If UBound(parts) >= 2 Then sText = parts(2)
    If UBound(parts) >= 3 Then sLen  = Trim(parts(3))
    If UBound(parts) >= 4 Then sLine = Trim(parts(4))
    If UBound(parts) >= 5 Then sCol  = Trim(parts(5))

    Dim mi
    mi = CreateMenuIndex(sType)
    If mi < 0 Then
        L "WARNING: unknown element TYPE '" & sType & "' on row " & (i + 1) & " -- skipped."
    Else
        If AddOneElement(mi, sType, sName, sText, sLen, sLine, sCol) Then
            added = added + 1
        End If
    End If
Next

If added = 0 Then
    L "ERROR: no elements were added (all rows failed). See warnings above."
    oLog.Close : WScript.Quit 1
End If

' ------ 5. Save (tbar[0]/btn[11]) -------------------------------------------
L "INFO: Saving..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[0]/btn[11]").press
WScript.Sleep 1500
Err.Clear
On Error GoTo 0
HandleSavePopups "SAVE"

' ------ 6. Activate (Ctrl+F3 = tbar[1]/btn[27]) -----------------------------
L "INFO: Activating..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[1]/btn[27]").press
WScript.Sleep 2500
Err.Clear
On Error GoTo 0
HandleSavePopups "ACTIVATE"

' handle activation worklist (SAPLSPO1) / inactive-objects popup
On Error Resume Next
Dim a
a = 0
Do While InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 And a < 5
    L "INFO: activation popup: " & oSession.findById("wnd[1]").Text
    oSession.findById("wnd[1]").sendVKey VKEY_ENTER
    WScript.Sleep 2000
    a = a + 1
Loop
Err.Clear
On Error GoTo 0

' ------ 7. Final status -----------------------------------------------------
Dim sType2, sMsg
On Error Resume Next
sMsg   = oSession.findById("wnd[0]/sbar").Text
sType2 = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0
L "INFO: status bar [" & sType2 & "] " & sMsg

If sType2 = "E" Or sType2 = "A" Then
    L "ERROR: activation reported an error -- " & sMsg
    oLog.Close : WScript.Quit 1
End If

L "SUCCESS: " & added & " element(s) added to " & UCase(PROGRAM_NAME) & " " & SCREEN_NUMBER & "."
oLog.Close
WScript.Quit 0

' ===========================================================================
' AddOneElement -- place cursor, open the create dialog, fill it, transfer.
' ===========================================================================
Function AddOneElement(nMenuIdx, sType, sName, sText, sLen, sLine, sCol)
    AddOneElement = False

    ' Place cursor on the target work-area cell, then open Edit > Create
    ' Element > <type>. Two pitfalls handled here:
    '  (a) Work-area cells txt[col,row] exist ONLY at element boundaries, not at
    '      every column. txt[0,row] (column 0) always exists; an arbitrary column
    '      like txt[9,row] usually does NOT, so focusing it fails (err 619) and
    '      the create menu then silently opens nothing. We therefore try the
    '      requested cell first, then fall back to the always-present txt[0,row]
    '      anchor on the same line.
    '  (b) After a previous element's Transfer the editor needs a beat to settle
    '      its cursor/menu state -- the menu select can otherwise no-op. We retry
    '      the focus+menu up to 3 times until wnd[1] appears.
    ' NOTE on positioning: the element lands at the CURSOR cell. The dialog's
    ' FELD-LINE / FELD-COLN fields are advisory and are rejected for I/O fields
    ' (err 613) -- do not rely on them. For precise "label + input" layouts use
    ' the sap_se51_layout_rebuild.vbs reference (gap-cell discovery).
    Dim cell, anchor, attempt
    cell   = "wnd[0]/usr/txt[" & sCol & "," & sLine & "]"
    anchor = "wnd[0]/usr/txt[0," & sLine & "]"
    For attempt = 1 To 3
        On Error Resume Next
        oSession.findById(cell).setFocus
        oSession.findById(cell).caretPosition = 0
        If Err.Number <> 0 Then
            ' requested cell doesn't exist -- fall back to the column-0 anchor
            Err.Clear
            oSession.findById(anchor).setFocus
            oSession.findById(anchor).caretPosition = 0
        End If
        Err.Clear
        On Error GoTo 0
        WScript.Sleep 300

        ' Edit (menu[1]) > Create Element (menu[2]) > <type> (menu[nMenuIdx])
        On Error Resume Next
        oSession.findById("wnd[0]/mbar/menu[1]/menu[2]/menu[" & nMenuIdx & "]").select
        WScript.Sleep 1000
        Err.Clear
        On Error GoTo 0

        If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then Exit For
        L "INFO: create-element dialog not open yet for '" & sName & "' (attempt " & attempt & "/3) -- retrying."
        WScript.Sleep 500
    Next

    If InStr(oSession.ActiveWindow.Id, "wnd[1]") = 0 Then
        L "WARNING: create-element dialog did not open for '" & sName & "' after 3 attempts."
        Exit Function
    End If

    ' fill the create dialog (best-effort; fields differ per element type)
    '   txtFELD-NAME name  txtFELD-STXT text  txtFELD-LINE line
    '   txtFELD-COLN column  txtFELD-LENG length
    On Error Resume Next
    If Len(sName) > 0 Then oSession.findById("wnd[1]/usr/txtFELD-NAME").Text = sName
    If Len(sText) > 0 Then oSession.findById("wnd[1]/usr/txtFELD-STXT").Text = sText
    If Len(sLen)  > 0 Then oSession.findById("wnd[1]/usr/txtFELD-LENG").Text = sLen
    If Len(sLine) > 0 Then oSession.findById("wnd[1]/usr/txtFELD-LINE").Text = sLine
    If Len(sCol)  > 0 Then oSession.findById("wnd[1]/usr/txtFELD-COLN").Text = sCol
    Err.Clear
    On Error GoTo 0

    ' Refresh/validate (btn[0]) then Transfer/place (btn[5]) -- per the recorder.
    On Error Resume Next
    oSession.findById("wnd[1]/tbar[0]/btn[0]").press
    WScript.Sleep 600
    If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
        oSession.findById("wnd[1]/tbar[0]/btn[5]").press
        WScript.Sleep 800
    End If
    Err.Clear
    On Error GoTo 0

    ' residual validation popup (e.g. position occupied) leaves wnd[1] open
    If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
        L "WARNING: '" & sName & "' left a popup open: " & oSession.findById("wnd[1]").Text & _
          " -- cancelling (F12)."
        On Error Resume Next
        oSession.ActiveWindow.sendVKey VKEY_F12
        WScript.Sleep 500
        Err.Clear
        On Error GoTo 0
        Exit Function
    End If

    L "INFO: added " & UCase(sType) & " '" & sName & "' text='" & sText & _
      "' at line " & sLine & " col " & sCol & "."
    AddOneElement = True
End Function

' ===========================================================================
' HandleSavePopups -- walk the dialog chain SAP raises on first Save / Activate
' of a transportable screen (recorded live on S/4HANA 1909):
'   1. "Create Object Directory Entry" (SAPLSTRD/300) -- package field
'      ctxtTADIR-DEVCLASS normally PREFILLED; Continue = tbar[0]/btn[8].
'   2. "Prompt for transportable change request" (SAPLSTRD/300) -- fill
'      ctxtKO008-TRKORR with SAP_TRANSPORT; Continue = tbar[0]/btn[8].
' Each dialog is dispatched by the DDIC field it exposes (language-neutral).
' Aborts if a TR is required but SAP_TRANSPORT is empty.
' ===========================================================================
Sub HandleSavePopups(sPhase)
    On Error Resume Next
    Dim n
    n = 0
    Do While InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 And n < 8
        Dim AW
        AW = oSession.ActiveWindow.Id

        ' (a) transport-request prompt -- KO008-TRKORR present
        Dim oTR
        Set oTR = Nothing
        Set oTR = oSession.findById(AW & "/usr/ctxtKO008-TRKORR")
        If Err.Number = 0 And Not (oTR Is Nothing) Then
            If SAP_TRANSPORT = "" Then
                L "ERROR: " & sPhase & " prompted for a transport request but TRANSPORT is empty."
                L "       Resolve a modifiable TR via /sap-transport-request and re-run."
                oLog.Close : WScript.Quit 1
            End If
            If Trim(oTR.Text) = "" Then oTR.Text = SAP_TRANSPORT
            L "INFO: " & sPhase & " TR prompt -- entering " & SAP_TRANSPORT & "."
            Err.Clear
            PressContinue AW
        Else
            Err.Clear
            ' (b) Create Object Directory Entry -- TADIR-DEVCLASS present
            Dim oDev
            Set oDev = Nothing
            Set oDev = oSession.findById(AW & "/usr/ctxtTADIR-DEVCLASS")
            If Err.Number = 0 And Not (oDev Is Nothing) Then
                If Trim(oDev.Text) = "" And SAP_PACKAGE <> "" Then oDev.Text = SAP_PACKAGE
                L "INFO: " & sPhase & " Object Directory Entry -- package=" & oDev.Text & "."
                Err.Clear
                PressContinue AW
            Else
                Err.Clear
                L "INFO: " & sPhase & " popup '" & oSession.findById(AW).Text & "' -- Continue/Enter."
                PressContinue AW
            End If
        End If
        WScript.Sleep 1200
        n = n + 1
    Loop
    Err.Clear
    On Error GoTo 0
End Sub

' Press a dialog's Continue button (tbar[0]/btn[8] on SAPLSTRD), Enter fallback.
Sub PressContinue(sWnd)
    On Error Resume Next
    Dim oBtn
    Set oBtn = Nothing
    Set oBtn = oSession.findById(sWnd & "/tbar[0]/btn[8]")
    If Err.Number = 0 And Not (oBtn Is Nothing) Then
        oBtn.press
    Else
        Err.Clear
        oSession.findById(sWnd).sendVKey VKEY_ENTER
    End If
    Err.Clear
    On Error GoTo 0
End Sub
