' =============================================================================
' sap_bp_check.vbs  -  SAP GUI Scripting: Check if Business Partner exists
'
' Generated by the sap-bp skill.
' Attaches to an existing SAP GUI session, navigates to BP transaction,
' uses Open BP to check if the partner number exists.
'
' Output: "EXIST" or "NOT_EXIST" (last line of stdout, parseable by skill).
'
' Tokens replaced at run time:
'   %%BP_NUMBER%%  Business Partner number  e.g. "14"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const BP_NUMBER  = "%%BP_NUMBER%%"
Const VKEY_ENTER = 0
Const SESSION_PATH  = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to BP ---------------------------------------------------
WScript.Echo "INFO: Navigating to BP transaction..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nBP"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Open BP popup and enter number -----------------------------------
WScript.Echo "INFO: Checking Business Partner: " & BP_NUMBER
oSession.findById("wnd[0]/tbar[1]/btn[17]").Press  ' Open BP (Shift+F5)
WScript.Sleep 500

On Error Resume Next
oSession.findById("wnd[1]/usr/ctxtBUS_JOEL_MAIN-OPEN_NUMBER").Text = BP_NUMBER
oSession.findById("wnd[1]").sendVKey VKEY_ENTER
WScript.Sleep 1000
On Error GoTo 0

' ------ 4. Determine result -------------------------------------------------
Dim sStatus, sStatusType
sStatus = oSession.findById("wnd[0]/sbar").Text
sStatusType = oSession.findById("wnd[0]/sbar").MessageType

If sStatusType = "E" Then
    WScript.Echo "INFO: " & sStatus
    ' Close the popup if still open
    On Error Resume Next
    oSession.findById("wnd[1]").sendVKey 12  ' Cancel/F12
    Err.Clear
    On Error GoTo 0
    WScript.Echo "NOT_EXIST"
    WScript.Quit 0
End If

' Check if title shows Display (BP was found)
Dim sTitle
sTitle = oSession.findById("wnd[0]").Text
If InStr(sTitle, "Display") > 0 Then
    WScript.Echo "INFO: Business Partner " & BP_NUMBER & " exists. " & sTitle
    ' Navigate back to clean state
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nBP"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    WScript.Echo "EXIST"
    WScript.Quit 0
End If

' Check if title shows Change (BP was already in change mode)
If InStr(sTitle, "Change") > 0 Then
    WScript.Echo "INFO: Business Partner " & BP_NUMBER & " exists. " & sTitle
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nBP"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    WScript.Echo "EXIST"
    WScript.Quit 0
End If

WScript.Echo "INFO: Could not determine existence. Title: " & sTitle & " Status: " & sStatus
WScript.Echo "NOT_EXIST"
WScript.Quit 0
