' =============================================================================
' sap_bp_update.vbs  -  SAP GUI Scripting: Update Business Partner via BP
'
' Generated by the sap-bp skill.
' Attaches to an existing SAP GUI session, navigates to BP transaction,
' opens the partner for change, switches to General Data view, fills
' field values from a definition file, and saves.
'
' Definition file format (tab-separated, one field per line):
'   TAB_01	BUT000-NAME_ORG1	Updated Company Name
'   TAB_01	ADDR1_DATA-CITY1	Shanghai
'
' Sections: TAB_01-TAB_14 (tab panels in General Data view)
' Lines starting with # are comments. Blank lines are skipped.
'
' Tokens replaced at run time:
'   %%BP_NUMBER%%       Business Partner number
'   %%DEFINITION_FILE%% Path to field definitions
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const BP_NUMBER       = "%%BP_NUMBER%%"
Const DEFINITION_FILE = "%%DEFINITION_FILE%%"

Const VKEY_ENTER    = 0
Const VKEY_F11_SAVE = 11

Dim oSAPGUI, oApplication, oSession
Dim oCandidate, oSessIter

' ------ Helper: Find input field by name within a container (recursive) -----
Function FindField(oContainer, sFieldName)
    Set FindField = Nothing
    On Error Resume Next
    Dim ch
    Set ch = oContainer.Children
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    On Error GoTo 0

    Dim j, c, cName, cType
    For j = 0 To ch.Count - 1
        Set c = ch(CLng(j))
        On Error Resume Next
        cName = c.Name
        cType = c.Type
        Err.Clear
        On Error GoTo 0

        If cName = sFieldName Then
            If cType = "GuiTextField" Or cType = "GuiCTextField" Or _
               cType = "GuiComboBox" Or cType = "GuiCheckBox" Then
                Set FindField = c
                Exit Function
            End If
        End If

        If cType = "GuiSimpleContainer" Or cType = "GuiScrollContainer" Or _
           cType = "GuiTabStrip" Or cType = "GuiTab" Then
            Dim found
            Set found = FindField(c, sFieldName)
            If Not (found Is Nothing) Then
                Set FindField = found
                Exit Function
            End If
        End If
    Next
End Function

' ------ Helper: Find and select a tab by name (recursive) -------------------
Function SelectTab(oContainer, sTabName)
    SelectTab = False
    On Error Resume Next
    Dim ch
    Set ch = oContainer.Children
    If Err.Number <> 0 Then
        Err.Clear
        Exit Function
    End If
    On Error GoTo 0

    Dim j, c, cName, cType
    For j = 0 To ch.Count - 1
        Set c = ch(CLng(j))
        On Error Resume Next
        cName = c.Name
        cType = c.Type
        Err.Clear
        On Error GoTo 0

        If cName = sTabName And cType = "GuiTab" Then
            c.Select
            SelectTab = True
            Exit Function
        End If

        If cType = "GuiSimpleContainer" Or cType = "GuiScrollContainer" Or _
           cType = "GuiTabStrip" Then
            If SelectTab(c, sTabName) Then
                SelectTab = True
                Exit Function
            End If
        End If
    Next
End Function

' ------ Helper: Set field value based on control type -----------------------
Sub SetFieldValue(oField, sValue)
    Select Case oField.Type
        Case "GuiTextField", "GuiCTextField"
            oField.Text = sValue
        Case "GuiComboBox"
            oField.Key = sValue
        Case "GuiCheckBox"
            If UCase(sValue) = "X" Or sValue = "1" Or UCase(sValue) = "TRUE" Then
                oField.Selected = True
            Else
                oField.Selected = False
            End If
    End Select
End Sub

' ------ 1. Attach to existing SAP GUI session -------------------------------
On Error Resume Next
Set oSAPGUI = GetObject("SAPGUI")
If Err.Number <> 0 Or oSAPGUI Is Nothing Then
    WScript.Echo "ERROR: SAP GUI is not running."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

Set oApplication = oSAPGUI.GetScriptingEngine
If oApplication Is Nothing Then
    WScript.Echo "ERROR: Could not get SAP Scripting Engine."
    WScript.Quit 1
End If

Set oSession = Nothing
On Error Resume Next
For Each oCandidate In oApplication.Children
    For Each oSessIter In oCandidate.Children
        Set oSession = oSessIter
        Exit For
    Next
    If Not (oSession Is Nothing) Then Exit For
Next
On Error GoTo 0

If oSession Is Nothing Then
    WScript.Echo "ERROR: No SAP GUI session found. Run the login step first."
    WScript.Quit 1
End If
WScript.Echo "INFO: Session acquired."

' ------ 2. Read definition file ---------------------------------------------
Dim oFSO, oFile, sLine
Set oFSO = CreateObject("Scripting.FileSystemObject")

If Not oFSO.FileExists(DEFINITION_FILE) Then
    WScript.Echo "ERROR: Definition file not found: " & DEFINITION_FILE
    WScript.Quit 1
End If

Dim arrSections(), arrFields(), arrValues()
Dim iCount
iCount = 0

Set oFile = oFSO.OpenTextFile(DEFINITION_FILE, 1, False)
Do While Not oFile.AtEndOfStream
    sLine = oFile.ReadLine
    ' Strip UTF-8 BOM if present on first line
    If iCount = 0 And Len(sLine) > 0 Then
        Do While Len(sLine) > 0 And Asc(Left(sLine, 1)) > 127
            sLine = Mid(sLine, 2)
        Loop
    End If

    sLine = Trim(sLine)

    If Len(sLine) > 0 And Left(sLine, 1) <> "#" Then
        Dim iParts
        iParts = InStr(sLine, vbTab)

        If iParts > 0 Then
            Dim sSection, sRest
            sSection = Trim(Left(sLine, iParts - 1))
            sRest = Mid(sLine, iParts + 1)

            Dim iParts2
            iParts2 = InStr(sRest, vbTab)

            If iParts2 > 0 Then
                Dim sField, sValue
                sField = Trim(Left(sRest, iParts2 - 1))
                sValue = Mid(sRest, iParts2 + 1)

                ReDim Preserve arrSections(iCount)
                ReDim Preserve arrFields(iCount)
                ReDim Preserve arrValues(iCount)
                arrSections(iCount) = UCase(sSection)
                arrFields(iCount) = sField
                arrValues(iCount) = sValue
                iCount = iCount + 1
            End If
        End If
    End If
Loop
oFile.Close

WScript.Echo "INFO: Read " & iCount & " field definitions from file."

' ------ 3. Navigate to BP and open partner ----------------------------------
WScript.Echo "INFO: Navigating to BP transaction..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nBP"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' Open BP popup and enter number
WScript.Echo "INFO: Opening Business Partner: " & BP_NUMBER
oSession.findById("wnd[0]/tbar[1]/btn[17]").Press  ' Open BP (Shift+F5)
WScript.Sleep 500

oSession.findById("wnd[1]/usr/ctxtBUS_JOEL_MAIN-OPEN_NUMBER").Text = BP_NUMBER
oSession.findById("wnd[1]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' Check for errors (BP doesn't exist)
Dim sStatus
sStatus = oSession.findById("wnd[0]/sbar").Text
If oSession.findById("wnd[0]/sbar").MessageType = "E" Then
    ' Close popup
    On Error Resume Next
    oSession.findById("wnd[1]").sendVKey 12
    Err.Clear
    On Error GoTo 0
    WScript.Echo "ERROR: " & sStatus
    WScript.Quit 1
End If

' ------ 4. Switch to Change mode --------------------------------------------
WScript.Echo "INFO: Switching to Change mode..."
oSession.findById("wnd[0]/tbar[1]/btn[6]").Press   ' Switch Display/Change (F6)
WScript.Sleep 1000

Dim sTitle
sTitle = oSession.findById("wnd[0]").Text
If InStr(sTitle, "Change") = 0 Then
    WScript.Echo "ERROR: Failed to switch to Change mode. Title: " & sTitle
    WScript.Quit 1
End If
WScript.Echo "INFO: Change mode reached: " & sTitle

' ------ 5. Switch to General Data view --------------------------------------
WScript.Echo "INFO: Switching to General Data view..."
oSession.findById("wnd[0]/tbar[1]/btn[25]").Press   ' General Data (Ctrl+F1)
WScript.Sleep 1000

' ------ 6. Fill tab fields --------------------------------------------------
Dim oUsr
Set oUsr = oSession.findById("wnd[0]/usr")

' Collect unique tab IDs in order
Dim arrTabs()
Dim iTabCount
iTabCount = 0

Dim iTmp
For iTmp = 0 To iCount - 1
    Dim bFound
    bFound = False
    Dim iChk
    For iChk = 0 To iTabCount - 1
        If arrTabs(iChk) = arrSections(iTmp) Then
            bFound = True
            Exit For
        End If
    Next
    If Not bFound Then
        ReDim Preserve arrTabs(iTabCount)
        arrTabs(iTabCount) = arrSections(iTmp)
        iTabCount = iTabCount + 1
    End If
Next

WScript.Echo "INFO: Processing " & iTabCount & " tabs..."

Dim iTab
For iTab = 0 To iTabCount - 1
    Dim sTabSection
    sTabSection = arrTabs(iTab)

    ' Convert TAB_XX to SCREEN_1100_TAB_XX for tab selection
    Dim sTabName
    sTabName = "SCREEN_1100_" & sTabSection

    ' Select the tab
    If Not SelectTab(oUsr, sTabName) Then
        WScript.Echo "WARNING: Tab " & sTabSection & " not found, trying to set fields anyway."
    Else
        WScript.Echo "INFO: Selected tab: " & sTabSection
    End If
    WScript.Sleep 500

    ' Set fields for this tab
    Dim iFld
    For iFld = 0 To iCount - 1
        If arrSections(iFld) = sTabSection Then
            Dim oField
            Set oField = FindField(oUsr, arrFields(iFld))
            If oField Is Nothing Then
                WScript.Echo "WARNING:   Field not found: " & arrFields(iFld)
            Else
                On Error Resume Next
                SetFieldValue oField, arrValues(iFld)
                If Err.Number <> 0 Then
                    WScript.Echo "WARNING:   Error setting " & arrFields(iFld) & ": " & Err.Description
                    Err.Clear
                Else
                    WScript.Echo "INFO:   " & arrFields(iFld) & " = " & arrValues(iFld)
                End If
                On Error GoTo 0
            End If
        End If
    Next
Next

' Press Enter to commit inline edits
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 7. Save -------------------------------------------------------------
WScript.Echo "INFO: Saving Business Partner..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 2000

' Handle warning: press Enter to acknowledge, then save again
Dim sSaveStatus, sSaveType
sSaveStatus = oSession.findById("wnd[0]/sbar").Text
sSaveType = oSession.findById("wnd[0]/sbar").MessageType
If sSaveType = "W" Then
    WScript.Echo "INFO: Warning after save: " & sSaveStatus & " - acknowledging..."
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 1000
    oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
    WScript.Sleep 2000
End If

' Handle popups (transport, etc.)
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    WScript.Echo "INFO: Popup detected."
    oSession.findById("wnd[1]/tbar[0]/btn[7]").Press  ' Local Object
    If Err.Number <> 0 Then
        Err.Clear
        oSession.ActiveWindow.sendVKey VKEY_ENTER
    End If
    WScript.Sleep 2000
End If

If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSession.ActiveWindow.sendVKey VKEY_ENTER
    WScript.Sleep 1000
End If
Err.Clear
On Error GoTo 0

' ------ 8. Check result -----------------------------------------------------
sStatus = oSession.findById("wnd[0]/sbar").Text
Dim sStatusType
sStatusType = oSession.findById("wnd[0]/sbar").MessageType

' Navigate back to clean state
sTitle = oSession.findById("wnd[0]").Text
If InStr(sTitle, "Change") > 0 Or InStr(sTitle, "Display") > 0 Then
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    On Error Resume Next
    oSession.findById("wnd[1]/usr/btnSPOP-OPTION1").Press
    Err.Clear
    On Error GoTo 0
    WScript.Sleep 500
End If

WScript.Echo "INFO: Status (" & sStatusType & "): " & sStatus

If sStatusType = "E" Or sStatusType = "A" Then
    WScript.Echo "ERROR: Business Partner update failed. " & sStatus
    WScript.Quit 1
End If

WScript.Echo "SUCCESS: Business Partner " & BP_NUMBER & " updated in SAP."
WScript.Quit 0
