' =============================================================================
' sap_se37_update.vbs  -  SAP GUI Scripting: Update existing function module via SE37
'
' Generated by the sap-se37 skill.
' Attaches to an existing SAP GUI session, navigates to SE37, opens the
' function module in change mode, uploads new source code to the Source code
' tab, saves, and activates.
'
' Tokens replaced at run time:
'   %%FM_NAME%%            Function module name       e.g. "ZHKFM_TEST001"
'   %%ABAP_SOURCE_FILE%%   Absolute path to .abap file with full FM source
'                          (MUST include FUNCTION/ENDFUNCTION wrapper and
'                           Local Interface comment block)
'   [INTERFACE_CODE]       Generated VBS lines that fill Import/Export/Changing/
'                          Tables/Exceptions tabs from the parsed FM interface.
'                          REQUIRED on UPDATE: the source upload writes only the
'                          source body. On activation SAP REGENERATES the
'                          *"Local Interface comment from the tabs (FUNCT /
'                          FUPARAREF), so tabs must reflect the new interface.
'                          When SAP shows the "Copy or Rename Parameter" popup,
'                          press Rename (btnSPOP-VAROPTION1). When the status
'                          bar shows a warning, press Enter to dismiss it.
'   %%PACKAGE%%            SAP package (optional, blank = local $TMP)
'   %%TRANSPORT%%          Transport request (optional, blank = local)
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909 (S4D).
' =============================================================================

Option Explicit

Const FM_NAME          = "%%FM_NAME%%"
Const ABAP_SOURCE_FILE = "%%ABAP_SOURCE_FILE%%"
Const SAP_PACKAGE      = "%%PACKAGE%%"
Const SAP_TRANSPORT    = "%%TRANSPORT%%"
Const SESSION_PATH     = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER    = 0
Const VKEY_F3_BACK  = 3
Const VKEY_F11_SAVE = 11

ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()
' Syntax-check classifier (GetSyntaxErrorWord / ExtractIconId /
' IsErrorMsgType) - locale-aware MSGTYPE match for the Ctrl+F2 grid.
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SYNTAX_CHECK_LIB_VBS%%", 1).ReadAll()

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SE37 -------------------------------------------------
WScript.Echo "INFO: Navigating to SE37..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nSE37"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

On Error Resume Next
Dim oFMField
Set oFMField = oSession.findById("wnd[0]/usr/ctxtRS38L-NAME")
If Err.Number <> 0 Or oFMField Is Nothing Then
    WScript.Echo "ERROR: SE37 function module name field not found (ID: wnd[0]/usr/ctxtRS38L-NAME)."
    WScript.Quit 1
End If
On Error GoTo 0

' ------ 3. Enter FM name and open in change mode (btnBUT4) ------------------
oFMField.Text = UCase(FM_NAME)
WScript.Sleep 300

WScript.Echo "INFO: Opening function module in change mode: " & UCase(FM_NAME)
oSession.findById("wnd[0]/usr/btnBUT4").press
WScript.Sleep 2000

' ------ 3a. Original-language mismatch popup (program SAPLSETX) -------------
' If wnd[1] is the "Different original and logon languages" dialog, press
' "Maint. in orig. lang." (btnPUSH1). Keeps TADIR-MASTERLANG unchanged.
' Fingerprint: ctxtRSETX-MASTERLANG present in wnd[1]/usr.
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim oMasterLangFld
    Set oMasterLangFld = Nothing
    Err.Clear
    Set oMasterLangFld = oSession.findById("wnd[1]/usr/ctxtRSETX-MASTERLANG")
    If Err.Number = 0 Then
        If Not (oMasterLangFld Is Nothing) Then
            Dim oMaintBtn
            Set oMaintBtn = Nothing
            Err.Clear
            Set oMaintBtn = oSession.findById("wnd[1]/usr/btnPUSH1")
            If Err.Number = 0 Then
                If Not (oMaintBtn Is Nothing) Then
                    WScript.Echo "INFO: Original-language popup detected (logon != MASTERLANG=" & _
                                 oMasterLangFld.Text & ") — pressing 'Maint. in orig. lang.'."
                    oMaintBtn.press
                    WScript.Sleep 1500
                End If
            End If
        End If
    End If
End If
Err.Clear
On Error GoTo 0

' Dismiss any other confirmation popup
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSession.ActiveWindow.sendVKey VKEY_ENTER
    WScript.Sleep 1000
End If
Err.Clear
On Error GoTo 0

' Verify we are in the Function Builder editor
On Error Resume Next
Dim oTabStrip
Set oTabStrip = oSession.findById("wnd[0]/usr/tabsFUNC_TAB_STRIP")
Dim bInEditor
bInEditor = (Err.Number = 0) And Not (oTabStrip Is Nothing)
Err.Clear
On Error GoTo 0

If Not bInEditor Then
    WScript.Echo "ERROR: Could not open function module in change mode." & vbCrLf & _
                 "       Check that the FM exists and you have authorization."
    WScript.Quit 1
End If
WScript.Echo "INFO: Function module opened in change mode."

' ------ 3b. Pre-save TR claim --------------------------------------------------
' Send Ctrl+S to provoke any "Prompt for local Workbench request" popup.
' Outcomes:
'   (a) wnd[1] with field ctxtKO008-TRKORR → fill SAP_TRANSPORT, Enter.
'   (b) Other popup → Enter to dismiss.
'   (c) No popup → object is local ($TMP) or already locked to a modifiable TR.
' If a TR popup appears but SAP_TRANSPORT is empty, abort.
' Diagnostics: TADIR-DEVCLASS, E071, E070-TRSTATUS.
WScript.Echo "INFO: Pre-save (Ctrl+S) to check whether a TR popup appears..."
On Error Resume Next
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1500
Err.Clear
On Error GoTo 0

On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim oPreTR
    Set oPreTR = oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR")
    If Err.Number = 0 And Not (oPreTR Is Nothing) Then
        Err.Clear
        If SAP_TRANSPORT = "" Then
            WScript.Echo "ERROR: SE37 prompted for a transport request but SAP_TRANSPORT is empty." & vbCrLf & _
                         "       Resolve a modifiable TR via /sap-transport-request and re-run."
            WScript.Quit 1
        End If
        oPreTR.Text = SAP_TRANSPORT
        WScript.Echo "INFO: Pre-save TR popup detected — entering " & SAP_TRANSPORT & "."
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1000
    Else
        Err.Clear
        WScript.Echo "INFO: Pre-save popup (no TR field) — pressing Enter to dismiss."
        oSession.ActiveWindow.sendVKey VKEY_ENTER
        WScript.Sleep 800
    End If
Else
    WScript.Echo "INFO: No pre-save popup — object is local ($TMP) or already locked to a modifiable TR."
End If
Err.Clear
On Error GoTo 0

' --- Lock the SAP session UI for the source upload + save + activate + syntax check critical section ---
' Per Rule 7: LockSessionUI blocks user input races inside SAP. We do NOT
' need an OS-level foreground guard here (unlike sap-se38) because the
' source is uploaded via SE37's Utilities > Upload menu — the file is
' read from disk by the SAP process; no clipboard, no SendKeys, no
' Windows-foreground race. Released after activation.
Dim wasLocked : wasLocked = TryLockSession(oSession)
If wasLocked Then
    WScript.Echo "INFO: Session UI locked for the source upload + save + activate + syntax check critical section."
Else
    WScript.Echo "INFO: LockSessionUI not available on this SAP GUI build; continuing without lock."
End If

' ------ 4. Navigate to Source code tab and upload source ---------------------
oSession.findById("wnd[0]/usr/tabsFUNC_TAB_STRIP/tabpSOURCE").select
WScript.Sleep 1500

WScript.Echo "INFO: Uploading source file: " & ABAP_SOURCE_FILE

Dim oFSO
Set oFSO = CreateObject("Scripting.FileSystemObject")
If Not oFSO.FileExists(ABAP_SOURCE_FILE) Then
    WScript.Echo "ERROR: Source file not found: " & ABAP_SOURCE_FILE
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

' Convert UTF-8 source file to appropriate encoding for SAP GUI upload.
' On Unicode SAP systems (codepage 4110), upload UTF-8 directly.
' On non-Unicode systems, convert to the Windows system ANSI codepage.
Dim bIsUnicode
bIsUnicode = False
On Error Resume Next
Dim iSAPCodepage
iSAPCodepage = oSession.Info.Codepage
If Err.Number = 0 And (CStr(iSAPCodepage) = "4110" Or CStr(iSAPCodepage) = "4103") Then
    bIsUnicode = True
End If
Err.Clear
On Error GoTo 0

Dim sUploadFile
If bIsUnicode Then
    sUploadFile = ABAP_SOURCE_FILE
    WScript.Echo "INFO: Unicode SAP system (codepage " & iSAPCodepage & "). Uploading UTF-8 source directly."
Else
    Dim oWMI, colItems, oItem, sCodePage
    Set oWMI = GetObject("winmgmts:\\.\root\cimv2")
    Set colItems = oWMI.ExecQuery("SELECT CodeSet FROM Win32_OperatingSystem")
    sCodePage = ""
    For Each oItem In colItems
        If oItem.CodeSet <> "" Then sCodePage = oItem.CodeSet
    Next
    Dim sCharset
    Select Case sCodePage
        Case "932"   : sCharset = "shift_jis"
        Case "936"   : sCharset = "gb2312"
        Case "949"   : sCharset = "ks_c_5601-1987"
        Case "950"   : sCharset = "big5"
        Case "1250"  : sCharset = "windows-1250"
        Case "1251"  : sCharset = "windows-1251"
        Case "1253"  : sCharset = "windows-1253"
        Case "1254"  : sCharset = "windows-1254"
        Case "1255"  : sCharset = "windows-1255"
        Case "1256"  : sCharset = "windows-1256"
        Case "65001" : sCharset = "utf-8"
        Case Else    : sCharset = "windows-1252"
    End Select

    sUploadFile = ABAP_SOURCE_FILE & ".upload.txt"
    Dim oInStream, oOutStream
    Set oInStream = CreateObject("ADODB.Stream")
    oInStream.Type = 2
    oInStream.Charset = "utf-8"
    oInStream.Open
    oInStream.LoadFromFile ABAP_SOURCE_FILE

    Set oOutStream = CreateObject("ADODB.Stream")
    oOutStream.Type = 2
    oOutStream.Charset = sCharset
    oOutStream.Open

    Dim sAbapContent
    sAbapContent = oInStream.ReadText
    oInStream.Close
    oOutStream.WriteText sAbapContent
    oOutStream.SaveToFile sUploadFile, 2
    oOutStream.Close
    WScript.Echo "INFO: Converted source file from UTF-8 to " & sCharset & " for upload."
End If

' Utilities > More Utilities > Upload/Download > Upload
' menu[3]/menu[9]/menu[3]/menu[0]
On Error Resume Next
oSession.findById("wnd[0]/mbar/menu[3]/menu[9]/menu[3]/menu[0]").select
If Err.Number <> 0 Then
    WScript.Echo "ERROR: Could not open Upload menu (menu[3]/menu[9]/menu[3]/menu[0])." & vbCrLf & _
                 "       Use Scripting Recorder to find the correct menu path."
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0
WScript.Sleep 1000

' Fill in the upload dialog
On Error Resume Next
Dim iSlash, sDir, sFile
iSlash = InStrRev(sUploadFile, "\")
sDir   = Left(sUploadFile, iSlash)
sFile  = Mid(sUploadFile, iSlash + 1)

oSession.findById("wnd[1]/usr/ctxtDY_PATH").Text     = sDir
oSession.findById("wnd[1]/usr/ctxtDY_FILENAME").Text = sFile
WScript.Sleep 300
oSession.findById("wnd[1]").sendVKey VKEY_ENTER
WScript.Sleep 2000

If Err.Number <> 0 Then
    WScript.Echo "ERROR: Upload dialog interaction failed: " & Err.Description
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

' Dismiss "Replace existing text?" confirmation if it appears
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSession.ActiveWindow.sendVKey VKEY_ENTER
    WScript.Sleep 1000
End If
Err.Clear
On Error GoTo 0

WScript.Echo "INFO: Source code uploaded."

' ------ 4b. Fill interface tabs (generated from parsed FM source) -----------
' On UPDATE the source upload writes only the body. On activation SAP
' regenerates the *" Local Interface comment from the tab contents
' (FUNCT/FUPARAREF), so the Import/Export/Changing/Tables/Exceptions tabs
' must be re-synced from the new source ourselves.
'
' Conventions used by the generated code below:
'   - For each parameter row we write fields then sendVKey 0 to commit.
'   - When SAP shows the "Copy or Rename Parameter" popup (it appears when
'     a parameter name in an existing row is overwritten with a new name),
'     press Rename: btnSPOP-VAROPTION1.
'   - After commit, status-bar warnings (e.g. "TABLES parameters are
'     obsolete") are dismissed by sending Enter once.
%%INTERFACE_CODE%%
' ------ 5. Save (Ctrl+S / F11) ----------------------------------------------
' Pre-save in step 3b already locked the object to SAP_TRANSPORT (or it is
' local / already locked), so the TR popup should not reappear. Any popup
' here is a safety net.
WScript.Echo "INFO: Saving..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 1500

On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim oTrField2
    Set oTrField2 = oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR")
    If Err.Number = 0 And Not (oTrField2 Is Nothing) Then
        Err.Clear
        If SAP_TRANSPORT <> "" Then
            oTrField2.Text = SAP_TRANSPORT
            WScript.Echo "INFO: (safety-net) TR popup re-appeared on save — re-entering " & SAP_TRANSPORT & "."
        End If
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1000
    Else
        Err.Clear
        WScript.Echo "INFO: (safety-net) Save popup (no TR field) — Enter to dismiss."
        oSession.ActiveWindow.sendVKey VKEY_ENTER
        WScript.Sleep 800
    End If
End If
Err.Clear
On Error GoTo 0
WScript.Echo "INFO: Saved."

' ------ 6. Activate (Ctrl+F3) — must activate BEFORE syntax check ---------
' If the function group has an inactive version, syntax check reports
' "Statement is not accessible" for ALL lines. Activating first resolves this.
WScript.Echo "INFO: Activating..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[1]/btn[27]").press  ' Ctrl+F3 Activate
WScript.Sleep 1500

' Handle "Inactive Objects" worklist popup. The popup may appear up to ~10s
' after pressing Activate (esp. when sibling FUGR objects are also inactive
' after a recent Reassign). Poll, then Select All (Ctrl+A = sendVKey 26)
' before pressing Continue (btn[0]) — pressing Continue alone with nothing
' selected leaves the popup up.
Dim iWaitAct
For iWaitAct = 1 To 10
    If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then Exit For
    WScript.Sleep 1000
Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    WScript.Echo "INFO: Inactive objects list — Select All + Continue..."
    Err.Clear
    oSession.findById("wnd[1]").sendVKey 26   ' Ctrl+A = Select All
    WScript.Sleep 500
    oSession.findById("wnd[1]/tbar[0]/btn[0]").press  ' Continue
    WScript.Sleep 5000
End If

' Handle "Activation errors" popup (wnd[2]) — press Activate to proceed
If InStr(oSession.ActiveWindow.Id, "wnd[2]") > 0 Then
    WScript.Echo "WARNING: Activation errors — pressing Activate anyway..."
    On Error Resume Next
    oSession.findById("wnd[2]/usr/btnSPOP-VAROPTION1").press
    If Err.Number <> 0 Then
        Err.Clear
        oSession.findById("wnd[2]/usr/btnBUTTON_1").press
    End If
    On Error GoTo 0
    WScript.Sleep 3000
End If
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSession.findById("wnd[1]").sendVKey 12
    WScript.Sleep 1000
End If
Err.Clear
On Error GoTo 0

' ------ 7. Syntax check (Ctrl+F2) — read error grid -----------------------
WScript.Echo "INFO: Running syntax check..."
oSession.findById("wnd[0]/tbar[1]/btn[26]").press  ' Ctrl+F2 Check
WScript.Sleep 3000

' Dismiss any popup
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    oSession.ActiveWindow.sendVKey VKEY_ENTER
    WScript.Sleep 500
End If
Err.Clear
On Error GoTo 0

' Read syntax errors from the error grid. The AbapEditor swallows status bar
' messages, so we read the grid instead. The container PATH is RELEASE-SPECIFIC
' (S/4 1909 = shellcont[1]/shell; ECC 6.0 nests it deeper at
' shellcont[2]/shell/shellcont[0]/shell), so locate it via FindSyntaxErrorGrid
' (shared sap_syntax_check_lib.vbs) which WALKS wnd[0]/shellcont for the
' GridView carrying a MSGTYPE column. A hardcoded path silently resolves to a
' different/empty grid on the other release -> RowCount 0 -> false "no findings"
' -> false SUCCESS while the FM stays INACTIVE (the 2026-06-16 EC6/ER1 incident).
' This check runs AFTER Activate (Ctrl+F3 above), so it doubles as the
' post-activate gate. Columns: MSGTYPE (icon format @5C\QError@), LINE, TEXT.
' Errors come in pairs: row N has MSGTYPE+LINE+FM name, row N+1 has description.
Dim oSyntaxGrid, nSyntaxRows, bSyntaxOK
bSyntaxOK = True

On Error Resume Next
Set oSyntaxGrid = FindSyntaxErrorGrid(oSession)
If Err.Number = 0 And Not (oSyntaxGrid Is Nothing) Then
    nSyntaxRows = oSyntaxGrid.RowCount
    Err.Clear
    If nSyntaxRows > 0 Then
        Dim nErrorCount
        nErrorCount = 0
        ' --- Resolve logon language so the shared IsErrorMsgType classifier can
        ' match SAP's localized "Error" label in MSGTYPE (e.g. ZH "错误", JA
        ' "エラー"). Icon-ID prefix is the locale-independent fallback inside
        ' the helper — see shared/scripts/sap_syntax_check_lib.vbs.
        Dim sLogonLang
        On Error Resume Next
        sLogonLang = UCase(CStr(oSession.Info.Language))
        On Error GoTo 0
        If Len(sLogonLang) = 0 Then sLogonLang = "E"
        WScript.Echo "INFO: Logon language = '" & sLogonLang & _
                     "'; matching syntax-error word = '" & GetSyntaxErrorWord(sLogonLang) & "'."
        Dim iSynRow
        For iSynRow = 0 To nSyntaxRows - 1
            Dim sSynType, sSynLine, sSynText
            sSynType = ""
            sSynLine = ""
            sSynText = ""
            sSynType = oSyntaxGrid.getCellValue(iSynRow, "MSGTYPE")
            Err.Clear
            sSynLine = oSyntaxGrid.getCellValue(iSynRow, "LINE")
            Err.Clear
            sSynText = oSyntaxGrid.getCellValue(iSynRow, "TEXT")
            Err.Clear
            Dim bIsError
            bIsError = IsErrorMsgType(sSynType, sLogonLang)
            If bIsError Then nErrorCount = nErrorCount + 1
            ' Only output rows that have actual text
            If sSynText <> "" Then
                If bIsError Then
                    If sSynLine <> "" Then
                        WScript.Echo "ERROR: Line " & sSynLine & ": " & sSynText
                    Else
                        WScript.Echo "ERROR:     -> " & sSynText
                    End If
                Else
                    If sSynLine <> "" Then
                        WScript.Echo "WARNING: Line " & sSynLine & ": " & sSynText
                    Else
                        WScript.Echo "WARNING:     -> " & sSynText
                    End If
                End If
            End If
        Next
        If nErrorCount > 0 Then
            bSyntaxOK = False
            WScript.Echo "ERROR: Syntax check found " & nErrorCount & " error(s)."
        Else
            WScript.Echo "INFO: Syntax check passed with " & nSyntaxRows & " warning(s) only."
        End If
    Else
        WScript.Echo "INFO: Syntax check passed — no findings."
    End If
Else
    Err.Clear
    ' Grid not found — fall back to status bar check
    Dim sSyntaxMsg, sSyntaxType
    sSyntaxMsg  = oSession.findById("wnd[0]/sbar").Text
    sSyntaxType = oSession.findById("wnd[0]/sbar").MessageType
    Err.Clear
    If sSyntaxType = "E" Then
        bSyntaxOK = False
        WScript.Echo "ERROR: Syntax check failed - " & sSyntaxMsg
    ElseIf sSyntaxMsg = "" Then
        WScript.Echo "INFO: Syntax check — no findings (sbar empty, AbapEditor may swallow messages)."
    Else
        WScript.Echo "INFO: Syntax check passed."
    End If
End If
On Error GoTo 0

If Not bSyntaxOK Then
    ' Clean up temp file before exiting
    On Error Resume Next
    If sUploadFile <> ABAP_SOURCE_FILE Then
        If oFSO.FileExists(sUploadFile) Then oFSO.DeleteFile sUploadFile
    End If
    Err.Clear
    On Error GoTo 0
    WScript.Echo "ERROR: Fix syntax errors and retry."
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If

' --- Release the session UI lock; Step 8 is read-only status check ---
ReleaseSession oSession, wasLocked
If wasLocked Then WScript.Echo "INFO: Session UI lock released."

' ------ 8. Final status check -----------------------------------------------
' Clean up temp upload file (only delete if it was a converted temp copy, not the original)
On Error Resume Next
If sUploadFile <> ABAP_SOURCE_FILE Then
    If oFSO.FileExists(sUploadFile) Then oFSO.DeleteFile sUploadFile
End If
Err.Clear
On Error GoTo 0

Dim sFinalMsg, sFinalType
On Error Resume Next
sFinalMsg  = oSession.findById("wnd[0]/sbar").Text
sFinalType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

If sFinalType = "E" Then
    WScript.Echo "WARNING: Activation may have errors - " & sFinalMsg
Else
    WScript.Echo "INFO: SAP status: " & sFinalMsg
End If

WScript.Echo "SUCCESS: Function module " & UCase(FM_NAME) & " updated and activated in SAP."
WScript.Quit 0
