# =============================================================================
# sap_gui_probe_synthesize.ps1
# -----------------------------------------------------------------------------
# Walk every step_NN_action.json in the run folder and emit a single
# synthesized.vbs that, when run via 32-bit cscript, replays the same actions
# in order. Suitable for dropping into a future transaction-specific skill
# as a starting template.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File sap_gui_probe_synthesize.ps1 `
#       -RunFolder <abs-path>                  # the {RUN_FOLDER}
#       [-OutFile <abs-path>]                  # default <RunFolder>\synthesized.vbs
#
# The emitted VBS:
#   * Begins with a header comment naming the source run folder + timestamp.
#   * Attaches to the active SAP GUI session via GetObject("SAPGUI").
#   * For each action: emits a step-delimited comment + the literal VBS line
#     that performs the action, plus a WScript.Sleep matching the original.
#   * Ends with "WScript.Echo ""REPLAY DONE""".
# =============================================================================

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $RunFolder,

    [string] $OutFile = ''
)

if (-not (Test-Path $RunFolder)) {
    Write-Error "RunFolder not found: $RunFolder"
    exit 1
}

if (-not $OutFile) {
    $OutFile = Join-Path $RunFolder 'synthesized.vbs'
}

$actionFiles = Get-ChildItem -Path $RunFolder -Filter 'step_*_action.json' -File |
               Sort-Object Name

if (-not $actionFiles -or $actionFiles.Count -eq 0) {
    Write-Error "no step_NN_action.json files in $RunFolder -- nothing to synthesize"
    exit 1
}

function Escape-VbsString {
    param([string] $s)
    if ($null -eq $s) { return '""' }
    return '"' + ($s -replace '"', '""') + '"'
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("' =============================================================================")
[void]$sb.AppendLine("' synthesized.vbs -- auto-generated by sap-gui-probe")
[void]$sb.AppendLine("' source run folder : $RunFolder")
[void]$sb.AppendLine("' generated at      : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
[void]$sb.AppendLine("' action count      : $($actionFiles.Count)")
[void]$sb.AppendLine("' ")
[void]$sb.AppendLine("' Replay: cscript //NoLogo synthesized.vbs")
[void]$sb.AppendLine("' Requires an active SAP GUI session positioned at the same starting screen")
[void]$sb.AppendLine("' as the original probe (typically SAP Easy Access).")
[void]$sb.AppendLine("' =============================================================================")
[void]$sb.AppendLine("Option Explicit")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("Dim oSAP, oApp, oCon, oSess")
[void]$sb.AppendLine("Set oSAP  = GetObject(""SAPGUI"")")
[void]$sb.AppendLine("Set oApp  = oSAP.GetScriptingEngine")
[void]$sb.AppendLine("Set oCon  = oApp.Children(0)")
[void]$sb.AppendLine("Set oSess = oCon.Children(0)")
[void]$sb.AppendLine("")

$stepIdx = 0
foreach ($file in $actionFiles) {
    $stepIdx++
    try {
        $a = Get-Content -Path $file.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
    } catch {
        Write-Warning "skipping $($file.Name) -- not valid JSON"
        continue
    }

    $verb   = "$($a.verb)".ToUpperInvariant()
    $target = "$($a.target)"
    $value  = "$($a.value)"
    $vkey   = $a.vkey
    $row    = $a.row
    $note   = "$($a.note)"
    $sleep  = if ($null -ne $a.sleep -and "$($a.sleep)" -ne '') { [int]$a.sleep } else { 800 }

    [void]$sb.AppendLine("' --- step $('{0:D2}' -f $stepIdx) | $verb | $note")

    switch ($verb) {
        'SET_TEXT' {
            [void]$sb.AppendLine("oSess.findById($(Escape-VbsString $target)).Text = $(Escape-VbsString $value)")
        }
        'SET_OKCD' {
            $tgt = if ($target) { $target } else { 'wnd[0]/tbar[0]/okcd' }
            [void]$sb.AppendLine("oSess.findById($(Escape-VbsString $tgt)).Text = $(Escape-VbsString $value)")
            [void]$sb.AppendLine("oSess.findById(""wnd[0]"").sendVKey 0")
        }
        'SEND_VKEY' {
            $tgt = if ($target) { $target } else { 'wnd[0]' }
            [void]$sb.AppendLine("oSess.findById($(Escape-VbsString $tgt)).sendVKey $vkey")
        }
        'PRESS' {
            [void]$sb.AppendLine("oSess.findById($(Escape-VbsString $target)).press")
        }
        'SELECT_ROW' {
            [void]$sb.AppendLine("oSess.findById($(Escape-VbsString $target)).getAbsoluteRow($row).Selected = True")
        }
        'DOUBLE_CLICK' {
            [void]$sb.AppendLine("oSess.findById($(Escape-VbsString $target)).doubleClick")
        }
        default {
            [void]$sb.AppendLine("' WARNING: unknown verb '$verb' -- skipped in synthesis")
        }
    }

    [void]$sb.AppendLine("WScript.Sleep $sleep")
    [void]$sb.AppendLine("")
}

[void]$sb.AppendLine("WScript.Echo ""REPLAY DONE""")

[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), [System.Text.UnicodeEncoding]::new($false, $true))
Write-Output "synthesized: $OutFile ($($actionFiles.Count) actions)"
exit 0
