' =============================================================================
' sap_se24_check.vbs  -  SAP GUI Scripting: Check if ABAP class exists
'
' Generated by the sap-se24 skill.
' Attaches to an existing SAP GUI session, navigates to SE24,
' attempts Display, and checks if the Class Builder editor opens.
'
' Output: "EXIST" or "NOT_EXIST" (last line of stdout, parseable by skill).
'
' Tokens replaced at run time:
'   %%CLASS_NAME%%  ABAP class name  e.g. "ZCL_HK_TEST001"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const CLASS_NAME = "%%CLASS_NAME%%"
Const VKEY_ENTER = 0

Dim oSAPGUI, oApplication, oSession
Dim oCandidate, oSessIter

' ------ 1. Attach to existing SAP GUI session -------------------------------
On Error Resume Next
Set oSAPGUI = GetObject("SAPGUI")
If Err.Number <> 0 Or oSAPGUI Is Nothing Then
    WScript.Echo "ERROR: SAP GUI is not running."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

Set oApplication = oSAPGUI.GetScriptingEngine
If oApplication Is Nothing Then
    WScript.Echo "ERROR: Could not get SAP Scripting Engine."
    WScript.Quit 1
End If

Set oSession = Nothing
On Error Resume Next
For Each oCandidate In oApplication.Children
    For Each oSessIter In oCandidate.Children
        Set oSession = oSessIter
        Exit For
    Next
    If Not (oSession Is Nothing) Then Exit For
Next
On Error GoTo 0

If oSession Is Nothing Then
    WScript.Echo "ERROR: No SAP GUI session found. Run the login step first."
    WScript.Quit 1
End If
WScript.Echo "INFO: Session acquired."

' ------ 2. Navigate to SE24 -------------------------------------------------
WScript.Echo "INFO: Navigating to SE24..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nSE24"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Enter class name and click Display -------------------------------
WScript.Echo "INFO: Checking class: " & UCase(CLASS_NAME)
oSession.findById("wnd[0]/usr/ctxtSEOCLASS-CLSNAME").Text = UCase(CLASS_NAME)
oSession.findById("wnd[0]/usr/btnPUSH_DISPLAY").press
WScript.Sleep 2000

' ------ 4. Determine result -------------------------------------------------
' If the class exists, the Class Builder editor opens with tabsCTS tab strip.
' If it does not exist, we stay on the SE24 initial screen with a status message.
On Error Resume Next
Dim oTabStrip
Set oTabStrip = oSession.findById("wnd[0]/usr/tabsCTS")
Dim bFound
bFound = (Err.Number = 0 And Not (oTabStrip Is Nothing))
Err.Clear
On Error GoTo 0

If bFound Then
    WScript.Echo "INFO: Class " & UCase(CLASS_NAME) & " exists."
    ' Navigate back to SE24 initial screen
    oSession.findById("wnd[0]/tbar[0]/okcd").text = "/nSE24"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    WScript.Echo "EXIST"
Else
    Dim sStatus
    sStatus = oSession.findById("wnd[0]/sbar").Text
    WScript.Echo "INFO: " & sStatus
    WScript.Echo "NOT_EXIST"
End If

WScript.Quit 0
