' =============================================================================
' sap_pfcg_create.vbs  -  SAP GUI Scripting: create a single PFCG role
'                         (role name + description, save)
'
' Generated by the /sap-pfcg skill (create mode). Attaches to the pinned SAP GUI
' session, navigates to PFCG, enters the role name, creates a single role via the
' index-stable Role > Create > Role menu path, sets the short description, saves,
' and (defensively) resolves a transport-request popup for the rare transportable
' single role. Single roles are usually CLIENT-LOCAL and never prompt for a TR.
'
' Language independence (per shared/rules/language_independence_rules.md):
'   controls are addressed by ID + DDIC field name + index-stable menu path;
'   verdicts read wnd[0]/sbar.MessageType (S/W/E/I/A), NEVER translated .Text /
'   .Tooltip / window titles. Popups are detected by wnd[1] + a DDIC control id.
'   (The flow was captured on a JA logon via IDs -- it must work in any language.)
'
' Reference flow (EC2 ERP/800, ECC6 rel 731; S/4 1909 structurally identical):
'   /nPFCG -> 121 SAPLPRGN_TREE -> ctxtAGR_NAME_NEU -> Role>Create>Role
'   (mbar/menu[0]/menu[0]/menu[0]) -> 300 -> txtS_AGR_TEXTS-TEXT -> Save btn[11]
'
' Tokens replaced at run time:
'   %%ROLE_NAME%%        Single-role name (UPPERCASE)      e.g. "Z_SAPDEV_ROLE"
'   %%ROLE_DESC%%        Role short description
'   %%TRANSPORT%%        Customizing/Workbench TR for a transportable role. Empty
'                         for the usual client-local single role; if PFCG prompts
'                         and this is empty the script ABORTS (never blind-Enter).
'   %%SESSION_PATH%%     /app/con[N]/ses[M] pin (empty = auto-resolve)
'   %%ATTACH_LIB_VBS%%   abs path to shared sap_attach_lib.vbs
'   %%SESSION_LOCK_VBS%% abs path to shared sap_session_lock.vbs
'
' Outputs (parseable):
'   STATUS_TYPE: <S|W|E|I|A>   STATUS_TEXT: <text>
'   PFCG_NO_AUTH_CREATE: ...   (create step returned E/A -- sbar text verbatim)
'   ABORT_EMPTY_TR: ...        (TR popup appeared but no TRANSPORT supplied)
'   SUCCESS: PFCG role <name> created. | ERROR: ...
' Exit: 0 success, 1 failure.
' =============================================================================

Option Explicit

Const ROLE_NAME     = "%%ROLE_NAME%%"
Const ROLE_DESC     = "%%ROLE_DESC%%"
Const SAP_TRANSPORT = "%%TRANSPORT%%"
Const SESSION_PATH  = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER = 0
Const VKEY_SAVE  = 11

' Include shared helpers. Order matters: attach FIRST (the session-lock lib's
' pre-unlock popup sweep reads from oSession), then the session-lock lib.
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()

Dim oSession
Dim wasLocked : wasLocked = False

' Guard the unsubstituted-token case for the optional transport. Built from
' Chr(37) ("%") so the wrapper's global %%TOKEN%% replace cannot corrupt this
' comparison (same idiom as sap_se01_remove_objects.vbs).
Dim gTransport : gTransport = SAP_TRANSPORT
If gTransport = Chr(37) & Chr(37) & "TRANSPORT" & Chr(37) & Chr(37) Then gTransport = ""

' ------ 1. Attach to the pinned SAP GUI session -----------------------------
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to PFCG + enter the role name ---------------------------
WScript.Echo "INFO: Creating PFCG role " & UCase(ROLE_NAME) & "..."
On Error Resume Next
oSession.findById("wnd[0]").maximize
On Error GoTo 0

Dim oOk : Set oOk = F("wnd[0]/tbar[0]/okcd")
If oOk Is Nothing Then Fail "Could not address the OK-code field (wnd[0]/tbar[0]/okcd)."
On Error Resume Next
oOk.Text = "/nPFCG"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
On Error GoTo 0
WScript.Sleep 1000

Dim oRole : Set oRole = F("wnd[0]/usr/ctxtAGR_NAME_NEU")
If oRole Is Nothing Then Fail "PFCG initial screen (121) not reached -- role field ctxtAGR_NAME_NEU missing."
On Error Resume Next
oRole.Text = UCase(ROLE_NAME)
On Error GoTo 0

' ------ 3. Role > Create > Role via the index-stable menu path ---------------
' (The btn%#AUTOTEXT create button carries a release-unstable id -- use the menu.)
Dim oMenu : Set oMenu = F("wnd[0]/mbar/menu[0]/menu[0]/menu[0]")
If oMenu Is Nothing Then Fail "Create menu path wnd[0]/mbar/menu[0]/menu[0]/menu[0] not found on the PFCG initial screen."
On Error Resume Next
oMenu.select
On Error GoTo 0
WScript.Sleep 1200

' ------ 4. Create-step gate -------------------------------------------------
' The create authorization (S_USER_AGR activity 01) is enforced here. Any E/A
' means we never entered create mode. Report the sbar text VERBATIM (echo only);
' do NOT branch on the localized message text -- the MessageType code is the gate.
Dim sTypeC : sTypeC = SbarType()
If sTypeC = "E" Or sTypeC = "A" Then
    WScript.Echo "STATUS_TYPE: " & sTypeC
    WScript.Echo "STATUS_TEXT: " & SbarText()
    WScript.Echo "PFCG_NO_AUTH_CREATE: create step returned [" & sTypeC & "] " & SbarText()
    Fail "Could not create role " & UCase(ROLE_NAME) & " (create-step message type " & sTypeC & "). Most likely missing S_USER_AGR create authorization."
End If

' ------ 5. Confirm the Create Role detail screen (300) -----------------------
Dim oDesc : Set oDesc = F("wnd[0]/usr/txtS_AGR_TEXTS-TEXT")
If oDesc Is Nothing Then
    WScript.Echo "STATUS_TYPE: " & SbarType()
    WScript.Echo "STATUS_TEXT: " & SbarText()
    Fail "Did not reach the Create Role detail screen (300) -- description field txtS_AGR_TEXTS-TEXT missing."
End If

' ------ 6. Critical section: description + Save ------------------------------
wasLocked = TryLockSession(oSession)

On Error Resume Next
oDesc.Text = ROLE_DESC
On Error GoTo 0
WScript.Echo "INFO: Description = " & ROLE_DESC

Dim oSave : Set oSave = F("wnd[0]/tbar[0]/btn[11]")
On Error Resume Next
If oSave Is Nothing Then
    oSession.findById("wnd[0]").sendVKey VKEY_SAVE
Else
    oSave.press
End If
On Error GoTo 0
WScript.Sleep 1500

' ------ 7. Optional transport-request popup (transportable roles only) -------
' Detect by the DDIC control id, never by the modal title. Single roles are
' usually client-local and never reach this branch.
Dim oPop : Set oPop = F("wnd[1]")
If Not (oPop Is Nothing) Then
    Dim oTr : Set oTr = F("wnd[1]/usr/ctxtKO008-TRKORR")
    If Not (oTr Is Nothing) Then
        If gTransport = "" Then
            WScript.Echo "ABORT_EMPTY_TR: PFCG prompted for a transport request but no TRANSPORT was supplied."
            Fail "TR popup appeared but TRANSPORT is empty -- resolve a Customizing TR via /sap-transport-request --type customizing and re-run."
        End If
        WScript.Echo "INFO: Filling transport " & gTransport & "..."
        On Error Resume Next
        oTr.Text = gTransport
        On Error GoTo 0
        Dim oTrOk : Set oTrOk = F("wnd[1]/tbar[0]/btn[0]")
        On Error Resume Next
        If oTrOk Is Nothing Then
            oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        Else
            oTrOk.press
        End If
        On Error GoTo 0
        WScript.Sleep 1200
    End If
End If

' ------ 8. Read status + verdict (read BEFORE releasing the lock) -----------
Dim sType : sType = SbarType()
Dim sText : sText = SbarText()
WScript.Echo "STATUS_TYPE: " & sType
WScript.Echo "STATUS_TEXT: " & sText

ReleaseSession oSession, wasLocked

If sType = "E" Or sType = "A" Then
    WScript.Echo "ERROR: Create/save reported [" & sType & "] " & sText
    WScript.Quit 1
End If

WScript.Echo "SUCCESS: PFCG role " & UCase(ROLE_NAME) & " created."
WScript.Quit 0

' ============================ helper routines ===============================
' Every findById is funnelled through F() so a missing control returns Nothing
' instead of crashing. Callers check Is Nothing and fail loud via Fail().
Function F(sId)
    Set F = Nothing
    On Error Resume Next
    Set F = oSession.findById(sId, False)
    On Error GoTo 0
End Function

' Fail loud, release the session lock (idempotent no-op if never locked), quit 1.
Sub Fail(sMsg)
    WScript.Echo "ERROR: " & sMsg
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End Sub

Function SbarType()
    SbarType = ""
    Dim o : Set o = F("wnd[0]/sbar")
    If Not (o Is Nothing) Then
        On Error Resume Next
        SbarType = o.MessageType
        On Error GoTo 0
    End If
End Function

Function SbarText()
    SbarText = ""
    Dim o : Set o = F("wnd[0]/sbar")
    If Not (o Is Nothing) Then
        On Error Resume Next
        SbarText = o.Text
        On Error GoTo 0
    End If
End Function
