' =============================================================================
' sap_pfcg_generate.vbs  -  SAP GUI Scripting: generate the authorization
'                           profile for an existing PFCG role
'
' Generated by the /sap-pfcg skill (generate mode). Attaches to the pinned SAP
' GUI session, opens the role in change mode, enters the profile generator from
' the Authorizations tab (WITHOUT editing the auth tree), presses Generate,
' accepts the proposed profile name, and saves. The SKILL.md re-reads AGR_PROF +
' AGR_1251 over RFC afterwards -- that is the authoritative verdict; this driver
' only has to reach a clean (non-E/A) status bar.
'
' Language independence (per shared/rules/language_independence_rules.md):
'   controls are addressed by ID + DDIC field name + index-stable menu path;
'   verdicts read wnd[0]/sbar.MessageType (S/W/E/I/A), NEVER translated .Text /
'   .Tooltip / window titles. Popups are detected by wnd[1] + a DDIC control id.
'   (The flow was captured on a JA logon via IDs -- it must work in any language.)
'
' Reference flow (EC2 ERP/800, ECC6 rel 731; S/4 1909 structurally identical):
'   /nPFCG -> 121 -> ctxtAGR_NAME_NEU -> Role>Change (mbar/menu[0]/menu[1])
'   -> 300 -> Authorizations tab tabsTABSTRIP1/tabpTAB5 -> btnPROFIL1
'   -> [optional SAPLSUPV template popup: btn[19] No Template Selection / Shift+F7]
'   -> 120 SAPMSSY0 auth editor -> Generate tbar[1]/btn[17] (Shift+F5)
'   -> 670 SAPLSUPRN profile-name popup: confirm tbar[0]/btn[0] -> Save btn[11]
'
' The subscreen id fragment ":SAPLPRGN_TREE:0350" in the btnPROFIL1 path is
' RELEASE-SENSITIVE, so btnPROFIL1 is located robustly: try the exact id, then
' scan the tabpTAB5 subtree for any control whose id ends in "/btnPROFIL1".
' If it cannot be located, the driver degrades to PFCG_NEEDS_RECORDING (exit 3)
' rather than guessing a click.
'
' Tokens replaced at run time:
'   %%ROLE_NAME%%        Existing role name (UPPERCASE)
'   %%SESSION_PATH%%     /app/con[N]/ses[M] pin (empty = auto-resolve)
'   %%ATTACH_LIB_VBS%%   abs path to shared sap_attach_lib.vbs
'   %%SESSION_LOCK_VBS%% abs path to shared sap_session_lock.vbs
'
' Outputs (parseable):
'   STATUS_TYPE: <S|W|E|I|A>   STATUS_TEXT: <text>
'   PFCG_NEEDS_RECORDING: ...  (btnPROFIL1 not locatable on this release; exit 3)
'   SUCCESS: PFCG profile generated for <name>. | ERROR: ...
' Exit: 0 success, 1 failure, 3 needs-recording.
' =============================================================================

Option Explicit

Const ROLE_NAME    = "%%ROLE_NAME%%"
Const SESSION_PATH = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER  = 0
Const VKEY_SAVE   = 11
Const VKEY_BACK   = 3
Const VKEY_NOTMPL = 19    ' Shift+F7 = No Template Selection (SAPLSUPV popup)

' The exact (release-sensitive) candidate id for the Change-Authorization-Data
' button. If this misses, the subtree scan below finds it by "/btnPROFIL1".
Const PROFIL1_EXACT = "wnd[0]/usr/tabsTABSTRIP1/tabpTAB5/ssubSUB1:SAPLPRGN_TREE:0350/btnPROFIL1"

' Include shared helpers. Order matters: attach FIRST (the session-lock lib's
' pre-unlock popup sweep reads from oSession), then the session-lock lib.
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()

Dim oSession
Dim wasLocked : wasLocked = False

' ------ 1. Attach to the pinned SAP GUI session -----------------------------
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to PFCG + enter the role name ---------------------------
WScript.Echo "INFO: Generating profile for PFCG role " & UCase(ROLE_NAME) & "..."
On Error Resume Next
oSession.findById("wnd[0]").maximize
On Error GoTo 0

Dim oOk : Set oOk = F("wnd[0]/tbar[0]/okcd")
If oOk Is Nothing Then Fail "Could not address the OK-code field (wnd[0]/tbar[0]/okcd)."
On Error Resume Next
oOk.Text = "/nPFCG"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
On Error GoTo 0
WScript.Sleep 1000

Dim oRole : Set oRole = F("wnd[0]/usr/ctxtAGR_NAME_NEU")
If oRole Is Nothing Then Fail "PFCG initial screen (121) not reached -- role field ctxtAGR_NAME_NEU missing."
On Error Resume Next
oRole.Text = UCase(ROLE_NAME)
On Error GoTo 0

' ------ 3. Role > Change via the index-stable menu path ---------------------
Dim oMenu : Set oMenu = F("wnd[0]/mbar/menu[0]/menu[1]")
If oMenu Is Nothing Then Fail "Change menu path wnd[0]/mbar/menu[0]/menu[1] not found on the PFCG initial screen."
On Error Resume Next
oMenu.select
On Error GoTo 0
WScript.Sleep 1200

' ------ 4. Change-mode gate -------------------------------------------------
Dim sTypeC : sTypeC = SbarType()
If sTypeC = "E" Or sTypeC = "A" Then
    WScript.Echo "STATUS_TYPE: " & sTypeC
    WScript.Echo "STATUS_TEXT: " & SbarText()
    Fail "Could not open role " & UCase(ROLE_NAME) & " in change mode (message type " & sTypeC & "). Role may not exist or you lack change authorization."
End If

' ------ 5. Confirm the Change Role screen (300) via the Authorizations tab ---
Dim oTab : Set oTab = F("wnd[0]/usr/tabsTABSTRIP1/tabpTAB5")
If oTab Is Nothing Then
    WScript.Echo "STATUS_TYPE: " & SbarType()
    WScript.Echo "STATUS_TEXT: " & SbarText()
    Fail "Did not reach the Change Role screen (300) -- Authorizations tab tabsTABSTRIP1/tabpTAB5 missing."
End If

' ------ 6. Critical section: enter the profile generator + Generate + Save --
wasLocked = TryLockSession(oSession)

' Select the Authorizations tab (loads the ssubSUB1 subscreen).
On Error Resume Next
oTab.select
On Error GoTo 0
WScript.Sleep 1000

' Locate the Change-Authorization-Data button robustly (release-sensitive id).
Dim oProfil : Set oProfil = F(PROFIL1_EXACT)
If oProfil Is Nothing Then Set oProfil = FindDescBySuffix(F("wnd[0]/usr/tabsTABSTRIP1/tabpTAB5"), "/btnPROFIL1")
If oProfil Is Nothing Then
    WScript.Echo "PFCG_NEEDS_RECORDING: btnPROFIL1 (Change Authorization Data) not located under tabpTAB5 on this release."
    WScript.Echo "                      Re-capture the generate flow with /sap-gui-probe --record (see SKILL.md)."
    ReleaseSession oSession, wasLocked
    WScript.Quit 3
End If
On Error Resume Next
oProfil.press
On Error GoTo 0
WScript.Sleep 1500

' Optional template-selection popup (SAPLSUPV) for menu-less / empty roles:
' press "No Template Selection" (btn[19] / Shift+F7). Detect by wnd[1] presence;
' tolerate its absence (roles with content skip straight to the auth editor).
Dim oTpl : Set oTpl = F("wnd[1]")
If Not (oTpl Is Nothing) Then
    Dim oNoTpl : Set oNoTpl = F("wnd[1]/tbar[0]/btn[19]")
    On Error Resume Next
    If oNoTpl Is Nothing Then
        oSession.findById("wnd[1]").sendVKey VKEY_NOTMPL
    Else
        oNoTpl.press
    End If
    On Error GoTo 0
    WScript.Sleep 1200
End If

' Auth editor (SAPMSSY0, screen 120): Generate = tbar[1]/btn[17] (Shift+F5).
Dim oGen : Set oGen = F("wnd[0]/tbar[1]/btn[17]")
If oGen Is Nothing Then Fail "Auth editor (screen 120) not reached -- Generate button wnd[0]/tbar[1]/btn[17] missing."
On Error Resume Next
oGen.press
On Error GoTo 0
WScript.Sleep 1500

' Profile-name popup (SAPLSUPRN, screen 670): accept the proposed name (btn[0]).
Dim oProfPop : Set oProfPop = F("wnd[1]")
If Not (oProfPop Is Nothing) Then
    Dim oConfirm : Set oConfirm = F("wnd[1]/tbar[0]/btn[0]")
    On Error Resume Next
    If oConfirm Is Nothing Then
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
    Else
        oConfirm.press
    End If
    On Error GoTo 0
    WScript.Sleep 1200
End If

' ------ 7. Gate MessageType after the generate write ------------------------
Dim sTypeG : sTypeG = SbarType()
If sTypeG = "E" Or sTypeG = "A" Then
    WScript.Echo "STATUS_TYPE: " & sTypeG
    WScript.Echo "STATUS_TEXT: " & SbarText()
    Fail "Profile generation reported [" & sTypeG & "] " & SbarText()
End If

' ------ 8. Save + gate ------------------------------------------------------
Dim oSave : Set oSave = F("wnd[0]/tbar[0]/btn[11]")
On Error Resume Next
If oSave Is Nothing Then
    oSession.findById("wnd[0]").sendVKey VKEY_SAVE
Else
    oSave.press
End If
On Error GoTo 0
WScript.Sleep 1500

Dim sType : sType = SbarType()
Dim sText : sText = SbarText()
WScript.Echo "STATUS_TYPE: " & sType
WScript.Echo "STATUS_TEXT: " & sText
If sType = "E" Or sType = "A" Then Fail "Save after generate reported [" & sType & "] " & sText

' ------ 9. F3 back to the initial screen (best-effort cleanup) --------------
On Error Resume Next
oSession.findById("wnd[0]").sendVKey VKEY_BACK
On Error GoTo 0
WScript.Sleep 500

ReleaseSession oSession, wasLocked

WScript.Echo "SUCCESS: PFCG profile generated for " & UCase(ROLE_NAME) & "."
WScript.Quit 0

' ============================ helper routines ===============================
' Every findById is funnelled through F() so a missing control returns Nothing
' instead of crashing. Callers check Is Nothing and fail loud via Fail().
Function F(sId)
    Set F = Nothing
    On Error Resume Next
    Set F = oSession.findById(sId, False)
    On Error GoTo 0
End Function

' Fail loud, release the session lock (idempotent no-op if never locked), quit 1.
Sub Fail(sMsg)
    WScript.Echo "ERROR: " & sMsg
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End Sub

Function SbarType()
    SbarType = ""
    Dim o : Set o = F("wnd[0]/sbar")
    If Not (o Is Nothing) Then
        On Error Resume Next
        SbarType = o.MessageType
        On Error GoTo 0
    End If
End Function

Function SbarText()
    SbarText = ""
    Dim o : Set o = F("wnd[0]/sbar")
    If Not (o Is Nothing) Then
        On Error Resume Next
        SbarText = o.Text
        On Error GoTo 0
    End If
End Function

' Depth-first scan of oRoot's descendants for the first control whose id ends
' in sSuffix (used to locate btnPROFIL1 under a release-sensitive subscreen id).
' Leaf controls have no .Children -- guarded so the recursion terminates. This
' is a LOCAL subtree walk of a container's Children, NOT the forbidden legacy
' session-attach loop over the application's connections.
Function FindDescBySuffix(oRoot, sSuffix)
    Set FindDescBySuffix = Nothing
    If oRoot Is Nothing Then Exit Function
    Dim oChildren
    On Error Resume Next
    Set oChildren = oRoot.Children
    On Error GoTo 0
    If oChildren Is Nothing Then Exit Function
    Dim oCh, sId, oFound
    For Each oCh In oChildren
        sId = ""
        On Error Resume Next
        sId = oCh.Id
        On Error GoTo 0
        If sId <> "" Then
            If Len(sId) >= Len(sSuffix) Then
                If Right(sId, Len(sSuffix)) = sSuffix Then
                    Set FindDescBySuffix = oCh
                    Exit Function
                End If
            End If
        End If
        Set oFound = FindDescBySuffix(oCh, sSuffix)
        If Not (oFound Is Nothing) Then
            Set FindDescBySuffix = oFound
            Exit Function
        End If
    Next
End Function
