' =============================================================================
' sap_se19_create.vbs  -  SAP GUI Scripting: Create BAdI Implementation via SE19
'
' Generated by the sap-se19 skill.
' Attaches to an existing SAP GUI session, navigates to SE19, creates a new
' Enhancement Implementation (outer container), then adds a BAdI Implementation
' within it (inner element), creates the implementing class, saves, and
' activates.
'
' Two-level creation:
'   1. Enhancement Implementation (container) — created via SE19 "Create" section
'   2. BAdI Implementation (element) — added via tree toolbar in TABS_5
'
' Tokens replaced at run time:
'   %%ENH_SPOT%%           Enhancement Spot name          e.g. "ME_PROCESS_PO_CUST"
'   %%ENH_IMPL_NAME%%      Enhancement Implementation     e.g. "ZHK_BADI_PO_001"
'   %%ENH_IMPL_TEXT%%       Enh Impl short description     e.g. "PO processing enhancement"
'   %%BADI_DEFINITION%%     BAdI Definition name           e.g. "ME_PROCESS_PO_CUST"
'   %%BADI_IMPL_NAME%%      BAdI Implementation name       e.g. "ZHK_IM_PO_001"
'   %%IMPL_CLASS%%          Implementing class name        e.g. "ZCL_IM_ZHK_PO_001"
'   %%BADI_IMPL_TEXT%%      BAdI Impl short description    e.g. "PO processing BAdI impl"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909 (S4D).
' =============================================================================

Option Explicit

Const ENH_SPOT       = "%%ENH_SPOT%%"
Const ENH_IMPL_NAME  = "%%ENH_IMPL_NAME%%"
Const ENH_IMPL_TEXT  = "%%ENH_IMPL_TEXT%%"
Const BADI_DEFINITION = "%%BADI_DEFINITION%%"
Const BADI_IMPL_NAME = "%%BADI_IMPL_NAME%%"
Const IMPL_CLASS     = "%%IMPL_CLASS%%"
Const BADI_IMPL_TEXT = "%%BADI_IMPL_TEXT%%"

Const VKEY_ENTER     = 0
Const VKEY_F2        = 2
Const VKEY_F11_SAVE  = 11
Const VKEY_F12_CANCEL = 12

Dim oSAPGUI, oApplication, oSession
Dim oCandidate, oSessIter

' ------ 1. Attach to existing SAP GUI session -------------------------------
On Error Resume Next
Set oSAPGUI = GetObject("SAPGUI")
If Err.Number <> 0 Or oSAPGUI Is Nothing Then
    WScript.Echo "ERROR: SAP GUI is not running."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

Set oApplication = oSAPGUI.GetScriptingEngine
If oApplication Is Nothing Then
    WScript.Echo "ERROR: Could not get SAP Scripting Engine."
    WScript.Quit 1
End If

Set oSession = Nothing
On Error Resume Next
For Each oCandidate In oApplication.Children
    For Each oSessIter In oCandidate.Children
        Set oSession = oSessIter
        Exit For
    Next
    If Not (oSession Is Nothing) Then Exit For
Next
On Error GoTo 0

If oSession Is Nothing Then
    WScript.Echo "ERROR: No SAP GUI session found. Run the login step first."
    WScript.Quit 1
End If
WScript.Echo "INFO: Session acquired."

' ------ 2. Navigate to SE19 -------------------------------------------------
WScript.Echo "INFO: Navigating to SE19..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE19"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Create Enhancement Implementation (outer container) ---------------
WScript.Echo "INFO: Creating Enhancement Implementation: " & UCase(ENH_IMPL_NAME)

' Select "New BAdI" radio in Create section
oSession.findById("wnd[0]/usr/radG_IS_NEW_2").Select
' Enter Enhancement Spot
oSession.findById("wnd[0]/usr/ctxtG_ENHSPOTNAME").Text = UCase(ENH_SPOT)
' Press Create
oSession.findById("wnd[0]/usr/btnPUSHBUTTON_IMPLEMENT_TEXT").Press
WScript.Sleep 2000

' Handle "Create Enhancement Implementation" popup (wnd[1])
On Error Resume Next
Dim oPopup
Set oPopup = oSession.findById("wnd[1]")
If Err.Number <> 0 Or oPopup Is Nothing Then
    WScript.Echo "ERROR: Create Enhancement Implementation popup did not appear." & vbCrLf & _
                 "       Status: " & oSession.findById("wnd[0]/sbar").Text
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

WScript.Echo "INFO: Filling Enhancement Implementation name and short text..."
oSession.findById("wnd[1]/usr/txtG_ENHSTRU-ENHNAME").Text = UCase(ENH_IMPL_NAME)
oSession.findById("wnd[1]/usr/txtG_ENHSTRU-SHORTTEXT").Text = ENH_IMPL_TEXT
WScript.Sleep 300

' Press Enter to submit
oSession.findById("wnd[1]/tbar[0]/btn[0]").Press
WScript.Sleep 2000

' After Enter, wnd[2] "Create Object Directory Entry" appears (transport dialog)
' while wnd[1] stays open behind it
On Error Resume Next
Dim oWnd2a
Set oWnd2a = oSession.findById("wnd[2]")
If Err.Number = 0 And Not (oWnd2a Is Nothing) Then
    WScript.Echo "INFO: " & oWnd2a.Text & " — pressing Local Object..."
    oSession.findById("wnd[2]/tbar[0]/btn[7]").Press
    WScript.Sleep 2000
End If
Err.Clear
On Error GoTo 0

' After transport, wnd[1] transforms to "Create BAdI Implementation" confirmation
' Press Enter to confirm and navigate to the detail screen
On Error Resume Next
Set oPopup = oSession.findById("wnd[1]")
If Err.Number = 0 And Not (oPopup Is Nothing) Then
    WScript.Echo "INFO: " & oPopup.Text & " — confirming..."
    oSession.findById("wnd[1]/tbar[0]/btn[0]").Press
    WScript.Sleep 2000
End If
Err.Clear
On Error GoTo 0

' Verify we are on the Enhancement Implementation detail screen
Dim sTitle
sTitle = oSession.findById("wnd[0]").Text
If InStr(1, sTitle, "Enhancement Implementation", vbTextCompare) = 0 Then
    WScript.Echo "ERROR: Could not create Enhancement Implementation." & vbCrLf & _
                 "       Title: " & sTitle & vbCrLf & _
                 "       Status: " & oSession.findById("wnd[0]/sbar").Text
    WScript.Quit 1
End If
WScript.Echo "INFO: Enhancement Implementation created. Title: " & sTitle

' ------ 4. Add BAdI Implementation (inner element) --------------------------
WScript.Echo "INFO: Adding BAdI Implementation..."

' Switch to "Enh. Implementation Elements" tab (TABS_5)
oSession.findById("wnd[0]/usr/tabsTS_ENHANCEMENTS/tabpTABS_5").Select
WScript.Sleep 1000

' Press "Create BAdI Implementation" on the tree toolbar
Dim sTreeBase
sTreeBase = "wnd[0]/usr/tabsTS_ENHANCEMENTS/tabpTABS_5/ssubSUBS_5:SAPLENH_EDT_BADI:2100" & _
            "/splcSPLITTER:SAPLENH_EDT_BADI:2100/ssubBADI_TREE_LEFT:SAPLENH_EDT_BADI:0099" & _
            "/cntlBADI_IMPL_TREE/shellcont/shell/shellcont[1]"

On Error Resume Next
oSession.findById(sTreeBase & "/shell[0]").PressButton "FC_CREATE_BADI_IMPL"
If Err.Number <> 0 Then
    WScript.Echo "ERROR: Could not press Create BAdI Implementation button." & vbCrLf & _
                 "       Tree toolbar path may differ. Error: " & Err.Description
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0
WScript.Sleep 1500

' Fill the "Create BAdI Implementation" popup (wnd[1])
On Error Resume Next
Set oPopup = oSession.findById("wnd[1]")
If Err.Number <> 0 Or oPopup Is Nothing Then
    WScript.Echo "ERROR: Create BAdI Implementation popup did not appear."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

WScript.Echo "INFO: Filling BAdI Implementation details..."
oSession.findById("wnd[1]/usr/ctxtENH_BADI_IMPL_CREATE-BADI_DEFINITION").Text = UCase(BADI_DEFINITION)
oSession.findById("wnd[1]/usr/txtENH_BADI_IMPL_CREATE-BADI_IMPLEMENTATION").Text = UCase(BADI_IMPL_NAME)
oSession.findById("wnd[1]/usr/ctxtENH_BADI_IMPL_CREATE-IMPL_CLASS").Text = UCase(IMPL_CLASS)
oSession.findById("wnd[1]/usr/txtENH_BADI_IMPL_CREATE-IMPL_SHORTTEXT").Text = BADI_IMPL_TEXT
WScript.Sleep 300

' First Enter (submit)
oSession.findById("wnd[1]/tbar[0]/btn[0]").Press
WScript.Sleep 2000

' Second Enter (confirmation — fields become read-only, press Enter again)
On Error Resume Next
Set oPopup = oSession.findById("wnd[1]")
If Err.Number = 0 And Not (oPopup Is Nothing) Then
    oSession.findById("wnd[1]/tbar[0]/btn[0]").Press
    WScript.Sleep 2000
End If
Err.Clear
On Error GoTo 0

' ------ 5. Handle class creation popups -------------------------------------
' wnd[2] "Class <name>" Yes/No confirmation — press Yes
On Error Resume Next
Dim oWnd2
Set oWnd2 = oSession.findById("wnd[2]")
If Err.Number = 0 And Not (oWnd2 Is Nothing) Then
    WScript.Echo "INFO: Class creation confirmation — pressing Yes..."
    oSession.findById("wnd[2]/usr/btnBUTTON_1").Press
    WScript.Sleep 2000
End If
Err.Clear
On Error GoTo 0

' wnd[2] "Create Implementation Class" — select Create Empty Class (F2)
On Error Resume Next
Set oWnd2 = oSession.findById("wnd[2]")
If Err.Number = 0 And Not (oWnd2 Is Nothing) Then
    Dim sW2Title
    sW2Title = oWnd2.Text
    If InStr(sW2Title, "Create Implementation Class") > 0 Then
        WScript.Echo "INFO: Create Implementation Class — selecting Create Empty Class..."
        oSession.findById("wnd[2]/tbar[0]/btn[2]").Press   ' Create Empty Class (F2)
        WScript.Sleep 2000
    End If
End If
Err.Clear
On Error GoTo 0

' wnd[2] "Create Object Directory Entry" — press Local Object (F7)
On Error Resume Next
Set oWnd2 = oSession.findById("wnd[2]")
If Err.Number = 0 And Not (oWnd2 Is Nothing) Then
    Dim sW2Title2
    sW2Title2 = oWnd2.Text
    If InStr(sW2Title2, "Create Object Directory Entry") > 0 Then
        WScript.Echo "INFO: Transport dialog — pressing Local Object..."
        oSession.findById("wnd[2]/tbar[0]/btn[7]").Press   ' Local Object (F7)
        WScript.Sleep 2000
    End If
End If
Err.Clear
On Error GoTo 0

' Verify class was created
Dim sCreateStatus
sCreateStatus = oSession.findById("wnd[0]/sbar").Text
WScript.Echo "INFO: " & sCreateStatus

' Close remaining wnd[1] if still open
On Error Resume Next
Set oPopup = oSession.findById("wnd[1]")
If Err.Number = 0 And Not (oPopup Is Nothing) Then
    oSession.findById("wnd[1]").sendVKey VKEY_F12_CANCEL
    WScript.Sleep 1000
End If
Err.Clear
On Error GoTo 0

' ------ 6. Save (Ctrl+S) ----------------------------------------------------
WScript.Echo "INFO: Saving Enhancement Implementation..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 2000

' Handle transport popup on save
On Error Resume Next
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    Dim oLocalBtn
    Set oLocalBtn = oSession.findById("wnd[1]/tbar[0]/btn[7]")
    If Err.Number = 0 And Not (oLocalBtn Is Nothing) Then
        WScript.Echo "INFO: Transport dialog — pressing Local Object..."
        oLocalBtn.Press
    Else
        Err.Clear
        oSession.ActiveWindow.sendVKey VKEY_ENTER
    End If
    WScript.Sleep 2000
End If
Err.Clear
On Error GoTo 0

WScript.Echo "INFO: Saved."

' ------ 7. Activate (Ctrl+F3) -----------------------------------------------
WScript.Echo "INFO: Activating..."
On Error Resume Next
oSession.findById("wnd[0]/tbar[1]/btn[27]").Press
WScript.Sleep 3000

' Handle "Inactive Objects" list popup
If InStr(oSession.ActiveWindow.Id, "wnd[1]") > 0 Then
    WScript.Echo "INFO: Inactive objects list — confirming activation..."
    oSession.findById("wnd[1]").sendVKey VKEY_ENTER
    WScript.Sleep 5000
End If
Err.Clear
On Error GoTo 0

' ------ 8. Final status check ------------------------------------------------
Dim sFinalMsg, sFinalType
On Error Resume Next
sFinalMsg  = oSession.findById("wnd[0]/sbar").Text
sFinalType = oSession.findById("wnd[0]/sbar").MessageType
On Error GoTo 0

If sFinalType = "E" Then
    WScript.Echo "WARNING: Activation may have errors - " & sFinalMsg
Else
    WScript.Echo "INFO: SAP status: " & sFinalMsg
End If

WScript.Echo "SUCCESS: BAdI Implementation " & UCase(BADI_IMPL_NAME) & _
             " created in Enhancement Implementation " & UCase(ENH_IMPL_NAME) & _
             " with implementing class " & UCase(IMPL_CLASS) & "."
WScript.Quit 0
