' =============================================================================
' sap_se41_check.vbs  -  SAP GUI Scripting: Check if PF-STATUS exists
'
' Generated by the sap-se41 skill.
' Attaches to an existing SAP GUI session, navigates to SE41,
' attempts Display, and checks if the editor opens.
'
' Output: "EXIST" or "NOT_EXIST" (last line of stdout, parseable by skill).
'
' Tokens replaced at run time:
'   %%PROGRAM%%   Program / interface name   e.g. "SAPLZHKT05"
'   %%STATUS%%    PF-STATUS name             e.g. "ZTEST01"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const PROGRAM_NAME = "%%PROGRAM%%"
Const STATUS_NAME  = "%%STATUS%%"
Const SESSION_PATH = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default
Const VKEY_ENTER   = 0

ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SE41 -------------------------------------------------
WScript.Echo "INFO: Navigating to SE41..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE41"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Enter program/status, select Status radio, press Display ---------
WScript.Echo "INFO: Checking status: " & UCase(PROGRAM_NAME) & " / " & UCase(STATUS_NAME)
oSession.findById("wnd[0]/usr/radRSMPE-B_STATUS").Select
oSession.findById("wnd[0]/usr/ctxtRSMPE-PROGRAM").Text = UCase(PROGRAM_NAME)
oSession.findById("wnd[0]/usr/ctxtRSMPE-STATUS").Text  = UCase(STATUS_NAME)
oSession.findById("wnd[0]/usr/btn%#AUTOTEXT003").Press   ' Display button
WScript.Sleep 2000

' ------ 4. Determine result -------------------------------------------------
' If the status exists, the editor opens with title "Display Status ...".
' If not, we stay on the initial screen with a status bar error.
Dim sTitle
sTitle = oSession.findById("wnd[0]").Text

If InStr(sTitle, "Display Status") > 0 Then
    WScript.Echo "INFO: Status " & UCase(STATUS_NAME) & " of " & UCase(PROGRAM_NAME) & " exists."
    ' Navigate back to SE41 initial screen
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE41"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    WScript.Echo "EXIST"
Else
    Dim sStatus
    sStatus = oSession.findById("wnd[0]/sbar").Text
    WScript.Echo "INFO: " & sStatus
    WScript.Echo "NOT_EXIST"
End If

WScript.Quit 0
