' =============================================================================
' sap_se41_check.vbs  -  SAP GUI Scripting: Check if PF-STATUS exists
'
' Generated by the sap-se41 skill.
' Attaches to an existing SAP GUI session, navigates to SE41,
' attempts Display, and checks if the editor opens.
'
' Output: "EXIST" or "NOT_EXIST" (last line of stdout, parseable by skill).
'
' Tokens replaced at run time:
'   %%PROGRAM%%   Program / interface name   e.g. "SAPLZHKT05"
'   %%STATUS%%    PF-STATUS name             e.g. "ZTEST01"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const PROGRAM_NAME = "%%PROGRAM%%"
Const STATUS_NAME  = "%%STATUS%%"
Const VKEY_ENTER   = 0

Dim oSAPGUI, oApplication, oSession
Dim oCandidate, oSessIter

' ------ 1. Attach to existing SAP GUI session -------------------------------
On Error Resume Next
Set oSAPGUI = GetObject("SAPGUI")
If Err.Number <> 0 Or oSAPGUI Is Nothing Then
    WScript.Echo "ERROR: SAP GUI is not running."
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

Set oApplication = oSAPGUI.GetScriptingEngine
If oApplication Is Nothing Then
    WScript.Echo "ERROR: Could not get SAP Scripting Engine."
    WScript.Quit 1
End If

Set oSession = Nothing
On Error Resume Next
For Each oCandidate In oApplication.Children
    For Each oSessIter In oCandidate.Children
        Set oSession = oSessIter
        Exit For
    Next
    If Not (oSession Is Nothing) Then Exit For
Next
On Error GoTo 0

If oSession Is Nothing Then
    WScript.Echo "ERROR: No SAP GUI session found. Run the login step first."
    WScript.Quit 1
End If
WScript.Echo "INFO: Session acquired."

' ------ 2. Navigate to SE41 -------------------------------------------------
WScript.Echo "INFO: Navigating to SE41..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE41"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Enter program/status, select Status radio, press Display ---------
WScript.Echo "INFO: Checking status: " & UCase(PROGRAM_NAME) & " / " & UCase(STATUS_NAME)
oSession.findById("wnd[0]/usr/radRSMPE-B_STATUS").Select
oSession.findById("wnd[0]/usr/ctxtRSMPE-PROGRAM").Text = UCase(PROGRAM_NAME)
oSession.findById("wnd[0]/usr/ctxtRSMPE-STATUS").Text  = UCase(STATUS_NAME)
oSession.findById("wnd[0]/usr/btn%#AUTOTEXT003").Press   ' Display button
WScript.Sleep 2000

' ------ 4. Determine result -------------------------------------------------
' If the status exists, the editor opens with title "Display Status ...".
' If not, we stay on the initial screen with a status bar error.
Dim sTitle
sTitle = oSession.findById("wnd[0]").Text

If InStr(sTitle, "Display Status") > 0 Then
    WScript.Echo "INFO: Status " & UCase(STATUS_NAME) & " of " & UCase(PROGRAM_NAME) & " exists."
    ' Navigate back to SE41 initial screen
    oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE41"
    oSession.findById("wnd[0]").sendVKey VKEY_ENTER
    WScript.Sleep 500
    WScript.Echo "EXIST"
Else
    Dim sStatus
    sStatus = oSession.findById("wnd[0]/sbar").Text
    WScript.Echo "INFO: " & sStatus
    WScript.Echo "NOT_EXIST"
End If

WScript.Quit 0
