' =============================================================================
' sap_cmod_change_description.vbs  -  SAP GUI Scripting: Change a CMOD project's
'                                     short text (description)
'
' Generated by the sap-cmod skill.
' Attaches to a SAP GUI session, navigates to CMOD, selects the Attributes
' sub-object (radMODF-HEAD), opens the project in change mode (btnPAEND),
' overwrites the short text (txtMOD0-MODTEXT), and saves.
'
' Tokens replaced at run time:
'   %%PROJECT_NAME%%   CMOD project name (UPPERCASE, max 8)   e.g. "ZHKPJ001"
'   %%SHORT_TEXT%%     New short description
'   %%TRANSPORT%%      Transport request for the post-save TR popup. Optional;
'                       empty for local ($TMP) projects. If the popup appears
'                       with TRANSPORT blank the script aborts.
'
' Recording reference: C:\Temp\Record_CMOD_ChangeProjectDescription.vbs.
'
' Outputs (parseable):
'   STATUS_TYPE: <S|W|E|I|A>   STATUS_TEXT: <text>
'   SUCCESS: ... | ERROR: ...
' =============================================================================

Option Explicit

Const PROJECT_NAME  = "%%PROJECT_NAME%%"
Const SHORT_TEXT    = "%%SHORT_TEXT%%"
Const SAP_TRANSPORT = "%%TRANSPORT%%"
Const SESSION_PATH  = "%%SESSION_PATH%%"

Const VKEY_ENTER = 0
Const VKEY_SAVE  = 11

ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()

Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ Navigate to CMOD, select Attributes, open in change mode ------------
WScript.Echo "INFO: Changing description of CMOD project " & UCase(PROJECT_NAME) & "..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nCMOD"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 800
oSession.findById("wnd[0]/usr/ctxtMOD0-NAME").Text = UCase(PROJECT_NAME)
oSession.findById("wnd[0]/usr/radMODF-HEAD").select   ' Attributes sub-object
oSession.findById("wnd[0]/usr/btnPAEND").press        ' Change
WScript.Sleep 1500

' ------ Confirm we reached the Attributes screen (component presence) --------
Dim oText : Set oText = oSession.findById("wnd[0]/usr/txtMOD0-MODTEXT", False)
If oText Is Nothing Then
    WScript.Echo "STATUS_TYPE: " & oSession.findById("wnd[0]/sbar").MessageType
    WScript.Echo "STATUS_TEXT: " & oSession.findById("wnd[0]/sbar").Text
    WScript.Echo "ERROR: Did not reach the Attributes screen (txtMOD0-MODTEXT not found)."
    WScript.Quit 1
End If

Dim wasLocked : wasLocked = TryLockSession(oSession)

' ------ Overwrite short text + Save -----------------------------------------
oText.Text = SHORT_TEXT
WScript.Echo "INFO: Short text set to: " & SHORT_TEXT
oSession.findById("wnd[0]").sendVKey VKEY_SAVE
WScript.Sleep 1500

' ------ Handle optional transport-request popup (KO008-TRKORR) --------------
Dim oPop : Set oPop = oSession.findById("wnd[1]", False)
If Not (oPop Is Nothing) Then
    Dim oTr : Set oTr = oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR", False)
    If Not (oTr Is Nothing) Then
        If SAP_TRANSPORT = "" Then
            WScript.Echo "ERROR: SAP prompted for a transport request but TRANSPORT is empty."
            WScript.Echo "       Resolve a TR via /sap-transport-request and re-run."
            ReleaseSession oSession, wasLocked
            WScript.Quit 1
        End If
        WScript.Echo "INFO: Filling transport " & SAP_TRANSPORT & "..."
        oTr.Text = SAP_TRANSPORT
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1200
    Else
        WScript.Echo "INFO: Dismissing popup after save (Enter)..."
        oPop.sendVKey VKEY_ENTER
        WScript.Sleep 1000
    End If
End If

' ------ Read status ---------------------------------------------------------
Dim sMsg, sType
sMsg  = oSession.findById("wnd[0]/sbar").Text
sType = oSession.findById("wnd[0]/sbar").MessageType
WScript.Echo "STATUS_TYPE: " & sType
WScript.Echo "STATUS_TEXT: " & sMsg

ReleaseSession oSession, wasLocked

If sType = "E" Or sType = "A" Then
    WScript.Echo "ERROR: Save reported [" & sType & "] " & sMsg
    WScript.Quit 1
End If

oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER

WScript.Echo "SUCCESS: Short text of " & UCase(PROJECT_NAME) & " updated."
WScript.Quit 0
