' =============================================================================
' sap_cmod_delete.vbs  -  SAP GUI Scripting: Delete a CMOD enhancement project
'
' Generated by the sap-cmod skill. IRREVERSIBLE — the skill MUST confirm with
' the user before running this.
' Attaches to a SAP GUI session, navigates to CMOD, enters the project name,
' presses Delete (tbar[1]/btn[14]), confirms the "Delete?" popup with
' btnSPOP-OPTION1 (Yes), handles the optional post-delete transport popup,
' and reports status. Verify removal via MODATTR (sap_cmod_query.ps1).
'
' Tokens replaced at run time:
'   %%PROJECT_NAME%%   CMOD project name (UPPERCASE, max 8)   e.g. "ZHKPJ001"
'   %%TRANSPORT%%      Transport request for the post-delete TR popup. Optional;
'                       empty for local ($TMP) projects.
'
' Recording reference: C:\Temp\Record_CMOD_DeleteProject.vbs (S/4HANA 1909).
'
' Outputs (parseable):
'   STATUS_TYPE: <S|W|E|I|A>   STATUS_TEXT: <text>
'   SUCCESS: ... | ERROR: ...
' =============================================================================

Option Explicit

Const PROJECT_NAME  = "%%PROJECT_NAME%%"
Const SAP_TRANSPORT = "%%TRANSPORT%%"
Const SESSION_PATH  = "%%SESSION_PATH%%"

Const VKEY_ENTER = 0

ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%SESSION_LOCK_VBS%%", 1).ReadAll()

Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ Navigate to CMOD + enter project ------------------------------------
WScript.Echo "INFO: Deleting CMOD project " & UCase(PROJECT_NAME) & "..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nCMOD"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 800
oSession.findById("wnd[0]/usr/ctxtMOD0-NAME").Text = UCase(PROJECT_NAME)
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 500

Dim wasLocked : wasLocked = TryLockSession(oSession)

' ------ Press Delete (initial-screen application toolbar) -------------------
On Error Resume Next
oSession.findById("wnd[0]/tbar[1]/btn[14]").press
WScript.Sleep 1500
If Err.Number <> 0 Then
    WScript.Echo "ERROR: Could not press Delete (tbar[1]/btn[14]): " & Err.Description
    ReleaseSession oSession, wasLocked
    WScript.Quit 1
End If
Err.Clear
On Error GoTo 0

' ------ Confirm the deletion popup (btnSPOP-OPTION1 = Yes) -------------------
Dim oPop : Set oPop = oSession.findById("wnd[1]", False)
If Not (oPop Is Nothing) Then
    Dim oYes : Set oYes = oSession.findById("wnd[1]/usr/btnSPOP-OPTION1", False)
    If Not (oYes Is Nothing) Then
        WScript.Echo "INFO: Confirming deletion (Yes)..."
        oYes.press
        WScript.Sleep 1500
    Else
        WScript.Echo "INFO: Unknown popup on Delete — pressing Enter."
        oPop.sendVKey VKEY_ENTER
        WScript.Sleep 1500
    End If
Else
    WScript.Echo "INFO: No confirmation popup appeared (project may not exist)."
End If

' ------ Handle optional post-delete transport popup (KO008-TRKORR) ----------
Set oPop = oSession.findById("wnd[1]", False)
If Not (oPop Is Nothing) Then
    Dim oTr : Set oTr = oSession.findById("wnd[1]/usr/ctxtKO008-TRKORR", False)
    If Not (oTr Is Nothing) Then
        If SAP_TRANSPORT = "" Then
            WScript.Echo "ERROR: SAP prompted for a transport request but TRANSPORT is empty."
            WScript.Echo "       Resolve a TR via /sap-transport-request and re-run."
            ReleaseSession oSession, wasLocked
            WScript.Quit 1
        End If
        WScript.Echo "INFO: Filling transport " & SAP_TRANSPORT & "..."
        oTr.Text = SAP_TRANSPORT
        oSession.findById("wnd[1]").sendVKey VKEY_ENTER
        WScript.Sleep 1200
    Else
        WScript.Echo "INFO: Dismissing popup after delete (Enter)..."
        oPop.sendVKey VKEY_ENTER
        WScript.Sleep 1000
    End If
End If

' ------ Read status ---------------------------------------------------------
Dim sMsg, sType
sMsg  = oSession.findById("wnd[0]/sbar").Text
sType = oSession.findById("wnd[0]/sbar").MessageType
WScript.Echo "STATUS_TYPE: " & sType
WScript.Echo "STATUS_TEXT: " & sMsg

ReleaseSession oSession, wasLocked

If sType = "E" Or sType = "A" Then
    WScript.Echo "ERROR: Deletion reported [" & sType & "] " & sMsg
    WScript.Quit 1
End If

oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER

WScript.Echo "SUCCESS: Enhancement project " & UCase(PROJECT_NAME) & " deleted (verify MODATTR row gone)."
WScript.Quit 0
