' =============================================================================
' sap_cmod_change_include.vbs  -  SAP GUI Scripting: Edit an exit include
'                                 via SE38 (ABAP Editor)
'
' Generated by the sap-cmod skill.
' Attaches to an existing SAP GUI session, navigates to SE38, opens the
' include in Change mode, uploads the ABAP source from a local file,
' saves, performs syntax check, and activates.
'
' Tokens replaced at run time:
'   %%INCLUDE_NAME%%      Include program name     e.g. "ZXV00U01"
'   %%ABAP_SOURCE_FILE%%  Full local file path     e.g. "{WORK_TEMP}\ZXV00U01.abap"
'
' Component IDs recorded from SAP GUI 7.60 on S/4HANA 1909.
' =============================================================================

Option Explicit

Const INCLUDE_NAME     = "%%INCLUDE_NAME%%"
Const ABAP_SOURCE_FILE = "%%ABAP_SOURCE_FILE%%"
Const SESSION_PATH     = "%%SESSION_PATH%%"   ' empty / unsubstituted = use default

Const VKEY_ENTER    = 0
Const VKEY_F3_BACK  = 3
Const VKEY_F11_SAVE = 11

' Include shared attach helper.
ExecuteGlobal CreateObject("Scripting.FileSystemObject") _
    .OpenTextFile("%%ATTACH_LIB_VBS%%", 1).ReadAll()

' ------ 1. Attach to existing SAP GUI session (via shared attach helper) ----
Dim oSession
Set oSession = AttachSapSession(SESSION_PATH)

' ------ 2. Navigate to SE38 -------------------------------------------------
WScript.Echo "INFO: Navigating to SE38..."
oSession.findById("wnd[0]").maximize
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/nSE38"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 1000

' ------ 3. Enter include name and Change ------------------------------------
WScript.Echo "INFO: Opening include: " & UCase(INCLUDE_NAME)
oSession.findById("wnd[0]/usr/ctxtRS38M-PROGRAMM").Text = UCase(INCLUDE_NAME)
oSession.findById("wnd[0]/usr/btnCHAP").press    ' Change button
WScript.Sleep 2000

' Check we reached the ABAP Editor
Dim sTitle, sStatus, sStatusType
sTitle = oSession.findById("wnd[0]").Text
If InStr(sTitle, "ABAP Editor") = 0 And InStr(sTitle, "Include") = 0 Then
    sStatus = oSession.findById("wnd[0]/sbar").Text
    WScript.Echo "ERROR: Did not reach ABAP Editor. Title: " & sTitle
    WScript.Echo "ERROR: Status: " & sStatus
    WScript.Quit 1
End If
WScript.Echo "INFO: ABAP Editor reached: " & sTitle

' ------ 4. Upload ABAP source -----------------------------------------------
' Split full path into directory and filename
Dim oFSO, sDir, sFile
Set oFSO = CreateObject("Scripting.FileSystemObject")
sDir  = oFSO.GetParentFolderName(ABAP_SOURCE_FILE)
sFile = oFSO.GetFileName(ABAP_SOURCE_FILE)
Set oFSO = Nothing

WScript.Echo "INFO: Uploading from: " & ABAP_SOURCE_FILE
' Utilities > More Utilities > Upload/Download > Upload
oSession.findById("wnd[0]/mbar/menu[3]/menu[9]/menu[3]/menu[0]").select
WScript.Sleep 1000

' File dialog - fill path and filename
On Error Resume Next
oSession.findById("wnd[1]/usr/ctxtDY_PATH").Text     = sDir
oSession.findById("wnd[1]/usr/ctxtDY_FILENAME").Text  = sFile
If Err.Number <> 0 Then
    Err.Clear
    On Error GoTo 0
    WScript.Echo "ERROR: Upload dialog not found. Check SAP GUI Security settings."
    WScript.Quit 1
End If
On Error GoTo 0

' Press Replace (green tick) in the upload dialog
oSession.findById("wnd[1]/tbar[0]/btn[0]").press
WScript.Sleep 2000

' Handle "Replace" confirmation popup if it appears
On Error Resume Next
Dim oPop
Set oPop = oSession.findById("wnd[1]")
If Err.Number = 0 And Not (oPop Is Nothing) Then
    Dim sPopText
    sPopText = oPop.Text
    If InStr(LCase(sPopText), "replace") > 0 Or InStr(LCase(sPopText), "overwrite") > 0 Then
        WScript.Echo "INFO: Confirming replace..."
        oPop.findById("tbar[0]/btn[0]").press  ' Yes / Replace
        WScript.Sleep 1000
    End If
End If
Err.Clear
On Error GoTo 0

sStatus = oSession.findById("wnd[0]/sbar").Text
WScript.Echo "INFO: Upload: " & sStatus

' ------ 5. Save --------------------------------------------------------------
WScript.Echo "INFO: Saving..."
oSession.findById("wnd[0]").sendVKey VKEY_F11_SAVE
WScript.Sleep 2000

' Handle transport popup
On Error Resume Next
Set oPop = oSession.findById("wnd[1]")
If Err.Number = 0 And Not (oPop Is Nothing) Then
    WScript.Echo "INFO: Transport dialog: " & oPop.Text
    Dim oLocalBtn
    Set oLocalBtn = oPop.findById("tbar[0]/btn[7]")
    If Err.Number = 0 And Not (oLocalBtn Is Nothing) Then
        WScript.Echo "INFO: Assigning Local Object..."
        oLocalBtn.press
    Else
        Err.Clear
        oPop.sendVKey VKEY_ENTER
    End If
    WScript.Sleep 1000
End If
Err.Clear
On Error GoTo 0

sStatus = oSession.findById("wnd[0]/sbar").Text
WScript.Echo "INFO: Save: " & sStatus

' ------ 6. Syntax check ------------------------------------------------------
WScript.Echo "INFO: Running syntax check..."
oSession.findById("wnd[0]/tbar[1]/btn[26]").press
WScript.Sleep 2000

sStatus = oSession.findById("wnd[0]/sbar").Text
sStatusType = oSession.findById("wnd[0]/sbar").MessageType
WScript.Echo "INFO: Syntax: " & sStatus

If sStatusType = "E" Then
    WScript.Echo "ERROR: Syntax check failed."
    WScript.Quit 1
End If

' ------ 7. Activate -----------------------------------------------------------
WScript.Echo "INFO: Activating..."
oSession.findById("wnd[0]/tbar[1]/btn[27]").press
WScript.Sleep 2000

' Handle "Inactive Objects" popup if it shows a list
On Error Resume Next
Set oPop = oSession.findById("wnd[1]")
If Err.Number = 0 And Not (oPop Is Nothing) Then
    sTitle = oPop.Text
    If InStr(LCase(sTitle), "inactive") > 0 Then
        WScript.Echo "INFO: Confirming activation in popup..."
        oPop.sendVKey VKEY_ENTER
        WScript.Sleep 2000
    End If
End If
Err.Clear
On Error GoTo 0

sStatus = oSession.findById("wnd[0]/sbar").Text
sStatusType = oSession.findById("wnd[0]/sbar").MessageType
WScript.Echo "INFO: Activate: " & sStatus

If sStatusType = "E" Then
    WScript.Echo "ERROR: Activation failed: " & sStatus
    WScript.Quit 1
End If

' Navigate back to clean state
oSession.findById("wnd[0]/tbar[0]/okcd").Text = "/n"
oSession.findById("wnd[0]").sendVKey VKEY_ENTER
WScript.Sleep 500

WScript.Echo "SUCCESS: Include " & UCase(INCLUDE_NAME) & " uploaded, saved, and activated."
WScript.Quit 0
